### ISSUE TITLE
Connection Screen UI

### ISSUE THREAD

**Issue by nclzz** [kiwiirc/kiwiirc#100]
I'm opening this issue to share a proposal for one of the areas that @prawnsalad suggested in #78  for some UI improvements, the connection screen. **This is just the first iteration**, I'd like some feedbacks to understand if this could be the right direction. 

Be sure to click on the image to expand it.

![join-network](https://user-images.githubusercontent.com/1044343/29487130-db06b790-84f4-11e7-8e43-43a7d19271ca.png)

**Comment by prawnsalad** [comment]
Oh that's nice \o/ Clean look :)

I like the bit of text at the bottom too, that would be a nice area for any warning notices or general messages, with a little ⚠️  icon in there if needed.

The password box; Most people don't actually enter a password so that's why I've always had it toggable. Just to reduce the number of boxes on screen to keep it simpler.

What are your thoughts about the background? As the rest of the app has a white background so there would be a big change after this connection screen closes. Unless the rest of the add had that background colour too.. that could look good possibly.

Definitely in the right direction though!

**Comment by nclzz** [comment]
Glad that you liked it!

Password: i'm quite new to IRC, can you give me more context about it? Is it required for the user login, private network or private channel? If it's not common to enter the password i'll hide it but my idea is to move from the checkbox into something different.

Background: that was an attempt, extend it to the whole app could be an overhead right now. The UI works well also with a white background, see the screenshot below.

![join-network](https://user-images.githubusercontent.com/1044343/29489665-97923a66-8526-11e7-8d78-583119bd7d5d.png)

**Comment by prawnsalad** [comment]
Oops, thought I'd replied to this yesterday.

A lot of users don't create an account to use IRC. They just enter a nickname and connect. This means that when they disconnect then somebody else can use their nick. If further down the line they register their nickname to protect it, then they can start entering a password.

**Comment by TheMythPT** [comment]
About password, it's mainly used to identify the nickname after successfully connected to the network, or in some cases as SASL authentication prior to connecting.

**Comment by nclzz** [comment]
I have designed a solution without the checkbox in order to keep everything clean and simple. In this way, the password field is shown only when needed. I believe this should be feasible and quite easy to implement, what do you think?

![connect-password](https://user-images.githubusercontent.com/1044343/29541736-51fd2590-86d6-11e7-97ac-11f38ff12d2d.gif)

**Comment by prawnsalad** [comment]
Simplicity, looks good!

Thinking of users that press tab to cycle through web forms, they would first have focus in the nick box, press tab then expect to be in some form of password related field. Which means in this case the focus would be in the nick box and then up to the password link, then back down to the channel box. A bit jumpy all over the page for that.

Thoughts?

**Comment by nclzz** [comment]
I don't know if that could be a usability problem, but your feedback made me rethink about the checkbox. This is the results, I really like it because it's clear that the password is linked to the nickname.

![connect-password](https://user-images.githubusercontent.com/1044343/29576293-984e57c6-8767-11e7-8723-2c76ccd0f98a.gif)

**Comment by prawnsalad** [comment]
And back to the original layout :) It's simple and to the point.

Have you had any thoughts to the connect button as yet? Ie. clicking it and the text changes to a loading icon or something. Currently it slides up to hide the boxes while it's connecting too.

**Comment by Novitsh** [comment]
Could be something as simple as this **example**: <img src="http://www.jqueryscript.net/images/jQuery-Plugin-For-Built-In-Loading-Indicator-In-Buttons-Button-Loader.jpg" />

**Comment by nclzz** [comment]
![join-freenode-loading](https://user-images.githubusercontent.com/1044343/30491376-6271a44e-9a3d-11e7-9eab-574d3a271db6.png)

I believe a simple approach with a button in disabled state and `Connecting...` copy works well. I won't hide the boxes while it's connecting, in case of errors it will be easier to handle the different use cases.

**Comment by TheMythPT** [comment]
So, how's this going. Any news/improvements?
:)

**Comment by AllanOcelot** [comment]
@TheMythPT @prawnsalad @nclzz - is there a PR to review for this? All looks good to me design/UI wise. Nice work.
