### ISSUE TITLE
Auto ignore user

### ISSUE THREAD

**Issue by sistematico** [kiwiirc/kiwiirc#1001]
There is anyway to auto-ignore some user for all clients?
User **VirtuaLife** in this case...

![Captura de tela_2019-05-23_07-06-00](https://user-images.githubusercontent.com/97509/58248151-5d106f00-7d29-11e9-909f-8a61e55262fe.png)

**Comment by sistematico** [comment]
Workaround:
```
.kiwi-messagelist-message[data-nick='VirtuaLife'] {
    display: none;
}
```

**Comment by AllanOcelot** [comment]
@prawnsalad - I've been thinking about this lately, we have 2/3 other existing issues relating to essentially muting users.

I was planning on doing the following:
- have a global array in Kiwi (blacklist_users)
- A user can edit this from advanced settings , or add a user to the list via the user's user_box buttons
- In the messagelist, we would check the user's username is not contained in blacklist_users

This would ensure a 'blanket mute' across all channels the user goes into.

The downside on this, is if a username is the same across 2 different networks, that could cause some problems. Would love to know your thoughts on this!

**Comment by prawnsalad** [comment]
This can be done via a plugin if you're hosting it yourself.

~~~~javascript
kiwi.plugin('auto_ignore', function(kiwi) {
    kiwi.on('network.new', function(event) {
        let user = kiwi.state.addUser(event.network.id, {nick: 'some_nick'});
    });
});
~~~~

**Comment by sistematico** [comment]
And more than one? 2 or 3 nicks?

**Comment by prawnsalad** [comment]
For each user you would repeat these lines:
~~~javascript
        user = kiwi.state.addUser(event.network.id, {nick: 'some_nick'});
        user.ignore = true;
~~~
