### ISSUE TITLE
Nginx proxy_pass

### ISSUE THREAD

**Issue by sistematico** [kiwiirc/kiwiirc#1002]
`site.com:port` to `chat.site.com`

```
server {
    listen 80;
    listen [::]:80;

    server_name chat.site.com;

    location / {
        proxy_pass http://localhost:7778;
    }
}
```
Why this is not working?

I only get a blank page with Kiwi IRC on title.

**Comment by ItsOnlyBinary** [comment]
It seems like you might be trying to setup the old kiwiirc there, come pay us a visit @ https://kiwiirc.com/nextclient/irc.freenode.net/#kiwiirc

here is my nginx config for new kiwiirc https://gist.github.com/ItsOnlyBinary/3e244106bfa4101f70f8a20c2d0e76b3

**Comment by ItsOnlyBinary** [comment]
https://github.com/kiwiirc/kiwiirc/blob/master/static/config.json#L18

in "statupOptions" section of /etc/kiwiirc/client.json you can add `"encoding": "theEncoding",`

i will also close this issue as hopefully it solved for you ;)
