### ISSUE TITLE
[Suggestion]: Make yellow color more dark in Default theme

### ISSUE THREAD

**Issue by westor7** [kiwiirc/kiwiirc#1004]
Hello,

There is an display problem with yellow color, i cannot see what someone is writing when including a yellow color (i don't know if mine display monitor has this issue only).

The suggestion is to make it more dark (e.g: https://rgbcolorcode.com/color/E6BF00)

Examples:

While messages were unread:
![firefox_2019-05-21_18-50-14](https://user-images.githubusercontent.com/3636159/58111200-b2e5f980-7bf9-11e9-97ba-cd67791b1d14.png)

While messages have been read:
![firefox_2019-05-21_18-50-22](https://user-images.githubusercontent.com/3636159/58111154-a19ced00-7bf9-11e9-84c2-b15d675b3a39.png)

- Thanks!

**Comment by AllanOcelot** [comment]
hi @westor7 - We have updated the colours in #969  , I cannot guarantee the yellow will stand out more on white, but it should be an improvement atleast .

You can preview that PR here ( https://builds.kiwiirc.com/kiwiirc/pull-969/ ) and see if it helps? 

Thanks for reporting the issue :)

**Comment by westor7** [comment]
@AllanOcelot ,

Thank you for your reply mate, i've test 969 PR but seems yellow is unreadable man, so the issue still exists.

- Thanks!

**Comment by AllanOcelot** [comment]
No problem at all, I'll test the PR again tomorrow and see if I cannot fix it :) 

As always, thank you for helping us make Kiwi great by submitting these issues :)

**Comment by westor7** [comment]
@AllanOcelot 

I tested that PR #969 and the yellow color is still looking ugly, it would be appreciated if you could make it more dark to test it out.

- Thanks!
