### ISSUE TITLE
Automatic network selection in "nextclient"

### ISSUE THREAD

**Issue by Jon-guy30** [kiwiirc/kiwiirc#1009]
When I wanted to connect to IRC I was looking for a web client. I always look for open source solutions and I found kiwiIRC. I don't use IRC, but this time I wanted to ask some questions so I needed IRC, I didn't want to install a client just to ask a few questions so that's why I wanted a web client. 

When I did manage to get connected Kiwi worked fine, but it was not very clear that I actually needed to fill out the connection information and port number, just like on a desktop client. I looked at online tutorials but they were all for the old version of Kiwi that's now deprecated. 

There should be a feature that when you select a network in the list it will actually connect to it when you hit "connect". I read the documentation, but there was no actual end-user documentation. In the old client all you had to do was select a network in the list of networks you wanted to join and connect. This new version is more complicated, it should be an easy solution. Those who look for a web client want a simple solution. You should only need to fill out connection information when you enter a custom network that's not listed. 

I'm reporting my experience to let you know that the user experience needs to be improved, or at least add end-user documentation to the website, instructions on how to actually use it and connect to a network.

There's a password field when filling out network information, I assume it's for password protected networks? Also, I don't know how to use SASL, in desktop clients there's an option to "identify automatically" when joining.

If I was confused and I'm someone who usually knows how to use software and computers, then it's safe to say there are probably others who are also confused.

**Comment by Shillos** [comment]
There is a Wiki [here](https://github.com/kiwiirc/kiwiirc/wiki) on github, but yeah it needs updating and lots of things have changed since. But due of continual development it might take longer for a new documentation to be re-written for the new client.

> There's a password field when filling out network information, I assume it's for password protected networks?

No. It's for login in the network just like using **/msg nickserv id pass** just put your pass for your login there and you are set to go.

**Comment by prawnsalad** [comment]
@Jon-guy30 thanks for the issue, it was actually a bug preventing the list from populating the fields. That's fixed now and it should work as expected if you refresh the page :)

**Comment by Jon-guy30** [comment]
Thanks, it works now!

But now there's a cosmetic issue, the network one selects doesn't display.

D'oh!
