### ISSUE TITLE
[Suggestion]: Add user mode classes in avatars on Modern style

### ISSUE THREAD

**Issue by westor7** [kiwiirc/kiwiirc#1014]
Hello,

It would be nice, to be able to change in Modern style the avatar based on nicklist emoji that is set, or to add a specific one for users that having specific channel modes (**~&@%+**), i will provide some CSS examples that would be nice to see supported.

```
.kiwi-messagelist-nick--mode-a .kiwi-messagelist-avatar {
  color: transparent;
  background-color: #F1F1F1 !important;
}
 
.kiwi-messagelist-nick--mode-a .kiwi-messagelist-avatar::before {
    content: "\1F432" !important;
    z-index: 1001;
    margin: 5px;
    color: black;
}
```
- Thanks!

**Comment by AllanOcelot** [comment]
This is a good idea, but I'm not sure if it's a good enough use case for core Kiwi.
Maybe this would be best as a plugin / or an option?
