### ISSUE TITLE
Websocket fallback connection 

### ISSUE THREAD

**Issue by H7-25** [kiwiirc/kiwiirc#1017]
A fine feature should be a fallback connection to webirc gateway when is set to use a direct connection and the browsers don't support websocket.

**Comment by H7-25** [comment]
Fallback connection could also be used if direct connection fail for any other reason.

**Comment by prawnsalad** [comment]
The normal kiwi transport has fallbacks and is why I always recommend using that over direct websockets. IRCds implementing websockets only have websockets and nothing else to fallback to.
