### ISSUE TITLE
Send Button not shown on chrome for android

### ISSUE THREAD

**Issue by H7-25** [kiwiirc/kiwiirc#1018]
The send button is not shown on chrome for android

![e589c187-b86e-4812-86e0-5e5e526ce447](https://user-images.githubusercontent.com/2895452/58470114-4c089900-8141-11e9-8549-02417e869907.JPG)

**Comment by AllanOcelot** [comment]
Hi @H7-25  - could you test again on the latest version of master and see if the issue still exists?

If it does still exist, could you please give information on your device and version of chrome for debugging?

**Comment by H7-25** [comment]
I've not checked my self it's an user feedback. It look that the button disappear when text it's too long.
Device Xiaomi mi a2 with Android 9

**Comment by prawnsalad** [comment]
This looks fine to me on master. If you still see the problem please reopen this issue. Thanks!
