### ISSUE TITLE
Restore existing nick for the network on welcome startup

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/kiwiirc#1021]

**Comment by AllanOcelot** [comment]
@TheBeerbarian  's PR looks like it does the job and should work. When testing on our builds server it does not seem to remember my username (even registered) however, I think that's because of the builds environment.

Asking @ItsOnlyBinary  to test this for me to confirm :)

**Comment by ItsOnlyBinary** [comment]
you need to set startupOptions: remember_buffers: true for it to save the network and the nick, i did test it yesterday but forgot to approve
