### ISSUE TITLE
KiwiIRC truncates messages

### ISSUE THREAD

**Issue by stdedos** [kiwiirc/kiwiirc#1027]
Hello there,

On seemingly random occassions, my IRC messages seem to get truncated.

e.g., on this chat:
```
/msg test Hello there, and apologies for abusing private messages. I try to join #842 , but I keep receiving: "Cannot join channel (+b) - you are banned". Please help# Complete
# Then, from the private message chat:
Not to my knowledge, n#Truncated
That's what's weird about it#Complete
I don't think I've even come to #abc be#Truncated
before#Truncated: `before*`
sabcdrt@gmail.#Truncated
*com (my irc client is truncating messages for some reason#Truncated
Thank y#Truncated
thank you****
```

Please advise

**Comment by ItsOnlyBinary** [comment]
Could you please try to give a little more info for this.

Are you hosting your own kiwiirc or using kiwiirc.com?
What network are you experiencing this issue on?
Is there any errors in console when this happens? (normally f12 to open console)

**Comment by stdedos** [comment]
> Are you hosting your own kiwiirc or using kiwiirc.com?

kiwiirc.com

> What network are you experiencing this issue on?

Define: "what network"
However, I have experienced that "for a long time", "on a number of occasions", so, I don't feel confident answering that (I would have reported the bug earlier, if I knew this repository existed).

> Is there any errors in console when this happens? (normally f12 to open console)

I haven't thought of that. I would assume no, but I cannot say for sure.
I'll check next time.

**Comment by ItsOnlyBinary** [comment]
kiwiirc.com can connect to many different irc networks, the default is irc.freenode.net. are you connecting to that or another? if you would rather not share which network your connecting to could you at least find out the irc server type and version, eg inspircd 2.0 / unrealircd 4

also what browser are you using.

trying to find out as much information as possible so i can reproduce the issue. without being able to reproduce it we wont know how to fix it

**Comment by stdedos** [comment]
> trying to find out as much information as possible so i can reproduce the issue. without being able to reproduce it we wont know how to fix it

Definitely! But, I don't know what to add 😂😂😂😂😂😂 
It's a very weird error, and it happens every once in a while (and has occured in a big timespan so far), I really don't know what would be of significance.
It would be nice if there is a bug report template (even a draft-y one).

> kiwiirc.com can connect to many different irc networks, the default is irc.freenode.net. are you connecting to that or another? if you would rather not share which network your connecting to could you at least find out the irc server type and version, eg inspircd 2.0 / unrealircd 4

I am mostly using Freenode server, so I don't have enough data about that.

> also what browser are you using.

and Chrome 74 (I think)

**Comment by stdedos** [comment]
![image](https://user-images.githubusercontent.com/133706/58869219-7ec50b00-86c6-11e9-80e9-57e154ba2952.png)
(I usually end my text with `...` and not with `..`)

**Comment by ItsOnlyBinary** [comment]
Those errors are just our analytics getting blocked, like by a plugin. you need to check console after truncation has occurred.

I've been trying to reproduce this without any luck.

It could maybe be one of your plugins, but not sure

**Comment by stdedos** [comment]
It is not entirely clear, but the last row in the screenshot has the truncated line.

> It could maybe be one of your plugins, but not sure

I thought of that too, but since I don't have accurate or regular reproduction, there will be enough functionality disabled (many plugins), and "necessary" functionality (ad-/track-blockers) that I am not willing to make without for an extended period.

I could try activate a more verbose mode, if there is such thing.

**Comment by ItsOnlyBinary** [comment]
if you wanted to share a list of your plugins i could try to work out which could be causing the issue, you could also private message me on freenode if you didnt want the list public.

**Comment by ItsOnlyBinary** [comment]
I remember chatting with you about this. but dont remember if we found a solution. is this still an issue?

**Comment by stdedos** [comment]
It seems that a "fresh" chromium does not show this problem; so it could very well be one of my extensions.

If there is "easy debugging" that can be made, I would be happy to follow it; otherwise I guess we can close this

**Comment by ItsOnlyBinary** [comment]
I think we covered all my bright ideas in our chat, i will close this issue. If you do figure out what extension please add it here so anyone searching the issues can find it ;) thanks for speedy reply ;)
