### ISSUE TITLE
KiwiIRC does not properly sanitize hostnames before hand-off to IRCd

### ISSUE THREAD

**Issue by duckspike** [kiwiirc/kiwiirc#103]
For more information, see https://github.com/inspircd/inspircd/issues/1365

Description: KiwiIRC does not properly sanitize the hostnames of users before hand-off to the IRCd. This allows a user to connect with a hostname that contains the illegal character "@". This is tested with the "next" client.

We use the hosted KiwiIRC.com client, therefore it is not possible to provide logs from our server. All other information is referenced in the InspIRCd issue.

**Comment by prawnsalad** [comment]
This is now fixed in the server-side codebase here https://github.com/kiwiirc/webircgateway/commit/4d0c684acbade2b3d6eeb84a2159afbe373d6183
