### ISSUE TITLE
nicklist long nicks wrap onto another line

### ISSUE THREAD

**Issue by ItsOnlyBinary** [kiwiirc/kiwiirc#1033]
when the nick is too long it wraps onto another line, also the typing indicator can be pushed onto a 3rd line

**Comment by digitalcircuit** [comment]
Example screenshot:

![Screenshot of the Kiwi IRC nickname sidebar, showing two nicks, "SeventeenCharNik" and "longest_nickname_allowed_here".  The second one overflows onto a second line, looking broken.](https://zorro.casa/sync/Hosting/Utilities/Development/KiwiIRC/issues/long-nick-overflow/Nickname%20overflow%20with%20long%20nick.png#v1 )

**Comment by westor7** [comment]
I can confirm this!

Example Video: http://j.mp/2XVZgSy
