### ISSUE TITLE
Extra characters

### ISSUE THREAD

**Issue by emersonveenstra** [kiwiirc/kiwiirc#1061]
Currently kiwiirc will treat `)` as part of a URL and include it in the link. This is problematic as some channels and bots will wrap URLs in `()` to separate them from the rest of the sentence, including freenode's NickServ post-registration text, which shows as:

![Screen Shot 2019-06-24 at 4 17 02 PM](https://user-images.githubusercontent.com/5402360/60049087-8c552b80-969b-11e9-9bae-9ec90ac8e520.png)

While ) is technically a valid character in a URL, it's rarely used and I think not including it will break more things than including it

**Comment by prawnsalad** [comment]
It's used in some wikipedia URLs which is fun. But yea, we could detect if it's wrapped in some type of punctuation/brackets and ignore them if that's the case.

**Comment by ItsOnlyBinary** [comment]
this has been fixed in master here: https://github.com/kiwiirc/kiwiirc/commit/0d4aef85d4e991c779fc7cf7e0b0de5e984721ce
