### ISSUE TITLE
Incorrect display of channel mode +q

### ISSUE THREAD

**Issue by emersonveenstra** [kiwiirc/kiwiirc#1063]
channel mode +q is sometimes for a quiet list, and sometimes for "owner" of a channel. kiwiirc (tested with nextclient) always displays +q as "gives owner to #channel", even if +q means a quiet, like on freenode (and in doing so hides the mask that was set)

**Comment by prawnsalad** [comment]
Updated in https://github.com/kiwiirc/kiwiirc/commit/9eeaa0d43bd23753087e242150f37be0d3f0d306
