### ISSUE TITLE
Incorrect password leads to long timeout

### ISSUE THREAD

**Issue by glguy** [kiwiirc/kiwiirc#1070]
When testing on webchat.freenode.net I've found that if I put in the wrong password before connecting that I get a long spinning busy icon followed by an eventual timeout message.

I'd expect the incorrect password status to be returned to the user instead so that they could quickly try fixing their password.

**Comment by ItsOnlyBinary** [comment]
This has been fixed in master and will be fixed on webchat.freenode.net when they next update
