### ISSUE TITLE
Include emojis

### ISSUE THREAD

**Issue by finalhit** [kiwiirc/kiwiirc#1083]
emojiLocation points to "https://kiwiirc.com/shared/emoji/".

Is it possible to include emojis locally instead of referencing them on the external server?

**Comment by prawnsalad** [comment]
You can download the emoji pack yourself, https://www.joypixels.com/
And then just update the URL in `emojiLocation` to your new location

**Comment by finalhit** [comment]
Thanks, this could be added to wiki:
https://github.com/kiwiirc/kiwiirc/wiki/Configuration-Options#emojilocation

**Comment by poVoq** [comment]
It sort of works with the png version of https://openmoji.org/ as well, but the default configured emojis other then the heart do not show up.
