### ISSUE TITLE
Default ident / username for IRC connections

### ISSUE THREAD

**Issue by finalhit** [kiwiirc/kiwiirc#1085]
Previous version had default ident setting, which is suitable for tracking what IRC clients are visitors using.

It would be nice to have it back:

```
/*
* Default ident / username for IRC connections
* %n will be replaced with the users nick
* %h will be replaced with the users hostname
* %i will be replaced with a hexed value of the users IP
*/
conf.default_ident = '%i';
```

**Comment by ItsOnlyBinary** [comment]
webircgateway has this feature

https://github.com/kiwiirc/webircgateway/blob/master/config.conf.example#L26

**Comment by abcbarryn** [comment]
But, if webircgateway does the ident, won't it show the IP of the web server connecting to the webircgateway and not the IP of the user's web browser?

**Comment by abcbarryn** [comment]
Also it looks like it listens on port 113 which would conflict the an OS ident daemon?
