### ISSUE TITLE
Clicking channel name doesn't bring focus to newly opened channel

### ISSUE THREAD

**Issue by finalhit** [kiwiirc/kiwiirc#1092]
When click channel name inside the chat, it opens such channel in the background, but it does not bring focus to newly created window.

When manually type /join #something, it does focus on newly opened channel window.

**Comment by finalhit** [comment]
The same issue when click "Join Channel" in channel list.

**Comment by ItsOnlyBinary** [comment]
for the channel list there is #755 
on large screens it will open the channel on first click and switch on second click (this is to allow joining multiple channels without it switching away from the channel list)
