### ISSUE TITLE
Automatically refresh channels list

### ISSUE THREAD

**Issue by finalhit** [kiwiirc/kiwiirc#1095]
When opening "Channels" tab for the first time, the window is completely empty and requires clicking refresh icon to list channels, which is pretty odd.

My suggestion is to remove refresh icon completely and to automatically refresh channel list every time "Channels" tab is accessed.

**Comment by prawnsalad** [comment]
Unfortunately on larger networks this channel refreshing can slow the browser down for a good minute - sometimes locking it up entirely on older browsers. That's why we require to click it manually
