### ISSUE TITLE
Inside IFRAME on iPhone: Clicking username changes scale

### ISSUE THREAD

**Issue by finalhit** [kiwiirc/kiwiirc#1096]
Please see below screenshots before and after.

HTML code to display client inside IFRAME:
```
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<iframe src="index.html" width="100%" height="100%" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe>
```
Cannot reproduce on Android nor outside IFRAME.

![IMG_3928](https://user-images.githubusercontent.com/2339712/60910741-e05a3580-a281-11e9-84c0-4dc8c62d0462.PNG)

![IMG_3929](https://user-images.githubusercontent.com/2339712/60910756-e8b27080-a281-11e9-932f-22b7e474b787.PNG)

**Comment by finalhit** [comment]
After the following change in src/components/ControlInput.vue:

```
@media screen and (max-width: 769px) {
    .kiwi-controlinput-selfuser--open .kiwi-controlinput-selfuser {
        /*width: 100%;*/
    }
```

the problem seems to be in pushing Send message box to the right:

![IMG_3944](https://user-images.githubusercontent.com/2339712/61486645-3a56ab80-a9a4-11e9-8897-94cebc30f4f5.PNG)

Maybe this dialog should be on top of the Send message box instead beside it, since nobody will do both things at the same time?

**Comment by prawnsalad** [comment]
Running things within iframes on mobile is always a bit dodgy unfortunately, so I would recommend not putting it in an iframe on mobile devices. No matter how much work we put into this there will always be some issues within iframes.

**Comment by Shillos** [comment]
Better to use WebView or WebChromeClient in java than iframes. Iframes is a horrible idea when building with mobile apps.

**Comment by finalhit** [comment]
We need IFRAME so we can insert custom header and footer above and below IRC client. The same on desktop and mobile devices.
