### ISSUE TITLE
Whois channels with modes not clickable

### ISSUE THREAD

**Issue by ManiacTwister** [kiwiirc/kiwiirc#110]
In the /whois output all channels where the whoisd user has an "special" channel mode (like op, voice, ,,) are not clickable.
![kiwiibug](https://user-images.githubusercontent.com/893193/30733138-f96a26ae-9f75-11e7-91f0-54a34f8f5ba4.png)

**Comment by prawnsalad** [comment]
This is now fixed in master. Thanks!
