### ISSUE TITLE
"too long script" error on internet explorer

### ISSUE THREAD

**Issue by KoraggKnightWolf** [kiwiirc/kiwiirc#1100]
It appears that occasionally KiwiIRC will sometimes freeze with a "too long script" error. I am opening up this issue as it seems based from conversations on #kiwiirc this might not be the only issue on IE.

00:16:55 <westor> actually kiwi is having more issues in IE, so it would be better to report that issue

Hopefully the issue(s) can be resolved swiftly so all browsers can be used well with KiwiIRC.

Regards,

Koragg

**Comment by prawnsalad** [comment]
I've been running kiwi on IE for about a week for unrelated debugging but I never saw this issue happening. If you're still seeing this issue please reopen this issue with the IE version you're using. Thanks!
