### ISSUE TITLE
Button to restore settings to their original defaults

### ISSUE THREAD

**Issue by finalhit** [kiwiirc/kiwiirc#1112]
There should be a button to restore settings to their original defaults.

**Comment by prawnsalad** [comment]
There is a forget me link when you click the user circle in the top left.

![image](https://user-images.githubusercontent.com/725880/61480880-d8d81200-a98e-11e9-9036-b654b7f377e6.png)

**Comment by finalhit** [comment]
That's not intuitive, I would never find it.

My suggestion is to move it to Settings and call "Reset Settings".
