### ISSUE TITLE
Config param to hide Settings

### ISSUE THREAD

**Issue by finalhit** [kiwiirc/kiwiirc#1113]
Beside "hide_advanced" option, it would be nice to have "hide_settings" to hide them completely.

**Comment by westor7** [comment]
Already exist that one;

https://github.com/kiwiirc/kiwiirc/blob/master/src/res/configTemplates.js#L100

**Comment by finalhit** [comment]
Nice, then Wiki should be updated: https://github.com/kiwiirc/kiwiirc/wiki/Configuration-Options

**Comment by prawnsalad** [comment]
Yup, I'm currently working on all the updated documentation at the moment. There's a lot of it to get through...
