### ISSUE TITLE
[Feature request] Report button

### ISSUE THREAD

**Issue by finalhit** [kiwiirc/kiwiirc#1123]
It would be nice to have Report button, so users of public chats could report nudity links, violence, harassment, hate speech and similar things.

User would select lines that would like to include in report, select or type the reason for reporting,
click Submit and Kiwi would send them to some user defined in configuration (e.g. to user "reports") or to some channel (e.g. #reports) monitored by IRC operators.

**Comment by prawnsalad** [comment]
That would be better suited to a plugin. Plugins can add buttons to the top left/right of kiwi, in the bottom left/right or in menus. People would have different ways to report to a server and have different rules so it's definitely not for the core.

**Comment by finalhit** [comment]
Is there some other more suitable place for plugins, to open this feature request?
