### ISSUE TITLE
Job for kiwiirc.service failed because the control process exited with error code. See "systemctl status kiwiirc.service" and "journalctl -xe" for details.

### ISSUE THREAD

**Issue by legendskyk** [kiwiirc/kiwiirc#1124]
I am getting error while in installation of new version kiwiirc in my root:

dpkg -i kiwiirc_19.04.24.1-1_amd64.deb
(Reading database ... 100260 files and directories currently installed.)
Preparing to unpack kiwiirc_19.04.24.1-1_amd64.deb ...
Unpacking kiwiirc (19.04.24.1-1) over (19.04.24.1-1) ...
Setting up kiwiirc (19.04.24.1-1) ...
Job for kiwiirc.service failed because the control process exited with error code. See "systemctl status kiwiirc.service" and "journalctl -xe" for details.
dpkg: error processing package kiwiirc (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (229-4ubuntu21.22) ...
Processing triggers for ureadahead (0.100.0-19.1) ...
Errors were encountered while processing:
 kiwiirc

**Comment by prawnsalad** [comment]
What do the details show?

**Comment by legendskyk** [comment]
I post it detail already above what is really that issue?

**Comment by prawnsalad** [comment]
> Job for kiwiirc.service failed because the control process exited with error code. See "systemctl status kiwiirc.service" and "journalctl -xe" for details.

What does running `systemctl status kiwiirc.service` show you?

**Comment by legendskyk** [comment]
systemd[1]: Starting LSB: KiwiIRC server...
 kiwiirc[30460]: Starting kiwiirc
 Unable to start, see /var/log/kiwiirc.
 systemd[1]: kiwiirc.service: Control process exited, c
 systemd[1]: Failed to start LSB: KiwiIRC server.
 systemd[1]: kiwiirc.service: Unit entered failed state
 kiwiirc.service: Failed with result 'exit-
lines 1-12/12 (END)

**Comment by legendskyk** [comment]
I got resolved it and found it the bug and Its work fine now but i have to ask a thing

**Comment by legendskyk** [comment]
how put this options in connecting window?

![image](https://user-images.githubusercontent.com/42233490/61760612-8ca12d80-ade5-11e9-96e2-1514f42fe18d.png)

**Comment by legendskyk** [comment]
and also this extra emoji option?

![image](https://user-images.githubusercontent.com/42233490/61760717-da1d9a80-ade5-11e9-82ad-16b0c3e3d768.png)

**Comment by legendskyk** [comment]
any idea? i got those things from a guy kiwiirc i want to do same setup in mine? how i customized it like that??

**Comment by legendskyk** [comment]
ok i did resolved the issue of emojis one but i dont able to add gender option on connecting box

**Comment by Shillos** [comment]
The emoji option is a plugin go here https://github.com/kiwiirc/plugin-emojis There are full instructions there!

**Comment by legendskyk** [comment]
yes i did it, but the gender one issue how is that set it?

**Comment by legendskyk** [comment]
its also possible geoip flags show on nicklist?? from which country user are?

**Comment by Shillos** [comment]
I've never seen gender option on kiwiirc or age or location unless whoever uses that is for statistics. It's useless for most Kiwi users because they are anonymous as far as I know. Most IRC networks are trying not to show ip's of other users, so in most cases, it's impossible to see from what country they are unless it's your own IRC network that you allow users to see everyone's IP.

**Comment by Shillos** [comment]
What if a user uses Tor or VPN, how are you going to terminate on where they are from?!

**Comment by legendskyk** [comment]
I actually talk like how flags of users show on mibbit widget ever you try it?? even irc network hide ip still widget show country flag by connecting mibbit web socket
