### ISSUE TITLE
Using network.new event to change e.network.username does not take effect

### ISSUE THREAD

**Issue by iwalkalone69** [kiwiirc/kiwiirc#113]
```
        kiwi.state.$on('network.new', function(e) {
            e.network.username = 'foo';
        });
```
User still connects by default realname.

**Comment by prawnsalad** [comment]
Quick note: https://github.com/kiwiirc/kiwiirc/blob/master/src/libs/IrcClient.js#L62

This should include the realname option being passed on.

**Comment by prawnsalad** [comment]
Added in https://github.com/kiwiirc/kiwiirc/commit/15c230018461b1b5996b93def2e58245b1dbe134
