### ISSUE TITLE
Add messages translation 

### ISSUE THREAD

**Issue by zoltyvigo** [kiwiirc/kiwiirc#1135]
- The nickname pepe is already in use!
- Enter new nickname...
- You must enter a new username
- Username must not start with a number

**Comment by ItsOnlyBinary** [comment]
Translations are community provided and added here: https://crowdin.com/project/kiwiirc

These strings are errors from the ircd so can not be easily translated as each ircd might send a different message:
`You must enter a new username`
`Username must not start with a number`

**Comment by zoltyvigo** [comment]
![image](https://user-images.githubusercontent.com/6929524/62368449-e4017500-b52c-11e9-986e-62bac68ba961.png)


![image](https://user-images.githubusercontent.com/6929524/62368480-f8457200-b52c-11e9-8fe1-ffb3af55a4af.png)

src/components/SelfUser.vue

**Comment by ItsOnlyBinary** [comment]
oh well found those could be added as translations

**Comment by zoltyvigo** [comment]
![image](https://user-images.githubusercontent.com/6929524/62369152-fda3bc00-b52e-11e9-99ed-117757248b3f.png)

**Comment by ItsOnlyBinary** [comment]
for that one i will point you back to #531
