### ISSUE TITLE
Google reCAPTCHA v3 Support

### ISSUE THREAD

**Issue by zoltyvigo** [kiwiirc/kiwiirc#1144]
Kiwi currently supports Google reCAPTCHA v2, but there is a problem, if you embed Kiwi on a Web that has reCAPTCHA v3, it gives compatibility problems.

**Comment by SilverWolf32** [comment]
Would adding v3 support break v2? I personally find reCAPTCHA v3 _extremely_ creepy – from what I've read, it sounds like they want to follow you everywhere you go on the website. I don't particularly want to be forced into using v3 if the site otherwise wouldn't.

**Comment by prawnsalad** [comment]
Closing this in favour of https://github.com/kiwiirc/kiwiirc/issues/1201. Adding alternative captchas
