### ISSUE TITLE
[Suggestion] TAGMSG: Make the dots animation!

### ISSUE THREAD

**Issue by gokturkyilmaz** [kiwiirc/kiwiirc#1146]
Is it possible to make the dots _(**…**)_ animations, when someone(s) typing a message in PM or channel like Skype, facebook….

**Comment by AllanOcelot** [comment]
Yes, this could easily be done by someone using CSS animations.
Would be a great first commit for someone to the project I think :)

**Comment by Shillos** [comment]
Here is something that might give you an idea https://codepen.io/rajarju/pen/pFrIt

**Comment by westor7** [comment]
@Shillos nice idea about https://nzbin.github.io/three-dots/ , looking very pretty..
