### ISSUE TITLE
Nickname issue

### ISSUE THREAD

**Issue by H7-25** [kiwiirc/kiwiirc#1167]
Nickname like Cu`Cu` are formatted as codes

![Schermata 2019-10-04 alle 08 07 34](https://user-images.githubusercontent.com/2895452/66185149-bea0fc80-e67e-11e9-8e63-4131d6eae6f3.png)

**Comment by prawnsalad** [comment]
Making this perfect will be a huge task, but Ive now improved this so that If the ` character is in the middle of another word, then it won't be matched as a codeblock.
