### ISSUE TITLE
Direct Websocket connection to UnrealIRCD & Future of Websockets

### ISSUE THREAD

**Issue by dhannyz** [kiwiirc/kiwiirc#118]
@prawnsalad 
As stated in your readme 
```To use your own server you either need to be using a websocket capable IRC server (none yet support this)```
Newer unrealircd version do in-fact offer native websocket support, as well as a few other more modern/experimental servers, Oragono (golang) for example.

What would be involved in making a direct connection to unreal?

Also, regarding websockets and their lack of a spec for HTTP2 (and thus QUIC), do you have any plans to address this? The Streams API looks promising but still very young, but I've had success using it as a websocket replacement on my own site, falling back to an indexed XHR stream where window.WritableStream isn't supported. We may try splicing this into your webircgateway

**Comment by DanielOaks** [comment]
Speaking of Oragono, we actually just ripped our support out so we can copy how one of the bigger servers does it ;)

Unreal has it, the Insp testnet has it iirc, and Chary had some support for it but not sure if that's actively being maintained these days.

**Comment by dhannyz** [comment]
@DanielOaks 
I noticed your experimental API too, this would in part resolve my second point regarding the future of websockets I believe.

**Comment by prawnsalad** [comment]
I had a go at working with the unrealircd dev at getting websockets working correctly, but they have a few caveats that make it unworkable with kiwiirc unfortunately.

* The web developer should not have to encode/decode string encodings in the webpage itself.
* The messages sent through the websocket should be dealt as strings, not binary. As thy were intended to be used.

I've mentioned these points to the unrealircd dev so until they're resolved I can't reasonably see any wide-use client that uses multiple encodings being made available. Inspircd was making changes to be more inline with this I believe.

The webircgateway project currently supports native websockets and SockJs for HTTP/Ajax polling fallbacks. All of these transports support multiple encodings (webircgateway converts to/from UTF8 as needed), and emits plain text messages without the need to convert from binary as the web technologies were intended for.

HTTP2 streams sound interesting as a transport. Does the client-side have access to the individual messages sent from this?

**Comment by dhannyz** [comment]
@prawnsalad Thanks for clarifying the status of the websocket links. We will have to develop something custom using your webircgateway I think.

Regarding HTTP2 + Fetch + Streams API
Given an endpoint that is serving a continuous stream to clients (we are using golang and gorilla/mux)
The client fetch's that endpoint and pipes the response.body to a writableStream to read chunks
```
fetch(url).then(response => {
        response.body.pipeTo(new WritableStream({
            write(chunk){
                //handle chunk
```
More Info.
https://developer.mozilla.org/en-US/docs/Web/API/WritableStream

I believe you can also use just ReadableStream where WritableStream isn't support, (only currently supported in chrome/chromium) however using WritableStream allows you to have Stream backpressure.

Otherwise a fallback to indexed XHR (a bit hacky, but works)
```
function XhrFallback(){
    var last_index = 0;
    var url = "url";
    var xhr = new XMLHttpRequest();
    xhr.open("GET", url);
    xhr.onprogress = function () {
        var curr_index = xhr.responseText.length;
        if (last_index == curr_index) return; 
        var obj = JSON.parse(xhr.responseText.substring(last_index, curr_index));
        last_index = curr_index;
        //use your obj
    };
    xhr.send();
}
```
Bi Directional streams would be nice, or a second stream for client -> server, but I've not figured that out just yet. However that isn't really required, the stream from server to client is the most important part, the client can then just fetch-post individual messages to another endpoint

I've currently got this working for pushing metadata from my online radio

**Comment by prawnsalad** [comment]
Wouldn't that increase the traffic overhead by a huge factor as it includes all the HTTP headers for every IRC line, @dhannyz? If an MOTD has 20 lines for example, using XHR over HTTP2 would make it roughly 100+ lines of data to be transferred instead.

Since HTTP/1.1 isn't going anywhere anytime soon (all HTTP2 webservers still support HTTP/1.1 that websockets require) it seems backward to add this sort of support in.

Either way, as I haven't type up docs on how this works as yet; You will need to implement a client transport. Here's the websocket transport as an example: https://github.com/kiwiirc/webircgateway/blob/master/pkg/webircgateway/clientWebsocket.go

You hook into the HTTP router as shown in `websocketHTTPHandler`. Do the relevant client address + origin checks, and create a client instance via `NewClient()`. This instance is the interface to be piping lines of data into and to receive signals (data from the ircd, irc connection closed, etc) from.

The transport you create can literally do anything to support your needs. The `clientKiwiirc.go` transport for example implements multiplexed client connections so multiple IRC connections can be piped through a single websocket/xhr connection and wraps the IRC lines in its own tiny wrapper to the browser to support this.

**Comment by dhannyz** [comment]
@prawnsalad 
Headers should only be sent once on initial connection as this is a long-lived stream on response.body.
As i'm implementing QUIC, (http over UDP), websockets just wont work in that domain and the future outlook of websockets being spec-ed is grim.

For Client -> Server the header issue you mention would hold unless you implemented a long-lived uplink stream (think chunked uploads) similar to the server-client connection.

If you wanted to see a server->client fetch stream in action https://rekt.network
Note: QUIC currently not working in latest chrome version, waiting for a golang library update

Thanks a bunch for the info on the client transport :)

**Comment by The5heepDev** [comment]
Heyo @prawnsalad I'm the one behind the backend of https://rekt.network

Just got home and looking into the client transport stuff. It should be super easy to implement a fetch/xhr stream onto your existing work, I'll update you on progress!

**Comment by prawnsalad** [comment]
Closing this issue as it's off-topic to kiwiirc now.

@The5heepDev if you need to discuss the webircgateway project at all or post any updates, feel free to mention them on http://github.com/kiwiirc/webircgateway !

**Comment by poVoq** [comment]
Looks like InspIRCd now supports websocket connections since version 3.0:
http://www.inspircd.org/2019/05/03/v300-released.html
