### ISSUE TITLE
Proper Client Exit

### ISSUE THREAD

**Issue by dstasinski** [kiwiirc/kiwiirc#1186]
When using the official Kiwi page, when closing the browser, the client exits the IRC server cleanly and immediately.  When doing the same on a personal installation, when closing the browser, the client remains until it ultimately pings out several minute later.  I cannot find any settings in Kiwi or webircgateway to correct this.

**Comment by prawnsalad** [comment]
There isn't any settings for this to find. Can you switch your kiwi server / webircgateway logs to debug and paste the log from just before you close your browser page?

**Comment by dstasinski** [comment]
2019/10/22 00:15:58.018441 L_DEBUG client:2 Traffic (Client -> BNC) WHO #Main
2019/10/22 00:15:58.018465 L_DEBUG client:2 Traffic (BNC -> Upstream) WHO #Main
2019/10/22 00:15:58.018739 L_DEBUG client:2 Traffic (Upstream -> BNC) :irc.disabilities-r-us.com 352 DanielTest #Main 4ba7a3ba E129E89D.89BD65A1.6F328D84.IP irc.disabilities-r-us.com DanielTest Hr :0 Disabilities-R-Us Web Chat
2019/10/22 00:15:58.018749 L_DEBUG client:2 Traffic (Upstream -> BNC) :irc.disabilities-r-us.com 352 DanielTest #Main handibot handibot.disabilities-r-us.com irc.disabilities-r-us.com HandiBot HrB@ :0 http://www.disabilities-r-us.com/
2019/10/22 00:15:58.018752 L_DEBUG client:2 Traffic (Upstream -> BNC) :irc.disabilities-r-us.com 352 DanielTest #Main daniel admin.disabilities-r-us.com irc.disabilities-r-us.com Daniel Hr%!:(MISSING)0 Daniel
2019/10/22 00:15:58.018755 L_DEBUG client:2 Traffic (Upstream -> BNC) :irc.disabilities-r-us.com 315 DanielTest #Main :End of /WHO list.
2019/10/22 00:15:58.018758 L_DEBUG client:2 signal:data :irc.disabilities-r-us.com 352 DanielTest #Main 4ba7a3ba E129E89D.89BD65A1.6F328D84.IP irc.disabilities-r-us.com DanielTest Hr :0 Disabilities-R-Us Web Chat
2019/10/22 00:15:58.018761 L_DEBUG client:2 signal:data :irc.disabilities-r-us.com 352 DanielTest #Main handibot handibot.disabilities-r-us.com irc.disabilities-r-us.com HandiBot HrB@ :0 http://www.disabilities-r-us.com/
2019/10/22 00:15:58.018764 L_DEBUG client:2 signal:data :irc.disabilities-r-us.com 352 DanielTest #Main daniel admin.disabilities-r-us.com irc.disabilities-r-us.com Daniel Hr% :0 Daniel
2019/10/22 00:15:58.018807 L_DEBUG client:2 signal:data :irc.disabilities-r-us.com 315 DanielTest #Main :End of /WHO list.
2019/10/22 00:16:05.504287 L_DEBUG kiwi connection closed (sockjs: session not in open state)
2019/10/22 00:16:05.504421 L_DEBUG client:2 StartShutdown(client_closed) ShuttingDown=false
2019/10/22 00:16:05.504431 L_INFO client:2 Client disconnected
2019/10/22 00:16:05.504454 L_INFO client:2 Removing channel from connection
2019/10/22 00:16:05.504470 L_DEBUG client:2 client.Recv closed
2019/10/22 00:16:05.504473 L_DEBUG client:2 leaving clientLineWorker
2019/10/22 00:19:10.368265 L_DEBUG client:2 StartShutdown(upstream_closed) ShuttingDown=true

**Comment by prawnsalad** [comment]
Thanks, those last 2 lines help. Does this happen every time or only sometimes? For everybody or just you?

**Comment by dstasinski** [comment]
Every time, every user who has tested so far.

**Comment by prawnsalad** [comment]
@dstasinski do you have a link to your kiwi instance so I can see how it's running?

**Comment by dstasinski** [comment]
Yep, the gateway is at https://speak.disabilities-r-us.com/  and the irc server itself is at speak.disabilities-r-us.com   This is a test server.

**Comment by ensoulsharp-emre** [comment]
Same issue.

2019/11/01 03:48:22.335902 Using config /Users/demo/dev/go/src/github.com/kiwiirc/webircgateway/config.conf
2019/11/01 03:48:22.337988 L_INFO Listening on 0.0.0.0:80
2019/11/01 03:48:23.508937 L_INFO client:2 New kiwiirc channel on localhost from ::1 ::1
2019/11/01 03:48:23.512958 L_DEBUG client:2 Traffic (Client -> BNC) HOST irc.test.com:6667
2019/11/01 03:48:23.512994 L_DEBUG client:2 Traffic (Client -> BNC) ENCODING windows-1254
2019/11/01 03:48:23.512998 L_DEBUG client:2 Set encoding to windows-1254
2019/11/01 03:48:23.513000 L_DEBUG client:2 Traffic (Client -> BNC) CAP LS 302
2019/11/01 03:48:23.513003 L_DEBUG client:2 Enabling client Messagetags feature
2019/11/01 03:48:23.513005 L_DEBUG client:2 Traffic (Client -> BNC) NICK test1 
2019/11/01 03:48:23.513007 L_DEBUG client:2 Traffic (Client -> BNC) USER test1 0 * :Demo Applet
2019/11/01 03:48:23.513587 L_INFO client:2 Using client given upstream
2019/11/01 03:48:23.529735 L_DEBUG client:2 Traffic (BNC -> Upstream) CAP LS 302
2019/11/01 03:48:23.529821 L_DEBUG client:2 Traffic (BNC -> Upstream) NICK test1
2019/11/01 03:48:23.529828 L_DEBUG client:2 Traffic (BNC -> Upstream) USER test1 0 * :Demo Applet
2019/11/01 03:48:23.529925 L_DEBUG client:2 signal:state connected
2019/11/01 03:48:23.905313 L_DEBUG client:2 Traffic (Upstream -> BNC) :irc.test.com CAP * LS :account-notify away-notify multi-prefix tls userhost-in-names
2019/11/01 03:48:23.905590 L_DEBUG client:2 signal:data :irc.test.com CAP * LS :account-notify away-notify multi-prefix tls userhost-in-names message-tags
2019/11/01 03:48:23.905671 L_DEBUG client:2 signal:data :irc.test.com 433 * test1 :Rumuz şu anda kullanımda.
2019/11/01 03:48:23.910675 L_DEBUG client:2 Traffic (Client -> BNC) CAP REQ :account-notify away-notify multi-prefix userhost-in-names message-tags
2019/11/01 03:48:23.910701 L_DEBUG client:2 Traffic (BNC -> Upstream) CAP REQ :account-notify away-notify multi-prefix userhost-in-names
2019/11/01 03:48:23.915337 L_DEBUG client:2 Traffic (Client -> BNC) NICK test72
2019/11/01 03:48:23.915375 L_DEBUG client:2 Traffic (BNC -> Upstream) NICK test72
2019/11/01 03:48:24.089199 L_DEBUG kiwi connection closed (sockjs: session not in open state)
2019/11/01 03:48:24.089302 L_DEBUG client:2 StartShutdown(client_closed) ShuttingDown=false
2019/11/01 03:48:24.089309 L_INFO client:2 Client disconnected
2019/11/01 03:48:24.089316 L_INFO client:2 Removing channel from connection
2019/11/01 03:48:24.089503 L_DEBUG client:2 client.Recv closed
2019/11/01 03:48:24.089511 L_DEBUG client:2 leaving clientLineWorker

**Comment by dstasinski** [comment]
After digging through the source of webircgateway, I see that setting **send_quit_on_client_close = "something"** in config.conf seems to solve the issue.

**Comment by ensoulsharp-emre** [comment]
Yes, it worked 😅
