### ISSUE TITLE
multiline `CAP LS 302` response handled incorrectly

### ISSUE THREAD

**Issue by slingamn** [kiwiirc/kiwiirc#1193]
This can be reproduced with https://kiwiirc.com/nextclient/ by attempting to connect to testnet.oragono.io (either plaintext on 6667 or TLS on 6697).

Kiwi sends `CAP LS 302` and the oragono testnet sends back a [multiline response](https://ircv3.net/specs/core/capability-negotiation.html#multiline-replies-to-cap-ls-and-cap-list):

```
:oragono.test CAP * LS * :account-notify account-tag away-notify batch cap-notify chghost draft/acc draft/event-playback draft/labeled-response-0.2 draft/languages=13,en,~bs,~de,~el,~en-AU,~es,~fr-FR,~no,~pl,~pt-BR,~ro,~tr-TR,~zh-CN draft/rename draft/resume-0.5 draft/setname echo-message extended-join invite-notify message-tags multi-prefix oragono.io/bnc oragono.io/maxline-2=2048 oragono.io/nope sasl=PLAIN,EXTERNAL server-time sts=duration=86400,port=6697
:oragono.test CAP * LS :userhost-in-names znc.in/playback znc.in/self-message
```

Kiwi appears to interpret only the second line --- moreover, negotiation stalls and Kiwi never proceeds to send `CAP END`:

```
> NICK Guest76
> USER 68c89961 0 * :[https://kiwiirc.com] Development release
> CAP REQ :userhost-in-names znc.in/self-message
< :oragono.test CAP * ACK :userhost-in-names znc.in/self-message
[ negotiation stalls ]
```

With an oragono server whose `CAP LS 302` response fits on a single line (e.g., https://irc.darwin.network), negotiation works as expected.

**Comment by slingamn** [comment]
From discussion on https://github.com/thelounge/thelounge/issues/3500, this may be an issue in the library https://github.com/kiwiirc/irc-framework (which is used by both Kiwi and The Lounge).

**Comment by prawnsalad** [comment]
Cheers for the heads up, @slingamn. Fixed in the latest irc-framework and kiwi via https://github.com/kiwiirc/kiwiirc/commit/00293099507fc6dc66ccfaa0bc04f5d482416ecb
