### ISSUE TITLE
[Suggestion]: Add /forgetme alias 

### ISSUE THREAD

**Issue by westor7** [kiwiirc/kiwiirc#1195]
Hello,

I wanna suggest that alias to be added to help out newbie users to solve any issues and use the default settings, i know that there is a "Forget me" button there but that alias seems an alternative easy way to help in some cases.

EDIT: If that is able via addon then it is appreciate if someone can paste the code.. 

- Thanks!

**Comment by prawnsalad** [comment]
If this is for newbie users then another /command is the opposite for what you need... the UI button is easier for that. If you really want this then you can add a plugin that creates the /forgetme command:

~~~javascript
kiwi.plugin('forgetmealias', function(kiwi, log) {
    kiwi.on('input.command.forgetme', function(event) {
        event.handled = true;
        if (!confirm('Really forget you? This will reset all your settings and refresh your page!')) {
            return;
        }
        kiwi.state.persistence.forgetState();
        window.location.reload();
    });
});
~~~
