### ISSUE TITLE
Channel black list (client)

### ISSUE THREAD

**Issue by fede220** [kiwiirc/kiwiirc#1196]
Hi it's possibile add the feature to prevent and block access to the channel adding it to the black list? Example when I write /join #channel the client prevents and block access to the channel.

**Comment by prawnsalad** [comment]
Any reason you can't add this restriction on the IRCd itself? Adding this into the client isn't very secure as it can easily be worked around no matter what we do.

**Comment by fede220** [comment]
Because not expert with the configuration of the IRCd. I don't know how to implement it.

**Comment by prawnsalad** [comment]
I'm closing this as it's not secure to do it in the client. if you don't want some users joining a channel then you should find out how to do it in the server - that is the only secure way to do this.
