### ISSUE TITLE
When captcha is enabled it is impossible to reconnect without refreshing

### ISSUE THREAD

**Issue by ItsOnlyBinary** [kiwiirc/kiwiirc#1200]
to duplicate /quit on a captcha enabled kiwi then try to use the reconnect button

**Comment by ItsOnlyBinary** [comment]
This was fixed with https://github.com/kiwiirc/kiwiirc/pull/1217

**Comment by ianjosephwilson** [comment]
This also does not work for me, I'm not sure if the problem is from the same source, but once i disconnect, maybe within 2-3 hours, the reconnect fails saying the recaptcha is invalid similar to #1211.  Does this fix depend on the browser version?

I'm using chromium 80.0.3987.132 on gentoo linux.
