### ISSUE TITLE
Allow alternative to reCAPTCHA

### ISSUE THREAD

**Issue by mirrorwolf** [kiwiirc/kiwiirc#1201]
One of the servers I'd like to join has a reCAPTCHA in place. I don't want Google following me around, and the server admins don't like having it either, but they want to have something there to prevent abuse.

Would you mind adding a simple built-in CAPTCHA, or a honeypot, or _something_ so server admins can stop spambots and the like without having to resort to Google?

**Comment by prawnsalad** [comment]
I'd be happy to accept a PR that integrates a different captcha.

Do you have any logs of the spambots that you're trying to block? Every time this topic has come up over the years it has always been an actual person doing the spamming.

**Comment by ObsidianWolf64** [comment]
Huh, I didn't think about that. I don't have any logs, unfortunately; I think in this case it's actually a preemptive measure because they've had issues with abuse on previous servers they've run in the past.

So, you're saying the reCAPTCHA is to help against targeted attacks by someone with an interest in attacking that particular server?

And awesome that you're open to this, thanks! Sounds like I need to figure out how all of this fits together. (:

**Comment by naiaokami** [comment]
Hello,

I run the server that @ObsidianWolf64 mentions. We implement the RECAPTCHA on connect as an anti-abuse measure. I would rather have a form of locally-hosted CAPTCHA due to the privacy concerns of my users.

**Comment by prawnsalad** [comment]
@naiaokami do you use the captcha against active abuse or is it purely preemptive? If it's against active abuse would you mind sharing some details on that as I've never seen any abuse that would have been stopped by a captcha, not that it's impossible.
In every case somebody has used the captcha that I've seen, it simply makes things more annoying for 100% of their user base while not actually doing anything else.

**Comment by naiaokami** [comment]
> @naiaokami do you use the captcha against active abuse or is it purely preemptive? If it's against active abuse would you mind sharing some details on that as I've never seen any abuse that would have been stopped by a captcha, not that it's impossible.
> In every case somebody has used the captcha that I've seen, it simply makes things more annoying for 100% of their user base while not actually doing anything else.

It's a slightly higher barrier to entry for people who are banned but have a lot of disposable machines. For the time being, I have turned it off and we'll see how that goes.

**Comment by ItsOnlyBinary** [comment]
hCaptcha is now supported see here: https://github.com/kiwiirc/kiwiirc/wiki/reCaptcha-and-hCaptcha
