### ISSUE TITLE
Cycling a channel with +H (chanhistory) enabled

### ISSUE THREAD

**Issue by H7-25** [kiwiirc/kiwiirc#1204]
Cycling a channel with +H (chanhistory) enable show duplicate messages when you rejoin the channel
![Screenshot (7)](https://user-images.githubusercontent.com/2895452/70989746-706b9900-20c4-11ea-87a9-ac1194936ca0.png)

**Comment by prawnsalad** [comment]
There's not much we can do here without hacks that can easily break. However, if the IRCd supports msgids then the duplicate messages won't be added again.
