### ISSUE TITLE
Firefox 72 won't show Notification prompt due to delay after clicking Start

### ISSUE THREAD

**Issue by digitalcircuit** [kiwiirc/kiwiirc#1206]
## In brief
* Firefox 72 blocks the notification request [due to delay after clicking `Start` to request permission](https://hacks.mozilla.org/2019/11/upcoming-notification-permission-changes-in-firefox-72/ )
  * Kiwi should request permission as soon as `Start` is clicked, don't wait for connection
  * Test in Firefox 71 by flipping `dom.webnotifications.requireinteraction.enabled` and `dom.webnotifications.requireuserinteraction` to `true` in `about:config`

### DevTools in Firefox 71
> Requesting Notification permission outside a short running user-generated event handler is deprecated and will not be supported in the future.

### DevTools in Firefox 72 (simulated with `about:config` in Firefox 71)
> The Notification permission may only be requested from inside a short running user-generated event handler.

*No notification prompt is shown, just a tiny, easy-to-miss bubble [as per the Mozilla Hacks blog post](https://hacks.mozilla.org/2019/11/upcoming-notification-permission-changes-in-firefox-72/).*

**Note: you must not have previously allowed/denied Kiwi IRC's notification prompt.  Try a fresh Firefox profile, remove past notification grants, or something equivalent.**

---

*This is a quick issue filed for future reference.  It can be expanded upon if needed.*

**Comment by crashbuggy** [comment]
I tested in a fresh profile and saw the warning "Requesting Notification permission outside a short running user-generated event handler is deprecated and will not be supported in the future." in devtools

**Comment by digitalcircuit** [comment]
Quick follow-up: I've confirmed this behavior with Firefox 72 beta, no `about:config` changes.

> The Notification permission may only be requested from inside a short running user-generated event handler.

![Screenshot of Firefox 72 Beta edition showing the above error in the Developer Tools console after loading the Kiwi IRC master build page.](https://zorro.casa/sync/Hosting/Utilities/Development/KiwiIRC/issues/firefox72-notify-prompt-blocked/Firefox%2072%20notification%20prompt%20blocked.png#v1 )

There's no prompt, only the easy-to-miss tiny icon added to the URL bar.

**Comment by prawnsalad** [comment]
Agreed on this. Moving it directly to the start button should solve this.

**Comment by digitalcircuit** [comment]
This has been worked around [in pull request #1207 - "Desktop notification permission on click"](https://github.com/kiwiirc/kiwiirc/pull/1207 ).

Future improvements:
* Prompt for notification permission upon sending message via <kbd>Enter</kbd>/some other keyboard trigger
  * Addresses folks using keyboard navigation and accessibility tools - currently, a click must be simulated before notification permissions can be granted
* Remove prompt on click/<kbd>Enter</kbd> and switch to an infobar at the top, akin to GMail and Discord
  * Cleaner, more respectful approach that requires a lot more work (including new translations)

I'd rather not close this issue until some way of handling keyboard events exists (filing a new issue for the long-term infobar approach), but I'd understand if that's not desired.

Regardless, thank you @prawnsalad for being so quick to respond!
