### ISSUE TITLE
Show Time Stamps and Left Join Hide Issue

### ISSUE THREAD

**Issue by legendskyk** [kiwiirc/kiwiirc#1214]
Hello,
I set config.json 
	"show_joinparts": false,
	"show_timestamps": false,
but still join part being show and also time stamps too so tell me the correct configuration to hide them?

**Comment by prawnsalad** [comment]
Can you paste your full kiwi config? I suspect you've added them to the wrong place

**Comment by legendskyk** [comment]
{
	"windowTitle": "",
	"startupScreen": "welcome",
	"kiwiServer": "/webirc/kiwiirc/",
	"restricted": true,
	"show_joinparts": false,
	"show_timestamps": false,
	"scrollback_size": 250,
	"messageLayout": "modern",
	"theme": "default",

	"themes": [
		{ "name": "Default", "url": "static/themes/default" },
		{ "name": "Dark", "url": "static/themes/dark" },
		{ "name": "Coffee", "url": "static/themes/coffee" },
		{ "name": "GrayFox", "url": "static/themes/grayfox" },
		{ "name": "Nightswatch", "url": "static/themes/nightswatch" },
		{ "name": "Osprey", "url": "static/themes/osprey" },
		{ "name": "Radioactive", "url": "static/themes/radioactive" },
		{ "name": "Sky", "url": "static/themes/sky" }
	],

	
	"startupOptions" : {
		"server": "",
		"port": 6667,
		"tls": false,
		"direct": false,
		"channel": "",
		"nick": "",
		"greetingText": "Welcome :-)",
		"infoBackground": "",
		"show_joinparts": false,
		"show_timestamps": false,
		"scrollback_size": 250,		
		"infoContent": ""
	
	},

**Comment by Shillos** [comment]
Those lines should be in buffer not in startupOptions

**Comment by prawnsalad** [comment]
As @Shillos mentions!

**Comment by legendskyk** [comment]
yes thanks its work now, but old one version was work even without buffer we set that, anyways thanks for the help.
