### ISSUE TITLE
Shared Typing not showing up in channel.

### ISSUE THREAD

**Issue by Shillos** [kiwiirc/kiwiirc#1215]
Hi! I have noticed an issue lately with Shared Typing in a channel or even private even when it is on. Nothing showed up in console dev tools, nor anywhere. So in raw, I noticed the [C] @+draft/typing=active TAGMSG #cyprus when sending a message and on the other receiving end in raw this [S] @time=2020-01-11T17:48:47.916Z;msgid=oVHg9R7rDDwFOQaNXXahyg :Guest9028!Guest90@6AF79623.24339472.433122AE.IP PRIVMSG #cyprus :hi
Yet again in the channel, nothing was showing up of the 3 dots, nor in nicklist, nor in the channel and nor in beneath. Just to note here when I worked with unrealircd 4 it was fine but now I'm using unrealircd 5.0.1. Not sure if that has anything to do with it.
Here is a screenshot of the issue in raw.
https://imgur.com/a/SjUAi2V

**Comment by westor7** [comment]
@Shillos 

Unrealircd 5 doesn't support this feature because a lack of IRCV3 CAP message-tags draft/typing

Read more: https://github.com/ircv3/ircv3-specifications/issues/333

**Comment by Shillos** [comment]
But it worked fine in unreal 4. I think this is more client based than server-based, as what I was told on chat.

**Comment by Shillos** [comment]
I guess for now better to close this one, as there is nothing to be done until Caps are stable in Unrealircd 5, (unless they might have a module for it) then I hope they put back the shared typing.
