### ISSUE TITLE
Current .deb (17.10.06.1) not accepting channel in URL?

### ISSUE THREAD

**Issue by KlaasT** [kiwiirc/kiwiirc#122]
Hi,

I downloaded kiwiirc_17.10.06.1-1_amd64.deb just today and have noticed I can't override the channel using the URL parameters like in the hosted version.

When trying https://kiwiirc.com/nextclient/irc.example.com/#blafasel I see the fields filled with the parameters. On the own hosted one nickname and channel are empty. I'm updating from kiwiirc_17.04.22.1-1_amd64.deb.

Thanks.

**Comment by KlaasT** [comment]
Ok if I change the startup screen from the default setting to "Welcome" it works.

**Comment by prawnsalad** [comment]
As you've found, different startup screens have different options. The welcome screen is designed more for single networks with channel+nick overrides.

It's not in-depth as yet, but a little more info on these screens can be found here: https://github.com/kiwiirc/kiwiirc/wiki/Startup-screens
