### ISSUE TITLE
Clients are not able to connect to chat server with 6667 port.

### ISSUE THREAD

**Issue by amansingh14** [kiwiirc/kiwiirc#1221]
Hi team, 
     I have installed Kiwi IRC on centos, but client is not able to connect to the server. Below is my client.json and config.
**client.json**
`{
        "windowTitle": "Kiwi IRC - chat2.xxxxxx.com",
        "startupScreen": "welcome",
        "kiwiServer": "chat2.xxxxxx.com",
        "restricted": true,
        "theme": "default",
        "themes": [
                { "name": "Default", "url": "static/themes/default" },
                { "name": "Dark", "url": "static/themes/dark" },
                { "name": "Coffee", "url": "static/themes/coffee" },
                { "name": "GrayFox", "url": "static/themes/grayfox" },
                { "name": "Nightswatch", "url": "static/themes/nightswatch" },
                { "name": "Osprey", "url": "static/themes/osprey" },
                { "name": "Radioactive", "url": "static/themes/radioactive" },
                { "name": "Sky", "url": "static/themes/sky" }
        ],
        "startupOptions" : {
                "server": "chat2.xxxxxx.com",
                "port": 6667,
                "tls": false,
                "direct": false,
                "channel": "#kiwiirc-default",
                "nick": "web?",
                "greetingText": "Hello!",
                "infoBackground": "",
                "infoContent": ""
        }
}`

**config.conf**
# 1 = Debug; 2 = Info; 3 = Warn;
logLevel = 3

# Enable the built in identd server (listens on port 113)
identd = false

# The name of this gateway as reported in WEBIRC to IRC servers
gateway_name = "webircgateway"

# A secret string used for generating client JWT tokens. Do not share this!
secret = ""

[verify]
recaptcha_secret = ""
recaptcha_key = ""

[clients]
# Default username / realname for IRC connections. If disabled it will use
# the values provided from the IRC client itself.
# %h will be replaced with the users hostname
# %i will be replaced with a hexed value of the users IP
username = "%i"
realname = "I am a webchat user"

# This hostname value will only be used when using a WEBIRC password
#hostname = "%h"

# The websocket / http server
[server.1]
bind = "0.0.0.0"
port = 80

# Example TLS server
#[server.2]
#bind = "0.0.0.0"
#port = 443
#tls = true
#cert = server.crt
#key = server.key
# If you don't have a certificate, uncomment the below line to automatically generate a
# free certificate using letsencrypt.com (overrides the above cert/key options). This requires
# a server running on port 80 to initially generate the certificate.
#letsencrypt_cache = ./certs

# Example unix socket server
#[server.3]
#bind = unix:/tmp/webircgateway.sock
#bind_mode = 0777

# Serve static files from a web root folder.
# Optional, but handy for serving the Kiwi IRC client if no other webserver is available
[fileserving]
enabled = true
webroot = /usr/share/kiwiirc/

[transports]
websocket
sockjs
kiwiirc

# Websites (hostnames) that are allowed to connect here
# No entries here will allow any website to connect.
[allowed_origins]
#*://example.com

# If using a reverse proxy, it must be whitelisted for the client
# hostnames to be read correctly. In CIDR format.
# The user IPs are read from the standard X-Forwarded-For HTTP header
[reverse_proxies]
127.0.0.0/8
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
"::1/128"
"fd00::/8"

# Connections will be sent to a random upstream
[upstream.1]
hostname = "172.0.0.1"
port = 6667
tls = false
# Connection timeout in seconds
timeout = 5
# Throttle the lines being written by X per second
throttle = 2
# Webirc password as set in the IRC server config
webirc = "********"
serverpassword = '*******'

# A public gateway to any IRC network
# If enabled, Kiwi IRC clients may connect to any IRC network (or a whitelisted
# network below) through the kiwiirc engine
[gateway]
enabled = false
timeout = 5
throttle = 2

# Whitelisted IRC networks while in public gateway mode
# If any networks are in this list then connections can only be made to these
[gateway.whitelist]
#irc.example.com
#*.example2.com

# Webirc passwords used when running in the public gateway mode
[gateway.webirc]
irc.network.org = webirc_password
irc.network2.org = webirc_password

kiwi only opens port 80 on server, Kindly help.

**Comment by amansingh14** [comment]
Hi team,
I have installed Kiwi IRC on centos, but client is not able to connect to the server. Below is my client.json and config.
client.json
{ "windowTitle": "Kiwi IRC - chat2.xxxxxx.com", "startupScreen": "welcome", "kiwiServer": "chat2.xxxxxx.com", "restricted": true, "theme": "default", "themes": [ { "name": "Default", "url": "static/themes/default" }, { "name": "Dark", "url": "static/themes/dark" }, { "name": "Coffee", "url": "static/themes/coffee" }, { "name": "GrayFox", "url": "static/themes/grayfox" }, { "name": "Nightswatch", "url": "static/themes/nightswatch" }, { "name": "Osprey", "url": "static/themes/osprey" }, { "name": "Radioactive", "url": "static/themes/radioactive" }, { "name": "Sky", "url": "static/themes/sky" } ], "startupOptions" : { "server": "chat2.xxxxxx.com", "port": 6667, "tls": false, "direct": false, "channel": "#kiwiirc-default", "nick": "web?", "greetingText": "Hello!", "infoBackground": "", "infoContent": "" } }

config.conf

1 = Debug; 2 = Info; 3 = Warn;
logLevel = 3

Enable the built in identd server (listens on port 113)
identd = false

The name of this gateway as reported in WEBIRC to IRC servers
gateway_name = "webircgateway"

A secret string used for generating client JWT tokens. Do not share this!
secret = ""

[verify]
recaptcha_secret = ""
recaptcha_key = ""

[clients]

Default username / realname for IRC connections. If disabled it will use
the values provided from the IRC client itself.
%h will be replaced with the users hostname
%i will be replaced with a hexed value of the users IP
username = "%i"
realname = "I am a webchat user"

This hostname value will only be used when using a WEBIRC password
#hostname = "%h"

The websocket / http server
[server.1]
bind = "0.0.0.0"
port = 80

Example TLS server
#[server.2]
#bind = "0.0.0.0"
#port = 443
#tls = true
#cert = server.crt
#key = server.key

If you don't have a certificate, uncomment the below line to automatically generate a
free certificate using letsencrypt.com (overrides the above cert/key options). This requires
a server running on port 80 to initially generate the certificate.
#letsencrypt_cache = ./certs

Example unix socket server
#[server.3]
#bind = unix:/tmp/webircgateway.sock
#bind_mode = 0777

Serve static files from a web root folder.
Optional, but handy for serving the Kiwi IRC client if no other webserver is available
[fileserving]
enabled = true
webroot = /usr/share/kiwiirc/

[transports]
websocket
sockjs
kiwiirc

Websites (hostnames) that are allowed to connect here
No entries here will allow any website to connect.
[allowed_origins]
#*://example.com

If using a reverse proxy, it must be whitelisted for the client
hostnames to be read correctly. In CIDR format.
The user IPs are read from the standard X-Forwarded-For HTTP header
[reverse_proxies]
127.0.0.0/8
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
"::1/128"
"fd00::/8"

Connections will be sent to a random upstream
[upstream.1]
hostname = "172.0.0.1"
port = 6667
tls = false

Connection timeout in seconds
timeout = 5

Throttle the lines being written by X per second
throttle = 2

Webirc password as set in the IRC server config
webirc = "********"
serverpassword = '*******'

A public gateway to any IRC network
If enabled, Kiwi IRC clients may connect to any IRC network (or a whitelisted
network below) through the kiwiirc engine
[gateway]
enabled = false
timeout = 5
throttle = 2

Whitelisted IRC networks while in public gateway mode
If any networks are in this list then connections can only be made to these
[gateway.whitelist]
#irc.example.com
#*.example2.com

Webirc passwords used when running in the public gateway mode
[gateway.webirc]
irc.network.org = webirc_password
irc.network2.org = webirc_password

kiwi only opens port 80 on server, Kindly help.

**Comment by prawnsalad** [comment]
This probably isn't a bug but just a configuration issue, so I'm going to close this but we can still reply as normal.

What error message do you see that suggests it isn't working?

**Comment by amansingh14** [comment]
it says not able to connect to host.

**Comment by amansingh14** [comment]
Hi any update?

**Comment by amansingh14** [comment]
Error connecting to the upstream IRCd. dial tcp 127.0.0.1:6667:connect: connection refused.
above error I am getting also no port 6667 is opened on server.

Kindly help.

**Comment by prawnsalad** [comment]
In your config.conf file:
~~~
[upstream.1]
hostname = "172.0.0.1"
port = 6667
tls = false
~~~

Is this the address to your IRC server? The error message say it isn't correct.
