### ISSUE TITLE
 Help plugin for gecos and password server

### ISSUE THREAD

**Issue by Rapman4** [kiwiirc/kiwiirc#1222]
here I come here because I tried to create a plugin to get my url: http://exemple.com:9000/?&nick=test&age=30&gender=M&City=Reims&password=PassServer
by writing a plugin:

```
kiwi.plugin('customident', function(kiwi, log) {
	function getASL(str) {
	let result = str.match(/\[(\d+|U)\/([MFOU])\/(.*)\]/);
	let sex = {'M': 'Male', 'F': 'Female', 'O': 'Other'};
	if (result && result.length === 4) {
        let age = result[1] === 'U' ? null : result[1];
        let gender = result[2] === 'U' ? null : sex[result[2]];
        let City = result[3] === 'U' ? null : result[3];
    kiwi.on('network.connecting', function(event) {
        event.network.ircClient.options.gecos = {a, s, l};
    });
	};
};
});
```
But the gecos does not change.
Moreover I seek to make understand to the kiwi the password to enter on the server

Thank you for you precious help

**Comment by ItsOnlyBinary** [comment]
in webircgateway config you need to make sure `realname =` is commented out https://github.com/kiwiirc/webircgateway/blob/master/config.conf.example#L29

also i dont think that is valid javascript seems to be something wrong with the }'s

**Comment by Rapman4** [comment]
so yes i copy the wrong sorry code the code i have in my plugin and therefore:
```
kiwi.plugin('customident', function(kiwi, log) {
	function getASL(str) {
	let result = str.match(/\[(\d+|U)\/([MFOU])\/(.*)\]/);
	let sex = {'M': 'Male', 'F': 'Female', 'O': 'Other'};
	if (result && result.length === 4) {
        let age = result[1] === 'U' ? null : result[1];
        let gender = result[2] === 'U' ? null : sex[result[2]];
        let City = result[3] === 'U' ? null : result[3];
    kiwi.on('network.connecting', function(event) {
        event.network.ircClient.options.gecos = {age, sexe, City};
    });
};
};
});

```

in the console I have no error so what I don't understand is that I can't get the information from the url if I but the code:

```
kiwi.plugin('customident', function(kiwi, log) {
    kiwi.on('network.connecting', function(event) {
        event.network.ircClient.options.gecos = "Age,Sexe,Ville";
    });
});
```

the gecos that changes well

**Comment by ItsOnlyBinary** [comment]
that code will not get ASL from the url, getASL(str) is designed to parse the gecos back to var's

**Comment by Rapman4** [comment]
okay would you have an example please

**Comment by ItsOnlyBinary** [comment]
untested and just from my mind:
```
var Misc = kiwi.require('helpers/Misc');
var sex = Misc.queryStringVal('sex');
```

**Comment by Rapman4** [comment]
It's ok thank you very much I will post the full code if it can help the world :)

**Comment by ItsOnlyBinary** [comment]
Im going to close this as its not really a kiwiirc issue. I will still get notifications if you have any more questions related to this.

You can also visit irc for help https://kiwiirc.com/nextclient/chat.freenode.net/#kiwiirc
