### ISSUE TITLE
Problem connecting domain with multiple ip's

### ISSUE THREAD

**Issue by plusin** [kiwiirc/kiwiirc#1226]
Hello, a friend has his webchat working correctly with his domain, recently we tried to assign several ips to the same domain so that the webchat is connecting with his server and with 2 other servers with different ip more, but we began to notice an error that happens some quite a few times and says: We couldn't connect to the server :( Could not connect securely

All servers are unreal4, all have port 6697 with ssl enabled, we do not have webircgateway installed because it always worked without it.

What can we modify so that this error does not appear anymore?

Thank you

**Comment by ItsOnlyBinary** [comment]
webircgateway is required to connect to raw tcp ports as they are unsupported by web browsers. The other option is to enable websocket support in the ircd and have kiwiirc connect directly to that websocket port.

generally if you get intermittent connection errors with multi server setups, its one server that is miss configured
