### ISSUE TITLE
Why is kiwiirc running as root?

### ISSUE THREAD

**Issue by ThiefMaster** [kiwiirc/kiwiirc#1229]
I installed the deb from the downloads page. After starting it, I realized that the whole thing is running as root - this is a major security risk, since a web server should NOT have root permissions except during startup (in case it needs to bind to a privileged port).

**Comment by ThiefMaster** [comment]
OK, I just found https://github.com/kiwiirc/kiwiirc_packager/issues/3#issuecomment-339150555 as a workaround, but please fix this in the web (ie add an unprivileged user and run as this user by default)

**Comment by prawnsalad** [comment]
Closing for https://github.com/kiwiirc/kiwiirc_packager/issues/3#issuecomment-339150555 instead
