### ISSUE TITLE
Big nicknames doesn't displaying correctly in nicklist

### ISSUE THREAD

**Issue by westor7** [kiwiirc/kiwiirc#1231]
Hello,

I saw that when a user uses a big nickname about 25+ nick chars then kiwiirc doesn't displaying correctly that nickname in nicklist.

I tried to use `.kiwi-nicklist-user-nick { text-overflow: ellipsis; }` but didn't fixed.

Image Example: https://i.imgur.com/fT7GyQc.png

- Thanks!

**Comment by ItsOnlyBinary** [comment]
This should now be fixed in master
