### ISSUE TITLE
Nicklist sytle overlapping avatar and nick [IE11] 

### ISSUE THREAD

**Issue by ItsOnlyBinary** [kiwiirc/kiwiirc#1243]
![image](https://user-images.githubusercontent.com/558946/75192661-8fce1480-574c-11ea-9760-229acb7bd1fc.png)

**Comment by ItsOnlyBinary** [comment]
Seems to be caused flex: 0; here:by https://github.com/kiwiirc/kiwiirc/commit/b168c37e845953a0857983fd7a6988bc2057a772#diff-465b9baf67d6acf808008c8a18a29eb5R106

**Comment by AllanOcelot** [comment]
* General anger towards IE 11 *

**Comment by ItsOnlyBinary** [comment]
IE11 cannot be supported forever
