### ISSUE TITLE
Undo close channel / List of recently closed channels

### ISSUE THREAD

**Issue by stdedos** [kiwiirc/kiwiirc#1248]
It might be helpful to maintain a MRU closed channel list, either by itself (so that I don't need to have channels connected in order to have them visible) or additionally with the option to "undo" closing a channel (ala Ctrl+Shift+T for browser tabs)

**Comment by ItsOnlyBinary** [comment]
Closing of channels now presents a confirmation dialogue to prevent accidental closes. (configurable)

Hopefully that negates the need for this feature

https://github.com/kiwiirc/kiwiirc/pull/1579

**Comment by stdedos** [comment]
That could sound twice as annoying 😂
On the other hand it has the benefit of not loosing the ephemeral channel history.

Oh well. Actual implementation/UX will tell
