### ISSUE TITLE
Everyone is a bot

### ISSUE THREAD

**Issue by CoryChaplin** [kiwiirc/kiwiirc#1262]
When running a whois, either from the userlist or from a command line, every user is classified as a bot.
I'm using inspircd 2.
Example below.

<img width="1677" alt="Kiwi_IRC_-_The_web_IRC_client-7" src="https://user-images.githubusercontent.com/5139669/77903664-83753400-7283-11ea-8ddd-a28188358180.png">

**Comment by ping86** [comment]
Can you send the raw log?

Thanks.

**Comment by H7-25** [comment]
It's because the geoip module is using a wrong numeric on inspircd2, if you don't plan to upgrade to inspircd3 you have to change the numeric on that module like in the new one.

**Comment by ItsOnlyBinary** [comment]
Numeric conflict not a kiwiirc issue
