### ISSUE TITLE
Issue with latest build warnings

### ISSUE THREAD

**Issue by Shillos** [kiwiirc/kiwiirc#1274]
I have encountered some odd warnings during yarn && yarn build on the latest kiwiirc build.

yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.99s.
yarn run v1.22.4
$ npm run translate && vue-cli-service build
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--158677272420                                                                                                                                3-0.8697810693630574/node but npm is using /root/.nvm/versions/node/v12.16.2/b                                                                                                                                in/node itself. Use the `--scripts-prepend-node-path` option to include the pa                                                                                                                                th for the node binary npm was executed with.

> kiwiirc@1.4.0 translate /var/www/html/kiwiirc
> node build/webpack/locales.js

✔ translating languages...

⠧  Building for production...

 WARNING  Compiled with 2 warnings                                  1:12:44 PM

 warning

asset size limit: The following asset(s) exceed the recommended size limit (97                                                                                                                                7 KiB).
This can impact web performance.
Assets:
  static/plugins/plugin-emoji.min.js (1.56 MiB)

 warning

webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to                                                                                                                                 lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

  File                                      Size             Gzipped

  dist/static/plugins/plugin-emoji.min.j    1600.01 KiB      235.38 KiB
  s
  dist/static/plugins/plugin-conference.    92.00 KiB        24.18 KiB
  min.js
  dist/static/plugins/plugin-emoji-preli    3.84 KiB         2.16 KiB
  m.min.js
  dist/static/js/vendor.3b4ab93c.js         873.61 KiB       284.76 KiB
  dist/static/js/app.94fbe511.js            425.75 KiB       102.24 KiB
  dist/static/plugins/plugin-nickserv.js    18.23 KiB        4.92 KiB
  dist/static/css/app.064ed753.css          83.21 KiB        13.79 KiB
  dist/static/themes/radioactive/theme.c    27.68 KiB        5.76 KiB
  ss
  dist/static/themes/common/base.css        24.73 KiB        3.82 KiB
  dist/static/themes/nightswatch/theme.c    8.72 KiB         1.83 KiB
  ss
  dist/static/themes/elite/theme.css        6.28 KiB         1.45 KiB
  dist/static/themes/dark/theme.css         5.84 KiB         1.34 KiB
  dist/static/themes/grayfox/theme.css      4.29 KiB         1.10 KiB
  dist/static/themes/coffee/theme.css       4.27 KiB         1.12 KiB
  dist/static/themes/osprey/theme.css       3.84 KiB         0.98 KiB
  dist/static/themes/sky/theme.css          3.37 KiB         0.93 KiB
  dist/static/themes/default/theme.css      3.14 KiB         0.86 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deploy                                                                                                                                ment.html

Done in 41.24s.

I managed to resolve one of the problems by using 

`npm config set scripts-prepend-node-path true` 

The other `npm run translate && vue-cli-service build` I could not seem to get it working it came out to be : -bash: vue-cli-service: command not found
So, what I'm I missing here? Shouldn't this be automated within kiwiirc latest build yarn.lock or something?

**Comment by Shillos** [comment]
I used `npx vue-cli-service help` and the commands where there but when i run it using `npm run translate && vue-cli-service build` it showed the same output: -bash: vue-cli-service: command not found... strange!

**Comment by prawnsalad** [comment]
Have you tried just running yarn? `yarn build`?

**Comment by Shillos** [comment]
i used `npx vue-cli-service build` and no warnings at all, but when running yarn && yarn build again it showed up as saying :

yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.71s.
yarn run v1.22.4
$ npm run translate && vue-cli-service build

> kiwiirc@1.4.0 translate /var/www/html/kiwimini
> node build/webpack/locales.js

✔ translating languages...

⠏  Building for production...

 DONE  Compiled successfully in 13419ms                             3:48:35 PM

  File                                      Size             Gzipped

  dist/static/js/vendor.3b4ab93c.js         873.61 KiB       284.69 KiB
  dist/static/js/app.ade4f16a.js            425.75 KiB       102.22 KiB
  dist/static/css/app.79654e14.css          83.21 KiB        13.79 KiB
  dist/static/themes/radioactive/theme.c    27.68 KiB        5.76 KiB
  ss
  dist/static/themes/common/base.css        24.73 KiB        3.82 KiB
  dist/static/themes/nightswatch/theme.c    8.72 KiB         1.83 KiB
  ss
  dist/static/themes/elite/theme.css        6.28 KiB         1.45 KiB
  dist/static/themes/dark/theme.css         5.84 KiB         1.34 KiB
  dist/static/themes/grayfox/theme.css      4.29 KiB         1.10 KiB
  dist/static/themes/coffee/theme.css       4.27 KiB         1.12 KiB
  dist/static/themes/osprey/theme.css       3.84 KiB         0.98 KiB
  dist/static/themes/sky/theme.css          3.37 KiB         0.93 KiB
  dist/static/themes/default/theme.css      3.14 KiB         0.86 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html

Done in 16.46s.

Looks alright just the message about $ `npm run translate && vue-cli-service build`

**Comment by Shillos** [comment]
I bet i just have to ignore that but all warnings are basically maybe from the plugins as i saw with emoji plugin had some sort of warning.

**Comment by Shillos** [comment]
The only warnings are these : 

 WARNING  Compiled with 2 warnings                                  3:53:46 PM

 warning

asset size limit: The following asset(s) exceed the recommended size limit (977 KiB).
This can impact web performance.
Assets:
  static/plugins/plugin-emoji.min.js (1.56 MiB)

 warning

webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

Otherwise, it works ok.

**Comment by prawnsalad** [comment]
That's expected then. It now compiles any .js files it finds in the static/ folder and warns you if they are a little large - which the emoji plugin is. All is good :)
