### ISSUE TITLE
URL identification issues

### ISSUE THREAD

**Issue by stdedos** [kiwiirc/kiwiirc#1285]
> [...] (which is not clearly mentioned in https://git-scm.com/docs/pretty-formats), [...]

is typed as:

> [...] (which is not clearly mentioned in <https://git-scm.com/docs/pretty-formats),> [...]

**Comment by prawnsalad** [comment]
I'm not sure what this is about?

**Comment by stdedos** [comment]
For the rich-format parsing done by KiwiIRC

I am about to open one other issue, so I would appreciate if you would tell me how to more carefully phrase my bug report

**Comment by prawnsalad** [comment]
I've adjusted this now so that common punctuation is removed before checking for opening/closing brackets. Thanks for the report!

![image](https://user-images.githubusercontent.com/725880/81477357-59fae100-920f-11ea-8834-35ce95a6cb83.png)

**Comment by stdedos** [comment]
Thank you for acting on this 😄 

Some food for thought:
* I see no unit tests. Since you are already doing them manually ... why not automate them?
  I won't go into guild wars on "which framework is best", but anything that would allow you to make that image into a "machine verifiable" test would be nice (for you and fellow contributors)
  And then, you might want to consider Github actions (should be free for your open-source project)
* The last two seem to be failing your cause:
  `while` this `url[url.length - 1]` character can be found in `punctuation` array, _don't count that character as part of the URL_.
  While the 3rd-last excludes `;:`, your last two accept `;`,`:` (and then reject `)`)
