### ISSUE TITLE
Text color temporarily resets to black when text entry field loses focus

### ISSUE THREAD

**Issue by utoxin** [kiwiirc/kiwiirc#130]
Text color is temporarily reset after an empty text input loses focus. 

Steps to reproduce:
1. Set text color.
2. Send something. Note that the text is the color you selected.
3. Click out of the text input, change channels, or something else to lose text area focus.
4. Click back in, send something. Note that the text is black again.
5. Send another thing without losing focus on text entry. Note that text is the color you selected again.

**Comment by ItsOnlyBinary** [comment]
This still seems to be an issue, although it is somewhat improved
