### ISSUE TITLE
904 ERR_SASLFAIL produces no error messages

### ISSUE THREAD

**Issue by slingamn** [kiwiirc/kiwiirc#1300]
As far as I can tell, there's no visible error message on failure to authenticate with SASL. This makes it harder to debug authentication issues.

**Comment by slingamn** [comment]
This is with `"disconnectOnSaslFail": false` in the config --- still seems like in principle there could be an error message, though.

**Comment by prawnsalad** [comment]
It now shows auth errors on the startup screen and also only closes the connection if it was in the connecting state.
