### ISSUE TITLE
embeded images are always reloading after changing rooms

### ISSUE THREAD

**Issue by kw-user123** [kiwiirc/kiwiirc#1307]
All previously loaded embedded images are getting reloaded each time I switch chat windows (to chat room or to private message). I can see network requests in browser network debug screen and it seems they are cached but it is very slow refreshing when you change chat windows.

Also after images loads again, scroll bar many times stays at the middle.

On auto-loaded embedded image, scroller does not scroll down until new message arrives but it would be nicer if it would scroll on completed loaded image.

**Comment by n1ce-0ne** [comment]
any fixes for this, it does break the embely code, i find on opera browser when they refresh they break to a white embedly box with no content

**Comment by ItsOnlyBinary** [comment]
This appears to have been resolved with changes to auto scrolling
