### ISSUE TITLE
/ctcp <nick> version is NOT displayed at all

### ISSUE THREAD

**Issue by KoraggKnightWolf** [kiwiirc/kiwiirc#131]
When a user utilizes /ctcp <nick> version on a user utlizing kiwiirc.com/nextclient then there is no notification (no notice, nowhere) sent to the kiwi user that someone used /ctcp on them. This issue has been tested and confirmed to at least occur on UnrealIRCd (4.0.15)

**Comment by prawnsalad** [comment]
Note to self: This is related to irc-framework not triggering the `ctcp request` event for `VERSION` or `CLIENTINFO`

**Comment by prawnsalad** [comment]
Now fixed in master. Thanks!
