### ISSUE TITLE
Bug when change channel

### ISSUE THREAD

**Issue by ping86** [kiwiirc/kiwiirc#1314]
You can view this issue when change channel in kiwiirc. 

This problem is in master branch. Go to status page and returns to channel tab.

Tested on chrome android.

![Screenshot_20200510-222432](https://user-images.githubusercontent.com/1170773/81509828-adebef80-930d-11ea-9f91-2858d9abb0f4.jpg)

Thanks.

**Comment by webvigo** [comment]
Confirmed 😞

**Comment by ping86** [comment]
Duplicated issue: https://github.com/kiwiirc/kiwiirc/issues/1343
