### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by zekirdekorg** [kiwiirc/kiwiirc#1315]
Hello, 

/etc/kiwiirc/ there was no such problem in the place where it was installed. 

**/usr/share/kiwiirc_master#  <-- after upgrading to the current version** 

I started having the problem below and I don't want to remove this module "m_requirectcp"

how do i fix this problem?

 thanks 

i use inspircd2.0 

> -irc.zekirdek.org- *** REQUIRECTCP: Suspicious connection on port 6697 (class main) from MisafirX!5f0ae9f6@167.172.63.235 (167.172.63.235) was blocked by m_requirectcp

[http://irc.ircop.net](url)

**Comment by zekirdekorg** [comment]
I also tried here

https://kiwiirc.com/nextclient/irc.zekirdek.org 

Closing link: (Guest65@107.161.19.109) [You have been blocked!Please get a better client.]

**Comment by ItsOnlyBinary** [comment]
Seems this is an issue with irc-framework expecting CTCP Version from a user and not the server

```
[S] :irc.zekirdek.org PRIVMSG MisafirX :VERSION
[C] NOTICE :VERSION Kiwi IRC
[S] :irc.zekirdek.org 461 MisafirX NOTICE :Not enough parameters.
```

https://github.com/kiwiirc/irc-framework/blob/master/src/commands/handlers/messaging.js#L81
