### ISSUE TITLE
parent window jumps when new message comes in irc channel inside iframe

### ISSUE THREAD

**Issue by mohan43u** [kiwiirc/kiwiirc#1317]
I use kiwiirc inside my website using iframe. whenever a new message arrives, webpage jumps automatically to show kiwiirc iframe.

Attached patch https://github.com/kiwiirc/kiwiirc/pull/1316 provides fix to this issue

**Comment by ChatFacile** [comment]
I have the same problem both from pc and smartphone, any word typed in public makes the screen jump up, this if kiwiirc is put in an iframe

**Comment by mohan43u** [comment]
This issue was fixed in the current master (see https://github.com/kiwiirc/kiwiirc/pull/1316). I'm not sure it is released yet.

**Comment by Shillos** [comment]
#1316 has been merged as it says there! Then just git pull and it should be ok!
