### ISSUE TITLE
message order is mixed if local clock is not correct

### ISSUE THREAD

**Issue by kw-user123** [kiwiirc/kiwiirc#1319]
If client system clock is couple of minutes different then the server time, messages appear several lines above the last shown.

You must first send one message and then new messages that comes from other users you will see above your line, not after.

This is also causing the problem that counter of new (private) messages is now showing correctly.

Using current kiwi nextclient.

**Comment by ItsOnlyBinary** [comment]
This should now be fixed, if your using unrealircd and still experiencing this issue please update your ircd
