### ISSUE TITLE
ZNC: "Other networks on this ZNC account will be listed in the network list" - How?

### ISSUE THREAD

**Issue by simonszu** [kiwiirc/kiwiirc#132]
Hi,

i was wondering: How does this work? I have a ZNC connected to 4 different networks. When i add my first network to Kiwiirc, and select ZNC as the connection type, i enter hostname, username, one of the networks, and the password. It connects to this network only. No other networks show up in the left sidebar. 

When i leave out the network field, it connects to the alphabetically first network, but i think this is because of ZNC logic. 

How can i achieve the connection to all 4 ZNC networks? They are configured in the same user account in ZNC. 

I would be happy if i had to configure each network manually, but i cannot figure out how to add a second IRC connection in Kiwi. The setting when clicking on the network name are network specific settings only. And the settings menu behind the cog wheel only has "General" and "Aliases" option, no option to add another network. 

I appreciate your work very much, but generally i think, the new kiwiirc lacks some documentation. Besides my UX issues, the wiki only has documentation for the client.json config file, but not for the config.conf file. And the general architecture is a little confusing. If kiwi is a webclient for IRC, why does it differentiate between a server config and a client config?

**Comment by prawnsalad** [comment]
Hey there, I agree with your points.

This new version of Kiwi is still very fresh so documentation is getting written at the moment. Without them everything does look much more complicated than they actually are as we now support different use cases. (Quick outline though - the kiwi server makes the actual IRC connection which requires more security thoughts, while the front-end can now be hosted anywhere, your CDN even).

As for ZNC, which version of ZNC are you using? When kiwi connects and detects any ZNC related traffic it will trigger commands to *status to list any networks. It parses the ZNC output from there to create a list of networks. I have tested it with ZNC versions < 1.7 without issue so far.

Another way you might prefer is to use the "personal" startup screen which will remember your connections between page reloads. https://github.com/kiwiirc/kiwiirc/wiki/Startup-screens

**Comment by simonszu** [comment]
I am using "ZNC 1.7.x-nightly-20151226-b17481b7 " (Honestly, i have no idea why especially this nightly version, it was a quite long time ago when i installed znc). I already have set up the personal startup screen. 
If you can tell me how to add a second network, i can workaround the ZNC issue. I don't want to downgrade ZNC, because i don't know if it's downgradeable.

**Comment by prawnsalad** [comment]
It looks like ZNC has changed it's language structure in 1.7 since it now supports transaltions so that will throw the network detections off :(

If you use the "customServer" startup screen on your own kiwi instance (or https://kiwiirc.com/nextclient on the hosted version) then you can click the + icon above the networks to add each one.

**Comment by prawnsalad** [comment]
Closing this as ZNC 1.7 makes it impossible to list networks as we previously did unfortunately.
