### ISSUE TITLE
Documentation - Is it possible to have more explanations / examples about plugins

### ISSUE THREAD

**Issue by crazycatdevs** [kiwiirc/kiwiirc#1323]
This is not an issue but a request.
I made a plugin for the previous version of kiwiirc and I want to redo it for the actual version, unless I can't upgrade my kiwi.
The plugin documentation is really poor, and I can't understand how to do my new version.
The previous plugin was:
```
kiwi.events.on('loaded', function() {
    if ("nick" in getUrlVars() && getUrlVars()["nick"]!='') { $('#server_select_nick').val(getUrlVars()["nick"]); }
    if ("channel" in getUrlVars() && getUrlVars()["channel"]!='') { $('#server_select_channel').val('#'+getUrlVars()["channel"]); }
    if ("nspass" in getUrlVars() && getUrlVars()["nspass"]!='') { $('#server_select_password').val(getUrlVars()["nspass"]); nspass = $('#server_select_password').val(); }
    if (getUrlVars()["autoconnect"] == 1) {
        $('#kiwi .server_select').css('display', 'none');
        $('.server_details button').click();
    }
});

network.on('connect', function(event, data) {
    if (nspass == '' && network.get('password')!='') { nspass = network.get('password'); }
    if (nspass != '') { network.msg('NickServ', 'identify '+nspass); }
});
```
I made some tries I didn't succeed.
The purpose of this plugin is to use an external form to automatically connect the user and send password to nickserv. 

Is it possible to have some tips about how to adapt this plugin, so I can understand how the mechanic has changed ?

Regards

**Comment by ItsOnlyBinary** [comment]
Most of this is already built in to kiwiirc `http://kiwi.example.com/?nick=someNick#chan1,#chan2`

The part that is not is password due to the security issues regarding putting a password in the url as plain text. The best solution is to have a php handler that your form posts to that then creates a client with with the config injected into the page.

see here for injecting the config: https://github.com/kiwiirc/kiwiirc/wiki/Configuration#json-string-directly-in-the-page

base your index.php off the index.html that gets built into `dist/`

**Comment by crazycatdevs** [comment]
I'd seen some things can be passed, and I use a method to crypt the password.
My big troubles are:
- how to force the auto-connect (startupOptions.autoConnect=true) from my plugin
- how can I do a /msg nickserv ? I didn't find the equivalent to network.msg in the plugin methods

**Comment by ItsOnlyBinary** [comment]
startupOptions.autoConnect can only be set via your config.json there is no support for it via the url
startupOptions.password would be used to SASL or nickserv identify depending if SASL is enabled

**Comment by crazycatdevs** [comment]
Ok, gonna try with php file to manage that

**Comment by crazycatdevs** [comment]
It's not far from working.
When I try to create the `<script name=kiwiconfig>{"windowTitle":"my test"}</script>`, I get error (**unexpected token: ':'**).
And sometimes (with more complex options): **semi-colon missing**

When I use the `<meta name="kiwiconfig" content="static/my.json">` it works.

**Comment by ItsOnlyBinary** [comment]
for <script> it needs to be a js object so slightly different than json. maybe take a look here for how it should look https://github.com/kiwiirc/kiwiirc/blob/master/src/res/configTemplates.js#L21

what you have shown here should not be giving unexpected token error, if it was multiple options it might have been you was missing a comma

**Comment by crazycatdevs** [comment]
I'll try to find how I get the token error, peharps was it whan I've tried `startupOptions.autoConnect: true;`
But is there an error in [the doc](https://github.com/kiwiirc/kiwiirc/wiki/Configuration#json-string-directly-in-the-page)?
I just tested what is given as example and it failed...

**Comment by ItsOnlyBinary** [comment]
Seems i give some bad info. <script name="kiwiConfig"> does need to be perfect JSON. It will always give the error `Uncaught SyntaxError: Unexpected token ':'`

This works for me: https://gist.github.com/ItsOnlyBinary/5f6fbb19ad5e2254318a7063015fefc3

If you want to go the json route you can check your json is valid here: https://jsonformatter.curiousconcept.com/

the other option is to write it into a function like: https://gist.github.com/ItsOnlyBinary/e65849e919b00849928b684e43b6e648

**Comment by crazycatdevs** [comment]
I'll test, but did you use these codes inline (into the index.html file) like explained in the json injection ?
As I said previously: _Note that the options I put are a copy of the working .json file, without adding or removing anything._ So my test is equivalent to your first example, and it failed. And my json is ok.

**Comment by ItsOnlyBinary** [comment]
I tested both gist's in my index.html  the first one gave the error about unexpected token but did still worked

**Comment by ItsOnlyBinary** [comment]
config.json uses JSON5 so is quite forgiving on being perfect json. things like comma dangles and comments do not bother it. but the inline json was still using normal JSON so it had to be perfect or it would fail.

I master does now have the fix for using JSON5 when loading inline configs

**Comment by ItsOnlyBinary** [comment]
I'm going to close this issue, but feel free to comment in it if you need more help/info i will still be notified.
