### ISSUE TITLE
Can you override configuration of embedded "nextclient"?

### ISSUE THREAD

**Issue by enceladus** [kiwiirc/kiwiirc#1330]
I followed the [embed guide here](https://github.com/kiwiirc/kiwiirc/wiki/Linking-to-and-Embedding-Kiwi-IRC) and tried to change the config (I'd like to pull in a custom theme). But it seems that this is not currently possible? I can't find anyone else asking this question.

**Comment by prawnsalad** [comment]
We don't support custom themes on kiwiirc.com as it can be used for abuse. You will need to host kiwiirc yourself to add your own themes.
