### ISSUE TITLE
Network/Server-List doesn't get cleared on new connect (reloading kiwi)

### ISSUE THREAD

**Issue by hnz101** [kiwiirc/kiwiirc#1335]
Hi,
I just updated to the latest git master and since then the Network list doesn't get cleared when reloading the site / reconnecting.
The old connections add up as disconnected in the list and there is no way to close them.
(Don't know if this makes a difference, but I am connecting to an ZNC-Bouncer)

![kiwi_networklist](https://user-images.githubusercontent.com/4280171/82800746-78eaab80-9e7c-11ea-92be-6f8b4a40b9cc.png)

**Comment by prawnsalad** [comment]
Could you paste your config.json file somewhere so we can take a look?

**Comment by hnz101** [comment]
> 
> 
> Could you paste your config.json file somewhere so we can take a look?

here is my config.json:
```
{
         "windowTitle": "Kiwi IRC",
         "startupScreen": "znc",
         "kiwiServer": "https://gateway.myurl.com/kiwiirc/",
         "restricted": true,
         "theme": "default",
         "themes": [
                 { "name": "Default", "url": "static/themes/default" }
         ],
         "startupOptions" : {
                 "network": "myZncNetworkName",
                 "channel": "#mydefaultchannel",
                 "username": "myZNCusername"
         },
         "embedly": {
                 "key": ""
         }
 }
```

**Comment by codeurimpulsif** [comment]
I have the same issue while reloading Kiwiirc.

**Comment by ItsOnlyBinary** [comment]
the following config.json option should help with this issue
```
"startupOptions" : {
    "remember_buffers": false,
}
```

The way networks, network settings and buffer settings are stored in kiwi does need a rethink/rewrite and is on my todo list

**Comment by hnz101** [comment]
> the following config.json option should help with this issue
> 
> ```
> "startupOptions" : {
>     "remember_buffers": false,
> }
> ```

Yes, that worked. Bummer I didn't tried that before diving into the code.
