### ISSUE TITLE
Add /disconnect as an alias to /quit

### ISSUE THREAD

**Issue by stdedos** [kiwiirc/kiwiirc#1336]
It feels more "fluent" to Connect/Disconnect than quit (if I want to quit, the action feels like I would be closing the browser tab), and search https://www.google.com/search?q=irc+disconnect gives results (instead e.g. of pointing to irc quit)

**Comment by prawnsalad** [comment]
`/quit` is definitely more IRC standard but no harm in adding `/disconnect` too. It's now in master, thanks!

**Comment by stdedos** [comment]
Thank you for satisfying my weirdness 😃😉 

How does your deployment work? Is it CI/CD from `master` to production, or something else?

**Comment by stdedos** [comment]
Dammit, one more issue and I would have had taken the l33t issue 😂

**Comment by prawnsalad** [comment]
I just had to steal the 1337 ;)

For kiwiirc.com I have separate deployment scripts detached from any github CI. I play it safer than throwing master live instantly but this will probably get deployed later today.

**Comment by Shillos** [comment]
I thought that was a strange issue open closed cos of 1337 (leet) 🤣
