### ISSUE TITLE
1337

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/kiwiirc#1337]
1337

**Comment by stdedos** [comment]
_**NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO**_
![desperate no](https://media.giphy.com/media/bGyKPJ40CDJja/giphy.gif)
![desperate no](https://media.giphy.com/media/2VAateam5qzde/giphy.gif)
![desperate no](https://media.giphy.com/media/26ybvMCkSlJxlT2rS/giphy.gif)
