### ISSUE TITLE
Major sidebar mess on mobile

### ISSUE THREAD

**Issue by CoryChaplin** [kiwiirc/kiwiirc#1343]
On the mobile, the sidebars get totally messed up when switching channels making Kiwi near impossible to use.
Here's a sample taken from https://builds.kiwiirc.com/kiwiirc/master/ with Chrome in a 470x706 window.

![mobile-sidebar-mess](https://user-images.githubusercontent.com/5139669/83361839-9d6aea00-a38c-11ea-8bbe-5d42914cc2d9.gif)

**Comment by bogdomania** [comment]
yeah, if u tap on the people icon, it will act normal, no biggie.

**Comment by bogdomania** [comment]
Is this a duplicate of #1314 ?

**Comment by CoryChaplin** [comment]
Definitely

**Comment by xam60** [comment]
Putting a setTimeout on the setActiveBuffer function of StateBrowserNetwork seems to be a working workaround 
`setActiveBuffer: function switchContainer(buffer) {
// Clear any active component to show the buffer again
this.$state.$emit('active.component', null);
if (this.$state.ui.is_narrow) {
this.$state.$emit('statebrowser.hide');
setTimeout(() => {
this.$state.setActiveBuffer(buffer.networkid, buffer.name);
}, 200);
} else {
this.$state.setActiveBuffer(buffer.networkid, buffer.name);
}
},`

**Comment by CoryChaplin** [comment]
This regression was introduced during refactoring of state, shortly after this https://github.com/kiwiirc/kiwiirc/commit/1473d1b4f4bfe7363c353145e75d4d0f6f4628ee

**Comment by ItsOnlyBinary** [comment]
Its caused by this commit https://github.com/kiwiirc/kiwiirc/commit/a7bb8e1f3b0ad40b0117c7432e6635f71e3d4765

**Comment by westor7** [comment]
A short reproduce video: https://bit.ly/2AZpb26

**Comment by prawnsalad** [comment]
Fixed in master :)
