### ISSUE TITLE
New PM blocking not working

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/kiwiirc#1379]
**Describe the bug**
When `Block new private messages` is enabled, I still get private messages

**To Reproduce**
* Enable `Block new private messages` in app settings
* Send a message to yourself from another client

**Expected behavior**
* Not to get a new PM

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by H7-25** [comment]
It look work, i think it has just been tested sending a message from an ircop user

**Comment by ItsOnlyBinary** [comment]
This feature is working correctly, your test sender must have been shared chan op or ircop
