### ISSUE TITLE
Necesito ayuda para la configuración 

### ISSUE THREAD

**Issue by MuriielAnahi** [kiwiirc/kiwiirc#1384]
Llevo días buscando como lograr configurar kiwiirc con mis imágenes, logo y un reproductor.. Algún tutorial que me ayude a hacer correr el código y luego poder montarlo en mi página web?

**Comment by ItsOnlyBinary** [comment]
I've been looking for days how to configure kiwiirc with my images, logo and a player .. Any tutorial to help me run the code and then be able to mount it on my web page?

**Comment by ItsOnlyBinary** [comment]
Most of the documentation for kiwiirc is here: https://github.com/kiwiirc/kiwiirc/wiki/Configuration

To make the changes your seeking you would have to host your own kiwiirc, Packages to help install kiwiirc on your own server can be found here: https://kiwiirc.com/downloads

to set an image on the welcome screen you need to use:
```
"startupOptions" : {
    "infoBackground": "http://example.com/background.png"
}
```

to add a logo you would need to create a plugin or edit the source
