### ISSUE TITLE
reCaptcha not working when connecting trough websocket

### ISSUE THREAD

**Issue by DjSxX** [kiwiirc/kiwiirc#1387]
reChaptcha is not showing when "direct: true" is enabled

**Comment by prawnsalad** [comment]
The captcha will only show if the server supports it. I'm assuming you're connecting directly to the IRC network and not a webircgateway server?

**Comment by DjSxX** [comment]
Yes, connecting trough websocket without webircgateway, is it possible to get reCaptcha working without the gateway? I'm running unrealircd 5.0.5.1

**Comment by prawnsalad** [comment]
Captcha requires a server-side part to verify the user. As far as I know it's only webircgateway that implements this
