### ISSUE TITLE
Transparent workspace and messagelist in transparent iframe

### ISSUE THREAD

**Issue by booyaamps** [kiwiirc/kiwiirc#1390]
First of all, thank you for this lovely software. It really fills a need for our organization and has been invaluable to us!

I feel that the ability to make the messagelist and side panels transparent could really assist some users. 
We'd like to overlay the chat over a training video, so people can still see the chat through the iframe.

Maybe this is do-able with a custom theme?

**Comment by ItsOnlyBinary** [comment]
This would be achievable via a plugin style element but would take some time to figure out what needs to be made transparent.

I suggest using your browser inspect function to dig through the dom and find what classes need to be made transparent

https://github.com/kiwiirc/kiwiirc/blob/master/static/plugins/customise.html

**Comment by booyaamps** [comment]
Ahhhhh, excellent!
