### ISSUE TITLE
[howto] change nick style in some channels userlist

### ISSUE THREAD

**Issue by crazycatdevs** [kiwiirc/kiwiirc#1395]
I'm looking for the way to change nicks style (append country flag) in some channels userlist.
The idea is to have some channels, enabled in configuration or hard-coded, doesnt' mind, where I can change the style of the nick, based on the realname (country code is the last part of realname, with a / before)
I began to create static/plugins/countryflags.html like this:
```
<style>
.kiwi-nicklist-user-nick .fr:after {
	content: "";
	background: url("icon-fr.jpg") no-repeat;
	width: 12px;
	height: 12px
}
.kiwi-nicklist-user-nick .gb:after {
	content: "";
	background: url("icon-gb.jpg") no-repeat;
	width: 12px;
	height: 12px
}
</style>
<script>
kiwi.plugin('countryflags', function(kiwi, log) {
	kiwi.on('irc.join', function (event, network) {
		let reg = /\/([a-zA-Z]{2})$/;
		let country = event.gecos.match(reg);
		if (country.length == 2) {
 			// add country[1] to class
		}
	});
});
</script>
```
So my two big troubles:
1. I don't know how to check if the channel is one where the plugin is enabled (don't know how to get the joined channel name)
2. I don't know how I can add the new class to username in userlist

Thanks by advance

**Comment by ItsOnlyBinary** [comment]
I suggest looking into kiwi.replaceModule() https://github.com/kiwiirc/kiwiirc/wiki/Plugins

Then you can replace NicklistUser.vue with a customised version of it
https://github.com/kiwiirc/kiwiirc/blob/master/src/components/NicklistUser.vue

You might find plugin-asl as a good example for replacing components, also as a template for working webpack with vue support
https://github.com/ItsOnlyBinary/kiwiirc-plugin-asl/blob/master/src/plugin.js#L19

**Comment by crazycatdevs** [comment]
Well, I saw your plugin before opening the issue, but not really sure to understand everything :(
Can I build the plugin (`yarn build`) on any machine and then upload the resulting js (rethoric question, I'll try by myself) ? If yes, I think I'll try modify your plugin which seems enough complete,

**Comment by ItsOnlyBinary** [comment]
yes can build on any machine and copy files inside dist/ to your plugins folder

**Comment by crazycatdevs** [comment]
Request can be forget, I'm trying plugin-asl and seems doing the job.
