### ISSUE TITLE
(Dis)Connected timestamp does not appear

### ISSUE THREAD

**Issue by stdedos** [kiwiirc/kiwiirc#1396]
It would be nice if it was hoverable (like all the other messages) and not only on copy-paste

**Comment by prawnsalad** [comment]
We've actually removed this message entirely in master, since the connection status is already available at the top of the page

**Comment by stdedos** [comment]
Too bad ... IRC is already kinda weird to use, and now I'll completely loose track on when I was signed in / listening, and when not.
