### ISSUE TITLE
List/tabs display

### ISSUE THREAD

**Issue by CoryChaplin** [kiwiirc/kiwiirc#14]

**Comment by AllanOcelot** [comment]
@prawnsalad  - empty issue, can we close?.

**Comment by prawnsalad** [comment]
Nope, this is referring to tabs along the top vs tabs down the side which needs to be looked at in future

**Comment by ItsOnlyBinary** [comment]
this and #158 are explaining the same feature, so I'm closing this one due to the other having a better description and pictures
