### ISSUE TITLE
issue in the block to change nick

### ISSUE THREAD

**Issue by GaMbiiTo** [kiwiirc/kiwiirc#1401]
when you choose to change your nickname if you do not fill in the empty space and type accept, that window is locked obstructing you to press any button again

**Comment by n1ce-0ne** [comment]
did you know that clicking the settings cog icon twice it clears it ?

**Comment by GaMbiiTo** [comment]
Yes, I know, you want to tell me that this is normal then?

**Comment by AllanOcelot** [comment]
@GaMbiiTo this is a good find - thank you. 
I'll look into this when I next have free time.
