### ISSUE TITLE
Input Box larger then text field

### ISSUE THREAD

**Issue by realredknight** [kiwiirc/kiwiirc#1405]
**Describe the bug**
The visual box for Text input is larger than the input form field. So you can click in the box without setting focus to the text input. If clicked on the wrong spot, instead of Text hotkeys are accepted, producing unwanted behaviour

**To Reproduce**
1. open any given kiwichat instance (e.g. freenode)
2. Move mouse pointer to the upper boundary of the input field
3. Mouse pointer changes from cursor to pointer (see screenshot) while still inside the box
4. click

**Expected behavior**
Focus the input field

**Screenshots**
![kiwiirc_input](https://user-images.githubusercontent.com/1524293/90173834-5003f380-dda5-11ea-8e44-b542630a98f3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser Chrome
 - Version 84 and before
 - Also seen on Firefox

**Comment by CoryChaplin** [comment]
This should be fixed in #1472
