### ISSUE TITLE
websocket ssl connection failed 

### ISSUE THREAD

**Issue by Eyecu** [kiwiirc/kiwiirc#1414]
**Websocket SSL connection between kiwiirc and server fails**

I have kiwiirc running on my webserver with the IRC server running on a different VPS. I have compiled kiwiirc from source and put it on my webserver. The webserver has valid ssl via letsencrypt.  IRC server also has a valid ssl via letsencrypt. 
I've configured kiwiirc to direct connect to the irc server using tls port 7003, irc server is listening to that port with gnutls and configured for websocket (inspircd-3.7.0). 
When i load the webchat and try and connect i get the following in the developer console
websocket.js:232 WebSocket connection to 'wss://cs1.coders-irc.net:7003/' failed: WebSocket opening handshake was canceled

The only way i can get it to connect is to visit https://cs1.coders-irc.net:7003 in a new browser tab (note no webserver running on the irc vps) once i do this i can go back to the kiwiirc tab and connect just fine. 

server details
https://www.coders-irc.net/chat   <---kiwiirc on main server running on decicated server montreal quebec
cs1.coders-irc.net  <----irc server setup for websocket connection running on linode in newark nj

**Comment by ItsOnlyBinary** [comment]
In your <sslprofile> for websockets make sure to set requestclientcert to "no"

also make sure you set `<wsorigin allow="">` it can be "*" for all

https://docs.inspircd.org/3/modules/ssl_gnutls/
https://docs.inspircd.org/3/modules/websocket/

**Comment by ItsOnlyBinary** [comment]
I think you need to update the kiwiirc client files @mcristi17

**Comment by mcristi17** [comment]
and how do i do that?

**Comment by mcristi17** [comment]
i took kiwiirc from here :)

**Comment by ItsOnlyBinary** [comment]
come see me in irc so we are not attacking the inboxes of the other people in this thread

**Comment by mcristi17** [comment]
ok
