### ISSUE TITLE
Double msg is send when typing in color

### ISSUE THREAD

**Issue by CWO-Stanley** [kiwiirc/kiwiirc#1420]
2 privmsg where send when typing with a color when a space is the last character;
This will not happen when no color is selected
![e7adab4f-b9c7-4e13-9c04-1519fabbb997](https://user-images.githubusercontent.com/46792280/92335452-58dfa080-f097-11ea-8cfb-3cff1e497365.png)

**Comment by ilmari-lauhakangas** [comment]
I can't reproduce this with the latest KiwiIRC and another person confirms the same. Can you re-test with the latest?

**Comment by CWO-Stanley** [comment]
I can reproduce it with firefox as browser.. Chrome and Edge Chromium it doesn't happen anymore

**Comment by ilmari-lauhakangas** [comment]
I was testing with Firefox. Which FF version? Latest KiwiIRC?

**Comment by CWO-Stanley** [comment]
Updated to today's master, i couldn't reproduce it anymore :)

**Comment by CWO-Stanley** [comment]
![afbeelding](https://user-images.githubusercontent.com/46792280/106370776-a4079200-635d-11eb-877f-4b6670d5ed63.png)
Correction with latest build and latest FireFox it still gives double messages

**Comment by prawnsalad** [comment]
@CWO-Stanley which lines are doubled in that screenshot?

**Comment by CWO-Stanley** [comment]
@prawnsalad not a double message, but an empty message, it just appears when typing a sentance with more than one word.
As you can see in the screenshot, when typing just one word, it doesn't give an empty message after..
