### ISSUE TITLE
Passwords Not Being Passed

### ISSUE THREAD

**Issue by Torngate** [kiwiirc/kiwiirc#1424]
**Describe the bug**
KiwiIRC is not passing passwords to NickServ, resulting in users with registered accounts being kicked off of their nicknames. This can be reproduced in our hosted version of IRC as well as the Kiwi official version hosted at [kiwiirc.com/nextclient/]

**To Reproduce**
1. Go to kiwiirc.com/nextclient/
2. Click on Add a Network
3. Enter the server details, nickname, and password
4. Click "Connect to network" (OPTIONAL: Also select "raw" for more data)

**Expected behavior**
Connection to the IRC network, with an attempt to message NickServ for IDENTIFICATION.

**Actual Behavior**
No attempt to contact NickServ is done, and so users do not get identified, nor are permissions granted.

**Desktop (please complete the following information):**
 - OS: Windows 10 [Version 1903]
 - Browser Firefox
 - Version 81

**Additional context**
This problem appears to occur on the newest version of KiwiIRC, but also our hosted version (last version) after enabling IPv6 on the network and client.

Additional information available upon request.

**Comment by prawnsalad** [comment]
Could you paste the raw log of it failing? Also note that the network must support SASL for it to accept passwords on connect.

**Comment by Torngate** [comment]
> Could you paste the raw log of it failing? Also note that the network must support SASL for it to accept passwords on connect.

Well before I answer the first half, this brings up a good question in the second half. 

The server does not support SASL, because I can't find any documentation as to 1) what SASL is, 2) how to configure it, and 3) how to make it work with my current services setting for authentication (m_sql_authentication in Anope) worth spit. There are references in all three, but no details as to how to properly configure it or what SASL is. 

I can't find anything in the KiwiIRC docs saying I need SASL, either, and it didn't used to require SASL up until about a week ago when it just stopped working. 

Thanks for any guidance, documentation, or pointers in the right direction for SASL or Kiwi you can provide.

**Comment by prawnsalad** [comment]
kiwiirc.com/nextclient hasn't changed in over a month so if something has stopped working then it couldn't be there.

SASL is the standard way IRC servers send the password to your services, it's not a client-side thing so we wouldn't document that. It's usually part of your IRC server by default. I'm not sure which IRC server you use but here are some docs on some:
https://www.unrealircd.org/docs/SASL
https://docs.inspircd.org/3/modules/sasl/

**Comment by Torngate** [comment]
We kept our local copy of kiwi nextclient back a version, where the previous version did somehow. I'm not sure. We've tried to follow all known documentation for SASL, but as I said any docs I can find are piss poor. As far as I can tell, we've enabled SASL but it doesn't identify users. 

Following: https://www.unrealircd.org/docs/SASL, https://wiki.anope.org/index.php/2.0/Modules/unreal, and https://wiki.anope.org/index.php/2.0/Modules. 

As far as we can TELL, (/CAP LS) SASL is a thing that exists on the server but it's not actually authenticating... anyone. 

I'm guessing this isn't exactly the right place to be asking these questions, so I guess i'll just close by asking if you know where to actually find help setting up this stuff as I can't find any documentation beyond what's already been linked or who to talk to.

**Comment by prawnsalad** [comment]
If you're using Unreal then I would start with their support channels.

Out of interest, which network are you trying to use?

**Comment by Torngate** [comment]
I'll head there and to anope's support channels here soon I guess.

It's an org I'm working with's own personal little server, which is using an external SQLDB to auth users w/ their website logins (using Anope's m_sql_authentication module), but also have access to the chat room via a hosted Kiwi instance. 

Thanks for your help and the guidance toward the right direction.

**Comment by know75** [comment]
I have a similar issue and it's causing a lot of confusion for my users that are being renamed as Guests.

I run my own KiwiIRC instance and webircgateway. When they connect to my own IRC network, no issues. I also link to external IRC networks that don't appear to have SASL and will not change their services setup for me alone.

Considering this, is it possible for KiwiIRC to fallback on the NickServ identify command if SASL fails?

If KiwiIRC can't be changed is it possible a plug-in can achieve this? Unfortunately, I am not able to write this myself. I am not very familiar with javascript. I willing to learn, but I don't know where to start.

Love KiwiIRC, just wanting the login page to work for every network. Thanks.

**Comment by know75** [comment]
Could somehow please point me in the right direction to ensure users can identify with NickServ without SASL?
