### ISSUE TITLE
Cannot connect to local webircgateway server due to CORS

### ISSUE THREAD

**Issue by Coteh** [kiwiirc/kiwiirc#1427]
Hi, I am trying to configure kiwiirc to connect to a local webircgateway server I have setup on my machine (which in turn, connects to a local ngIRCd server). I am running into a CORS issue connecting to the webircgateway server.

My `kiwiServer` field in `config.json` is set to `https://localhost/webirc/kiwiirc/`, and I have also tried configuring a local domain (e.g. coteh.local) pointing to 127.0.0.1, to rule out any issues with "localhost" specifically. I have also tried both Firefox and Chromium to rule out any browser compatibility issues.

I have also tried adding "proxy" field in `package.json` to redirect to the port that webircgateway is running on, and I have explicitly added the port running the kiwiirc server to webircgateway's `config.conf` as well, like this:
```
# Websites (hostnames) that are allowed to connect here
# No entries here will allow any website to connect.
# Origins do not include a trailing / after the host (and optional port)
[allowed_origins]
http://localhost:5000
#"*://example.com"
```
I also run webircgateway using `--config=config.conf` option, and the server outputs that it has successfully read the config file.

I have also checked out the latest version of kiwiirc and the latest version of webircgateway, and I have built both projects from source instead of downloading pre-built files.

**edit:** Forgot to mention, I can also confirm that the webircgateway server runs on port 80:
```
$ nmap -p 80 localhost
Starting Nmap 7.80 ( https://nmap.org ) at 2020-10-13 20:06 EDT
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00015s latency).

PORT   STATE SERVICE
80/tcp open  http

Nmap done: 1 IP address (1 host up) scanned in 0.02 seconds
```

and that it's producing a result:
```
$ curl localhost/webirc/kiwiirc/
Welcome to SockJS!
```

I am not sure what else to try. I'm just looking to install kiwiirc locally just to see if webircgateway works, before I begin writing a websocket client of my own that connects to it. From my prior research, it seems that kiwiirc should be able to connect to webircgateway server out of the box, but that doesn't seem to be the case for me. If anyone here has the time to help me out with this issue, I'd greatly appreciate it. Thanks in advance!

![Screenshot_2020-10-13 Kiwi IRC - The web IRC client](https://user-images.githubusercontent.com/3276350/95927336-6d950f80-0d8c-11eb-93cb-f316887f287a.png)
![image](https://user-images.githubusercontent.com/3276350/95927247-37f02680-0d8c-11eb-865f-dd1c9d0b58b0.png)
![image](https://user-images.githubusercontent.com/3276350/95927325-666e0180-0d8c-11eb-8873-be1a3f9f6994.png)

**Comment by n1ce-0ne** [comment]
tinker about with that kiwiServer url some more, doesn't look right to me.
[just my 2 cents]

**Comment by prawnsalad** [comment]
Thanks for the good writeup!

A couple things come to mind. 1, you can't usually make HTTPS requests from a HTTP page as you are. You do somehow seem to be getting around that (maybe websockets are exempt from this...) as the request is getting made but something to try out. 2, if it's a self-signed cert then you may need to visit the websocket URL directly in the browser first to allow it to accept the cert.

If none of those help, could you screenshot the response headers from the websocket request?

**Comment by Coteh** [comment]
I noticed that I had `kiwiServer` url as HTTPS, I changed it to HTTP today (`http://localhost/webirc/kiwiirc/`) and that didn't work either. (Still gave CORS error) I also tried `http://localhost:8080/webirc/sockjs/` and that also did not work.

I also tried opening up a WebSocket connection directly, using something like:
```
const socket = new WebSocket("ws://localhost/webirc/sockjs/");
```
and I get the following error on Firefox:
> Firefox can’t establish a connection to the server at ws://localhost/webirc/kiwiirc/.

and I get this error on Node using `ws` module:
> Error: connect ECONNREFUSED 127.0.0.1:80

This is also the case if I make a WebSocket request to `ws://localhost/webirc/kiwiirc/`

I have attached some screenshots of the WebSocket requests from Firefox Network tab:

![image](https://user-images.githubusercontent.com/3276350/96021011-dc21ae00-0e1c-11eb-9251-b4cbdc64387f.png)

![image](https://user-images.githubusercontent.com/3276350/96020917-be544900-0e1c-11eb-804b-5c35f1ba2fca.png)

Let me know if there's anything else you guys need to help diagnose the problem. Thank you so much for your responses!

**Comment by n1ce-0ne** [comment]
the url still doesn't look right, keep at it, its local right?

**Comment by Coteh** [comment]
Yes, I currently have kiwiirc, webircgateway, and ngIRCd all running locally on my machine. I will give it another go tomorrow and report back.

**Comment by Coteh** [comment]
I had an epiphany, it was due to webircgateway (and ngIRCd) running on WSL 2. I gave it the private IP of the WSL 2 box instead of `localhost` and voila!

![screenshot](https://user-images.githubusercontent.com/3276350/96054398-96caa400-0e4f-11eb-9c75-571129511580.png)

I'm gonna close this now. Thanks for the help guys!

**Comment by n1ce-0ne** [comment]
there you go.
