### ISSUE TITLE
Disable auto scrolling 

### ISSUE THREAD

**Issue by veryclevermind** [kiwiirc/kiwiirc#1429]
Hello, I would like to find out how I can disable the auto-scrolling on the latest release of Kiwiirc ? 
I've used one of the  pre-built packages from ready to use installers can be found at the downloads page, https://kiwiirc.com/downloads/

The problem is that I've two Chat frames and would like to keep them however Whenever Kiwi receives a message in the channel or the scroll bar moves it moves the page to the top? and i would like this disabled. Is there something i can delete to make this happen from the static files ?

**Comment by veryclevermind** [comment]
@prawnsalad any suggestions on this? I've two different chat rooms on a similar iframe so when embedding Kiwiirc into an iframe the page scroll bar jumps to the Kiwi client window whenever there is a new message in the channel  Is there a way to disable this auto-scrolling in this advance version? I've seen a similar post related to this but that method could only work for the Node Js installation.

**Comment by prawnsalad** [comment]
If you can build or download the latest kiwi verison from github (https://github.com/kiwiirc/kiwiirc/wiki/Switching-from-Kiwi-IRC-stable-to-git-master ) then this should solve it. The way scrolling works has changed since.

**Comment by veryclevermind** [comment]
Oh great, thanks. I'll get this tested on a development system first before deploying it to my public site.

**Comment by pedro-nonfree** [comment]
I confirm `Mar 20 00:05 kiwiirc_master.zip` solves the scrolling problem! Thanks!
