### ISSUE TITLE
Make the client more efficient to Google speed algorithm 

### ISSUE THREAD

**Issue by veryclevermind** [kiwiirc/kiwiirc#1432]
Hello,

@prawnsalad  Good day,

I'm thinking to switch to KiwiRC permanently but the speed performance is very poor. Is there any way that it can be optimized otherwise injecting Kiwiirc directly into my website [https://www.gupshupcorner.com/](url) will give a dent to my ranking if you could look to see if that's somehow possible so we can optimize the Java script delivery and do some CSS advancement into the new generation of Kiwi client? I've already a client running on my website if you would like to take a look.

Thanks

**Comment by prawnsalad** [comment]
Javascript is minified and compressed to your browser, assuming that's what you mean by optimising javascript delivery? What is "CSS advancement"? If you've noticed anything specific or have some type of report then we might have something to look at.

**Comment by veryclevermind** [comment]
Ok, so I've only the client running at https://myclient.gupshupcorner.com/ this has been optimized by Cloudflare as the page has been optimized for faster delivery even with that I'm getting the following results on the page speed test. I've more than 50% of the mobile traffic but placing the client on the main page will become troublesome in the eyes of google as the entire page speed will be reduced. Run a speed test by yourself. The link is running on Centos 8 server with no other content on the server other than KiwiIRC.
![image](https://user-images.githubusercontent.com/48657144/97091095-397ce280-1607-11eb-899c-e87650c79fe4.png)

**Comment by prawnsalad** [comment]
You have a lot of things being loaded here. Most of the time is waiting for the server to reply to the web requests. Kiwi IRC is just static files so you would need to tune your web server for improve this however you see fit. You are also loading a lot of plugins, you might want to try combining them into a single larger file perhaps. The cloudflare rocket-loader, proxycheck service and added jquery is also slowing things down. These are outside the scope of KiwiIRC and down to your server tweaks so there's not much we can do here. As you can see in the screenshot (Chrome Network tab)the kiwiirc app files are the faster loading assets on the entire page.
![image](https://user-images.githubusercontent.com/725880/97092075-a9f02780-1638-11eb-88c1-b8c756b9b994.png)
