### ISSUE TITLE
Unable to build the KiwiIRC client

### ISSUE THREAD

**Issue by mdziczkowski** [kiwiirc/kiwiirc#1435]
Due the attempt of building of the KiwiIRC client from the sources, I recieve following errors while beeing in the extracted folder of the downloaded sources):

`$ yarn install`
> 00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
or
> 00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.

and by building attempt:

`yarn build`
> 00h00m00s 0/0: : ERROR: [Errno 21] Is a directory: 'build'

could anyone fix that ?

**Comment by ItsOnlyBinary** [comment]
it seems the `yarn` you have is not yarnpkg

https://classic.yarnpkg.com/lang/en/

**Comment by mdziczkowski** [comment]
> it seems the `yarn` you have is not yarnpkg
> 
> https://classic.yarnpkg.com/lang/en/

I had downloaded it thru apt in my linux - it was the only avaliable for me yarn
