### ISSUE TITLE
Non-Latin alphabet symbols in nicknames is unsopported

### ISSUE THREAD

**Issue by acetoneRu** [kiwiirc/kiwiirc#1446]
The IRC server supports Cyrillic alphabet. However, Kiwi IRC blocks the "Start" button when entering any non-Latin character. Is there any way to configure it so that I can use nicknames other than the Latin alphabet? Thanks.

**Comment by ItsOnlyBinary** [comment]
`startupOptions.nick_format` in your config.json

Its a regex, the default is:
```
/^[a-z_\\[\]{}^`|][a-z0-9_\-\\[\]{}^`|]*$/i
```

note: as your putting it in a string you will need to double escape  `\\` special characters, the above is not in quotes so is only single escaped

It can include the regex markers `"/.*/i"` or just be a string `".*"` both options might behave differently

here is the code that handles it: https://github.com/kiwiirc/kiwiirc/blob/master/src/components/startups/Welcome.vue#L162

Good luck this can be a fun one, I have closed this issue but will still be notified of replies if you're still having issues
