### ISSUE TITLE
Embedding Kiwi IRC without remembering buffers

### ISSUE THREAD

**Issue by sergip76** [kiwiirc/kiwiirc#1458]
Is it possible to embed Kiwi IRC passing an option variable to not to remember buffers?
It would be cool the possibility to use any start option in URL as variables.

**Comment by prawnsalad** [comment]
We try not to put everything into URL variables as it will eventually become messy and difficult to debug. Something as specific as this I don't think warrants being a URL variable.

I'm assuming you're referring to the hosted option on kiwiirc.com, so I will think over adding the option to the client builder we have at https://kiwiirc.com/clientbuilder/
There's a few internal things that decide if buffers should be remembered so it's something I would need to think about properly for the future.

**Comment by sergip76** [comment]
I've just noticed that remember buffers is a good option for my project, so I finally want to use this option.

I have tried the client builder at https://kiwiirc.com/clientbuilder/ but it doesn't remember buffers as this normal link does:
https://kiwiirc.com/nextclient/(server)/?encoding=utf8&theme=relaxed&language=es-es&nick=(nick)

I'd like to use cliente builder to change some options, but it would be great if I could turn on "remember buffers".
