### ISSUE TITLE
Anyway we can add dynamic per user IRC server passwords?   

### ISSUE THREAD

**Issue by dewbieZ** [kiwiirc/kiwiirc#1478]
This is a pretty fundamental function of modern IRCDs and I don't notice or see documentation specifying this ability.  Currently I'm filtering per IP address for specific connections to accommodate my needs, without a password, but "auth lines" have this ability and there is no way to utilize them with passwords currently.

**Comment by ItsOnlyBinary** [comment]
sounds like your looking for SASL so you can restrict your server to registered users only. I would suggest speaking to your ircd's support channel.

**Comment by dewbieZ** [comment]
No, it's not really.  It's a normal RFC specification for IRC.  This is an IRC client.  Please reference https://tools.ietf.org/html/rfc1459 Section 7

**Comment by ItsOnlyBinary** [comment]
kiwiirc's webircgateway (config.conf) does support server passwords but they are not per user. if you want per user passwords then sasl really is the answer

**Comment by dewbieZ** [comment]
Please explain why this is a logical answer

**Comment by dewbieZ** [comment]
I have never reviewed this project, but are you telling me that the code currently in place is incapable of passing a variable to the connection thread to specify a password when it's creating it?

**Comment by ItsOnlyBinary** [comment]
if you have a server password it can be specified [here](https://github.com/kiwiirc/webircgateway/blob/master/config.conf.example#L99) so it is not exposed to the user.

The welcome screen will accept a user password and that will be used in [SASL](https://ircv3.net/specs/extensions/sasl-3.2) negotiation

**Comment by dewbieZ** [comment]
I'm not looking for that to happen.  I don't want this to occur during every connection, only when the client creating the connection specifies that it wants to use it to make the connection.

**Comment by ItsOnlyBinary** [comment]
No, the password box on the welcome screen will send the password as part of SASL auth.

If i remember rightly the sending of the user provided password as the server password was removed because some IRCD's reject the connection when the user password is passed in this way even when there is no server password set on the IRCD. To allow for servers that do use server password the extra server password option was added to webircgateway

**Comment by dewbieZ** [comment]
The RFC specification cites that all client and server connections should be able to accept a password.  So the code was changed to address a broken software?

**Comment by westor7** [comment]
@dewbieZ what exactly you cannot understand he explained it clearly if english is not your native language try to translate it.

KiwiIRC is the best web irc software in the world right now..

**Comment by dewbieZ** [comment]
Where is the TCP connection created for kiwiirc?  Is it generated in this project? or is this just a front end to some core server?

**Comment by ItsOnlyBinary** [comment]
web browsers do not allow the creation of tcp sockets. kiwiirc uses websockets to talk to [webircgateway](https://github.com/kiwiirc/webircgateway)

**Comment by dewbieZ** [comment]
Where do the USER and NICK criteria get passed to the IRC server for registration?

**Comment by ItsOnlyBinary** [comment]
https://github.com/kiwiirc/irc-framework/blob/master/src/client.js#L304

**Comment by dewbieZ** [comment]
So the preceeding line before it

        if (this.options.password) {
            this.raw('PASS', this.options.password);
        }

is that set by the password for the welcome screen?

**Comment by ItsOnlyBinary** [comment]
No, https://github.com/kiwiirc/kiwiirc/blob/master/src/components/startups/Welcome.vue#L326

**Comment by dewbieZ** [comment]
What would be the easiest way to use the password field that exists on the Welcome page currently to tie the password field here to it?

            net = net || this.$state.addNetwork('Network', this.nick, {
                server: netAddress,
                port: connectOptions.port,
                tls: connectOptions.tls,
                password: password,
                encoding: _.trim(options.encoding),
                direct: connectOptions.direct,
                path: connectOptions.direct_path || '',
                gecos: options.gecos,
                username: options.username,
            });

**Comment by dewbieZ** [comment]
https://github.com/kiwiirc/kiwiirc/blob/44ac7181a6284205fec41c91cc2d578efd8596a9/src/components/startups/Welcome.vue#L107

**Comment by dewbieZ** [comment]
Sorry : https://github.com/kiwiirc/kiwiirc/blob/44ac7181a6284205fec41c91cc2d578efd8596a9/src/components/startups/Welcome.vue#L306

**Comment by ItsOnlyBinary** [comment]
the else i linked to earlier
```
net.connection.password = password;
net.password = '';
```

**Comment by dewbieZ** [comment]
I guess I'm not knowledgeable about the project to figure this out.  I replaced:
net.connection.password = password;
net.password = '';

with

                net.connection.password = `${password}`;
                net.password = `${password}`;

What am I missing

**Comment by ItsOnlyBinary** [comment]
I'm hoping you solved this one so closing the issue, If you still need help i will be notified of replies here or you can join us on irc.freenode.net #kiwiirc
