### ISSUE TITLE
No Notification Sounds

### ISSUE THREAD

**Issue by KoraggKnightWolf** [kiwiirc/kiwiirc#148]
It appears that even when sounds are enabled and set properly (e.g. to play a sound when one's own nick is mentioned or even every message) that no sounds are played. This issue is confirmed to occur on Google Chrome (in Incognito Mode) and seems to be effecting other people as well.

**Comment by prawnsalad** [comment]
I can't replicate this issue. Can you give some steps on how to repoduce the error when first opening kiwiirc.com/nextclient/ in incognito mode?

**Comment by m35** [comment]
I made a video demonstrating it. There's no audio from the browser, but you can hear the sound test from Window's audio settings.

https://streamable.com/vq8jt

**Comment by KoraggKnightWolf** [comment]
Dear prawnsalad and m35,

Thank you for taking the time to investigate this issue. I am on Windows 8.1 and when I just use kiwiirc.com/nextclient/irc.example.net:+6697/#Chat (this as placeholder for any irc network i wish to access) there are no sound notifications on google chrome whatsoever. I have heard that in your sample it works correctly and the steps to reproduce are just immediately entering the address, port and channel i wish to connect to. Sound works on all other applications (windows media player, skype, even other irc clients) thus this appears as weird to me as no other programs are experiencing issues.

On non incognito mode it gives me toast notifications at least which it does not do in incognito mode upon further investigation. This was due to chrome blocking notifications from kiwiirc by default in the incognito tab yet not in the "normal" one. I was incapable of locating an option for speakers to be enabled but this might be the issue.

Best Regards,

Koragg

**Comment by prawnsalad** [comment]
Is this still an issue? I'm consistently getting sounds as expected so far.

**Comment by m35** [comment]
I just tried it again in Chrome and Firefox. I'm getting the pop-up notifications, but still no audio. 🤔

**Comment by ItsOnlyBinary** [comment]
@prawnsalad i quite sure this issue is a server misconfiguration issue https://kiwiirc.com/nextclient/irc.example.com:+6697/static/highlight.mp3 returns the welcome screen not the mp3, it also presents as not showing any fontawesome icons

**Comment by ItsOnlyBinary** [comment]
Many things have changed since this issue was last commented on, could you please confirm if its still a valid issue?

**Comment by prawnsalad** [comment]
@m35 could you try it when "I am mentioned" is selected and somebody highlights you? There might be a bug with the "All messages" option

**Comment by m35** [comment]
Tested on Firefox and Chrome. When my name is used I hear a sound. 👍

**Comment by prawnsalad** [comment]
Going from @m35's comment and testing the All Messages option this seems to be all working now. Let me know if you still have the same issue

**Comment by m35** [comment]
Tested Firefox and Chrome. Makes the sounds as expected. Thanks for fixing it 🙂
