### ISSUE TITLE
HTTPS not running

### ISSUE THREAD

**Issue by shalabajzr** [kiwiirc/kiwiirc#1495]
Hi,

I've set up kiwiirc on CentOs 7 on port 8181. It's working fine when I navigate to http://host:8181 however i get a blank page for http**s**://host:8181. Is there anything that needs to be set up in order for this work via https?

Thanks.

**Comment by prawnsalad** [comment]
@shalabajzr kiwiirc is just static web files so it all depends on your web server. Usually your web server would use a different port for http and https though.
