### ISSUE TITLE
Welcome Screen: Fields with invalid data should be marked

### ISSUE THREAD

**Issue by DarkTexas** [kiwiirc/kiwiirc#1496]
I've noticed some users are not used to IRC Webchats and do not know they can't use certain letters, spaces, etc on nicknames.

People do enter a nickname, such as "girl from germany" and the login button doesn't turn valid, as it's obiously a invalid nickname, but those people do not know it's because of the nickname being wrong. KiwiIRC should mark the field, where the invalid info was provided at with a red border, maybe even give a hint of what's wrong in form of a tooltip.

**Comment by ItsOnlyBinary** [comment]
Fixed in #1505
