### ISSUE TITLE
Status Window/Server Tab NOT receiving notification badges about new messages

### ISSUE THREAD

**Issue by KoraggKnightWolf** [kiwiirc/kiwiirc#150]
The status window/server tab does NOT receive notification badges when a new message is sent to it. This is highly inconvenient as all notices, wallops etc go to this window and it does not seem that they can be sent to other windows. At least for msgs from IRC Services (NickServ etc) people can use /ns set privmsg on but this is only a workaround and notices from other users for example are still sent to a window and the KiwiIRC user is not informed about this.

**Comment by ItsOnlyBinary** [comment]
This was fixed in  #1686
