### ISSUE TITLE
Can't Upload pics in the last week or so

### ISSUE THREAD

**Issue by MS17Organizing** [kiwiirc/kiwiirc#1503]
hi: I've been able to upload pictures at will to a number of channels on DALnet for years, as long as I've been using kiwiirc.  sometime in the last week or so, I suddenly cannot... upload window comes up when I paste a picture, but pct complete stays at 0%, and eventually get message "Upload failed" at bottom of the window, where "% Complete" usually is.  Doesn't seem to be an ISP problem, since can upload in other places (Skype, for example) and can send email.

Any idea why??  If not, how can I trouble shoot it?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 88.0.4324.190

**Comment by sergip76** [comment]
Yes, I have the same problem with Chrome and Safari, using Kiwi IRC widget.

**Comment by prawnsalad** [comment]
@MS17Organizing @sergip76 could you try this again and let me know if it is working again?

**Comment by sergip76** [comment]
> @MS17Organizing @sergip76 could you try this again and let me know if it is working again?

Yes. It works fine now! Thanks!!
