### ISSUE TITLE
Bug affichage liste des utilisateurs ?

### ISSUE THREAD

**Issue by Zell40** [kiwiirc/kiwiirc#1513]
Bonjour,

Après de multiples recherches sur internet et dans divers forums, je ne trouve pas la solution à mon problème !

Un bug d'affichage apparait lors du l'utilisation de kiwiirc sur smartphone ou tablette.
J'ai essayé avec plusieurs navigateurs et smartphones mais le résultat reste le même.

Mes problèmes : 
-1) lorsqu'un utilisateur cherche à changer de salon et qu'il clique sur un salon dans la barre latéral gauche, le salon s'affiche mais un bug apparait également séparant la page en deux partie. Sur le coté droit la liste des utilisateurs et sur le coté gauche une partie du salon concerné... 
pour pouvoir fermer la liste utilisateurs qui apparait, il faut cliquer sur le bouton paramètre ou utilisateur.. 
- 2) lorsqu'un utilisateur appui sur le bouton d'affichage de la liste des salons, les topics de salon sont affichés verticalement ce qui complique la bonne vision des noms de salons disponibles...

Je vous transmet les screenshots que j'ai fait via mon smarpthone samsung ainsi que la configuration de mon kiwiirc.

J'espère que vous allez pouvoir m'aider et trouver ces solutions !!
Merci @ vous d'avance.
Jessie.

[client.json.txt](https://github.com/kiwiirc/kiwiirc/files/6136818/client.json.txt)
[config.conf.txt](https://github.com/kiwiirc/kiwiirc/files/6136819/config.conf.txt)

![Screenshot_20210314-122424_Chrome](https://user-images.githubusercontent.com/77941996/111071297-cf8da880-84d5-11eb-8262-37e8ef4140a8.jpg)
![Screenshot_20210314-122336_Chrome](https://user-images.githubusercontent.com/77941996/111071305-d61c2000-84d5-11eb-91b2-5de28a9f3d0c.jpg)
![Screenshot_20210314-122623_Chrome](https://user-images.githubusercontent.com/77941996/111071310-d9afa700-84d5-11eb-88bd-33c5d47ed7d7.jpg)

**Comment by ItsOnlyBinary** [comment]
The channel changing bug is fixed in kiwiirc master, please see https://github.com/kiwiirc/kiwiirc/wiki/Switching-from-Kiwi-IRC-stable-to-git-master for instructions on how to use the master branch with the packaged version.

For the channel list please follow this issue #1392

If you need any further help please continue to reply here, or join us on irc.freenode.net #kiwiirc
