### ISSUE TITLE
Way to disable embedly.com

### ISSUE THREAD

**Issue by crazycatdevs** [kiwiirc/kiwiirc#1520]
**Is your feature request related to a problem? Please describe.**
We want a minimal kiwiirc without image and url embedding, but impossible to deactivate embedly.com feature

**Describe the solution you'd like**
Adding a config parameter to disable embedly.com api

**Comment by westor7** [comment]
If you want to complete disable link previews check these `config.json` options:

https://github.com/kiwiirc/kiwiirc/blob/master/src/res/configTemplates.js#L80-L82

**Comment by crazycatdevs** [comment]
Oh... I didn't see these options, peharps did I rode a too old doc...
Thanks a lot @westor7
