### ISSUE TITLE
Icons on inputbar out of order on smaller screens/mobile

### ISSUE THREAD

**Issue by CWO-Stanley** [kiwiirc/kiwiirc#1524]
**Describe the bug**
When having multiple icons on the input bar, such as fileuploader, emoji, gif, colorpicker, the hamburger menu button appears above them and when it is pushed the inputbar is back to normal.

![359d3357-2e7b-4fdb-bcbf-4f8e2ec5e40f](https://user-images.githubusercontent.com/46792280/115059673-26c4d580-9ee7-11eb-8507-314b10a9cca9.png)

**Comment by ItsOnlyBinary** [comment]
this should have been fixed by #1597
