### ISSUE TITLE
Does not clean up open file descriptors 

### ISSUE THREAD

**Issue by adamus1red** [kiwiirc/kiwiirc#153]
During a recent test of deploying kiwiirc we found that under decent load, the client will not properly close it's open sockets leaving the file descriptors open.
This causes a denial of service as kiwiirc runs out of resources and responds with an error 500 page.

Tested with version 17.10.06.1 and a soft limit of 10240 file descriptors

**Comment by prawnsalad** [comment]
There was a bug some time ago that caused this and no longer happens on kiwiirc.com. I'm getting an update rolled out in the next day or 2 so I'll update this thread when it's available try again.

**Comment by prawnsalad** [comment]
@adamus1red has this been improved for you now?

**Comment by adamus1red** [comment]
@prawnsalad I've ran it for week, but it just started to throw the "too many open files" again last night.
`2018/01/22 07:52:19 http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 640ms`

**Comment by prawnsalad** [comment]
Where $pid is your kiwi server process, can you paste the output of:
* cat /proc/$pid/limits
* ls -l /proc/$pid/fd/ | wc -l
* netstat -ntp | grep $pid/ | grep ESTABLISHED | wc -l
* netstat -ntp | grep $pid/ | grep -v ESTABLISHED | wc -l
