### ISSUE TITLE
Readability issue: green color (03) is too light as #0f0

### ISSUE THREAD

**Issue by jjnilton** [kiwiirc/kiwiirc#1531]
**Describe the bug**
The green color (03) is too light as `#0f0`, which can be confused with the light green (09).

**To Reproduce**
1. Write in green or white with green background.
2. Compare with other clients.

**Expected behavior**
The green should be a little darker. Below there's a comparison with three other IRC clients, note the white text with green background.

**Screenshots**
![kiwiirc-green](https://user-images.githubusercontent.com/228200/117029379-f77ada80-acd4-11eb-96e4-f112af74c9ec.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 88

**Additional context**
Some color references:
- https://www.mirc.com/colors.html
- https://modern.ircdocs.horse/formatting.html

**Comment by AllanOcelot** [comment]
@jjnilton  great spot! 
It turns out our shade of green was slightly off, I'll make a PR shortly to update this colour to the MIRC shade of green for consistency in the default Kiwi Theme, thanks.

**Comment by jjnilton** [comment]
Other themes (https://github.com/kiwiirc/kiwiirc/search?q=%230f0) also use the same shade of green, so would be good to change them too. I made a PR for the other themes (https://github.com/kiwiirc/kiwiirc/pull/1538) except Radioactive, which gets its colors from `globalStyles`.
