### ISSUE TITLE
Add options to enable/disable particular 'extended formatting' replacements.

### ISSUE THREAD

**Issue by tyzoid** [kiwiirc/kiwiirc#154]
Example:

![struct some_struct *my_st = malloc(sizeof *my_st);](https://i.imgur.com/ib4TVht.png)

When writing/talking about code, some formatting options are undesirable, where some others are desirable. It would be nice to be able to enable/disable individual formatting rules.

**Comment by prawnsalad** [comment]
Closing this issue as the formatting has been improved since so that characters are not removed. This makes either case of those examples work though the second would be better.
