### ISSUE TITLE
SSL checkbox for predefined networks

### ISSUE THREAD

**Issue by kasperk81** [kiwiirc/kiwiirc#1544]
In the predefined networks, there is currently no option to select SSL:
<img src="https://i.ibb.co/NVvM4HQ/2021-05-29-646x675-scrot.png" width="50%"
 />
 
 Please add an option (a checkbox?) so channels which require SSL can be joined.
 Currently we are getting this error from those channels:
 
 > You must connect via SSL to join this channel (+S)
 
 and the workaround is to manually add the network with SSL port.

**Comment by ItsOnlyBinary** [comment]
This is now be fixed on kiwiirc.com with SSL as default for Oftc

**Comment by kasperk81** [comment]
Confirmed. Thanks for the quick fix! \o
