### ISSUE TITLE
Embeddable widget not honouring port and SSL settings

### ISSUE THREAD

**Issue by tenleftfingers** [kiwiirc/kiwiirc#1545]
My widget will not connect unless the user expands the "Server and network" part of the UI and selects the SSL option manually. I've tried to compensate for this in the widget itself, but it doesn't make any difference. Here is the code and further below is the current documentation where I found these options.

`<iframe src="https://kiwiirc.com/nextclient/#ircs://irc.libera.chat:+6697/?nick=webUser|?&theme=cli#my-channel" style="border:0; width:100%; height:600px;"></iframe>`

The + is supposed to signify SSL, but SSL is still unchecked in the UI and the connection fails. The port number is also still at 6667 in the UI instead of the value provided in the code above.

There are two sources of info for creating an embeddable widget:
Basic code is generated by the kiwi embed generator here https://kiwiirc.com/embedding
Further options are documented here https://github.com/kiwiirc/kiwiirc/wiki/Linking-to-and-Embedding-Kiwi-IRC

**Comment by prawnsalad** [comment]
Hi, try using the newer client builder here, https://kiwiirc.com/clientbuilder/
This will give you more options.

And the connection will use the SSL options no matter what you specify as the Libera.Chat admins have that set on kiwiirc.com anyway.
