### ISSUE TITLE
HTML links not working in infoContent setting

### ISSUE THREAD

**Issue by poVoq** [kiwiirc/kiwiirc#1546]
**Describe the bug**
When I try to add a HTML link to the infoContent setting it fails with the following error:
`
Config file error: invalid character 'i' line 22, position 53`

**To Reproduce**
Setting:
`"infoContent": "Connect a IRC client via <a href="ircs://irc.example.comt:6697/#example">irc.example.com</a>",`

**Expected behavior**
It should be possible to add HTML links.

Maybe the problem is with the quotes?

**Comment by poVoq** [comment]
Indeed with 
`"infoContent": "Connect a IRC client via <a href='ircs://irc.example.comt:6697/#example'>irc.example.com</a>",`
It works.

Maybe good to add that to the wiki?

**Comment by ItsOnlyBinary** [comment]
I added some html to the example :)

https://github.com/kiwiirc/kiwiirc/wiki/Configuration#startupoptionsinfocontent
