### ISSUE TITLE
kiwi+oftc: Unknown domain name or host

### ISSUE THREAD

**Issue by kasperk81** [kiwiirc/kiwiirc#1551]
I tried signing in at https://kiwiirc.com/nextclient/irc.oftc.net/ and constantly receiving:

![2021-06-20_694x748_scrot](https://user-images.githubusercontent.com/83082615/122664116-f845ce00-d1a7-11eb-823c-12a8fb79bba3.png)

**Comment by n1ce-0ne** [comment]
working fine for me

**Comment by prawnsalad** [comment]
This has since been resolved - the kiwiirc.com IPs were temporarily added to a spam list and blocked. Thanks for the report!

**Comment by kasperk81** [comment]
Issue is back with a new "Banned" error. Can it be permanently added to allowed list?

**Comment by prawnsalad** [comment]
That banned error message now comes from OFTC themselves, meaning they have specifically banned kiwiirc.com. I haven't heard any reason why from them unfortunately.
