### ISSUE TITLE
[Feature Request]: Disable the sorting on channels treebar

### ISSUE THREAD

**Issue by westor7** [kiwiirc/kiwiirc#1559]
Hello,

Currently kiwiirc sorting alphabetically the channels on the left (treebar), i wanna suggest an option to disable that sorting and allow to use the order without sorting, so if now i use `/JOIN #B,#C,#A` it's going to sort it as `#A -> #B -> #C` so an option to disable that behavior would be much appreciated.

Suggesting config.json option like: `"AllowChannelsSort": false`

Executing: `/JOIN #B,#C,#A`

Currently behavior:

![](https://i.imgur.com/6Od3VkD.png)

Suggested behavior:

![](https://i.imgur.com/nfykhsQ.png)

- Thanks!

**Comment by ItsOnlyBinary** [comment]
plugin was provided to complete this issue
