### ISSUE TITLE
Show own disconnects in the event flow

### ISSUE THREAD

**Issue by mestaritonttu** [kiwiirc/kiwiirc#156]
It is rather difficult to notice the not connected message in the left sidebar. Also, the user currently has no way of knowing when exactly they were disconnected. Having this in the normal channel flow would solve these.

I have sent messages while I was disconnected because I did not notice :)

**Comment by prawnsalad** [comment]
This is now in master. Thanks!

**Comment by hnz101** [comment]
After an reconnect with this new feature all old messages are duplicated.
See the Screenshot, every old message should be one line, but it doubles every message during the reconnect. In some cases even quadrupled.
![kiwidouble](https://user-images.githubusercontent.com/4280171/34159745-8df0424c-e4ca-11e7-89fd-34932d42561e.PNG)
