### ISSUE TITLE
Your SSL cert expired.

### ISSUE THREAD

**Issue by dowodenum** [kiwiirc/kiwiirc#1564]
**Describe the bug**
Using nextclient,
"We couldn't connect to that server :( Unknown error"

**To Reproduce**
1. Go to https://kiwiirc.com/nextclient/irc.server.example/test
2. Fail to connect

**Expected behavior**
Connects properly in step 2 above.

**Screenshots**
![image](https://user-images.githubusercontent.com/57815700/125552431-5494d3ff-2b8c-4460-a066-0d9ebef17ccf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise LTSC 
 - Browser: Vivaldi 4.0.2312.36 (Stable channel) (64-bit)

**Comment by sergip76** [comment]
Same problem here. All my chats are down :-(
Please, help!!!

**Comment by prawnsalad** [comment]
Thanks for the report - it seems I missed the warning reminders :( It should be up and running again now!
