### ISSUE TITLE
nicklist on mobile view

### ISSUE THREAD

**Issue by legendskyk** [kiwiirc/kiwiirc#1576]
is that possible nicklist not be hide on mobile? keep pined even on mobile view?
if its possible then kindly tell how it could be?

**Comment by ItsOnlyBinary** [comment]
Unfortunately this is not possible due to the nicklist taking up too much space when in mobile view. There would be no room left for the messages

**Comment by legendskyk** [comment]
It can be manage via css file, just tell me how to pinned nicklist i will manage it after that.

**Comment by ItsOnlyBinary** [comment]
there is many places where the style is changed to accommodate mobiles, its not as easy as just pining the nicklist.

I think you would need to rewrite lots of that styling to get it to be pinable. I suggest using your favourite source code editor (VS code etc) to find in files (ctrl+shift+f) and search for "769" which is the screen size where it switches to mobile view

**Comment by legendskyk** [comment]
![Skype_Picture_2021_07_27T19_03_20_734Z](https://user-images.githubusercontent.com/42233490/127213052-b1166b5d-350d-47c7-8bd3-c66ee65dff06.jpeg)
I did that its work prefect and look beautifull on mobile our users also happy with it.
