### ISSUE TITLE
Improving on block user feature

### ISSUE THREAD

**Issue by Shrugged123** [kiwiirc/kiwiirc#1578]
Hi, 
I am a regular chatter at a chat site. I would like to raise an issue of abusers on the chat site. It has come into the notice that the abusing or misbehaving has been significantly increased over the site, specifically with the female chatters. If we put them at ignore , they very convienently change their nicknames, comes back and do the abusing or threatening. This issues has been raised many times to the admins of the chat site by different chatters but even they get helpless after a point as they can only ban the nicknames of those people, and can't ban them by their IPs or hostname. All the about stated things are making the chat experience awful. So, I would like you to look into the issue as soon as possible and maybe improve the block user feature (add IP/hostname of the user instead of nickname) (*!*@host) over the Kiwi IRC to make these sites safer to use by the chatter. Expecting concrete steps shall be taken. Thanks!

**Comment by prawnsalad** [comment]
The admins of the network need to enable WEBIRC to get the users hostnames/IPs set correctly. If you are using kiwiirc.com they can register their network there and get the configuration needed. If they are self hosting kiwiirc then they can find the webirc setting in their config files.
