### ISSUE TITLE
Bug mobile

### ISSUE THREAD

**Issue by MysterKB** [kiwiirc/kiwiirc#1581]
Big bug on mobile, just go to the list of rooms, click on a room and come back to the room, you will see a rather annoying bug.

**Comment by Shillos** [comment]
can you describe the bug or as a screenshot would help a lot!

**Comment by MysterKB** [comment]
Yes, please: https://www.youtube.com/watch?v=g79fkax3TU8

**Comment by ItsOnlyBinary** [comment]
@MysterKB is this kiwiirc.com or your own hosted kiwiirc install?

if your own install then both are fixed in master branch
https://github.com/kiwiirc/kiwiirc/wiki/Switching-from-Kiwi-IRC-stable-to-git-master

**Comment by MysterKB** [comment]
This is the .deb for Ubuntu

**Comment by ItsOnlyBinary** [comment]
Follow the above link then and switch to master, they deb is quite out of date and desperate for a new release (its on my todo list)

Been lots of fixes and improvements in master

**Comment by MysterKB** [comment]
Okay, thank you very much :D

**Comment by ItsOnlyBinary** [comment]
will close this issue but will be notified if you need more help ;)
