### ISSUE TITLE
Your SSL cert expired again

### ISSUE THREAD

**Issue by AltitudeApps** [kiwiirc/kiwiirc#1586]
FYI

![image](https://user-images.githubusercontent.com/70041186/132966730-4889899b-39bb-47c6-b5da-29d70efe4327.png)

**Comment by AltitudeApps** [comment]
https://github.com/kiwiirc/kiwiirc/issues/1564

linking the previous occurrence, just to see it work.

**Comment by prawnsalad** [comment]
Apologies - this has been updated!
