### ISSUE TITLE
Cannot connect to GameSurge server

### ISSUE THREAD

**Issue by MangaD** [kiwiirc/kiwiirc#1589]
I have the following embed on my site:

https://kiwiirc.com/nextclient/irc.gamesurge.net/#hfe

When I click "Start", the following error message shows:
> Closing Link: by Prothid.NY.US.GameSurge.net (Use a different port)

**Comment by westor7** [comment]
Try use their official portal: `https://irc.gamesurge.net/`

**Comment by westor7** [comment]
That's because their TLS certification is invalid, contact to owners.

As alternative use `https://webchat.gamesurge.net`

**Comment by MangaD** [comment]
@westor7 This one works. But how can I specify the channel and username?

**Comment by westor7** [comment]
Try: `https://webchat.gamesurge.net/?nick=NICKNAME_HERE&channel=#CHANNEL_HERE`

Example: `https://webchat.gamesurge.net/?nick=tester&channel=#whatever`

**Comment by westor7** [comment]
If you've figure out your issue, please close this issue.

- Thanks!

**Comment by MangaD** [comment]
@westor7 Thank you very much for your help. That works. Just one last thing: Is it possible to randomize the nickname, or omit it? I tried removing the `nick` parameter but then the `channel` parameter stops working.

**Comment by westor7** [comment]
Yes use `?` inside the nickname value.

Example: `https://webchat.gamesurge.net/?nick=test_??&channel=#CHANNEL_HERE`
