### ISSUE TITLE
Route undelivered message notices to the relevant buffer

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/kiwiirc#16]
The message sent from Unreal: `:porto.ptirc.org NOTICE Paula :Message to 'PeGaSuS' not delivered: User does not accept private messages`

**Comment by ItsOnlyBinary** [comment]
With notices going to the active buffer can this issue now be closed?

**Comment by AllanOcelot** [comment]
@ItsOnlyBinary  yes it can :D
