### ISSUE TITLE
Styling improvements on the NotConnected component

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/kiwiirc#161]
It currently doesn't separate itself enough from the rest of the messages. Suggestions welcome

![image](https://user-images.githubusercontent.com/725880/34083923-1bb3f42c-e370-11e7-8621-81d60c0d8653.png)

**Comment by AllanOcelot** [comment]
@prawnsalad  - I'd recommend having the disconnected message overwriting the 'connected' message or any other information above it, since the most important part here is the fact the user is disconnected.

If we did this I could style a more eye catching design 👍

**Comment by prawnsalad** [comment]
Removing the conversation when you get randomly disconnected would be really annoying though. If having it part of the conversation is too limiting, maybe dropping down from under the top bar or popping up from the bottom bar would work better?

**Comment by AllanOcelot** [comment]
Ahhh Didn't realise it would be replacing the conversation. Not had a solid poke around in the css yet - but I'm sure we could make the notification 'push' the content up and out of the way, so when it's closed the conversation can appear as normal?
