### ISSUE TITLE
help with configuration SSL

### ISSUE THREAD

**Issue by otello89** [kiwiirc/kiwiirc#1615]
Hi,
i can't get SSL connections to irc1.ircexample.net working in kiwiirc.com/nextclient but they work fine when i connect with ssl to irc2.ircexample.net

The error i get is below, without any further details:
We couldn't connect to that server :(
The Kiwi IRC server had an error

I have removed the SSl port in the network configuration for irc.ircexample.net because once i add it, the client refuses to connect to my network completely.
I'm hoping you can give me any indication why it refuses to connect with SSL while mIRC and Mibbit have no issues.

Kind regards

**Comment by ItsOnlyBinary** [comment]
are you sure you are putting the correct port for ssl? once an ssl port is provided nextclient will use that port to connect
