### ISSUE TITLE
Bug issue with yarn and KiwiIRC's latest merge

### ISSUE THREAD

**Issue by Shillos** [kiwiirc/kiwiirc#1625]
Based on the latest merge in KiwiIRC i got this when using yarn:

root@vmi387387:/var/www/html/kiwiirc# yarn
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @vue/babel-plugin-jsx@npm:1.1.1 doesn't provide @babel/core (p51001), requested by @babel/plugin-synta                                                                                            x-jsx
➤ YN0002: │ @vue/cli-plugin-unit-jest@npm:4.5.15 [afea8] doesn't provide vue (pcee52), requested by vue-jest
➤ YN0002: │ @vue/cli-plugin-unit-jest@npm:4.5.15 [afea8] doesn't provide vue-template-compiler (p8a272), requested                                                                                             by vue-jest
➤ YN0002: │ @vue/eslint-config-airbnb@npm:5.3.0 [afea8] doesn't provide webpack (p4db6f), requested by eslint-impo                                                                                            rt-resolver-webpack
➤ YN0002: │ font-awesome-webpack-4@npm:1.0.0 [afea8] doesn't provide less (p332bc), requested by less-loader
➤ YN0002: │ font-awesome-webpack-4@npm:1.0.0 [afea8] doesn't provide webpack (peec3b), requested by css-loader
➤ YN0002: │ font-awesome-webpack-4@npm:1.0.0 [afea8] doesn't provide webpack (pc9204), requested by less-loader
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, whe                                                                                            re <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 763ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 1s 388ms
➤ YN0000: ┌ Link step
➤ YN0076: │ fsevents@patch:fsevents@npm%3A1.2.13#~builtin<compat/fsevents>::version=1.2.13&hash=18f3a7 The linux-x                                                                                            64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=18f3a7 The linux-x64                                                                                             architecture is incompatible with this module, link skipped.
➤ YN0000: └ Completed in 2s 462ms
➤ YN0000: Done with warnings in 5s 46ms

I've never seen yarn act this way before with the specific numbering in front, then I tried to use the yarn stable release the same outcome then used the latest sources of yarn nothing changed.

When building this was the outcome:

root@vmi387387:/var/www/html/kiwiirc# yarn build
✔ translating languages...

⠹  Building for production...

 ERROR  Failed to compile with 1 error                                                                  7:33:34 PM

 error  in ./src/components/StateBrowserNetwork.vue

Syntax Error: TypeError: token.type.endsWith is not a function
Occurred while linting /var/www/html/kiwiirc/src/components/StateBrowserNetwork.vue:246
    at Array.every (<anonymous>)
    at Array.forEach (<anonymous>)

 @ ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./build/webpack/exports-loader.js!./node_modules/babel-loade                                                                                            r/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/co                                                                                            mponents/StateBrowser.vue?vue&type=script&lang=js& 69:50-82
 @ ./src/components/StateBrowser.vue?vue&type=script&lang=js&
 @ ./src/components/StateBrowser.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./build/webpack/exports-loader.js!./node_modules/babel-loade                                                                                            r/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/co                                                                                            mponents/App.vue?vue&type=script&lang=js&
 @ ./src/components/App.vue?vue&type=script&lang=js&
 @ ./src/components/App.vue
 @ ./src/main.js
 @ multi core-js/features/promise core-js/features/array/virtual/find-index core-js/features/array/virtual/include                                                                                            s ./src/main.js

 ERROR  Build failed with errors.
root@vmi387387:/var/www/html/kiwiirc#

Am I missing something here?

**Comment by ItsOnlyBinary** [comment]
`yarn -v` 
`node -v`

please

**Comment by Shillos** [comment]
Does corepack play any role in this? I'm using node v16.13.0 and npm 8.3.0

**Comment by Shillos** [comment]
yarn 3.1.0

**Comment by ItsOnlyBinary** [comment]
kiwi is using yarn 1.x not sure how its trying to build with yarn 3.x

**Comment by Shillos** [comment]
I have no idea how that happened I only used yarn and yarn build and that came up. How do I revert to yarn 1.x? although yarn has a newer version it seems.

**Comment by ItsOnlyBinary** [comment]
look for a file in kiwiirc folder called `.yarnrc.yml` and remove it if it exsists

**Comment by Shillos** [comment]
Well, I removed it then used yarn then yarn build and this came up:

root@vmi387387:/var/www/html/kiwiirc# yarn build
/var/www/html/kiwiirc/.pnp.cjs:30181
    throw firstError;
    ^

Error: Your application tried to access ora, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: ora
Required by: /var/www/html/kiwiirc/build/webpack/

Require stack:
- /var/www/html/kiwiirc/build/webpack/locales.js
    at Function.external_module_.Module._resolveFilename (/var/www/html/kiwiirc/.pnp.cjs:30180:55)
    at Function.external_module_.Module._load (/var/www/html/kiwiirc/.pnp.cjs:29979:48)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/www/html/kiwiirc/build/webpack/locales.js:3:11)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.external_module_.Module._load (/var/www/html/kiwiirc/.pnp.cjs:30029:14)
    at Function.moduleExports.runMain (/var/www/html/kiwiirc/.pnp.cjs:30230:31)
ERROR: "translate" exited with 1.

Not good! :-S

**Comment by ItsOnlyBinary** [comment]
remove node_modules and make sure your yarn 1.x is up to date `npm install -g yarn`

**Comment by ItsOnlyBinary** [comment]
closing this issue, I will still get notified if you have more to add

**Comment by Shillos** [comment]
Can KiwiIRC use the latest 3.1.0? I find it difficult to get rid of that version I also found out that thelounge uses the 3.1.0 which i have on the same VPS. I don't know why there isn't any compatibility, as yarn should have had done something about this issue. I will try another few ways if not I will have to redo everything from scratch. Thanks again, thought I hope also KiwiIRC would rather upgrade to the 3.x latest yarn edition.

**Comment by ItsOnlyBinary** [comment]
yarn >= 2.x should be a per project thing from what I understand.

it seems like you either installed yarn >= 2.x globally (which i dont think you should do) or you tried to migrate kiwi to yarn >= 2.x (which creates untracked files so dont get removed when switching branches etc)

It should be totally possible and expected setup to have yarn 1.x installed globally but use yarn >= 2.x for thelounge

**Comment by Shillos** [comment]
I found a solution, even though I might need to set every time versions due of me using thelounge and kiwiirc on the same vps. `yarn set version 1.22.15` and then `yarn set version latest` might help to switch for the one to the other, but first the `.yarnrc.yml` in the global section of the account should be removed.

What I did and this fixed the issue:

```
cat ~/.yarnrc.yml 
> yarnPath: ".yarn/releases/yarn-berry.cjs"

rm -f ~/.yarnrc.yml

npm install -g 'yarn@1.22.1'

yarn -v
> 1.22.10
```

Lesson learned that KiwiIRC still uses the old classic 1.x, so in case anyone else has the same trouble this can be linked here unless KiwiIRC sometime in the future might change to the latest yarn 3.x.
Some good link to switch from one version to another https://yarnpkg.com/cli/set/version

**Comment by Shillos** [comment]
Thanks @ItsOnlyBinary for the advice I will try and keep this in mind or just bookmark this issue in case I forget! Thanks again! :-)

**Comment by Codigo55** [comment]
![archivo](https://user-images.githubusercontent.com/121065386/208558495-a8894a6f-6533-472c-9a88-58ee62ab4d0b.jpg)

**Comment by Codigo55** [comment]
e intentado     arto

**Comment by ItsOnlyBinary** [comment]
sounds like it might be an issue with your nodejs version (too old/new), or maybe you tried installing dependencies using npm before yarn?

Parece que podría ser un problema con tu versión de nodejs (demasiado antigua/nueva), o tal vez intentaste instalar dependencias usando npm antes de yarn?

**Comment by Codigo55** [comment]
Despues  de   .   yarn   run  build    .que   biene

**Comment by Codigo55** [comment]
si  se  configuro  como  se   ejecuta   para  levantarlo
ese   kiwiirc
________________________________
De: ItsOnlyBinary ***@***.***>
Enviado: lunes, 19 de diciembre de 2022 22:33
Para: kiwiirc/kiwiirc ***@***.***>
Cc: Codigo55 ***@***.***>; Mention ***@***.***>
Asunto: Re: [kiwiirc/kiwiirc] Bug issue with yarn and KiwiIRC's latest merge (Issue #1625)


@Codigo55<https://github.com/Codigo55>
can you try changing vue.config.js lines 140-142 to:
¿Puedes intentar cambiar las líneas 140-142 de vue.config.js a:

    } catch (err) {

        console.error('Failed to get commit hash', err);

    }

**Comment by Codigo55** [comment]
Configure  todo pero  no  se  como  levantar lo  me  sale  error  en  kiwiirc

Enviado desde mi Movistar
Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
