### ISSUE TITLE
"The Kiwi IRC Server had an error :(" 

### ISSUE THREAD

**Issue by dowodenum** [kiwiirc/kiwiirc#1629]
Multiple users on our network reporting this, meanwhile those using other clients have no problem. Dunno if it's your SSL cert again or what but the error message isn't all that verbose.

**Comment by boolysteed** [comment]
LimeChat for IOS may be preferred, but the other trolls locked out using Windows as well.  Both.  Yes, HEX chat for Linux, & Windows.  And LimeChat for iOS.  However I was connecting from NA links without ever getting this error. Sir Vo TYFYC.

**Comment by boolysteed** [comment]
BTW I'm not a Ben/Bernadette.  I'm on the bleeding edge of this technology.

**Comment by dowodenum** [comment]
Well I just tested it again now and it works fine. 🤞

**Comment by boolysteed** [comment]
So I got the error again, after I signing on successfully. 
And I'm locked out of IRC chat.  Someone post a link to something I want to open later and can't return to troll room. Then when I sign back on I get the error msg. I guess that's a bug.

**Comment by prawnsalad** [comment]
@boolysteed are you using kiwiirc.com or some other kiwi URL? And which network address are you trying to connect to?

**Comment by boolysteed** [comment]
So, I am using the IRC client link from the NA show.net site.  I have successfully log'd in posted and some done actions in the chat.  

I am having intermittent lock out with that error msg.  
1. I'm on the NA stream & chat page of GitmoList
2. I connect to the URL hyper link CHAT
3. The page is labeled kiwirc.com
4. My Nick auto populates, as does my password
5. The channel is #noagenda
6. I am batting better than average getting in the chat, the error occurs when I link to preview to someone's link in the troll room and I can't get back.  And when I try to log in again I get the "error msg."  I'm on IOS iPad. But I have also gotten this msg from my NA -Linux phone.  *I think once the error msg comes up, it's a duplicate sign on?

I know others are experiencing something similar though a small minority.

Thanks.

**Comment by prawnsalad** [comment]
`The page is labeled kiwirc.com` - Do you mean `kiwiirc.com` is in the address bar? Can you paste the exact URL here so I can try it?

**Comment by boolysteed** [comment]
I successfully logged in. Attached is a screen shot.  Yes, the address bar reads kiwiirc.com  

Betty's iPad semaphore 🏁

**Comment by prawnsalad** [comment]
Missing screenshot

**Comment by boolysteed** [comment]
Betty's iPad semaphore 🏁

**Comment by prawnsalad** [comment]
Missing screenshot. Maybe try using the github web interface to send it

**Comment by boolysteed** [comment]
![image](https://user-images.githubusercontent.com/69763365/147497520-9b46f617-84a0-4def-a429-b1302b166862.png)

**Comment by prawnsalad** [comment]
That doesn't show the exact URL you are on. I need the URL of the page so I can make sure there's nothing wrong with the servers it's connecting to.
