### ISSUE TITLE
invite event invites every op in channel.

### ISSUE THREAD

**Issue by CWO-Stanley** [kiwiirc/kiwiirc#1632]
![Screenshot_20220101-152056_IRCCloud](https://user-images.githubusercontent.com/46792280/147852673-453e1432-ce24-4218-86a7-696e919a3a8d.jpg)
**Describe the bug**
Everytime when someone gets invited to the channel, all ops inside the channel gets the invite to.

This only happens on UnrealIRCd 6
![Screenshot_20220101-152039_Firefox](https://user-images.githubusercontent.com/46792280/147852713-9993920c-c212-44e7-bd6f-01cc473f37f2.jpg)

**Comment by ItsOnlyBinary** [comment]
please get the raw line for both personal invites and invites by another user `/set showRaw true` into the irc input box

im not convinced this is actually a bug, its likely a feature of unreal to notify other ops for invites

**Comment by CWO-Stanley** [comment]
Thanks for the awnser

Below the screenshot:
![Screenshot_20220101-153715_Firefox](https://user-images.githubusercontent.com/46792280/147852979-4416d8f1-b5ee-4fc4-9d6f-8dd6870b0887.jpg)

**Comment by CWO-Stanley** [comment]
![Uploading Screenshot_20220101-154237_Firefox.jpg…]()

**Comment by CWO-Stanley** [comment]
![Screenshot_20220101-154237_Firefox](https://user-images.githubusercontent.com/46792280/147853419-98b4a1b7-cf1d-48d9-a230-466c195d31a7.jpg)
