### ISSUE TITLE
hide grave accent character

### ISSUE THREAD

**Issue by kasperk81** [kiwiirc/kiwiirc#1635]
When I type

````
this is `a code block`
````
it is visible as:
![Screenshot from 2022-01-09 06-15-21](https://user-images.githubusercontent.com/83082615/148669222-ef4028bf-4906-4b88-bd0c-143f4caee171.png)
should be:
> this is `a code block`

**Comment by kasperk81** [comment]
something to do with https://github.com/kiwiirc/kiwiirc/blob/7d180410bdae175081b8de758163a3201bc95b54/src/libs/MessageFormatter.js#L158-L163
@prawnsalad, is it reasonable to remove opening and closing `` ` `` character from the rendered block on web, matching the behavior of markdown viewers?

**Comment by prawnsalad** [comment]
I'm not really involved in kiwiirc anymore, but when writing that I did purposely leave the characters in so people could see what caused that styling to happen.

**Comment by kasperk81** [comment]
makes sense. another plus is it also maintains formatting if we copy/paste such a message, which is not the case in github or other markdown web viewers. (on github, we have to press `Quote reply` from `...` menu to get the formatted message)
