### ISSUE TITLE
issue on kiwiirc.com/nextclient

### ISSUE THREAD

**Issue by otello89** [kiwiirc/kiwiirc#1636]
Hello,
i can't connect with https://kiwiirc.com/nextclient

in all networks  i try, i get this error:
We couldn't connect to that server :(
Unknown error

Best regards

**Comment by prawnsalad** [comment]
Hello, what IRC network address are you trying to connect to?

**Comment by otello89** [comment]
Hello @prawnsalad my is irc.crazychat.net, but don't work on any type like irc.freenode.net or irc.esper.net

**Comment by AltitudeApps** [comment]
The cert on the websocket endpoint expired.  ( do-e.clients.kiwiirc.com )

**Comment by AltitudeApps** [comment]
it is now fixed  :)

**Comment by otello89** [comment]
thanks @prawnsalad @AltitudeApps

**Comment by prawnsalad** [comment]
Yes you got it, sorry! It seems that server hadn't updated itself. I've updated the certs and all good now.
