### ISSUE TITLE
Sent messages returning to the control input on iOS devices only.

### ISSUE THREAD

**Issue by TimeRider07** [kiwiirc/kiwiirc#1649]
Hello Kiwiirc, There is a bug in my [kiwiirc chat](https://kiwichat.chatsansar.com) that sent messages returns to the control input on iOS devices though there is no such problem on Android devices.

When you join a channel after getting connected, then you PM someone. Then, you go back to the channel. Again, if you come back to the PM that you send to someone, you see the sent message appear in the input area.

**Comment by ItsOnlyBinary** [comment]
this should now be fixed in master
