### ISSUE TITLE
Broken user count

### ISSUE THREAD

**Issue by CoryChaplin** [kiwiirc/kiwiirc#165]
After a few hours on a large traffic channel (above 600 users with massive join/parts), the counter is at 1000 users instead of 660.

**Comment by prawnsalad** [comment]
Is this still an issue? I can't say I've seen this happen as yet after using the new version full time for several months.

**Comment by CoryChaplin** [comment]
I'll check again.

**Comment by ItsOnlyBinary** [comment]
I have left my home server connected to some big channels for several days an have not managed to reproduce this issue. All counts are still correct

**Comment by AllanOcelot** [comment]
Has not been raised again as an issue since 2018 - so closing this issue.
