### ISSUE TITLE
show_joinparts when false should still show the current users join/part/kick

### ISSUE THREAD

**Issue by ItsOnlyBinary** [kiwiirc/kiwiirc#1658]
Especially kick as currently when hiding joinparts it also hides the kick and reason

**Comment by gonzasylv** [comment]
It's true that it's a problem.

**Comment by gonzasylv** [comment]
Here is a plugin to display the reason for a kick even if show_joinpart is set to false : 

https://0bin.net/paste/jk3Z8DdV#k-w/YqEGh79RHOGiX7ay/bgMA/3q9QtJxTNI8iHJk1+
