### ISSUE TITLE
Web widget doesn't work

### ISSUE THREAD

**Issue by sergip76** [kiwiirc/kiwiirc#1663]
Web widget doesn't work for some days.

When trying to connect to a channel this is the error:
We couldn't connect to the server :( Unknown error

Until yesterday the error in console was:
[Error] Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “do-e.clients.kiwiirc.com”, which could put your confidential information at risk. (info, line 0)
https://do-e.clients.kiwiirc.com/webirc/kiwiirc/info?sid=3a8n5f88wocgc&p=1&t=1646979407565

But now, no error in console appears as I try to connect, but it doesn't work.

Mention: @prawnsalad

**Comment by peerau** [comment]
I can't use it either, 
![image](https://user-images.githubusercontent.com/909666/158008916-66fd5101-5c2f-4a76-b1ad-0a521b6992fd.png)

**Comment by prawnsalad** [comment]
Thanks for the heads up! Looks like one of the kiwiirc.com servers was playing up a bit, let me know if you have any more issues

**Comment by sergip76** [comment]
> Thanks for the heads up! Looks like one of the kiwiirc.com servers was playing up a bit, let me know if you have any more issues

Server is not working again.
Error: Took too long to connect

**Comment by sergip76** [comment]
Sorry. It’s ok.
The problem was the IRC Server.
Thanks very much!!!
