### ISSUE TITLE
Messages are being received out of order

### ISSUE THREAD

**Issue by CinchBlue** [kiwiirc/kiwiirc#1668]
**Describe the bug**
I have join an IRC with this client and messages are received and then *rendered* out of order on both Firefox + Chrome. Messages also have inconsistent timestamps on both clients.

**To Reproduce**
1. Join the IRC.
2. Watch as new messages come in and are inserted in the DOM in the past.

**Expected behavior**

**Screenshots**
From `holistic-bead` and `sloppy-steel`.

![image](https://user-images.githubusercontent.com/844699/159145168-be528a95-d11d-41cb-bcff-6874a868920c.png)
![image](https://user-images.githubusercontent.com/844699/159145182-b5997f6e-bdd2-40cd-809f-0eeb4908942e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox, Chrome
 - Version: 98.0.1 for Firefox, 99.0.4844.74 for Chrome (both 64-bit)

**Comment by ItsOnlyBinary** [comment]
This is often a sign that the ircd server you are connecting to, or your clients computer has a incorrect time set.

Kiwi IRC does attempt to calculate this difference to fill in timestamps on events that do not contain server-time timestamp.

If your hosting your own Kiwi IRC maybe its quite out of date and does not contain this feature.

to check the Kiwi IRC version you can type `kiwi.version` into the browsers console (F12) current version is 1.6.1
