### ISSUE TITLE
Cannot join channel (+r) but I can still post there

### ISSUE THREAD

**Issue by jesus2099** [kiwiirc/kiwiirc#1675]
**Describe the bug**

Restricted channel bug where I am denied join but I can still post.

**To reproduce**

Steps to reproduce the behaviour:

1. Join Libera.Chat #musicbrainz channel without account: https://kiwiirc.com/nextclient/irc.libera.chat/#musicbrainz
2. See error and you did not join and the animated kiwi? is still moving
3. Post text
4. Other users see your text and you can see it in the chatlogs: https://chatlogs.metabrainz.org/libera/musicbrainz/msg/5003498/

**Expected behaviour**

The text send input and submit should not be provided if you cannot join.

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Windows 10? (or was it Linux Debian 10?)
 - Browser: Vivaldi? (or was it Firefox?)
 - Version: Latest Vivaldi or latest Firefox ESR

**Smartphone (please complete the following information):**

**Additional context**

I'm using https://kiwiirc.com/nextclient/ to try to connect to #musicbrainz, which is slightly restricted against spammers.
I am not a pro of IRC, I don't really know what is an IRC account or what +r means, just guessing.

I get this big red banner message:

> Cannot join channel (+r) - you need to be logged into your NickServ account

- The kiwi-loading-logo is still visible and animated
- 0 Members are displayed
- The channel is in red
- I don't see what people are sending
- Channel members (connected) cannot see me in the member list and cannot type jes<tab> to mention me

I guess this is all normal.

But what I guess is not normal is that I can still send my texts with the bottom input text field.

- I can send text in the channel and the users see them in live
- I can see them in our chatlogs

The answers from the other users, I still cannot see them live, but I can read them in our chatlogs.

Our chatlogs: https://chatlogs.metabrainz.org/libera/musicbrainz/msg/5002986/

**The https://kiwiirc.com/nextclient/ web client shouldn't be sending my posts to Libera.Chat and Libera.Chat should not accept them.**

---

Copy of https://github.com/Libera-Chat/libera-chat.github.io/issues/230
I don't know if it's a Kiwi IRC bug, a Libera.Chat bug, or both, or none.

**Comment by ItsOnlyBinary** [comment]
This is not a bug, kiwi still allows you to type even though did not join so you could send other commands etc

I suggest you set +n in #musicbrainz "No external messages" https://libera.chat/guides/channelmodes

**Comment by jesus2099** [comment]
OK that's some strange "by design" IRC behaviour, then. :thinking: :smile: 
Thanks for the answer, I will transmit to the channel admins.

**Comment by jesus2099** [comment]
Please try, even though it is _normal_, you will see that it still **looks** buggy, with the animated loading image, the error messages and the text post.
