### ISSUE TITLE
user talked after he was kicked (priority kick event and messages ?)

### ISSUE THREAD

**Issue by avril-la** [kiwiirc/kiwiirc#1679]
**Describe the bug**
gaby's message appeared in the log after he was kicked from the channel

**To Reproduce**
dont know...

**Expected behavior**
the gaby's message "!coupe marron" should be appear in the log before the kick event

**Screenshots**
![kiwiirc](https://user-images.githubusercontent.com/106849156/171966527-e062e510-0699-4b41-bef3-f36b5d825829.png)

**Desktop (please complete the following information):**
 - OS: w10 familial
 - firefox
 - 101.0 (64 bits)

**Comment by ItsOnlyBinary** [comment]
make sure the channel has mode +m (no external messages) this is likely how they spoke without being a member of the channel

**Comment by ZarTek-Creole** [comment]
+n = no external messages
+m = moderate

**Comment by ItsOnlyBinary** [comment]
oops, thanks @ZarTek-Creole

**Comment by avril-la** [comment]
external message was disabled on this channel

**Comment by ItsOnlyBinary** [comment]
Retested and this is not a kiwiirc issue, if messages are getting through +n its a server issue.

inspircd replies with `You cannot send external messages to this channel whilst the +n (noextmsg) mode is set.`

It is intentional that the input box remains when kicked from a channel so commands can still be entered

**Comment by ZarTek-Creole** [comment]
The KICK action was executed almost at the same time as the PRIVMSG of the user gaby. What is surprising is that the KICK action was displayed before Gaby's PRIVMSG. Which makes illogical what we can see. If gaby's PRIVMSG was executed before the KICK, it should be displayed before and not AFTER. It's not a problem with unrealircd/inspircd or other IRCDs.

**Comment by ItsOnlyBinary** [comment]
when things happen at very close times, there can be ordering inconsistencies if the server and client times are not accurate

Its something i intend to try and improve within irc-framework

**Comment by avril-la** [comment]
after some investigations,
i can reproduce the "bug" with two clients views (from the same computer, connected to the same server ip)
![aya1](https://user-images.githubusercontent.com/106849156/189506682-b9029ba6-e993-4e46-a144-6d420a0dd2f0.png)
Cronos is a BotServ given by the server.
As you can see, the arrangement of the 3messages is not the same between KVIrc and KiwiIRC

![aya2](https://user-images.githubusercontent.com/106849156/189506872-446fd294-bbb4-4747-945b-ef79f8c2ce76.png)
it is because, the botserv is not giving a correct "server-time" to his clients through the IRCd
the IRCd and the botserv are not synchronized for the time
(thanks to Fira to have found the problem ^^)

KVIrc like most clients uses the "TCP" ordered packets to show the messages/actions
KiwiIRC use the "server-time" ordered to show the messages/actions

the time-server is used for bouncer playback (like ZNC..)
https://ircv3.net/specs/extensions/server-time
https://blog.alteroot.org/articles/2013-09-03/irc-server-time.html

sorry for my bad english
have a nice day

**Comment by avril-la** [comment]
after some investigations,
i can reproduce the "bug" with two clients views (from the same computer, connected to the same server ip)
![aya1](https://user-images.githubusercontent.com/106849156/189507821-233fe3de-4368-4a29-9943-2d5fd6506920.png)
Cronos is a BotServ given by the server.
As you can see, the arrangement of the 4messages is not the same between KVIrc and KiwiIRC

![aya2](https://user-images.githubusercontent.com/106849156/189507831-e3748763-060b-4609-a186-81f8339b354c.png)
it is because, the botserv is not giving a correct "server-time" to his clients through the IRCd
the IRCd and the botserv are not synchronized for the time
(thanks to Fira to have found the problem ^^)

KVIrc like most clients uses the "TCP" ordered packets to show the messages/actions
KiwiIRC use the "server-time" ordered to show the messages/actions

the time-server is used for bouncer playback (like ZNC..)
https://ircv3.net/specs/extensions/server-time
https://blog.alteroot.org/articles/2013-09-03/irc-server-time.html

sorry for my bad english
have a nice day
