### ISSUE TITLE
nextclient, issues in these days

### ISSUE THREAD

**Issue by otello89** [kiwiirc/kiwiirc#1680]
Hello 
is impossible to connect  on https://kiwiirc.com/nextclient/  
i receive these error randomly:

1) Took too long to connect
2) Unknown domain name or host

i test on https://kiwiirc.com/nextclient/irc.kiwiirc.com/ 
and other network

Best regards

**Comment by gokturkyilmaz** [comment]
I had the same issue I think kiwiirc.com has now new clients IPs **b.clients.kiwiirc.com 78.129.190.63** should be add in your webirc blog.

**Comment by otello89** [comment]
> I had the same issue I think kiwiirc.com has now new clients IPs **b.clients.kiwiirc.com 78.129.190.63** should be add in your webirc blog.

@gokturkyilmaz i already added this to the list of accepted IPs for kiwiirc

**Comment by gokturkyilmaz** [comment]
@otello89, the users from [kiwiirc.com/nextclient/](https://kiwiirc.com/nextclient/) connecting now under **b.clients.kiwiirc.com 78.129.190.63** and I solved mine by adding it.

**Comment by AltitudeApps** [comment]
I am seeing the same thing.  I was able to connect a few hours ago on my iPad.  But on my laptop, I cannot connect.  I try again on my iPad, and I CAN connect.

Now, trying again on my laptop, and I can connect.

very odd.

**Comment by AltitudeApps** [comment]
I was away from my desk for about 2 hours, and I come back to see that I'm disconnected, and unable to reconnect.  (As described above)

Perhaps it is being worked on, or perhaps the automated deployment and/or orchestrator is doing something weird.  Because it is being...  strange.

AH HA!  There, it happened again.  In the time that it took me to type this up, something changed, and I was able to connect.  Although, the first message I sent "/nick BlahBlah" was ignored...  sent it again and it worked as expected.

**Comment by roiconde** [comment]
It seems like some random error that displays (cant connect) "Unknown error". If you try maybe 5 times you connect once, get 4 "Unknown error" messages.

@prawnsalad are you aware of this? Also, is there anything we can do?

Thank you.

**Comment by hello-smile6** [comment]
For networks that have their own kiwiirc web client, try using `wss://<web-client-hostname>/webirc/websocket/` for the "Direct WebSocket" configuration option (in the advanced menu). This works for the following servers:
<table>
<tr><th>IRC network</th><th>URL</th></tr>
<tr><td>Libera.Chat</td><td><a href="https://web.libera.chat/">wss://web.libera.chat/webirc/websocket/</a></td></tr>
<tr><td>Solanum.repl</td><td><a href="https://solanum.9pfs.repl.co/">wss://solanum.9pfs.repl.co/webirc/websocket/</a></td></tr>
</table>

**Comment by roiconde** [comment]
It seems like the server broke completely, as there's no way to connect now. And the error comes instantly, there's no proccesing time.
I've opened another bug https://github.com/kiwiirc/kiwiirc/issues/1680 just in case it gets more attention.

@prawnsalad @ItsOnlyBinary

**Comment by ItsOnlyBinary** [comment]
This was caused by a server completely failing, it has since been replaced by new hardware
