### ISSUE TITLE
Support of UTF-8 or non-ascii nicks on KiwiIRC

### ISSUE THREAD

**Issue by EmmanuelChanel** [kiwiirc/kiwiirc#1689]
**Is your feature request related to a problem? Please describe.**
I use an InspIRCd server and I let its users use UTF-8 nick by my original locale. But my KiwiIRC doesn't let them do that.
I want your KiwiIRC project to enable UTF-8 or non-ascii nicks on KiwiIRC.

**Comment by ItsOnlyBinary** [comment]
It is possible to specify the nick format within your configuration to allow extra characters

https://github.com/kiwiirc/kiwiirc/wiki/Configuration-Options#nick_format

the default: https://github.com/kiwiirc/kiwiirc/blob/master/src/components/startups/Welcome.vue#L150
