### ISSUE TITLE
Nextclient certificate expired

### ISSUE THREAD

**Issue by roiconde** [kiwiirc/kiwiirc#1699]
It seems like the certificate for Nexclient is expired and the client is giving away unknown errors.

- Common Name (CN)	*.clients.kiwiirc.com
- Organization (O)	<Not Part Of Certificate>
- Organizational Unit (OU)	<Not Part Of Certificate>
- Common Name (CN)	R3
- Organization (O)	Let's Encrypt
- Organizational Unit (OU)	<Not Part Of Certificate>
- Issued On	Thursday, June 9, 2022 at 12:17:05 AM
- Expires On	**Wednesday, September 7, 2022 at 12:17:04 AM**
- SHA-256 Fingerprint	A2 FE 91 B8 23 43 25 1D 88 90 12 2C 8A 43 67 9D
- 33 74 57 CE 65 72 10 7E EC 14 9C 85 53 C1 A1 31
- SHA-1 Fingerprint	EC 7C FD DA 6D D6 1B 9D C2 61 D2 61 17 1D 51 8D
- D9 A8 F6 35

**Comment by roiconde** [comment]
@ItsOnlyBinary  @prawnsalad

**Comment by AltitudeApps** [comment]
came here to post this.   thanks for reporting.
