### ISSUE TITLE
KiwiIRC Widget - 'Couldn't connect to the server' error

### ISSUE THREAD

**Issue by RicBrooks** [kiwiirc/kiwiirc#1700]
Hi there,

This issue reported back in January seems to have arisen again. Users of the KiwiIRC embedded widget are reporting the following error: "We couldn't connect to the server :(
Unknown error"

Would appreciate it if you could look into this and get the widget operational again.

**Comment by ItsOnlyBinary** [comment]
Duplicate of #1699
