### ISSUE TITLE
Nexclient returning forbidden to connect on all networks

### ISSUE THREAD

**Issue by roiconde** [kiwiirc/kiwiirc#1703]
The nextclient is returning a "Forbidden to connect" error for all the networks I've tried so far.

Also, the custom clients with settings ( https://kiwiirc.com/nextclient/?settings=XXXXXXX ) is giving away a 500 error.

**Comment by roiconde** [comment]
Seems to be fixed now.

**Comment by roiconde** [comment]
Nexclient is giving now "Forbidden to connect" on all networks again.

**Comment by sergip76** [comment]
Yes, still giving "Forbidden to connect" on all networks.

**Comment by roiconde** [comment]
Internally there's a 500 error:

DevTools failed to load source map: Could not load content for https://kiwiirc.com/nextplugins/plugin-conference.min.js.map: HTTP error: status code 500, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kiwiirc.com/nextplugins/plugin-fileuploader.js.map: HTTP error: status code 500, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by AltitudeApps** [comment]
commenting to subscribe to this thread.

**Comment by roiconde** [comment]
@ItsOnlyBinary @prawnsalad is there any update on this?

**Comment by prawnsalad** [comment]
I'm starting to look into this now, sorry!

**Comment by prawnsalad** [comment]
Hi @roiconde could you confirm this is working again now?

We had a hardware failure and corrupt databases which confused a few things :(

**Comment by mark-y** [comment]
Hello, @prawnsalad -- it is working for me now. Thanks!

**Comment by roiconde** [comment]
@prawnsalad Working just fine! Thanks once again.
