### ISSUE TITLE
Custom clients in Nextclient error 500

### ISSUE THREAD

**Issue by roiconde** [kiwiirc/kiwiirc#1708]
The custom clients in Nextclient are giving error 500:

(Samples)
https://kiwiirc.com/nextclient/?settings=fe2597110a602a749a6d7180f4169a0a
https://kiwiirc.com/nextclient/?settings=ws64rbgn43d
https://kiwiirc.com/nextclient/?settings=3ae259d97c2bc6f334e35f27a2485574

The nextclient alone is working just fine.

@prawnsalad @ItsOnlyBinary

**Comment by prawnsalad** [comment]
Hi, I'm looking into this at the moment. We had a database failure last week and obviously something is quite right yet - will update when I have something!

**Comment by prawnsalad** [comment]
@roiconde thanks for those examples - I've managed to restore the correct database configs and they are loading correctly now. If you could give them a quick try to confirm!

**Comment by roiconde** [comment]
Seems to be working as expected now. Thanks!

**Comment by roiconde** [comment]
It seems like the issue is happening again @prawnsalad

**Comment by roiconde** [comment]
I've found that https://kiwiirc.com/login/reset_password is also broken with 500 error, with all the custom clients.

@prawnsalad  @ItsOnlyBinary

**Comment by troilus** [comment]
still 500 error
