### ISSUE TITLE
TLS protocol version and ciphers

### ISSUE THREAD

**Issue by M-Stenzel** [kiwiirc/kiwiirc#1709]
Hi team,

I was not able to find any information regarding TLS protocol version and cipher settings.
The default allows for protocol version 1.0 and 1.1 support - which are outdated.

Where to change this behavior?

Martin.

**Comment by ItsOnlyBinary** [comment]
Currently it just uses the golang tls defaults and does not expose those options via config.conf
If you want to edit the source code to change protocol versions etc see here: [gateway.go#L220](https://github.com/kiwiirc/webircgateway/blob/master/pkg/webircgateway/gateway.go#L220)

https://pkg.go.dev/crypto/tls#Config

**Comment by ItsOnlyBinary** [comment]
another option would be to reverse proxy webircgateway and use apache/nginx for the TLS part

[kiwiirc.nginx](https://gist.github.com/ItsOnlyBinary/ae8d41c4542e66bb259b0f1b312c7d29)
[kiwiirc.apache](https://gist.github.com/ItsOnlyBinary/3e38b66d71e51d12d7df32f739978799)
