### ISSUE TITLE
Problems with server

### ISSUE THREAD

**Issue by sergip76** [kiwiirc/kiwiirc#1716]
During the last 10 hours it has not been possible to access any network due to a problem in the Kiwi server.
When trying to access, a connection error with the server appears (Unknown error).
Please check it.
Thank you very much.

**Comment by roiconde** [comment]
issue with the server certificate (again)

**Comment by roiconde** [comment]
It seems like Certbot autorenew is not working properly in the server as the server certificate issue is recurring @prawnsalad @ItsOnlyBinary

**Comment by FavoritoHJS** [comment]
whatever it was, it seems to have fixed itself.
