### ISSUE TITLE
 Disable trying different nickname on connect

### ISSUE THREAD

**Issue by SPiRiT369** [kiwiirc/kiwiirc#1718]
**Description**
Could it be possible to add a config flag to disable trying to connect with different nick in case the provided one fails? (e.g. in use)

**Why this would be useful**
In my case, clicking "Connect" sends nick+password. If the user is already logged-in with other session, kiwi tries a different nick which fails due to invalid nick/password (that newly generated nick is unknown). The user then gets a wrong server reply ("wrong nick or password") instead of the original response ("nick is already in use").

I think this could be nice to have this feature as optional anyway.

**Comment by ItsOnlyBinary** [comment]
The following would need reworking to be all one block: [IrcClient.js#L874-L905](https://github.com/kiwiirc/kiwiirc/blob/master/src/libs/IrcClient.js#L874-L905)
can get setting with: `state.setting('changeNickOnCollision')`
It should also maybe trim any numbers from the nick before appending new ones

I will try to look into it soon if I don't get a pull-request

**Comment by SPiRiT369** [comment]
Works great, **thanks!** <3
Might be a good idea to update it on this page: https://github.com/kiwiirc/kiwiirc/wiki/Configuration-Options
