### ISSUE TITLE
Error Connecting (Error: xhr poll error)

### ISSUE THREAD

**Issue by S1700** [kiwiirc/kiwiirc#1735]
When I try connecting to an IRC chat, with any username and at any channel it fails and says `Error Connecting (Error: xhr poll error)`

Steps to reproduce the behaviour:
1. Add the iframe to your site
2. Load up the page
3. Type any random username and chat
4. See the error

**Expected behaviour**
Join the IRC?

**Screenshots**
![image](https://user-images.githubusercontent.com/68336568/220607677-9aea7537-865f-4ec0-8bd5-0d25bb298c0f.png)
![image](https://user-images.githubusercontent.com/68336568/220607713-2f03fbc9-edda-46c5-a8c5-aa135c706db6.png)
![image](https://user-images.githubusercontent.com/68336568/220607759-5d12888c-7550-49c0-b347-a23d7a92e17a.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Brave/Chrome
 - Version: 1.48.167

**Additional context**
I have tried disabling any adblocker or tracker blocker but still returned the same error

**Comment by S1700** [comment]
Ah, I think I just realized what is causing this, I made this site on localhost so there is no cert. And I guess that's causing the CORS error. Is there any way to develop it locally?

**Comment by S1700** [comment]
I installed a customer localhost cert and it still doesn't seem to work, idk if its cuz the cert is self-signed but I give up. If anyone has any ideas please let me know.

**Comment by skilo83** [comment]
I can confirm this is happening for me as well. it has nothing to do with the cert, i'm using certbot with Let's Encrypt.

**Comment by Marco-Lugo** [comment]
I confirm too.

**Comment by mariteaux** [comment]
I suspect this is because kiwiirc.com/client/ no longer works. This is the embedded page the iframe is trying to use--navigate to it and you'll be redirected to kiwiirc.com/nextclient/. This works just fine, though I'm looking into ways to customize the layout of the iframe because the new client is a bit of a tight fit in my 900px of space or so.

**Comment by mro-1337** [comment]
still doesn't work for me.
