### ISSUE TITLE
Can't connect to any servers due to a bad clients.kiwiirc.com certificate

### ISSUE THREAD

**Issue by FavoritoHJS** [kiwiirc/kiwiirc#1742]
Time for yet another showstopper!

**Describe the bug**
When trying to connect to any network, the connection fails.

After looking in the dev console, it says a cross-site request failed, and trying to access the url directly leads to a certificate error.

**To Reproduce**
1. Enter into the kiwiirc.com newclient
2. Attempt to join any network.
3. _Unknown error_. If this doesn't happen, I blame timezones.

**Expected behavior**
Join an IRC network.

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 x64
 - Browser: Firefox
 - Version: 110.0.1 64-bit

**Additional context**
The certificate expired as of half an hour or so.

**Comment by roiconde** [comment]
Recurring issue that happens every 2 months ( since last year )... @prawnsalad @ItsOnlyBinary

**Comment by FavoritoHJS** [comment]
how hard would it be to automatically refresh certificates every month?

**Comment by sergip76** [comment]
Certificate is still expired... :-(

**Comment by roiconde** [comment]
I've sent an e-mail to Darren ( @prawnsalad ) lets hope he reads it and fixes the issue soon.

**Comment by FavoritoHJS** [comment]
it's fixed now, it seems
