### ISSUE TITLE
Unknown error on connect

### ISSUE THREAD

**Issue by roiconde** [kiwiirc/kiwiirc#1745]
It seems like there's an issue with the kiwi server (this time not related to server certificates) I think its xhr server poll timeout but not sure as I'm on mobile now.

@prawnsalad @ItsOnlyBinary

**Comment by prawnsalad** [comment]
Thanks for reporting, it seems a digitalocean migration has interfered with something. I've kicked what I think might be causing an issue, could you give it a retry?

Also, which irc server address were you trying to connect to?
