### ISSUE TITLE
can't connect any server unknown error

### ISSUE THREAD

**Issue by umutcaptain** [kiwiirc/kiwiirc#1758]
hello,

i bought a dedicated machine and setup correctly everything with myself ( as a beginner i did perfect as i guess )

i stucked at 2 things for now and im waiting yr kindly helps asap.

1 - when i started webircgateway i got this error.

2023/05/26 10:34:57.240338 Using config /home/ubuntu/webircgateway/config.conf
2023/05/26 10:34:57.241268 L_WARN listen tcp 0.0.0.0:80: bind: permission denied

i couldnt find any solution how to pass this.

2 - i setup kiwiirc, page opening but i cant connect to any server. 

when i push the button "connect" it says " we couldnt connect to any server, unknown error."

if smbdy helps i would be so happy.

waiting yrs.

thx.

**Comment by umutcaptain** [comment]
ty very much for your kindly reply @ItsOnlyBinary 

first of all, i ve read all of your documentary but as a beginner "myself" i couldnt find how to use this reverse proxy and conf. can you explain to me if u ve a little bit time.

regards,

umut

**Comment by ItsOnlyBinary** [comment]
Its hard to explain without knowing what your stuck on, the linked files are example virtual server configs for nginx/apache

they would normally go in /etc/{apache2,nginx}/sites-available/ then be symlinked to sites-enabled (`a2ensite configName` for apache not sure for nginx)

**Comment by umutcaptain** [comment]
root@ns3096095:/etc/apache2/sites-enabled# 
000-default.conf  kiwiirc.apache

root@ns3096095:/etc/apache2/sites-enabled# service apache2 restart
root@ns3096095:~/webircgateway# ./webircgateway
2023/05/26 12:19:55.302476 Using config /root/webircgateway/config.conf
2023/05/26 12:19:55.303224 L_WARN listen tcp 0.0.0.0:80: bind: address already in use

somewhere else i m faulty.. sorry abt that.
