### ISSUE TITLE
Nicklist Avatar A B C

### ISSUE THREAD

**Issue by bernardleite** [kiwiirc/kiwiirc#1759]
Which plugin adds the default Kiwi avatar to channel member nicks? (Nicklist)

Ex: 
**A** @antony
**B** +bob
**C** +cezarr

**Comment by ItsOnlyBinary** [comment]
https://github.com/kiwiirc/kiwiirc/wiki/Configuration-Options#nicklist_avatars

^^^ note it goes in "buffers" with your config.json
