### ISSUE TITLE
KiwiIRC website down

### ISSUE THREAD

**Issue by roiconde** [kiwiirc/kiwiirc#1760]
Currently, the KiwiIRC website is down ( Gateway time-out Error code 504 from CloudFlare)

**Comment by roiconde** [comment]
@ItsOnlyBinary @prawnsalad

**Comment by westor7** [comment]
Any news? someone?

**Comment by ItsOnlyBinary** [comment]
Nothing I can do unfortunately

**Comment by sergip76** [comment]
Web site is still down. Chats don't work. Any news?

**Comment by ItsOnlyBinary** [comment]
prawnsalad has restored the website :)
