### ISSUE TITLE
Nodejs >=18 support 

### ISSUE THREAD

**Issue by d3xt3r01** [kiwiirc/kiwiirc#1764]
**Describe the bug**
The current 1.6.1 of kw seems to only support nodejs <=16 which will be EOL(including security) in 2 months. node 18 still has 1 year left though...

**To Reproduce**
get the 1.6.1 zip
yarn install && yarn build

**Expected behavior**
build

**Desktop (please complete the following information):**
 - OS: docker alpine:3.18

**Comment by ItsOnlyBinary** [comment]
v1.7.0 can now be built using node 18.x (maybe 20.x)

https://github.com/kiwiirc/kiwiirc/releases/latest
