### ISSUE TITLE
linkifyChannels is too greedy

### ISSUE THREAD

**Issue by TheDaemoness** [kiwiirc/kiwiirc#1767]
**Describe the bug**
When KiwiIRC parses channel names in message text, it adds characters to the channel name that are part of message formatting, e.g. the closing parenthesis of a kick reason if the channel name is at the end of a kick reason.

**To Reproduce**
1. Kick yourself from a channel with a kick reason that includes a channel name as the last word, e.g. "#test".
2. Note that the closing parenthesis is included as part of the clickable channel name, e.g. "#test)"

**Expected behavior**
Channel linkification shouldn't cross over from an argument to `formatText` to the rest of the template.

More generally, linkified channel names should *probably* omit trailing non-alphanumeric characters,
as these are probably more likely than not to *not* be part of a channel name.

**Comment by ItsOnlyBinary** [comment]
Could you provide some examples please with strings, what is matched and what is expected to match?
