### ISSUE TITLE
registration time out Inspircd

### ISSUE THREAD

**Issue by Menoblack** [kiwiirc/kiwiirc#1775]
Registration fails on the newest version of Inspircd in some cases. Kiwi doesn't send /CAP END after sending CAP LS 302 and receiving the answer CAP * LS :[inspircd.org/poison](http://inspircd.org/poison) . Inspircd waits for that response untill the registration times out.

Solution: Make sure CAP END is send properly

**Comment by ItsOnlyBinary** [comment]
is this on kiwiirc.com or hosted yourself?  if self hosted what version?

**Comment by Menoblack** [comment]
that workaround also worked :)

**Comment by ItsOnlyBinary** [comment]
when you said latest you are aware i did a release yesterday? which i think includes the fix for not having the modules loaded

**Comment by Menoblack** [comment]
is kiwiirc.com not on the latest yet then?

**Comment by ItsOnlyBinary** [comment]
not yet

**Comment by Menoblack** [comment]
Ah, then I guess I was on the version before the last. on 1.7 it seems to be fixed, unlucky timing
