### ISSUE TITLE
How to enable emoji picker in mobile view

### ISSUE THREAD

**Issue by legendskyk** [kiwiirc/kiwiirc#1795]
How i enable Emoji picker in Mobile View?

![image](https://github.com/kiwiirc/kiwiirc/assets/42233490/3cd5ae7b-09f5-4ce1-a0cc-d382f49098d6)

**Comment by ItsOnlyBinary** [comment]
if your using 1.7.x see my work-in-progress new documentation: https://github.com/ItsOnlyBinary/kiwiirc/wiki/Configuration#forceshowemojipicker

**Comment by legendskyk** [comment]
Its verion kiwiirc_19.04.24.1 i did put force show emoji picture still not show in mobile

**Comment by ItsOnlyBinary** [comment]
that's a super old version (2019) i don't think there is a way to force it.

Suggest updating https://github.com/kiwiirc/kiwiirc/releases/latest/

**Comment by legendskyk** [comment]
which one is for ubuntu?

**Comment by ItsOnlyBinary** [comment]
https://github.com/kiwiirc/kiwiirc/releases/download/v1.7.1/kiwiirc-server_v1.7.1-1_linux_amd64.deb

you may have to force the install due to versioning numbers changing from year

**Comment by ItsOnlyBinary** [comment]
backup your configs/plugins first to be safe

**Comment by legendskyk** [comment]
its give error:

Job for kiwiirc.service failed because the control process exited with error code.
See "systemctl status kiwiirc.service" and "journalctl -xe" for details.
dpkg: error processing package kiwiirc (--install):
 installed kiwiirc package post-installation script subprocess returned error exit status 1
Processing triggers for systemd (245.4-4ubuntu3.22) ...
Errors were encountered while processing:
 kiwiirc
root@vps585838:~# systemctl status kiwiirc.service
● kiwiirc.service - LSB: KiwiIRC server
     Loaded: loaded (/etc/init.d/kiwiirc; generated)
     Active: failed (Result: exit-code) since Fri 2023-09-15 01:12:09 UTC; 25s >
       Docs: man:systemd-sysv-generator(8)

Sep 15 01:12:09 vps585838 systemd[1]: Starting LSB: KiwiIRC server...
Sep 15 01:12:09 vps585838 kiwiirc[698017]: Starting kiwiirc
Sep 15 01:12:09 vps585838 kiwiirc[698017]: Unable to start, see /var/log/kiwiir>
Sep 15 01:12:09 vps585838 systemd[1]: kiwiirc.service: Control process exited, >
Sep 15 01:12:09 vps585838 systemd[1]: kiwiirc.service: Failed with result 'exit>
Sep 15 01:12:09 vps585838 systemd[1]: Failed to start LSB: KiwiIRC server.

**Comment by ItsOnlyBinary** [comment]
that might be because your /etc/kiwiirc/config.conf is now outdated.

the default config: https://github.com/kiwiirc/webircgateway/blob/master/config.conf.example

`journalctl -u kiwiirc -n 50` may give some clues

**Comment by legendskyk** [comment]
-- The job identifier is 129942 and the job result is failed.
Sep 15 01:23:39 vps585838 sshd[698387]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser=>
Sep 15 01:23:40 vps585838 sshd[698387]: Failed password for root from 218.92.0.97 port 38706 ssh2
Sep 15 01:23:44 vps585838 sshd[698387]: Failed password for root from 218.92.0.97 port 38706 ssh2
Sep 15 01:23:47 vps585838 sshd[698387]: Failed password for root from 218.92.0.97 port 38706 ssh2
Sep 15 01:23:48 vps585838 sshd[698387]: Received disconnect from 218.92.0.97 port 38706:11:  [preauth]
Sep 15 01:23:48 vps585838 sshd[698387]: Disconnected from authenticating user root 218.92.0.97 port 38706 [preauth]
Sep 15 01:23:48 vps585838 sshd[698387]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=21>

**Comment by ItsOnlyBinary** [comment]
they are errors/warnings from sshd not kiwiirc

**Comment by legendskyk** [comment]
kiwiirc not working

**Comment by legendskyk** [comment]
Sep 15 01:29:36 vps585838 kiwiirc[698498]: Starting kiwiirc
Sep 15 01:29:36 vps585838 kiwiirc[698498]: Starting kiwiirc
Sep 15 01:29:36 vps585838 kiwiirc[698498]: Unable to start, see /var/log/kiwiirc.log
Sep 15 01:29:36 vps585838 systemd[1]: kiwiirc.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- An ExecStart= process belonging to unit kiwiirc.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Sep 15 01:29:36 vps585838 systemd[1]: kiwiirc.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support

**Comment by ItsOnlyBinary** [comment]
`journalctl -u kiwiirc -n 50`  or `/var/log/kiwiirc.log`  maybe one will have a better clue

**Comment by legendskyk** [comment]
2023/09/13 23:11:01.318794 Using config /etc/kiwiirc/config.conf
2023/09/13 23:11:01.328234 L_WARN Config section reverse_proxies has invalid entry, 2400
2023/09/13 23:11:01.328253 L_WARN Config section reverse_proxies has invalid entry, 2606
2023/09/13 23:11:01.328273 L_WARN Config section reverse_proxies has invalid entry, 2803
2023/09/13 23:11:01.328277 L_WARN Config section reverse_proxies has invalid entry, 2405
2023/09/13 23:11:01.328287 L_WARN Config section reverse_proxies has invalid entry, 2a06
2023/09/13 23:11:01.328290 L_WARN Config section reverse_proxies has invalid entry, 2c0f
2023/09/13 23:17:56.125578 Using config /etc/kiwiirc/config.conf
2023/09/13 23:17:56.136810 L_WARN Config section reverse_proxies has invalid entry, 2400
2023/09/13 23:17:56.136827 L_WARN Config section reverse_proxies has invalid entry, 2606
2023/09/13 23:17:56.136830 L_WARN Config section reverse_proxies has invalid entry, 2803
2023/09/13 23:17:56.136834 L_WARN Config section reverse_proxies has invalid entry, 2405
2023/09/13 23:17:56.136844 L_WARN Config section reverse_proxies has invalid entry, 2a06
2023/09/13 23:17:56.136864 L_WARN Config section reverse_proxies has invalid entry, 2c0f
2023/09/14 17:39:40.221872 L_WARN client:36 Error connecting to the upstream IRCd. dial tcp: i/o timeout
kiwiirc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by kiwiirc)
kiwiirc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by kiwiirc)
kiwiirc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by kiwiirc)
kiwiirc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by kiwiirc)
kiwiirc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by kiwiirc)
kiwiirc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by kiwiirc)
kiwiirc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by kiwiirc)
kiwiirc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by kiwiirc)
kiwiirc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by kiwiirc)
kiwiirc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by kiwiirc)
kiwiirc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by kiwiirc)
kiwiirc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by kiwiirc)

**Comment by ItsOnlyBinary** [comment]
oh old ubuntu, install https://github.com/kiwiirc/kiwiirc/releases/download/v1.7.0/kiwiirc-server_v1.7.0-2_linux_amd64.deb

**Comment by legendskyk** [comment]
how we will make emoji show in mobile in this new version?

**Comment by legendskyk** [comment]
now i have to again see css file to pin nicklist in mobile view :S

**Comment by ItsOnlyBinary** [comment]
yes 1.7.0 will work with the new config.json option, i will need to manually build 1.7.1 again tomorrow, auto build is not working

**Comment by legendskyk** [comment]
kindly make it like nicklist can be pinned on mobile view is that possible in new version?

**Comment by ItsOnlyBinary** [comment]
Files are updated for 1.7.1 and should now work fine with older ubuntu https://github.com/kiwiirc/kiwiirc/releases/tag/v1.7.1
