### ISSUE TITLE
DeprecationWarning: Invalid 'main' field in

### ISSUE THREAD

**Issue by farazi** [kiwiirc/kiwiirc#1799]
[root@194 KiwiIRC]# ./kiwi build
(node:6693) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/mimajor                                                                                                             /KiwiIRC/node_modules/po2json/package.json' of './lib/po2json'. Please either fi                                                                                                             x that or report it to the module author

How can I fix. There is such an error.

**Comment by ItsOnlyBinary** [comment]
sounds like your trying to build the old unsupported kiwiirc at https://github.com/prawnsalad/KiwiIRC  not the one from here.

Check releases in this repo for prebuilt files.

Or read the work-in-progress new documentation here: https://github.com/ItsOnlyBinary/kiwiirc/wiki/Getting-Started

**Comment by farazi** [comment]
i dont know. i from turkiye. i trying install as your project web page (kiwiirc.com); 

Download the Kiwi source or clone the git repository
$ git clone https://github.com/prawnsalad/KiwiIRC.git && cd KiwiIRC

Install the dependencies
$ npm install

Copy and edit the configuration as needed
$ cp config.example.js config.js
$ nano config.js

Make sure the client code is built
$ ./kiwi build

**Comment by ItsOnlyBinary** [comment]
these are old instructions, for the old kiwiirc.

https://github.com/kiwiirc/kiwiirc/releases/latest

https://github.com/ItsOnlyBinary/kiwiirc/wiki/Getting-Started

**Comment by farazi** [comment]
> these are old instructions, for the old kiwiirc.
> 
> https://github.com/kiwiirc/kiwiirc/releases/latest
> 
> https://github.com/ItsOnlyBinary/kiwiirc/wiki/Getting-Started

yes it's working http://irc.beklenti.com.tr:8000/

kiwiirc very good thanks for kiwiirc.

**Comment by farazi** [comment]
> might now want to read https://github.com/ItsOnlyBinary/kiwiirc/wiki/Getting-Started#configconf
> 
> and use https://gist.github.com/ItsOnlyBinary/3e38b66d71e51d12d7df32f739978799 as an example to reverse proxy so the port number is not need ;)

perfect. :) So, how can I change the character set in the new system? Turkish characters as utf-8 seem problematic.

**Comment by ItsOnlyBinary** [comment]
"startupOptions": { "encoding": "utf-8" }

that is one missing from https://github.com/ItsOnlyBinary/kiwiirc/wiki/Configuration so i shall add that to my list

**Comment by ItsOnlyBinary** [comment]
I cannot fix the donate button on kiwiirc.com I will let prawnsalad (founder) know its not working next time i seem them though.

**Comment by farazi** [comment]
> I cannot fix the donate button on kiwiirc.com I will let prawnsalad (founder) know its not working next time i seem them though.

Ok. I have one last question. I think the codes in the link below are prepared for the litespeed vhost file. I am using nghitx. How should I fix the codes? kiwiirc: https://gist.github.com/ItsOnlyBinary/3e38b66d71e51d12d7df32f739978799

`server {
	listen 194.87.246.xx:80;	
	server_name mail.irc.xxx.com.tr;

	access_log /usr/local/apache/domlogs/irc.xxx.com.tr.bytes bytes;
	access_log /usr/local/apache/domlogs/irc.xxx.com.tr.log combined;
	error_log /usr/local/apache/domlogs/irc.xxx.com.tr.error.log error;

	location / {
		proxy_pass  http://127.0.0.1:2095;
		include proxy.inc;
	}`

**Comment by ItsOnlyBinary** [comment]
the one i attached was for apache2, seemed to be what you are running.
nginx config is here: https://gist.github.com/ItsOnlyBinary/ae8d41c4542e66bb259b0f1b312c7d29
