### ISSUE TITLE
SSL connection problem

### ISSUE THREAD

**Issue by farazi** [kiwiirc/kiwiirc#1801]
I configured it to log in without SSL and port but I can't connect.  I want to know exactly where the error information is.

**conclusion**
Working: https://irc.beklenti.com.tr
Working: http://irc.beklenti.com.tr
Working (no ssl): http://irc.beklenti.com.tr:8000
Not working: http://irc.beklenti.com.tr:8000

**My Configurations:**

**1) Creating ssl pem cert**

 [root@194 ~]# sudo certbot --nginx -d irc.beklenti.com.tr -d irc.beklenti.com.tr
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org
Requesting a certificate for irc.beklenti.com.tr
Deploying Certificate to VirtualHost /etc/nginx/conf.d/vhosts/irc.beklenti.com.tr.ssl.conf
Redirecting all traffic on port 80 to ssl in /etc/nginx/conf.d/vhosts/irc.beklenti.com.tr.conf

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Congratulations! You have successfully enabled https://irc.beklenti.com.tr
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Subscribe to the EFF mailing list (email: seda@beklenti.com.tr).
Starting new HTTPS connection (1): supporters.eff.org

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/irc.beklenti.com.tr/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/irc.beklenti.com.tr/privkey.pem
   Your certificate will expire on 2024-01-02. To obtain a new or
   tweaked version of this certificate in the future, simply run
   certbot again with the "certonly" option. To non-interactively
   renew *all* of your certificates, run "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

**2) editing /etc/nginx/conf.d/vhosts/irc.beklenti.com.tr.conf**

 server {
    listen 443 ssl;
    listen [::]:443 ssl;
    
    server_name irc.beklenti.com.tr;
    
    ssl_certificate /etc/letsencrypt/live/irc.beklenti.com.tr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/irc.beklenti.com.tr/privkey.pem;
    
    location / {
        index index.html;
        
        # Path to kiwiirc client files
        root /usr/share/kiwiirc/;
    }
    
    location /webirc/ {
        # Forward incoming requests to local webircgateway socket
        proxy_pass http://irc.beklenti.com.tr:8000/webirc/;

        # Set http version and headers
        proxy_http_version 1.1;
        
        # Add X-Forwarded-* headers
        proxy_set_header X-Forwarded-Host   $host;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_set_header X-Forwarded-For    $remote_addr;

        # Allow upgrades to websockets
        proxy_set_header Upgrade     $http_upgrade;
        proxy_set_header Connection  "upgrade";

    }
    
    location /files/ {
        # Forward incoming requests to local fileuploader instance
        proxy_pass http://irc.beklenti.com.tr:8000/files/;

        # Disable request and response buffering
        proxy_request_buffering  off;
        proxy_buffering          off;
        proxy_http_version       1.1;

        # Add X-Forwarded-* headers
        proxy_set_header X-Forwarded-Host   $host;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_set_header X-Forwarded-For    $remote_addr;

        # Allow fileuploader to control the max size
        client_max_body_size         0;
    }
}

**Restarting nginx and kiwiirc.**

**note: subdomain SSL working.**

**Comment by ItsOnlyBinary** [comment]
just do the https in your nginx and keep the kiwiirc server side http only (listen on 127.0.0.1 so its only accessible via nginx)

**Comment by farazi** [comment]
> just do the https in your nginx and keep the kiwiirc server side http only (listen on 127.0.0.1 so its only accessible via nginx)

nginx conf file now:

server {
    if ($host = irc.beklenti.com.tr) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 194.87.246.56:80;	
	server_name irc.beklenti.com.tr  www.irc.beklenti.com.tr;
	root /home/mimajor/public_html;
	index index.php index.html index.htm;
	access_log /usr/local/apache/domlogs/irc.beklenti.com.tr.bytes bytes;
	access_log /usr/local/apache/domlogs/irc.beklenti.com.tr.log combined;
	error_log /usr/local/apache/domlogs/irc.beklenti.com.tr.error.log error;

	location / {

		location ~.*\.(jpeg|jpg|png|gif|bmp|ico|svg|css|js)$ {			
			expires max;
		}
		
		location ~ [^/]\.php(/|$) {
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			if (!-f $document_root$fastcgi_script_name) {
				return  404;
			}

			fastcgi_pass    unix:/opt/alt/php-fpm/usr/var/sockets/mimajor.sock;
			fastcgi_index   index.php;
			include         /etc/nginx/fastcgi_params;
		}

	}

	location ~* "/\.(htaccess|htpasswd)$" {deny all;return 404;}

	disable_symlinks if_not_owner from=/home/mimajor/public_html;

	location /.well-known/acme-challenge {
		default_type "text/plain";
		alias /usr/local/apache/autossl_tmp/.well-known/acme-challenge;
	}

	location /.well-known/pki-validation {
		default_type "text/plain";
		alias /usr/local/apache/autossl_tmp/.well-known/acme-challenge;
	}


}

server {
	listen 194.87.246.56:80;	
	server_name webmail.irc.beklenti.com.tr;

	access_log /usr/local/apache/domlogs/irc.beklenti.com.tr.bytes bytes;
	access_log /usr/local/apache/domlogs/irc.beklenti.com.tr.log combined;
	error_log /usr/local/apache/domlogs/irc.beklenti.com.tr.error.log error;

	location / {
		proxy_pass  http://127.0.0.1:2095;
		include proxy.inc;
	}

	location ~ /\.ht    {deny all;}
	location ~ /\.svn/  {deny all;}
	location ~ /\.git/  {deny all;}
	location ~ /\.hg/   {deny all;}
	location ~ /\.bzr/  {deny all;}

	disable_symlinks if_not_owner from=/home/mimajor/public_html;

	location /.well-known/acme-challenge {
		default_type "text/plain";
		alias /usr/local/apache/autossl_tmp/.well-known/acme-challenge;
	}

	location /.well-known/pki-validation {
		default_type "text/plain";
		alias /usr/local/apache/autossl_tmp/.well-known/acme-challenge;
	}
}



server {
	listen 194.87.246.56:80;	
	server_name mail.irc.beklenti.com.tr;

	access_log /usr/local/apache/domlogs/irc.beklenti.com.tr.bytes bytes;
	access_log /usr/local/apache/domlogs/irc.beklenti.com.tr.log combined;
	error_log /usr/local/apache/domlogs/irc.beklenti.com.tr.error.log error;

	location / {
		proxy_pass  http://127.0.0.1:2095;
		include proxy.inc;
	}

	location ~ /\.ht    {deny all;}
	location ~ /\.svn/  {deny all;}
	location ~ /\.git/  {deny all;}
	location ~ /\.hg/   {deny all;}
	location ~ /\.bzr/  {deny all;}

	disable_symlinks if_not_owner from=/home/mimajor/public_html;

	location /.well-known/acme-challenge {
		default_type "text/plain";
		alias /usr/local/apache/autossl_tmp/.well-known/acme-challenge;
	}

	location /.well-known/pki-validation {
		default_type "text/plain";
		alias /usr/local/apache/autossl_tmp/.well-known/acme-challenge;
	}
}

server {
	listen 194.87.246.56:80;	
	server_name cpanel.irc.beklenti.com.tr;

	access_log /usr/local/apache/domlogs/irc.beklenti.com.tr.bytes bytes;
	access_log /usr/local/apache/domlogs/irc.beklenti.com.tr.log combined;
	error_log /usr/local/apache/domlogs/irc.beklenti.com.tr.error.log error;

	location / {
		proxy_pass  https://127.0.0.1:2083;
		include proxy.inc;
	}

	location /pma {
		proxy_pass  https://127.0.0.1:2031;
		include proxy.inc;
	}

	location /roundcube {
		proxy_pass  https://127.0.0.1:2031;
		include proxy.inc;
	}

	location ~ /\.ht    {deny all;}
	location ~ /\.svn/  {deny all;}
	location ~ /\.git/  {deny all;}
	location ~ /\.hg/   {deny all;}
	location ~ /\.bzr/  {deny all;}

	disable_symlinks if_not_owner from=/home/mimajor/public_html;

	location /.well-known/acme-challenge {
		default_type "text/plain";
		alias /usr/local/apache/autossl_tmp/.well-known/acme-challenge;
	}

	location /.well-known/pki-validation {
		default_type "text/plain";
		alias /usr/local/apache/autossl_tmp/.well-known/acme-challenge;
	}
}


server {
    listen 80;
    listen [::]:80;
    
    server_name irc.beklenti.com.tr;

    location / {
        # Redirect to https
        return 301 https://$server_name$request_uri;
    }
}

server {
    listen 80;
    listen [::]:80;
    
    server_name irc.beklenti.com.tr;

    location / {
        # Redirect to https
        return 301 https://$server_name$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    
    server_name irc.beklenti.com.tr;
    
    ssl_certificate /etc/letsencrypt/live/irc.beklenti.com.tr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/irc.beklenti.com.tr/privkey.pem;
    
    location / {
        index index.html;
        
        # Path to kiwiirc client files
        root /usr/share/kiwiirc/;
    }
    
    location /webirc/ {
        # Forward incoming requests to local webircgateway socket
        proxy_pass http://127.0.0.1:800/webirc/;

        # Set http version and headers
        proxy_http_version 1.1;
        
        # Add X-Forwarded-* headers
        proxy_set_header X-Forwarded-Host   $host;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_set_header X-Forwarded-For    $remote_addr;

        # Allow upgrades to websockets
        proxy_set_header Upgrade     $http_upgrade;
        proxy_set_header Connection  "upgrade";

    }
    
    location /files/ {
        # Forward incoming requests to local fileuploader instance
        proxy_pass http://127.0.0.1:8000/files/;

        # Disable request and response buffering
        proxy_request_buffering  off;
        proxy_buffering          off;
        proxy_http_version       1.1;

        # Add X-Forwarded-* headers
        proxy_set_header X-Forwarded-Host   $host;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_set_header X-Forwarded-For    $remote_addr;

        # Allow fileuploader to control the max size
        client_max_body_size         0;
    }
}

**Comment by ItsOnlyBinary** [comment]
that should be working ok?

maybe use a port > 1024 though for listening on localhost

**Comment by farazi** [comment]
> that should be working ok?
> 
> maybe use a port > 1024 though for listening on localhost

There seems to be no problem with the port... kiwiirc is working checked http://irc.beklenti.com.tr:8000 but i want to ssl  (https://irc.beklenti.com.tr:8000) and no port in url for kiwiirc login page. 


thanks for help

**Comment by ItsOnlyBinary** [comment]
oh it seems you have two configs where the server_name is irc.beklenti.com.tr
there can only be one that gets resolved for that server_name (i think its the first that is loaded)

**Comment by farazi** [comment]
> oh it seems you have two configs where the server_name is irc.beklenti.com.tr there can only be one that gets resolved for that server_name (i think its the first that is loaded)

my port 8000 listening

Do these ports belong to Kiwi for custom or should I replace them with 8000?

  location /files/ {
        # Forward incoming requests to local fileuploader instance
        **proxy_pass http://127.0.0.1:8088/files/;**

and 

    location /webirc/ {
        # Forward incoming requests to local webircgateway socket
        **proxy_pass http://127.0.0.1:7778/webirc/;**

**Comment by ItsOnlyBinary** [comment]
yes the proxy_pass host and port should match what you have defined as [server.1] in config.conf  (I suggest 127.0.0.1 & 7778 but that is up to you)

you can ignore/remove/comment `location /files/` block, its for [plugin-fileuploader](https://github.com/kiwiirc/plugin-fileuploader)

basically your setting it up so nginx will internally forward connections to irc.example.com to kiwiirc instance so that your users will not need to add a port to the url (as nginx is using the default 80/443)

**Comment by farazi** [comment]
> yes the proxy_pass host and port should match what you have defined as [server.1] in config.conf (I suggest 127.0.0.1 & 7778 but that is up to you)
> 
> you can ignore/remove/comment `location /files/` block, its for [plugin-fileuploader](https://github.com/kiwiirc/plugin-fileuploader)
> 
> basically your setting it up so nginx will internally forward connections to irc.example.com to kiwiirc instance so that your users will not need to add a port to the url (as nginx is using the default 80/443)

yes. now SSL working https://irc.beklenti.com.tr but kiwiirc was working before ssl, now it cannot connect to the irc server. error **message "unknown error."**  Is there a log file to understand why this is happening? how can we get information about why it is not connecting?

[https://i.vgy.me/IWGCax.jpg](url)

**Comment by ItsOnlyBinary** [comment]
the proxy_pass is not working, the following url should be returning `Welcome to Socks JS!` [https://irc.beklenti.com.tr/webirc/kiwiirc/](https://irc.beklenti.com.tr/webirc/kiwiirc/)

seems its not even trying as its returning 404 and not 50x

**Comment by ItsOnlyBinary** [comment]
it seems there is no location block for /webirc/ as that should be getting proxied to the other port

**Comment by farazi** [comment]
> it seems there is no location block for /webirc/ as that should be getting proxied to the other port

okey. where is directory webirc ? i find no file

[root@194 ~]# find / -name kiwiirc
/usr/share/kiwiirc
/usr/bin/kiwiirc
/etc/kiwiirc
/etc/rc.d/init.d/kiwiirc
[root@194 ~]# find / -name webirc
[root@194 ~]#

**Comment by ItsOnlyBinary** [comment]
its not a directory, its a virtual directory within the kiwiirc service basically example.com:8000/webirc/kiwiirc/

if there was a location block and proxy_pass was not connecting i would expect to see 50x error, the 404 means nginx is not seeing a location block for `/webirc/`

**Comment by farazi** [comment]
> its not a directory, its a virtual directory within the kiwiirc service basically example.com:8000/webirc/kiwiirc/
> 
> if there was a location block and proxy_pass was not connecting i would expect to see 50x error, the 404 means nginx is not seeing a location block for `/webirc/`

yes. this may be due to SSL. apparently; there is no such problem when logging in via IP (without SSL) http://194.87.246.56:8000/webirc/kiwiirc/ 

so where should i look for the problem? 1) a proper certificate was not generated 2) the nginx configuration is incorrect.

nginx irc.beklenti.com.tr.conf file: 
server {
    listen 80;
    server_name irc.beklenti.com.tr;

    location / {
        proxy_pass http://127.0.0.1:8000;
     return 301 https://$server_name$request_uri;
    }   
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    
    server_name irc.beklenti.com.tr;
    
    **ssl_certificate /etc/letsencrypt/live/irc.beklenti.com.tr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/irc.beklenti.com.tr/privkey.pem;**
    
    location / {
        index index.html;
        
        # Path to kiwiirc client files
        **root /usr/share/kiwiirc/;**
    }
    
    location /webirc/ {
        # Forward incoming requests to local webircgateway socket
        **proxy_pass http://127.0.0.1:8000/webirc/;**

        # Set http version and headers
        proxy_http_version 1.1;
        
        # Add X-Forwarded-* headers
        proxy_set_header X-Forwarded-Host   $host;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_set_header X-Forwarded-For    $remote_addr;

        # Allow upgrades to websockets
        proxy_set_header Upgrade     $http_upgrade;
        proxy_set_header Connection  "upgrade";

    }
    
    location /files/ {
        # Forward incoming requests to local fileuploader instance
        **proxy_pass http://127.0.0.1:8000/files/;**

        # Disable request and response buffering
        proxy_request_buffering  off;
        proxy_buffering          off;
        proxy_http_version       1.1;

        # Add X-Forwarded-* headers
        proxy_set_header X-Forwarded-Host   $host;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_set_header X-Forwarded-For    $remote_addr;

        # Allow fileuploader to control the max size
        client_max_body_size         0;
    }
}

**Comment by ItsOnlyBinary** [comment]
`location /webirc/ {` does not seem to be getting applied. Do you have only one config that is using `server_name irc.beklenti.com.tr;` now

**Comment by farazi** [comment]
> `location /webirc/ {` does not seem to be getting applied. Do you have only one config that is using `server_name irc.beklenti.com.tr;` now

there are several but i may not know which may conflict. i created a subdomain and added (a) record for irc.beklenti.com.tr. my irc server same ip with subdomain. cwp  automatically installed SSL for irc.beklenti.com.tr. and automatically creates configuration (virtual host) files. I edited these for kiwiirc. i want your help on this because I've been dealing with this for the last 24 hours. :/

ngnix conf files for subdomain: 

/etc/nginx/conf.d/vhosts/irc.beklenti.com.tr.ssl.conf  to see the codes: https://justpaste.it/cwjor
and
/etc/nginx/conf.d/vhosts/irc.beklenti.com.tr.conf to see the codes: https://justpaste.it/61doy

result error:
2023/10/05 18:59:57 [error] 31281#31281: *1 openat() "/usr/share/kiwiirc/webirc/kiwiirc" failed (2: No such file or directory), client: 141.196.194.113, server: irc.beklenti.com.tr, request: "GET /webirc/kiwiirc HTTP/1.1", host: "irc.beklenti.com.tr"

**Comment by ItsOnlyBinary** [comment]
ah only the ssl.conf is actually being used, i suspect its loading first. cannot have two configs with the same server_name.

need to merge the files, or add the location blocks from tr.conf to the tr.ssl.conf

**Comment by farazi** [comment]
> ah only the ssl.conf is actually being used, i suspect its loading first. cannot have two configs with the same server_name.
> 
> need to merge the files, or add the location blocks from tr.conf to the tr.ssl.conf

i merged files, restarted nginx server and kiwiirc but still results same don't working. 
please contact me on telegram: @kupayedilisi

**Comment by ItsOnlyBinary** [comment]
I don't have telegram sorry. For me its now showing certificate error.
