### ISSUE TITLE
Ensure webircgateway works with nginx in reverse_proxy mode using proxy_pass and kiwiirc

### ISSUE THREAD

**Issue by 9967819** [kiwiirc/kiwiirc#1816]
Hi !

Awesome project !! 

i am trying to mount my own webircgateway using nginx and proxy_pass atm.

### Configuration

```
example nginx.conf :

root /home/www;

upstream webircgateway { 
server 127.0.0.1:8888
keepalive 32;
}

location /webirc {
index index.html
proxy_pass http://webircgateway;
}

```

kiwiirc config :  

```
...
kiwiServer: "127.0.0.1:8888"
```

Note that i removed the "plugin" section in the configuration file because kiwiirc reported a missing customise.html file. 

My current webircgateway config.conf looks like this: 

```
[server.2]
bind = "127.0.0.1"
port = 8888
tls = false 

[transports]
kiwiirc

[reverse_proxies]
127.0.0.0/8
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
x.x.x.x/32 <-- the web server ipv4 address in CIDR format.
"::1/128".
"fd00::/8"
```

### Demo 

nginx 1.25.3 with proxy module (HTTP2/TLS 1.3) : https://open-neurosecurity.org/kiwiirc/

### Discussion

1. This setup currently isnt yet supported in nginx because some kiwiirc-specific CORS requests fails to complete when using proxy_pass. Using **proxy_pass** seems like the preferred method to mount server backends in reverse proxy mode with nginx.  

2. This feature should be documented because it would improves webirc and kiwiirc support for nginx. 
 
Thanks for your input!

Best regards.

**Comment by ItsOnlyBinary** [comment]
Example nginx config https://gist.github.com/ItsOnlyBinary/ae8d41c4542e66bb259b0f1b312c7d29

In config.json `kiwiServer` should point to the externally accessible webircgateway instance, if using the example config then `/webirc/kiwiirc/` should work. 

In config.conf you should not need to edit `[reverse_proxies]` as your reverse proxy will be connecting through 127.0.0.1 so it is already in the trusted list.

Your server details should go into `[upstream.1]`

I see in your demo url your trying to run kiwiirc in a subfolder, hopefully just changing `location /` to `location /kiwiirc/` should make that possible, although the example config was designed with a subdomain in mind.

I have been working on some new documentation here: https://github.com/ItsOnlyBinary/kiwiirc/wiki/Getting-Started#configconf

**Comment by 9967819** [comment]
@ItsOnlyBinary thanks a lot for your help!! As per your reply the kiwiirc client can now connect to irc.freenode.net as the default IRC gateway. 

### Notes : 
1. The client browser i use for development is Waterfox with websocket and http2 support. 
2. In my nginx conf, i have defined the following server upstream:
```
upstream backend {
    # webircgateway test
    server 127.0.0.1:8888;
    keepalive 32;
}
server {
  # enable http2
  http2 on;
  ...
  location /kiwiirc {
  index index.html;
  }
  location /webirc/ {
  include conf.d/kiwiirc.conf;
  }
  ...
}
```
3. kiwiirc.conf (aka webircgateway) : 
```
proxy_http_version 1.1;
proxy_set_header Upgrade  $http_upgrade;
proxy_set_header Connection  "upgrade";
proxy_set_header X-Real-IP  $remote_addr;
proxy_set_header X-Forwarded-Host  $host; # $http_host
proxy_set_header X-Forwarded-For  $remote_addr; # $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto  $scheme;
proxy_set_header Cache-Control "no-store max-age=0";
# reverse proxy backend to webircgateway app
proxy_pass http://backend/webirc/;
```                                                                               

4. The current webircgateway config:
```
[server.1]
bind = "127.0.0.1"
port = 8888

[transports]
websocket
sockjs
kiwiirc

[allowed_origins]
"*://open-neurosecurity.org"

[reverse_proxies]
127.0.0.0/8
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
"::1/128"
"fd00::/8"

# Connections will be sent to irc.freenode.net 
[upstream.1]
hostname = "irc.freenode.net"
port = 6667
tls = false
```

### Technical notes 

Theres currently no webircgateway.service for running the backend with systemd. Right now i am running the webircgateway backend from a terminal for testing... Nodejs version is 18.13.0. Note that nginx 1.25.3 is compiled with LibreSSL 3.8.2 and that tls=true is not needed for running the kiwiirc server/backend with nginx. I guess its better then to just configure SSL certificates and TLS in nginx rather than in the backend app itself. Lastly i have also disabled server-side caching (proxy_cache) while debugging.

Cheers!

**Comment by ItsOnlyBinary** [comment]
example systemd service file: https://gist.github.com/ItsOnlyBinary/405f99573be60f5344b68b45f75a6a55

Don't forget to create the user/group and working directory (with correct permissions)

Closing this issue, you can still post any future questions here I will get a notification
