### ISSUE TITLE
I set different port but its blanked on browser

### ISSUE THREAD

**Issue by legendskyk** [kiwiirc/kiwiirc#1828]
![image](https://github.com/kiwiirc/kiwiirc/assets/42233490/8d9fbf45-0284-460e-b305-49158b8b4f35)

what is the issue?

**Comment by ItsOnlyBinary** [comment]
open browser console for clues

**Comment by legendskyk** [comment]
![image](https://github.com/kiwiirc/kiwiirc/assets/42233490/5eaab5ed-4b87-4f80-aefe-87e2e64e442c)

**Comment by ItsOnlyBinary** [comment]
`startupScreen` is the name of the start screen not text you can edit. It should be `welcome`

**Comment by legendskyk** [comment]
thanks its worked

**Comment by ItsOnlyBinary** [comment]
:)
