### ISSUE TITLE
Cloudflare dns not support port system

### ISSUE THREAD

**Issue by legendskyk** [kiwiirc/kiwiirc#1829]
how my url work on cloudflare without port?? with port its not work mean now being browse.

**Comment by ItsOnlyBinary** [comment]
you will likely need to reverse proxy the kiwi server so its using default port numbers

https://github.com/ItsOnlyBinary/kiwiirc/wiki/Getting-Started#configconf

**Comment by legendskyk** [comment]
the problem is my vps already run website so i want to use different port is that possible to give direct access kiwiirc to a subdomain without port system??

**Comment by ItsOnlyBinary** [comment]
This is what reverse proxy is for. You would run kiwi on a different port then have apache/nginx connect to it for you. The user would connect to apache/nginx on the default port

The link i gave has example configs for apache and nginx reverse proxy

**Comment by legendskyk** [comment]
ok done thanks its work now.
