### ISSUE TITLE
webirc and serverpassword 

### ISSUE THREAD

**Issue by Reader9999** [kiwiirc/kiwiirc#1839]
Hello, what should be written in the webirc and serverpassword option in the configuration settings?

```
[upstream.1]
hostname = "irc.network.net"
port = 6697
tls = true
# Connection timeout in seconds
timeout = 5
# Throttle the lines being written by X per second
throttle = 2
webirc = ""
serverpassword = ""
# Outgoing protocol, valid options: tcp, tcp4, tcp6, unix
# this can be used to force ipv4, ipv6 etc
protocol = tcp
# IP address of the local network interface to bind for outgoing connections
localaddr = ""
```

**Comment by ItsOnlyBinary** [comment]
`webirc = ""` should match your webirc block in your ircd's config (this allows users to have their real IP address)
https://www.unrealircd.org/docs/WebIRC_block
https://docs.inspircd.org/3/modules/cgiirc/

`serverpassword = ""` is rarely used, its for servers that require a password to connect.
