### ISSUE TITLE
which prebuilt?

### ISSUE THREAD

**Issue by JuggaloIRC** [kiwiirc/kiwiirc#1842]
I'm currently running an IRCd on FreeBSD 12.2-RELEASE-pX amd64 and am trying to figure out which prebuilt should run and work? I've tried building my own but keep on running out of memory on my shell and have tried several versions.

**Comment by ItsOnlyBinary** [comment]
There is not a package for freebsd unfortunately. If you are running recent versions of inspircd, unrealircd (likely other modern ircd's) then you could use their websocket support to remove the need for webircgateway. then just serve the static html/js/css files with your favourite httpd. Static client files can be found here: https://builds.kiwiirc.com/zips/kiwiirc_master.zip

To connect directly without a webircgateway instance you need to set `startupOptions.direct: true` see here for more options: https://github.com/ItsOnlyBinary/kiwiirc/wiki/Configuration#direct

If none of the above is possible, then you could use another computer to build webircgateway for FreeBSD (like a virtual machine on your desktop)

to cross compile (this maybe will have cgo issues): 
``` bash
GOOS=freebsd GOARCH=amd64 go build -o webircgateway main.go
```

Normal build if your virtual machine is FreeBSD:
```
go build -o webircgateway main.go
```
