### ISSUE TITLE
building on FreeBSD 12.2-RELEASE-pX amd64

### ISSUE THREAD

**Issue by JuggaloIRC** [kiwiirc/kiwiirc#1844]
**Describe the bug**
won't build

**To Reproduce**
ran 'yarn install' went good then went to 'yarn run build' and getting errors

**Expected behavior**
build to be able to run

**Screenshots**

#
# Fatal process OOM in Failed to reserve virtual memory for CodeRange
#

error Command failed with signal "SIGILL".

**Desktop (please complete the following information):**
 - OS: FreeBSD 12.2-RELEASE-pX amd64

**Comment by ItsOnlyBinary** [comment]
Use the prebuilt static client files from here: https://builds.kiwiirc.com/zips/kiwiirc_master.zip

That error sounds like your shell does not have enough allocated memory to complete a build.

Please keep your FreeBSD related questions/issues to Issue #1842 so its easier for me to follow the discussion and not create multiple issues related to the same thing.

**Comment by JuggaloIRC** [comment]
I've been having trouble with my unrealircd server on a shell account accepting connections from my worrdpress website on https://hatchetshack.com/juggaloirc/ I have a mixed IRC/radio/discord gaming community

**Comment by ItsOnlyBinary** [comment]
Setup websockets on your ircd https://www.unrealircd.org/docs/WebSocket_support

Then you can just use apache and the static html/js/css files from https://builds.kiwiirc.com/zips/kiwiirc_master.zip

add your server details to static/config.json "startupOptions" make sure to use the websocket port not the normal 6667/6697
