### ISSUE TITLE
kiwiirc.com server doesn't work again

### ISSUE THREAD

**Issue by sergip76** [kiwiirc/kiwiirc#1853]
Again problems with kiwiirc.com client server and chats don't work:

No connection with server :(
Unknown error

Please @prawnsalad , coud you solve it?
Thanks!!

**Comment by xxcriticxx** [comment]
same here while connecting to irc.synirc.net:

We couldn't connect to that server :(
Unknown error

**Comment by lc-guy** [comment]
`*.clients.kiwiirc.com` certs are expired.

Can someone _please_ setup some auto-renewal? This isn't the first time it happens...

**Comment by sergip76** [comment]
> `*.clients.kiwiirc.com` certs are expired.
> 
> Can someone _please_ setup some auto-renewal? This isn't the first time it happens...

**Right. It seems to happen every 3 months. :-( **

**Comment by gund** [comment]
Guys rly, it's as simple as adding `sudo certbot renew` to a crontab on your server 😁

**Comment by dharma-poozle** [comment]
We couldn't connect to that server :(
Unknown error

message produced when attempt login to : https://kiwiirc.com/nextclient/irc.zeronode.net/?nick=webtroll?#NoAgenda

i believe its an expired certificate  issue seems to come up  in a 6 month cycle  

can the cert be updated in the server?
