### ISSUE TITLE
Error installing KiwiIRC on the server

### ISSUE THREAD

**Issue by Wachaapp** [kiwiirc/kiwiirc#1860]
Hello, I imagine it is not a bug but the question is that when installing KiwiIRC, I get this message:
error: No locale files could be found at client//assets/locales

and I can't find information about this error on the web

**Comment by ItsOnlyBinary** [comment]
if your only using the client files you need to setup websocket listener on your ircd (if using https the certificate must be fully trusted by web browsers, no self-signed). Once you have a websocket port on your ircd you can set [direct](https://github.com/ItsOnlyBinary/kiwiirc/wiki/Configuration#direct) to true and set your [server](https://github.com/ItsOnlyBinary/kiwiirc/wiki/Configuration#server), [port](https://github.com/ItsOnlyBinary/kiwiirc/wiki/Configuration#port), [tls](https://github.com/ItsOnlyBinary/kiwiirc/wiki/Configuration#tls) for the websocket

**Comment by Wachaapp** [comment]
I use unrealircd. I understand that I have to add in unrealircd.conf:
"startupOptions" : {
    "direct": false
}

Sorry, I'm quite lost on these topics.

**Comment by ItsOnlyBinary** [comment]
https://www.unrealircd.org/docs/WebSocket_support

`"startupOptions" : {` is a kiwiirc `config.json` thing

**Comment by Wachaapp** [comment]
Ok, Im going to try it but I have one question:

Can I add on the port 6697? for example:

"startupOptions" : {
    "port": 6697
}

I want that all connections to be through that port.

**Comment by ItsOnlyBinary** [comment]
no you will need to use another port for websockets, web browsers cannot connect directly to raw tcp sockets used by irc, you either need webircgateway (server side kiwiirc) to listen for websockets and proxy them to the ircd or websockets enabled inside your ircd.

**Comment by Wachaapp** [comment]
OK. The KiwiiRC server did not add it because I use FreeBSD and the commands that appeared in the manual to download, "Permission Denied" appeared when I type: "sudo dpkg -i kiwiirc-server_v1.7.0-2_linux_amd64.deb".

Anyway, I think I'll leave KiwiIRC, I'm making a mess of everything because there are concepts that I don't know and it would be asking a lot of questions.

I really appreciate all the help. Greetings and once again, thank you very much.

**Comment by ItsOnlyBinary** [comment]
Those packages are for linux debian/ubuntu systems, if you wanted to use webircgateway on FreeBSD you would have to compile it yourself.

The better option is to setup websockets on unrealircd and connect directly to that port, so only the static client files are needed.

Once you have the websockets configured on unrealircd it should be relatively easy to get kiwiirc working
