### ISSUE TITLE
Config file error: invalid character 'p' line 1, position 5

### ISSUE THREAD

**Issue by zer0de-r00tSec** [kiwiirc/kiwiirc#1868]
**Describe the bug**
Fresh install, basic Server config, very basic client config.

Server Start via console and service, same result:
Config file error: invalid character 'p' line 1, position 5

Loggin in Debug nothing show, no error nothing, only start and Listening on port information.

**To Reproduce**
install via *.deb file
add allowed URLs
config the client

start it

Nginx setup with:

`	location /webirc/ {
    	# Forward incoming requests to local webircgateway socket
    	proxy_pass http://62.171.139.183:7778/webirc/;
		# Set http version and headers
    	proxy_http_version 1.1;
    
    	# Add X-Forwarded-* headers
    	proxy_set_header X-Forwarded-Host   $host;
    	proxy_set_header X-Forwarded-Proto  $scheme;
    	proxy_set_header X-Forwarded-For    $remote_addr;

    	# Allow upgrades to websockets
    	proxy_set_header Upgrade     $http_upgrade;
    	proxy_set_header Connection  "upgrade";

	}`

settings, nginx restart. check in FF and Chrome via IP:Port, it works, now use a iframe with URL/webirc than u see error

**Expected behavior**
idk

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Linux-Mint
 - Browser FF & Chrome
 - Version 126.0.1 // 125.0.6422.112

**Comment by ItsOnlyBinary** [comment]
This is unlikely to be a  bug, seems you had added something invalid into `config.conf` like a missing " or possibly line endings not being unix. maybe start again with the config.conf using [config.conf.example](https://github.com/kiwiirc/webircgateway/blob/master/config.conf.example) as a template.

**Comment by 9967819** [comment]
my guess is a mimetype issue.... probably nginx is not returning a proper json response. hth
