### ISSUE TITLE
ERR_CERT_DATE_INVALID - kiwiirc.com/nextclient/

### ISSUE THREAD

**Issue by vindicatorr** [kiwiirc/kiwiirc#1870]
**Describe the bug**
```
We couldn't connect to that server :(
Unknown error
```

**To Reproduce**
1. Go to 'https://kiwiirc.com/nextclient/'
2. Open browser developer tools
3. Configure network to use Libera.chat
4. Connect
5. See error

**Expected behavior**
The certificate used is renewed on time without an `issue` having to be opened every time it occurs.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 123.0.6312.58

**Additional context**
```
GET https://do-e.clients.kiwiirc.com/webirc/kiwiirc/info?sid=<sanitized>&p=1&t=<sanitized> net::ERR_CERT_DATE_INVALID
```
It seems this is just https://github.com/kiwiirc/kiwiirc/issues/1853 repeating again (which appears to also be a repeat).

**Comment by Hex4dec** [comment]
Can confirm

**Comment by gamer191** [comment]
Confirmed at https://www.ssllabs.com/ssltest/analyze.html?d=do-e.clients.kiwiirc.com

**Comment by sergip76** [comment]
Yes, this problem recurs from time to time. Couldn't the certificate renewal be automated? Thank you.

**Comment by sergip76** [comment]
Please @prawnsalad , coud you solve it?
Thanks!!

**Comment by Hex4dec** [comment]
Dear god, it's like last time??? I'm not using KiwiIRC again.

**Comment by sergip76** [comment]
> Dear god, it's like last time??? I'm not using KiwiIRC again.

Which is the alternative?...

**Comment by vindicatorr** [comment]
I figure you can just use an app, or since most are on libera, just use their web portal directly: web.libera.chat

**Comment by Hex4dec** [comment]
> > Dear god, it's like last time??? I'm not using KiwiIRC again.
> 
> Which is the alternative?...

Using an actual IRC client, such as Irssi or HexChat. If you want to stay on the web there's Mibbit which sometimes works, and the strange qwebirc.

**Comment by mexie** [comment]
> > > Dear god, it's like last time??? I'm not using KiwiIRC again.
> > 
> > 
> > Which is the alternative?...
> 
> Using an actual IRC client, such as Irssi or HexChat. If you want to stay on the web there's Mibbit which sometimes works, and the strange qwebirc.

Mibbit is closing down on August 30. No more network or client.

**Comment by know75** [comment]
This is just so stupid. It's just an  SSL Certificate (https://letsencrypt.org/) that hasn't been set to auto renew.

Prawnsalad did so much, why hasn't he given itsonlybinary access to run the very simple command to update the SSL cert? It could even be automated. 

Surprised by Mibbit (that points here) as the solution to its closure. So two options: 

1) self host, that's what I do. Check out https://github.com/ItsOnlyBinary

2) or if you're okay having your channel on https://libera.chat/ Check out: https://libera.chat/guides/webchat

If neither suggestion is helpful I'm sure you can pay someone to set the client and gateway (if needed) up on your own server. 

Hope this helps someone! Many thanks to itsonlybinary for keeping this great client alive.
