### ISSUE TITLE
In the Italian translations, "gives" is spelled wrong

### ISSUE THREAD

**Issue by emanuele6** [kiwiirc/kiwiirc#1872]
**Describe the bug**
Today, I used kiwiirc from a PC that had Italian as system language to connect to libera.chat.

I gave voice to a bot using chanserv, and kiwiirc showed

    ⓘ ChanServ da lo stato di voice a cowdventurebot

That is not how you spell "dà" (gives); "da" without a grave accent on the "a" means "from", so I read that as "ChanServ from the state of voice to cowdventurebot" which makes no sense.

**Expected behavior**

    ⓘ ChanServ dà lo stato di voice a cowdventurebot

**Screenshots**
![Cattura](https://github.com/user-attachments/assets/30d02040-701e-4e90-89f0-cad3b5dd302d)

**Additional context**
https://github.com/kiwiirc/kiwiirc/blob/580e775fed57ddc1fe5aa0e9497faa0aa82856dd/src/res/locales/app.it-IT.po#L956
https://github.com/kiwiirc/kiwiirc/blob/580e775fed57ddc1fe5aa0e9497faa0aa82856dd/src/res/locales/app.it-IT.po#L964
https://github.com/kiwiirc/kiwiirc/blob/580e775fed57ddc1fe5aa0e9497faa0aa82856dd/src/res/locales/app.it-IT.po#L972
https://github.com/kiwiirc/kiwiirc/blob/580e775fed57ddc1fe5aa0e9497faa0aa82856dd/src/res/locales/app.it-IT.po#L980
https://github.com/kiwiirc/kiwiirc/blob/580e775fed57ddc1fe5aa0e9497faa0aa82856dd/src/res/locales/app.it-IT.po#L988

**Comment by ItsOnlyBinary** [comment]
fixed in #1873
