### ISSUE TITLE
Problem with chat users IP

### ISSUE THREAD

**Issue by sergip76** [kiwiirc/kiwiirc#1880]
I have installed Kiwiirc on my Ubuntu server along with Webircgateway. First I initialize Webircgateway with the config.cfg file that comes with the Kiwiirc package modifying only the irc network where I want to connect (irc.irc-hispano.org). Then I initialize the Kiwiirc service. Everything works correctly and I can access the chats.

The problem is that all the users that access the chats through my server do it with the IP of my server and not their own. This causes that only 3 users can connect to the irc network, since the limit per IP is 3.

I don't know how to configure it so that the users access with their own IP.
Does anyone know how to do it?
Thanks very much.

This is the configuration I am using now in Webircgateway (config.cfg):

```
# 1 = Debug; 2 = Info; 3 = Warn;
logLevel = 3

# Enable the built in identd server (listens on port 113)
identd = false

# The name of this gateway as reported in WEBIRC to IRC servers
gateway_name = "webircgateway"

# A secret string used for generating client JWT tokens. Do not share this!
secret = ""

# Send the server a quit message when the client is closed
# Comment out to disable
send_quit_on_client_close = "Client closed"

[verify]
recaptcha_url = "https://www.google.com/recaptcha/api/siteverify"
#recaptcha_url = "https://hcaptcha.com/siteverify"
recaptcha_secret = ""
recaptcha_key = ""

# If required, a client must always pass a captcha challenge before making an IRC connection
required = false

[clients]
# Default username / realname for IRC connections. If disabled it will use
# the values provided from the IRC client itself.
# %a will be replaced with the users ip address
# %h will be replaced with the users hostname
# %i will be replaced with a hexed value of the users IP
# %n will be replaced with the client provided nick
username = "%i"
realname = "I am a webchat user"

# This hostname value will only be used when using a WEBIRC password
#hostname = "%h"

# The websocket / http server
[server.1]
bind = "0.0.0.0"
port = 80

# Example TLS server
#[server.2]
#bind = "0.0.0.0"
#port = 443
#tls = true
#cert = server.crt
#key = server.key
# If you don't have a certificate, uncomment the below line to automatically generate a
# free certificate using letsencrypt.com (overrides the above cert/key options). This requires
# a server running on port 80 to initially generate the certificate.
#letsencrypt_cache = ./certs

# Example unix socket server
#[server.3]
#bind = unix:/tmp/webircgateway.sock
#bind_mode = 0777

# Serve static files from a web root folder.
# Optional, but handy for serving the Kiwi IRC client if no other webserver is available
[fileserving]
enabled = true
webroot = /usr/share/kiwiirc/

[transports]
websocket
sockjs
kiwiirc

# Websites (hostnames) that are allowed to connect here
# No entries here will allow any website to connect.
# Origins do not include a trailing / after the host and optional port
[allowed_origins]
#*://example.com

# If using a reverse proxy, it must be whitelisted for the client
# hostnames to be read correctly. In CIDR format.
# The user IPs are read from the standard X-Forwarded-For HTTP header
[reverse_proxies]
127.0.0.0/8
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
"::1/128"
"fd00::/8"

# Connections will be sent to a random upstream
[upstream.1]
hostname = "irc.irc-hispano.org"
port = 6667
tls = false
# Connection timeout in seconds
timeout = 5
# Throttle the lines being written by X per second
throttle = 2
# Webirc password as set in the IRC server config
webirc = ""
serverpassword = ""

# A public gateway to any IRC network
# If enabled, Kiwi IRC clients may connect to any IRC network (or a whitelisted
# network below) through the kiwiirc engine
[gateway]
enabled = false
timeout = 5
throttle = 2

# Whitelisted IRC networks while in public gateway mode
# If any networks are in this list then connections can only be made to these
[gateway.whitelist]
#irc.example.com
#*.example2.com

# Webirc passwords used when running in the public gateway mode
[gateway.webirc]
irc.network.org = webirc_password
irc.network2.org = webirc_password

[dnsbl]
# "verify" - if the client supports it, tell it to show a captcha
# "deny" - deny the connection entirely
action = deny

[dnsbl.servers]
dnsbl.dronebl.org
```

**Comment by pwpreacher** [comment]
It is not a bug.  read up on Webirc. For the ip number to be passed as their domain on an ircd there needs to be a webirc setup.

--
just a kiwiirc user.

**Comment by ItsOnlyBinary** [comment]
The ircd your connecting is required to have a webirc/cgiirc block, which allows the real ip to be passed to the server.

Once you have the webirc/cgiirc block password it should be added here:

```
[upstream.1]
webirc = "webirc_block_password"
```

The documentation for unrealircd and inspircd are here:

https://www.unrealircd.org/docs/WebIRC_Support
https://docs.inspircd.org/3/modules/cgiirc/
https://docs.inspircd.org/4/modules/gateway/

**Comment by sergip76** [comment]
Do I have to request the WebIrc password for each IRC network I want to connect to?
Is there another way to do it without having to request the password?
In some networks like irc.irc-hispano.org it is very difficult to contact the administrators...
Thanks

**Comment by ItsOnlyBinary** [comment]
only other way would be if the ircd admins have setup a websocket directly on the ircd that way a direct connection can be made. But most have not done this or do not advertise its port.

**Comment by sergip76** [comment]
> only other way would be if the ircd admins have setup a websocket directly on the ircd that way a direct connection can be made. But most have not done this or do not advertise its port.

In this case, should I configure something specific in the Kiwiirc client or should I simply know on which port of the ircd server this direct connection is possible?

**Comment by ItsOnlyBinary** [comment]
https://github.com/ItsOnlyBinary/kiwiirc/wiki/Configuration#startup

direct: true and port set to the websocket port on the ircd (this will not work with 6667 or 6697 as they are raw tcp ports not websocket ports)
