### ISSUE TITLE
is kiwi irc down ? [Error] Refused to display  in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

### ISSUE THREAD

**Issue by atv2016** [kiwiirc/kiwiirc#1881]
I'm getting this message in safari: [Error] Refused to display 'https://kiwiirc.com/nextclient/?theme=sky#irc://irc.libera.chat/#testchannel?nick=test_68975&encoding=utf8' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

Seems a long time to load and then timeout.

**Comment by ItsOnlyBinary** [comment]
The server was down, had many issues related to it so just closed them all once the server was back up.

This is not really the right place for kiwiirc.com issues as I only maintain the open-source project, not the hosted kiwiirc.com

**Comment by atv2016** [comment]
Cheers. Do you support both ?

**Comment by ItsOnlyBinary** [comment]
No just the open-source

**Comment by atv2016** [comment]
Cool. Where do I go to for the hosted version? (I'm using the embedded wordpress plugin version). Thy have their own GitHub but not sure that's the right place either, although probably more suited then this one :-)

**Comment by ItsOnlyBinary** [comment]
If your using it for your own ircd i would suggest setting up your own kiwiirc instance then modifying the wordpress plugin to use that.

Hosting your own instance would give you much more control over its configuration and plugins

**Comment by atv2016** [comment]
That's a good idea. I'll give that a go.

Is there a way of connecting to the self hosted version through the web by going to a specific URL/port and do away with the plugin completely?

**Comment by atv2016** [comment]
Hi, 
I decided to self host it. I wouldn't mind some help or points on this though.

1. I downloaded the kiwi irc client zip file and moved it to my /var/www/html root in directory kiwi.
2. Looking in the wordpress plugin, the file it seems to rely on is :
https://kiwiirc.com/nextclient/?theme=sky#irc://irc.libera.chat/#Grab.a.guru?nick=Guru_11685&encoding=utf8

If I look in my plugin directory I see this string:

public/index.php:    $url = KIWICHAT_URLBASE."nextclient/?";

and KIWICHAT_URLBASE is defined in :

kiwichat.php:define( 'KIWICHAT_URLBASE', 'https://kiwiirc.com/' );

I assume I just update this url to my server domain, but where is this next client supposed to be it is loading? What does that correspond to in the client files ? I have various .js files in the js directory, but no mention of nextclient.js or something similar.

Hopefully I'm on the right track here. Really appreciate your help with this.

**Comment by n1ce-0ne** [comment]
hey m8, just a guy reading & thought i'd try help a bit.
i use the [fileserving] section in config.conf to serve my files
i just set:
enabled = true
webroot = /home/USER/irc/

[could be located anywhere]
but thats just one way of doing it,

maybe try create a folder inside your html folder called something like 'irc' then put the kiwi files in there,
then try http://yoursite.com/irc:PORT_NUMBER

port number is set in config.conf under [upstream.1]

hope this helps :)

**Comment by atv2016** [comment]
Hi, thanks!
1. So are you hosting on linux? 
2. What files did you download, the client or ?
3. Where is the next client.js hosted?

**Comment by atv2016** [comment]
Ok, so I got this to work by moving the directory to name nextclient. I can now call it from wordpress with the shortcode using the plugin or just directly go to mydomain/nextclient and it seem to work.

For some reason I keep getting though:
![Screenshot 2024-10-01 at 10 25 08](https://github.com/user-attachments/assets/4f9b197e-8435-4243-acd0-d996c6979bd2)

**Comment by n1ce-0ne** [comment]
hey m8,
i would check these lines:

# Connections will be sent to a random upstream
[upstream.1]
hostname = "irc.libera.chat"

im fairly sure this should always point to your own local irc server, thats how i do it.

kiwiirc will communicate to libra.chat through your irc server, as far i know you cant connect your kiwi straight to there irc server

**Comment by atv2016** [comment]
Oh I didn’t realise I needed my own irc server. I guess if I don’t want that I should use the client and connect to a websocket irc server?
________________________________

**Comment by n1ce-0ne** [comment]
kiwi is the frontend to an irc server acting as a backend.

if your going to the lengths of running your own kiwi instance, installing your own irc server goes hand in hand with it.
i wouldn't let that stop you, super lightweight & installs in seconds with very little maintenance required once running.

however you connect kiwi to a backend on your server, it must be an irc server & you must be allowed to use it, aka your own.

hope this helps m8 :)
