### ISSUE TITLE
How do I connect to this?

### ISSUE THREAD

**Issue by atv2016** [kiwiirc/kiwiirc#1882]
So I get how to build and install this, but how do I connect to it as a client ?

Can I go to a certain URL and port or ?

After the recent server issue's self hosting this seems like a good idea. Currently using the wordpress kiwi irc plugin, ideally I would like to replicate the same client experience (just connecting from a webpage).

Also, I feel this open source version has many more features then the wordpress plugin for example, is that correct?

Thanks for any help.

**Comment by ItsOnlyBinary** [comment]
https://github.com/ItsOnlyBinary/kiwiirc/wiki/Getting-Started
