### ISSUE TITLE
Nick confirmation email didn't arrive

### ISSUE THREAD

**Issue by RU0Y** [kiwiirc/kiwiirc#1891]
I came back to irc after a year and had to create a new account sadly after typing registration command I didn't receive an confirmation email even after an hour and using resend command. Yes i checked spam folder, and even delated and also my other mails and i do not have confirmation email in any of them.

**Comment by ItsOnlyBinary** [comment]
You need to contact support for the irc server you are using, this is support for Kiwi IRC the open source irc client used by many servers.
