### ISSUE TITLE
Reloading leads to multiple IRC networks

### ISSUE THREAD

**Issue by anhofmann** [kiwiirc/kiwiirc#195]
When I start my kiwiirc chat, it automatically connects to my network. When I press F5 on my keyboard it still connects automatically to my network, but opens a new one in the left network list. They all have the same name. Here is a screenshot: https://imgur.com/buMo06k

**Comment by YanickFrehner** [comment]
Are there some news regarding this issue?
Is there a way to fix/solve this?
It would be nice if you can give me a hint, i would also fix this on my own if its possible

**Comment by YanickFrehner** [comment]
I was using the welcome page. But i also wasnt using the newest version.
I had installed the Debian package. I will test if the issue is still apearing in the newest version
