### ISSUE TITLE
closing the tab always throws a warning

### ISSUE THREAD

**Issue by anhofmann** [kiwiirc/kiwiirc#196]
Every time I close my kiwiirc tab in the browser, I get a javascript box that asks me if I really want to leave. The text is "Do you want to leave this site? Changes you made may not be saved.". This is a problem because I want to put the chat in a iframe and this message pops up everytime the user closes our website.

**Comment by AllanOcelot** [comment]
Hi @anhofmann , what browser are you using and what version? Can you give us steps to replicate?.

Any other information that would help , I've not experienced this issue myself.

**Comment by prawnsalad** [comment]
@anhofmann this is now configurable though I do think is it a bad idea to disable this as people may accidentally hit f5 and then loose their current conversations.

@AllanOcelot this is the prompt that appears when you close the page after you are connected to a network.

**Comment by anhofmann** [comment]
Awesome, thank you!
