### ISSUE TITLE
When I can't connect to the irc network I see no useful error message

### ISSUE THREAD

**Issue by anhofmann** [kiwiirc/kiwiirc#198]
When I put wrong credentials on the welcome screen and press "Start", I see the loading circle and then the welcome screen without any helpful information why I couldn't connect. This can also happen when there is a existing connection, for example in another tab of my browser.
the old kiwiirc shows the message from the IRC network in a red box. This way the user at least understands that something went wrong.

**Comment by prawnsalad** [comment]
This has now been improved and displays the last error message the server sends.
