### ISSUE TITLE
Issues with properly showing Global serv

### ISSUE THREAD

**Issue by Arkadietz** [kiwiirc/kiwiirc#20]
Hello,

I would like to inform you for that bug. Not show properly the service name such as Global.

![global](https://cloud.githubusercontent.com/assets/2511773/24001692/80031cb0-0a67-11e7-8944-73e9ee5bdcf4.PNG)

**Comment by ItsOnlyBinary** [comment]
After some testing this appears to no longer be an issue, please let me know if I'm mistaken and i will reopen the issue
