### ISSUE TITLE
Typo in the locale french file

### ISSUE THREAD

**Issue by DavidVerdier** [kiwiirc/kiwiirc#200]
https://github.com/kiwiirc/kiwiirc/blob/master/src/res/locales/app.fr-FR.po#L510

**Comment by CoryChaplin** [comment]
@DavidVerdier this needs to be fixed in Crowdin http://translations.kiwiirc.com/project/kiwiirc/fr#

**Comment by CoryChaplin** [comment]
Fixed here http://translations.kiwiirc.com/translate/kiwiirc/10/en-fr#q=user_server

**Comment by DavidVerdier** [comment]
I'll let you fix and close.

**Comment by prawnsalad** [comment]
This is now in the master branch. Thanks!

**Comment by CoryChaplin** [comment]
@prawnsalad Not sure why, but it's not aligned with what's in Crowdin http://translations.kiwiirc.com/translate/kiwiirc/10/en-fr#q=user_server http://translations.kiwiirc.com/translate/kiwiirc/10/en-fr#q=user_server
