### ISSUE TITLE
Port znc module to c++

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/kiwiirc#211]
Current python module: https://gist.github.com/prawnsalad/f317f9ae76b1948ad349bc72b80593a9
@tyzoid

**Comment by prawnsalad** [comment]
The current design doc: https://gist.github.com/prawnsalad/e20ee535c2cc6ee942b540ee3f20690c

view raw.

**Comment by AllanOcelot** [comment]
Closed cause we have a bouncer thanks to @prawnsalad  !
