### ISSUE TITLE
Using "/notice nick message" doesn't echo to the sender that the notice itself was sent

### ISSUE THREAD

**Issue by TheMythPT** [kiwiirc/kiwiirc#218]
When we send a notice to someone using `/notice nick message` we don't receive any kind of confirmation that the notice was sent.

**Comment by ItsOnlyBinary** [comment]
also incoming direct notices go to the server tab (may go unnoticed) maybe active buffer is a better location for them to go

**Comment by ItsOnlyBinary** [comment]
It now shows the outgoing message in the appropriate buffer but is not styled to differentiate it from a normal message.

@AllanOcelot i think red text is common for notices, maybe do a little investigation on how other projects are styling them

**Comment by AllanOcelot** [comment]
need to discuss with @prawnsalad best way to implement the notice messages. At the moment I don't seem to see when sending or receiving them. Could be another bug.

**Comment by prawnsalad** [comment]
Closing this as notices are now added to the display when sending, and receiving notices are now shown in the active tab if its buffer does not exist.

Styling notices issue is in #907
