### ISSUE TITLE
Language detection not working for Firefox

### ISSUE THREAD

**Issue by CoryChaplin** [kiwiirc/kiwiirc#219]
On https://kiwiirc.com/nextclient/ my language is correctly displayed on Chrome and Safari, not on Firefox.

**Comment by ItsOnlyBinary** [comment]
This is not an issue on the master branch, https://kiwiirc.com/nextclient/ is quite outdated.

**Comment by CoryChaplin** [comment]
@ItsOnlyBinary I'd love you to be right, but it's not ok on master. He're a screenshot from your build system.
<img width="1437" alt="kiwi_irc_preview_build_et_kiwi_irc_-_the_web_irc_client" src="https://user-images.githubusercontent.com/5139669/35594022-15cf4f10-0612-11e8-8ee1-01fc7e6a56dc.png">

**Comment by ItsOnlyBinary** [comment]
ah i checked with kiwi.i18n.language and got "en-GB" so seemed to be working.. as my lang is en i didnt realise the page was not changing... screenshot helps ;)

**Comment by CoryChaplin** [comment]
@ItsOnlyBinary I guess we're failing to match "fr" and "fr-FR". Probably needs a fallback test on first 2 chars of the language name when not matching.

**Comment by AllanOcelot** [comment]
We should look into @CoryChaplin 's suggestion of having a fallback and ensuring it works for chrome users, one of kiwi's big features is it's string translation :)

**Comment by ItsOnlyBinary** [comment]
This has been fixed now, please let us know if any further issues relating to this.
