### ISSUE TITLE
Add user password field

### ISSUE THREAD

**Issue by dvorapa** [kiwiirc/kiwiirc#223]
In the old client there was an input field for password next to the username input field. I can not see this in nextclient anywhere. There is some "password" input field, but it is not working for username passwords. Therefore the only possible way to identify is to write a command `/msg NickServ identify *password*`

**Comment by prawnsalad** [comment]
As explained in your last issue, this works in the exact same way as the old version. If the network supports SASL (most do by now) then you can enter your password in the password box. This will log you into services.

**Comment by dvorapa** [comment]
Oh, in Edge on Windows it works, there must be an issue with Firefox on Linux.

BTW why the password filed is next to the server and not next to the usename?

**Comment by prawnsalad** [comment]
Which URL are you using to test this out?

**Comment by dvorapa** [comment]
OK, on Firefox on Linux it also works, but after cleaning browser cache. But the position of that field is weird (https://kiwiirc.com/nextclient/)

**Comment by stdedos** [comment]
@prawnsalad I don't want to open a new issue, but indeed the password field is in a weird position.

Would you mind re-opening / renaming the issue?
