### ISSUE TITLE
Query with offline users

### ISSUE THREAD

**Issue by H7-25** [kiwiirc/kiwiirc#235]
If an user go offline during a PM session, you don't understand he is gone offline because you don't get any notice or any signal that he is no more online, you get "No such nick/channel" but only in the server tab.

**Comment by TheMythPT** [comment]
That's a use case where having notices being sent to current window would be good.
Perhaps checking if the message is sent in PM and if so and user it's not online, send the notice to the PM window?
I don't know how hard would be to separate things tho.

**Comment by ItsOnlyBinary** [comment]
This has been fixed, thanks for reporting the issue
