### ISSUE TITLE
Kiwiirc setup commands

### ISSUE THREAD

**Issue by ircalem** [kiwiirc/kiwiirc#242]
I can not build this kiwiirc, you can help me.
You could write the setup commands in order. (Centos)

**Comment by prawnsalad** [comment]
There are instructions in the readme. You may want to start reading here https://github.com/kiwiirc/kiwiirc#dependancies

Or if you just want to install kiwiirc to use it, then try here https://github.com/kiwiirc/kiwiirc#easy-supported-ways-to-install-kiwi-irc

**Comment by ircalem** [comment]
git clone https://github.com/kiwiirc/kiwiirc.git && cd kiwiirc
npm install
cp config.example.js config.js
./kiwi build
./kiwi start

These commands are incorrect

**Comment by CoryChaplin** [comment]
The doc doesn¹t say those commands.

It says :
>  <https://github.com/kiwiirc/kiwiirc#development-environment> Development
> environment
> # install dependencies
> yarn install
> 
> # development web server with hot reload at http://localhost:8080/
> yarn run dev
> Source files are linted automatically and will fail on any linting errors.
>  <https://github.com/kiwiirc/kiwiirc#building-for-production> Building for
> production
> # install dependencies
> $ yarn install
> 
> # build for production with minification
> $ yarn run build
> 
-- 
Elephantman

De :  ircalem <notifications@github.com>
Répondre à :  kiwiirc/kiwiirc
<reply+004e6cd58e900c2b0fec24a118483d873e6608273d134d7892cf000000011698957e9
2a169ce11a83544@reply.github.com>
Date :  lundi 12 février 2018 à 00:36
À :  kiwiirc/kiwiirc <kiwiirc@noreply.github.com>
Cc :  Subscribed <subscribed@noreply.github.com>
Objet :  Re: [kiwiirc/kiwiirc] Kiwiirc setup commands (#242)
