### ISSUE TITLE
Is it possible to set user options in javascript?

### ISSUE THREAD

**Issue by anhofmann** [kiwiirc/kiwiirc#243]
I have channels where people are constantly joining and parting. Every user can change the option if he/she wants to see the join/part messages. 
Is there a way to set these options ( 
![screenshot from 2018-02-12 18 14 26](https://user-images.githubusercontent.com/3919068/36109811-c3b23a12-1020-11e8-8cfe-d8e67edec593.png)
) in javascript for them?

**Comment by prawnsalad** [comment]
In the config you can set the following:
~~~
{
    "buffers": {
        "show_joinparts": false,
        "show_topics": false,
        "show_nick_changes": false,
        "show_mode_changes": false,
        "coloured_nicklist": false,
        "extra_formatting": false
    }
}
~~~

Full list of settings can be found here https://github.com/kiwiirc/kiwiirc/blob/f40dbe312e557eb9febd7dd96ac065b77323ba65/src/libs/state.js#L41
