### ISSUE TITLE
Kick notices and Ban Notice empty text

### ISSUE THREAD

**Issue by H7-25** [kiwiirc/kiwiirc#249]
When a user is kicked or banned from a channel , the notice contain info symbol only but not text
![immagine](https://user-images.githubusercontent.com/2895452/37198070-48e021b2-237d-11e8-875e-3772ebfe1dc0.png)

**Comment by H7-25** [comment]
All mode setting notice are empty, example " ChanBot sets mode: +v Tarkus " show only info icon

**Comment by prawnsalad** [comment]
After looking into this, the italian translation in master is incomplete so it doesnt return any strings for this. I'll get your translations merged before anything else major so that you can make use of those.
