### ISSUE TITLE
/commands to be ported from the current version

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/kiwiirc#25]
Most commands have now been ported but the following are still todo. Some of these are now avialable via the UI but we can't forget about the commands.
- [x] cycle
- [x] invite
- [x] kick
- [x] names
- [x] mode
- [x] quit
- [x] away
- [x] encoding
- [x] channel
- [x] settings
- [x] css
- [x] alias
- [x] ignore
- [x] unignore

**Comment by prawnsalad** [comment]
No longer supporting /alias and /settings as the UI offers a clearer way to visit those config sections.

/away does not need to be implemented as the RAW sent is already suitable.

**Comment by mestaritonttu** [comment]
Regarding /alias and /settings, is the UI accessible (for visually impaired users)?

**Comment by prawnsalad** [comment]
@mestaritonttu In what way accessible? You can take a look here by connecting and then selecting settings in the bottom left: https://kiwiirc.com/nextclient/

**Comment by mestaritonttu** [comment]
https://www.w3.org/WAI/WCAG20/quickref/#principle2

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA

Quoting a bit from here (emphasis mine): http://w3c.github.io/aria-in-html/

> All interactive ARIA controls must be usable with the keyboard.
> 
> If you create a widget that a user can click or tap or drag or drop or slide or scroll, **a user must also be able to navigate to the widget and perform an equivalent action using the keyboard.**
> 
> All interactive widgets must be scripted to respond to standard key strokes or key stroke combinations where applicable.
> 
> For example, if using role=button the element must be able to receive focus and a user must be able to activate the action associated with the element using both the enter (on WIN OS) or return (MAC OS) and the space key.

Here is an example of a Vue component with ARIA attributes: https://github.com/jayway/vue-js-workshop/blob/master/demo/src/components/AppNav.vue

**Comment by prawnsalad** [comment]
The aria properties will be coming up in a different commit when I sprinkle them around the entire app.
