### ISSUE TITLE
(CGI:IRC -- No access)

### ISSUE THREAD

**Issue by ircalem** [kiwiirc/kiwiirc#251]
there is such an error.
which file we are setting from

**Comment by prawnsalad** [comment]
You need to set the webirc password in the kiwi server. Check the upstream config file for the webirc option.

**Comment by ircalem** [comment]
@prawnsalad 

{
	"windowTitle": "Kiwi IRC - The web IRC client",
	"startupScreen": "welcome",
	"kiwiServer": "https://localdev.clients.kiwiirc.com/webirc/kiwiirc/",
	"restricted": true,
	"theme": "default",
	"themes": [
		{ "name": "Default", "url": "static/themes/default" }
	],
	"startupOptions" : {
		"server": "irc.ircalem.com",
		"port": 6667,
		"tls": false,
		"direct": false,
		"channel": "#sohbet",
		"nick": "kiwi-n?"
	},
	"embedly": {
		"key": ""
	}
}

where do i write the password

**Comment by prawnsalad** [comment]
That is the client config. You need to add webirc passwords to your kiwi server config. If you installed using the packages then you will find this in /etc/kiwiirc/config.conf. Find the upstream section called "webirc". It will look something like this: https://github.com/kiwiirc/webircgateway/blob/master/config.conf.example#L81

If you still have trouble, please use the mailing list as this is not a bug. https://groups.google.com/forum/?fromgroups#!forum/kiwiirc
