### ISSUE TITLE
How to change realname and direct ip 

### ISSUE THREAD

**Issue by mickyzth** [kiwiirc/kiwiirc#256]
dfce7016@Clk-5CAB7F13.clients.kiwiirc.com

Real name: [https://kiwiirc.com] Development release 

to dfce7016@real.cloak.userip
Real name: * Username or My Network

**Comment by prawnsalad** [comment]
These are settings made on the server. In your kiwi server config take a look at this section: https://github.com/kiwiirc/webircgateway/blob/master/config.conf.example#L13

**Comment by paulo-roger** [comment]
Maybe this is not the best place to ask, but what if I just serve static files with nginx?
