### ISSUE TITLE
Look into testing

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/kiwiirc#26]
* https://github.com/eddyerburgh/avoriaz

**Comment by ItsOnlyBinary** [comment]
this has been depreciated in favour of https://github.com/vuejs/vue-test-utils

**Comment by AllanOcelot** [comment]
Looks like unit testing has been put in place via vue-test-utils, as evidenced by the /tests/unit folder being populated with tests.

So I'm closing this issue.
