### ISSUE TITLE
PM messages not being properly "parsed"

### ISSUE THREAD

**Issue by TheMythPT** [kiwiirc/kiwiirc#28]
When PMing a nickname, we click on the nickname on channel user list, we choose "Send a message" and the PM window opens..

We type the message and this happens:
![pvt3](https://cloud.githubusercontent.com/assets/25697531/25309301/f5e8153c-27c9-11e7-820c-debc5363c700.png)

and this is how i receive it on my end:
![pvt3_irccloud](https://cloud.githubusercontent.com/assets/25697531/25309309/0cce1b3e-27ca-11e7-9f0b-1aa34b49ab3c.png)

Bottom of the issue, is when sending the PM message on the KiwiIRC NextGen, the receiver nickname is always included on the message and shouldnt be.

**Comment by prawnsalad** [comment]
Fixed in development. Thanks!
