### ISSUE TITLE
Make KiwiIRC send custom text if /list happens to be empty (e.g. due to a securelist module)

### ISSUE THREAD

**Issue by KoraggKnightWolf** [kiwiirc/kiwiirc#286]
KiwiIRC should display somekind of custom text when the retrieved /list should be empty. This is because many networks employ so called m_securelist modules which send clients within the first x seconds of connecting (usually up to 60 seconds) an empty /list to prevent spambots from connecting, fething a large /list and just quitting, stressing the server out heaps. 
This empty list in KiwiIRC should perhaps be handled in the way of sending a custom text like "/list is currently unavailable please try again later" as no response at all might confuse users and make them assume that either KiwiIRC or the network they are on may be malfunctioning (or that they are lagging bigtime). 
I hope this idea seems sensible enough to implement as this feature is also advertise in RAW 005 (incase this helps with implementing it) and it is a common practice on many networks.

Thank you for your time and effort in advance.

Regards,

Koragg

**Comment by prawnsalad** [comment]
This is now implemented in master. Thanks!
