### ISSUE TITLE
User list blank after closing private message (new design)

### ISSUE THREAD

**Issue by mestaritonttu** [kiwiirc/kiwiirc#290]
1. Click "x people here"
2. Start a private message with yourself
3. Close PM

Observe blank user list

**Comment by AllanOcelot** [comment]
HI @mestaritonttu  - Can you check if this is still the case in the 'new layout' branch, I've tested following your instructions and cannot replicate. ( Is this something you have fixed @prawnsalad  )

**Comment by mestaritonttu** [comment]
Yep, it's still in newlayout. Sorry for not mentioning: I used Firefox (59).
Yet, now I tested with more browsers and am seeing it in Chrome Version 65.0.3325.181 and Microsoft Edge 41.16299.371.0

**Comment by mestaritonttu** [comment]
Here is what I see after closing the PM: https://image.ibb.co/bXyLWn/blank_userlist.png

**Comment by mestaritonttu** [comment]
I see the bubbles for starting a private message are gone in the latest iteration, so the only option is to first click on a nick and then "Send a message". After closing the PM from this route, the user list is not blank.

**Comment by mestaritonttu** [comment]
This is now fixed in master! Cheers!
