### ISSUE TITLE
Remembering scroll position when switching away from a small messagelist

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/kiwiirc#293]
1. Be in a buffer that has enough messages to cause scrolling
2. Switch to a buffer that does not have a scrollbar
3. Switch back to the buffer in step 1, it will no longer auto scroll to the bottom since scroll-top of the buffer in step 2 was shorter.

**Comment by ItsOnlyBinary** [comment]
This no longer appears to be an issue
