### ISSUE TITLE
Join/Part messages on compact/traditional view.

### ISSUE THREAD

**Issue by TheBeerbarian** [kiwiirc/kiwiirc#299]
Message bleeds through time.
Time also slightly elevated vertically out of alignment with message.

![image](https://user-images.githubusercontent.com/24723440/39099725-5a11b5e0-463c-11e8-9440-bfc5bf7e6637.png)

**Comment by finalhit** [comment]
Both issues are still present:
- Time is elevated vertically out of alignment with message.
- Timestamps overlap join/part notifications on narrow displays (mobile phones).
