### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/kiwiirc#3]
Take a look into transifex.com as that appears to be easier to use than poeditor.com

**Comment by zoltyvigo** [comment]
I am a developer of IRC-Hispano (ChatHispano), I have signed up on transifex.com to translate KiwiIRC into Spanish and Galician :)

**Comment by zoltyvigo** [comment]
I have already translated Spanish and Galician in http://translations.kiwiirc.com
