### ISSUE TITLE
Nick completion not adding the choosen nick auto into input box

### ISSUE THREAD

**Issue by TheMythPT** [kiwiirc/kiwiirc#32]
When we use tab in order to have  nick completion, the highlighted nick should be atu-added into input box.
Right now we need to tab+enter to achieve that. Auto-adding nick to the input box would make users life easier.

**Comment by TheMythPT** [comment]
Any update on this issue?

**Comment by prawnsalad** [comment]
The input box is being re-written at the moment so this will most likely come with that. Not sure when it will land in master but it's in progress.

**Comment by TheMythPT** [comment]
Closed since the feature is added on #101
Reopen if mistaken
