### ISSUE TITLE
Nickname Mouse Over issue on Safari (osx) 

### ISSUE THREAD

**Issue by H7-25** [kiwiirc/kiwiirc#325]
Using safari on osx, i've this issue : 

https://www.youtube.com/watch?v=ZstyL3-Mw5A

It look be related to  .kiwi-messagelist-nick overflow css , disabling  this in the inspector  up&down scrolling on mouse over look disappear

**Comment by AllanOcelot** [comment]
@H7-25  - I'll look into this

**Comment by AllanOcelot** [comment]
Hi @H7-25  - please can you check if the above commits (now in master) have resolved this issue?

**Comment by H7-25** [comment]
I confirm, it fix the issue.

**Comment by H7-25** [comment]
The issue is back again ...

**Comment by AllanOcelot** [comment]
This does not appear to be an issue anymore, tested in Safari with master, using 'traditional' layout.

I cannot replicate, so am assuming a previous PR has addressed the issue :)
