### ISSUE TITLE
Untranslated Strings

### ISSUE THREAD

**Issue by H7-25** [kiwiirc/kiwiirc#326]
List of untranslated strings : 

In channel header : 
Display topic   button
Hide topic button
Channel Settings button

In channel settings tab
Channel Settings

In state browser 
Kiwi Settings  (kiwi-statebrowser-appsettings)

In Alias (kiwi settings)
What are aliases?

**Comment by AllanOcelot** [comment]
@H7-25  and I'll look into this one too, thanks for flagging them :)

**Comment by H7-25** [comment]
Found other strings : 

Filter Channels (in channels filter)
Find other channels (under channels filter)
Filter Users in channels ( in userslist channel filter)

**Comment by TonnesM** [comment]
In Kiwi settings - general
Default / Dark
Refresh Theme (tooltip)
Close X

**Comment by AllanOcelot** [comment]
I'm adding these in now, they shall be included in my latest PR, thanks for spotting these @H7-25  and @TonnesM  :)

**Comment by TonnesM** [comment]
Thanks.

New (?): "You are not currently connected!"

**Comment by zoltyvigo** [comment]
![image](https://user-images.githubusercontent.com/6929524/43314279-c1fa5c9c-9192-11e8-9de4-d18f02a9f1bf.png)
