### ISSUE TITLE
every mode on different row

### ISSUE THREAD

**Issue by Arkadietz** [kiwiirc/kiwiirc#33]
Hello,

I just notice that instead of kiwi set modes on the same row no matter how much they are it's set them each to separate row. 
You can check the screenshot below.

![kiwi3](https://cloud.githubusercontent.com/assets/2511773/26139158/458bae62-3ad7-11e7-88b2-fe93bf74ccc7.PNG)

**Comment by TheMythPT** [comment]
+1 to show all modes in a single line

**Comment by ItsOnlyBinary** [comment]
this has been improved, 
channel modes are no longer show on join
kiwi will now group mode changes happening in one command
