### ISSUE TITLE
Long nickname (>20characters) are overflowed in userlist

### ISSUE THREAD

**Issue by xam60** [kiwiirc/kiwiirc#336]
With the new ui, long nickname (greather than 20 characters) are overflowed on the next nickname in the list.
This issue is with sidebar pinned or unpinned.

![example1](https://user-images.githubusercontent.com/12534365/39961460-b8b89528-5636-11e8-8c87-aad04248aef3.PNG)

**Comment by prawnsalad** [comment]
Long nicks now no longer wrap underneath. Thanks!
