### ISSUE TITLE
embed option in video.

### ISSUE THREAD

**Issue by Indjov** [kiwiirc/kiwiirc#34]
Hello, 
When you type some youtube link in webcha embed option moves the messages bar into the middle of the video.

Web Browser:Chrome 5
![nextkiwi2](https://cloud.githubusercontent.com/assets/5468168/26451894/887cb596-4166-11e7-9ca4-2f9eb916d349.PNG)
8.0.3029.110 (64-bit)
OS: Windows 10
![kiwinext](https://cloud.githubusercontent.com/assets/5468168/26451517/0f3e27ec-4165-11e7-9145-330a34a55737.PNG)

**Comment by prawnsalad** [comment]
Hi, do you still see this issue?

**Comment by Indjov** [comment]
@prawnsalad , now it`s ok. 
Thanks
