### ISSUE TITLE
Channel Settings dialog width too small

### ISSUE THREAD

**Issue by TonnesM** [kiwiirc/kiwiirc#346]
In the preview build and when using a non-English locale, the right-sided dialog for the Channel Setting may be too narrow. The 3 top tabs don’t find and get wrapped, so the Notifications tab resides on a new line.

I also recall seeing some options below them that don’t fit, but now they do. Using a dynamic width (for both headers/tabs and options) may come in handy, or it could be based upon the longest available string in localizations.

**Comment by prawnsalad** [comment]
@TonnesM could you check the latest master for this now? Hows it looking?

**Comment by TonnesM** [comment]
Looks good, thanks.

**Comment by ItsOnlyBinary** [comment]
Thanks for verifying TonnesM, i shall close this issue now
