### ISSUE TITLE
Kiwi Settings - General panel may be too narrow

### ISSUE THREAD

**Issue by TonnesM** [kiwiirc/kiwiirc#349]
In Kiwi Settings - General, some localized strings may be a little too wide to fit, causing them to wrap. For instance, "Include join/part messages as activity" wraps for my locale, so one word is on a new line, the entire string also displays above the check box, and the check box is almost next to the one for the next option instead of where it should be.

Please widen this options dialog/column, either static or dynamic.

![kiwi_settings_general_width](https://user-images.githubusercontent.com/14834507/40181303-1aa9100e-59e9-11e8-9ce6-9ec159dc8630.png)

**Comment by AllanOcelot** [comment]
@prawnsalad  - can be closed, was fixed with styling fix branch merge

**Comment by prawnsalad** [comment]
@AllanOcelot this has not yet been fixed

**Comment by prawnsalad** [comment]
@TonnesM i can no longer replicate this issue. Is it solved for you now?

**Comment by TonnesM** [comment]
Yes I can, no change. This probably depends on font and/or screen settings.

Removing one word in the line in Dev view prevents wrapping and more importantly, the checkbox then appears on the proper place. Can you check or reproduce by using nl or bg (longest strings) or by adding words to en-US?

**Comment by prawnsalad** [comment]
Now fixed in https://github.com/kiwiirc/kiwiirc/commit/c7b832650544e9dfc6533c268eb391c1cd45aa5a, thanks!
