### ISSUE TITLE
api component leak

### ISSUE THREAD

**Issue by ItsOnlyBinary** [kiwiirc/kiwiirc#355]
example plugin: https://gist.github.com/ItsOnlyBinary/8b23f64f228b70ed01c947a2fa85dd8f

How: load the plugin -> start a query window -> switch to channel window.

Issue: the button component from the plugin should now be in the topic button.

Expected: the button should only be shown when buffer isQuery()

related pr #357 with its own issues

**Comment by prawnsalad** [comment]
Fixed in https://github.com/kiwiirc/kiwiirc/commit/b1bfa0fc48f16a82f353da808d21abcf74cfa5e8
