### ISSUE TITLE
When sending a private message with /msg, open a new tab for the discussion

### ISSUE THREAD

**Issue by mestaritonttu** [kiwiirc/kiwiirc#358]
Currently when you initiate a new private discussion through /msg it just disappears in space.

**Comment by ItsOnlyBinary** [comment]
I've just tested this against master and `/msg nick just a test message` does open a query buffer. Please let us know if I'm miss understanding or its an issue with a certain browser

**Comment by mestaritonttu** [comment]
Unfortunately it still does not work (using kiwiirc.com). Firefox 60.0.2 / Linux
The buffer is only opened on the recipient's end.
Is the fix deployed to kiwiirc.com?
