### ISSUE TITLE
When clicking on 'Remove Network' we are taken to a blank screen

### ISSUE THREAD

**Issue by AllanOcelot** [kiwiirc/kiwiirc#359]
**Replicate:**
- Click add network button
- Click 'Danger zone, remove network'
- You will be taken to a blank screen

**Solution:**
We should tell the user with feedback the network has been removed, then show the user a screen, even if that's a new 'Please choose a network' type placeholder screen in the main container :)

**Comment by ItsOnlyBinary** [comment]
To add to this issue, when removing the last network with customServer startup it does not get removed and only gets disconnected

**Comment by ItsOnlyBinary** [comment]
fixed
