### ISSUE TITLE
StartupScreen: welcome change text

### ISSUE THREAD

**Issue by MatijaTerzic** [kiwiirc/kiwiirc#369]
Hello,

Is it possibly to modify the text on startupscreen welcome ?

**Comment by prawnsalad** [comment]
You can add these to your config file. The last four items here are what you're looking for. https://github.com/kiwiirc/kiwiirc/wiki/Configuration#startupoptionsgreetingtext

You might want to ask general support questions on our mailing list in future, https://groups.google.com/forum/?fromgroups#!forum/kiwiirc
