### ISSUE TITLE
Bring Kiwi to desktop with electron

### ISSUE THREAD

**Issue by xnite** [kiwiirc/kiwiirc#372]
Excuse me if these instructions are a little off I apologize. But this should produce a working kiwiirc client in electron.

# building the client and electron app
    mkdir src-folder
    cd src-folder
    mkdir client
    git clone https://github.com/kiwiirc/kiwiirc.git
    cd kiwiirc
    yarn install
    yarn build
    cp -r dist/* ../client/
    cd ../
    wget https://gist.githubusercontent.com/xnite/6578c688a0b40d75ecc0dcf729744bb8/raw/5e35540449e791fffbffa10db958d0d5c39ff207/package.json -O client/package.json
    wget https://gist.githubusercontent.com/xnite/ce2f97995e4a94b670fb7cb046a08273/raw/cf5331aabc48ea7d2ac3858f163fad68e7fc46c9/main.js -O client/main.js

# Running for development
Go into the client/ folder, and run `electron .`

# building
outside of the client directory run `electron-packager ./client --electron-version=2.0.2 --all` (replace version with your current version).

You'll probably also want to look into these programs: electron-installer-debian,electron-installer-windows

My client/static/config.json looks like this: https://gist.github.com/xnite/a4f4e20a2489de2931dabf0799434ecd

**Comment by xnite** [comment]
Try https://github.com/kiwiirc/desktop-electron :smile:
If this does not work on your mac please let me know in an issue on that repository.
Thank you. :smile:

**Comment by CoryChaplin** [comment]
Works, awesome man !
