### ISSUE TITLE
Idle time being displayed incorrectly

### ISSUE THREAD

**Issue by KoraggKnightWolf** [kiwiirc/kiwiirc#374]
It appears that of the seconds idle, only the first few are interpreted, this is confirmed to occur on InspIRCd.  Testah
User account: Koragg
Testah!sid268081@Koragg.The.Knight.Wolf (IRCCloud)
Connected to server irc-can.icq-chat.com (ICQ-Chat CAN Server - Toronto, Canada)
Using a secure connection
Idle for 80 seconds

While the raw log shows this for the idle time: 
[S] :irc-can.icq-chat.com 317 kiwi_5921 Testah 80013 1524237686 :seconds idle, signon time

Hopefully this issue can be resolved soon, it seems to "cut off" for some reason.

Thank you for your time and effort in advance.

Regards,

Koragg

**Comment by ItsOnlyBinary** [comment]
The fix for this has now been merged into master. Thanks for the issue report
