### ISSUE TITLE
Changing nickname from server settings tab

### ISSUE THREAD

**Issue by H7-25** [kiwiirc/kiwiirc#385]
if you change nick from server setting tab, kiwi display the new nick  , but don't send the command to server, so  if you write in a channel you see your new nick , but you don't have it on ircd. In channel userlist you have the old nick.

**Comment by TheBeerbarian** [comment]
Tested to see if I could replicate.  Nick updates for me in userlist.  Notification and messages, and userlist for other users shows new nick.  Recent commits revolving around other userlist corrections may have fixed this.

**Comment by AllanOcelot** [comment]
Tested, cannot replicate, verified as stable by another user.

**Comment by prawnsalad** [comment]
To replicate:
* Connect to a network
* Open network settings
* Edit the nick box
* Notice how the nick changes locally, but not on the network itself

**Comment by TheBeerbarian** [comment]
Strange.. it is happening to me now.  Not sure what I was doing before, but definitely doesn't inform the ircd.
