### ISSUE TITLE
Use background color in own messages

### ISSUE THREAD

**Issue by TheMythPT** [kiwiirc/kiwiirc#386]
Something that might be useful on **KiwiIRC**:
There's something that I really like in IRCcloud: your own messages have a background too, a bit lighter than the highlight background.
Some might think the function is useless, but I find it handy to search your own messages between thousands of them.

Here's two screenshots (from web and mobile client):
[Mobile](https://imgur.com/AaNhu73)
[Web](https://imgur.com/YDi3P9a)

They look basically the same, just as comparison term.

**Comment by AllanOcelot** [comment]
Merged in on #811  :)  Thanks for the suggestion @TheMythPT
