### ISSUE TITLE
self-popup hard to close

### ISSUE THREAD

**Issue by strarsis** [kiwiirc/kiwiirc#391]
When clicking ones own name in kiwirc, a self-popup appears, this can also happen accidentally.
It was very hard for me figuring out how to close it (click again on the name to make it collapse)
and the popup actually covers the conversation text behind it.

There is no typical cross icon at the corner for example.
In the end I had to remove the DOM elements using browser inspector 
(because I didn't want to reload the whole page and restart the client).

**Comment by AllanOcelot** [comment]
#393 should resolve this once merged in :)

**Comment by ItsOnlyBinary** [comment]
The fix for this has been merged into master. Thanks for the report
