### ISSUE TITLE
User list gets wider after opening a PM tab from a bubble icon

### ISSUE THREAD

**Issue by mestaritonttu** [kiwiirc/kiwiirc#395]
1. Display user list
2. Click some bubble icon
3. Go back to a channel tab
Observe the user list width having increased.

**Comment by H7-25** [comment]
https://imgur.com/a/Zm7WeF1

**Comment by AllanOcelot** [comment]
Thanks for the gif @H7-25  - I shall apply a max width to this tonight 👍

**Comment by ItsOnlyBinary** [comment]
This is now fixed in master :) thanks for issue
