### ISSUE TITLE
Prevent HTTP users from connecting to servers with SSL

### ISSUE THREAD

**Issue by itsrachelfish** [kiwiirc/kiwiirc#408]
Users who visit http://kiwiirc.com/nextclient/ without encryption should not be allowed to connect to IRC servers via SSL. At the very least, there should be some way to differentiate between users who connect using HTTP vs HTTPS.

I run a channel which requires all users to connect via SSL. There is currently no way to tell if somebody is connecting to the channel using Mibbit / KiwiIRC using HTTP or HTTPS, so these web chats are banned.

**Comment by ItsOnlyBinary** [comment]
http://kiwiirc.com/nextclient/ redirects to https for me. Please confirm but I'm going to close this as an issue.

**Comment by ItsOnlyBinary** [comment]
after some further testing it seems urls with www.kiwiirc.com don't automatically redirect. I will see that this is investigates some more.

**Comment by itsrachelfish** [comment]
If you've visited the site with https in the past, most modern browsers will automatically redirect to https instead. Try opening the link in an incognito window :nerd_face:

**Comment by ItsOnlyBinary** [comment]
thanks it didn't redirect in incognito. I will try to look into this issue for a good solution in the week

**Comment by prawnsalad** [comment]
Ah this was an issue for the new kiwiirc.com page. I've put a fix in place now, thanks!
