### ISSUE TITLE
Get server responses on active channel buffer

### ISSUE THREAD

**Issue by madprops** [kiwiirc/kiwiirc#411]
I'm trying to get information from a bot using net.ircClient.raw('NOTICE', 'somebot', '!somecommand') which works but it shows the response on the server buffer instead of the channel. I need it to show it in the channel. Is there way to unify this to show everything in the channel buffer?

**Comment by mestaritonttu** [comment]
Related to #310

**Comment by madprops** [comment]
I think the way it's managed is around this line:

https://github.com/kiwiirc/kiwiirc/blob/1696f4389912bb8ab30c969cc0d586e35162b17d/src/libs/IrcClient.js#L308

**Comment by ItsOnlyBinary** [comment]
we already have issues for the lack of message routing, also about making it stand out when there is new information in the server buffer.
