### ISSUE TITLE
Confirmation on page reload with Kiwi iframe

### ISSUE THREAD

**Issue by madprops** [kiwiirc/kiwiirc#416]
I have an iframe that loads kiwiirc. When I try to reload or close the tab it shows this confirmation box [this message](https://i.imgur.com/q5K3JfI.jpg) "Changes you made made may not be saved".

Which is annoying of course. This happens on Chrome and Firefox. 

This only happens after the Kiwi iframe has been focused. 

Is this actually triggered by Kiwi, and is there a way to turn it off?

**Comment by prawnsalad** [comment]
Just to add to that, you woudl add that config options to your config.json file.
