### ISSUE TITLE
emojiOne Emoticons

### ISSUE THREAD

**Issue by spencerthayer** [kiwiirc/kiwiirc#42]
Is a complete emoticon package in the works? If one has not been decided upon may I suggest using the EmojiOne set? It's really easy to [install](https://github.com/emojione/emojione/blob/master/INSTALLATION.md) and use.

**Comment by LouisT** [comment]
Hello, I previously had written emoji plugins for the previous version of the kiwi client. Once the plugin interface is in place for this version I plan on updating (most likely full rewrites, however) some of my previous plugins. For the older client, they are available at [LouisT/KiwiIRC-Emoji-EmojiOne](https://github.com/LouisT/KiwiIRC-Emoji-EmojiOne) and [LouisT/KiwiIRC-Emoji-Twemoji](https://github.com/LouisT/KiwiIRC-Emoji-Twemoji). If there are any changes or improvements to these plugins that you'd like to see in the next versions, please open an issue in those repositories.

**Comment by prawnsalad** [comment]
I've now put emoji support into the core so that it can be better integrated. The main reason is that you can now see the emoji previews as you type

![image](https://user-images.githubusercontent.com/725880/30515761-d9e15ad6-9b25-11e7-8c7c-35958a5b6f32.png)

**Comment by spencerthayer** [comment]
This is great!
