### ISSUE TITLE
Dark theme unreadable text

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/kiwiirc#438]
The white box here should show some text. Secondaly, should this box even be white on the dark theme?
![image](https://user-images.githubusercontent.com/725880/42411807-765e6b2c-81fa-11e8-861a-335d44c9f9ec.png)

<Beerbarian> Effecting the Unread Messages text also.

**Comment by TheBeerbarian** [comment]
Possibly by line 546 in MessageList.vue overriding the theme setting?

https://github.com/kiwiirc/kiwiirc/blob/master/src/components/MessageList.vue#L546

**Comment by AllanOcelot** [comment]
@TheBeerbarian  is absolutely correct. The component is overriding the theme - the background should not be in the component but rather within the theme (if needed, in this case, the background isn't needed).


Made the pr here #439
