### ISSUE TITLE
Feature request: please remove "are you sure you're ready to leave" dialog box

### ISSUE THREAD

**Issue by jonassteinberg1** [kiwiirc/kiwiirc#441]
Subject says it all.  I find it extremely annoying.  It's like y'all put a leash on me.  I always want to go to leave and then y'all "yank" me back and ask "...are you sure?"  Y'all have done a great job, absolutely great job with making IRC accessible in a modern browser with a very intuitive and aesthetically pleasing UI.  But then there's that...

No disrespect intended.  In fact the only reason I even took the time to write this during my work day is because I do use y'alls platform.  

Thanks again, Jonas.

**Comment by prawnsalad** [comment]
if youre using kiwiirc.com then that's needed since a lot of people refresh or leave the page by mistake. Maybe we could an advanced option for this though.

If you're running your own instance of Kiwi, then you can add `"warnOnExit":false` to your config file.

**Comment by prawnsalad** [comment]
Actually we get more complaints when the warning is not in place as people then loose conversation and everybody they are talking to just sees that they quit the IRC channel without warning.

I've now added a new command that lets you disable this if you don't see the need in your use case though: `/set warnOnExit false`

**Comment by jonassteinberg1** [comment]
I appreciate it!
