### ISSUE TITLE
Update the default theme

### ISSUE THREAD

**Issue by TheMythPT** [kiwiirc/kiwiirc#45]
imho, in here:
https://github.com/kiwiirc/kiwiirc/blob/master/static/themes/default/theme.css#L314
the opacity sould be set to: "opacity: 100;" so that nick are always preppended to the message.
i think is kinda confusing for some people that are new to irc to understand to who the messages belong, when they dont see the nick before the message.
what do you think about that?

**Comment by prawnsalad** [comment]
The nick being hidden on messages if they are the same as the above message user is pretty common among messenger apps so I'm not sure who will be getting confused about it.
