### ISSUE TITLE
Feature: add bin script to package.json

### ISSUE THREAD

**Issue by dbkaplun** [kiwiirc/kiwiirc#469]
Hello,

It would be great if there was a bin script in package.json that ran KiwiIRC, so that instead of cloning the repo I could run
```sh
$ npm install -g kiwiirc
$ kiwiirc
```

Thanks!

**Comment by prawnsalad** [comment]
What would you see it running? Once you build the project you copy the static files to your webserver.

If you're looking for complete installation packages, take a look at https://kiwiirc.com/downloads/
