### ISSUE TITLE
Send button on Mobile view

### ISSUE THREAD

**Issue by H7-25** [kiwiirc/kiwiirc#477]
many users complain about the lack of a button to send the text on mobile device.
Also plugin icons should need a better solution because on mobile keep many space over text input.

**Comment by H7-25** [comment]
Modify line 45 on ControlInput.vue to : 
<button v-if="!this.$state.ui.is_touch" type="submit">Send</button>
will enable this feature, it need only a style.

**Comment by ItsOnlyBinary** [comment]
This feature has been added in the form of a plane icon. Thanks for your input ;)
