### ISSUE TITLE
Channel Search - input closes if no input value present

### ISSUE THREAD

**Issue by AllanOcelot** [kiwiirc/kiwiirc#479]
How to replicate:

- Join network
- Hover over network name in statebrowser
- Click search icon (The search form appears)
- Click on the 'Find more channels' link

The form you just clicked will now close rather than taking you to the channelist component.
If the user enters a value into the input, and then clicks the link, it works as expected. 

What should happen:
Clicking the link takes the user to the channellist component, without needing a search string in the input.

**Comment by ItsOnlyBinary** [comment]
This is now fixed in master
