### ISSUE TITLE
Startup Options password/autoconnect

### ISSUE THREAD

**Issue by cab10** [kiwiirc/kiwiirc#48]
Would be nice if startupOptions password for the server password would be added and also a autoconnect feature.

**Comment by prawnsalad** [comment]
Auto connecting is an option when using the `welcome` startup screen. I've just added it to the docs here https://github.com/kiwiirc/kiwiirc/wiki/Configuration#startupoptionsautoconnect

In what case would you want to specify a server password for auto connect? It defeats the purpose of having a password.

**Comment by cab10** [comment]
A password protected website where you see the actual IRC-Server password. The kiwiirc client would also be stored in that password protected environment. At the moment I am using the "old" kiwiirc client and send the password variable through a get parameter.

**Comment by prawnsalad** [comment]
I've now added a password option for the welcome startup screen. The autoconnect is already in there. Thanks for the suggestion!
