### ISSUE TITLE
How hide network tab and channel tab?

### ISSUE THREAD

**Issue by legendskyk** [kiwiirc/kiwiirc#489]
is there any possibility to hide network tab? and only visible channel tab?

**Comment by ItsOnlyBinary** [comment]
You can't hide the network tab on the left side.
You can hide the network settings tab though by setting "restricted": true in your config.json

Hope that helps

**Comment by legendskyk** [comment]
ok thanks for help, is that possible to give icon in png image to nick modes like @, +, % ?

**Comment by ItsOnlyBinary** [comment]
This would be possible by editing the themes, each user is given selectors like `.kiwi-nicklist-user--mode-o`
example: `.kiwi-nicklist-user--mode-o .kiwi-nicklist-user-prefix { whatever }`

some more reading: https://github.com/kiwiirc/kiwiirc/wiki/Theming

**Comment by legendskyk** [comment]
I did edit theme.css thats doesnt work, what is the correct css code for that?

**Comment by legendskyk** [comment]
ok images got work out i sort out css but now I cant able to set size of image in css what is the code for height and weight ?

**Comment by prawnsalad** [comment]
Searching google will be better for general CSS help. But try setting `display:inline-block; height:10px; width:10px;`.
