### ISSUE TITLE
One idea to show other user info on connecting (idea that comes from mibbit)

### ISSUE THREAD

**Issue by TheMythPT** [kiwiirc/kiwiirc#49]
I was wondering about the info we do receive when a user connects from a KiwiIRC instance (web version and self hosted version).
If we don't have a webirc block set, the IP that will appear is the IP that KiwiIRC uses to connect.
One thing that I've found out from Mibbit IRC client, is that if we don't have one webirc block, it will send the following info:
22:27:31 <+ Global> USERS: Mibbit_Tester!4d983529@64.62.228.82 (D310B93A.7BB08423.C8C5EA10.IP) (xx.xx.xxx.xx.rev.sfr.net) connected to the network (irc.network.here).
What do we have there?
Nickname!hexip@mibbit.ip (cloaked host) (real IP/hostname).
What do you think about this? Can this be ported to KiwiIRC?
That way we have 2 types of ban we can set (on UnrealIRCd at least, which is the one im using).
We can ban by hexip or by realname.
This is just one idea.
Waiting for further replies.

**Comment by TheMythPT** [comment]
Note: this only applies if someone connect to a network that don't have a proper webirc block set.

**Comment by prawnsalad** [comment]
This shouldn't be in the client as anybody could simply change it and get around bans. However on the server-side we use the webircgateway project that simply proxies the browser tot he IRC server. That supports rewriting the ident and real name which the info you're looking for.

https://github.com/kiwiirc/webircgateway/blob/master/config.conf.example#L12
