### ISSUE TITLE
Dark Theme: Search user list entry text for search to dark after PR#486

### ISSUE THREAD

**Issue by TheBeerbarian** [kiwiirc/kiwiirc#503]
![image](https://user-images.githubusercontent.com/24723440/44123943-e07700c2-9fe7-11e8-9ddc-1b9a1618f8d5.png)

**Comment by AllanOcelot** [comment]
Nice :)

**Comment by TheBeerbarian** [comment]
I added a fix with PR #505 for just the dark theme.   If that was the
correct fix I could do the same for the other themes that needed a slightly
lighter text for the search input.

Cowan

**Comment by TheBeerbarian** [comment]
Closed PR505 to new PR508 so would be from local branch. Made suggested review changes from PR505.

**Comment by TheBeerbarian** [comment]
Fixed with PR 508.
