### ISSUE TITLE
Channel Options Confusion

### ISSUE THREAD

**Issue by jamiejackson** [kiwiirc/kiwiirc#51]
We discussed some of this on #kiwiirc@freenode the other day:

* It's confusing that there are two channel options (the bell next to channel name, and at the top right). You were considering making them two entry points into the same menu.
* As implemented now, the bell icon isn't appropriate for icon next to the channel name, as it also has a channel delete option. (The bell would seem to encompass just notification options.)

**Comment by AllanOcelot** [comment]
Has been revised and hopefully fixed with the New layout merge, @prawnsalad

**Comment by jamiejackson** [comment]
Not sure if this is live or not, but if it is, minor thing: The left padding is squashed for me in chrome:

![image](https://user-images.githubusercontent.com/479475/39331920-ddb31ecc-4973-11e8-98df-30b5fabc1263.png)

**Comment by prawnsalad** [comment]
It's not yet live, @jamiejackson. However you can see the master build here: https://builds.kiwiirc.com/kiwiirc/master/
