### ISSUE TITLE
statusmsg doesn't display properly

### ISSUE THREAD

**Issue by emersonveenstra** [kiwiirc/kiwiirc#518]
sending a statusmsg to all voiced users of a channel, i.e. `PRIVMSG +##testing :hi` doesn't display in `##testing` like it should, rather it creates a new tab called `+##testing` where all those messages go. Sending a statusmsg to all ops of a channel shows up in the correct channel, but there's no indication that it's a statusmsg rather than a normal message, they look the same.

This is going to be a bit of an issue once https://github.com/freenode/ircd-seven/pull/31 is deployed

**Comment by prawnsalad** [comment]
This was fixed in the irc-framework library and we're just waiting on the next release of that which should be any day. https://github.com/kiwiirc/irc-framework/commit/9d9c5edfb996ad2a7c535c0b54030512962bda21

**Comment by ItsOnlyBinary** [comment]
The irc-framework changes this was waiting on has now been released and is included in recent builds of kiwiirc.
