### ISSUE TITLE
Delete on Invitation-Only Channel doesn't Work

### ISSUE THREAD

**Issue by jamiejackson** [kiwiirc/kiwiirc#52]
I can't delete an invitation-only channel (to which I'm not invited). (It keeps immediately reappearing in my channel list.)

![image](https://user-images.githubusercontent.com/479475/28474925-68a4b21c-6e18-11e7-8fb3-d6c24ec77135.png)

**Comment by prawnsalad** [comment]
Fixed in master, https://github.com/kiwiirc/kiwiirc/commit/18e321f711e53eae609df6dedf7be5f8f527e7cb
