### ISSUE TITLE
Add /bleep and /notify commands

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/kiwiirc#521]
/bleep would trigger an audio bleep while /notify would trigger a browser notification

**Comment by AllanOcelot** [comment]
I assume these commands would 'ping' everyone in the room, so all users get that notification etc?.
That'd would be really useful for small teams etc 👍

**Comment by prawnsalad** [comment]
Nope, that's what highlights and /notice is for. /bleep and /notify are to send yourself an audio ping or notification dialog so that they can be used in scripting. Eg. "if user X talks, run the command '/ping' so i get a sound"
