### ISSUE TITLE
how to tag nick?

### ISSUE THREAD

**Issue by legendskyk** [kiwiirc/kiwiirc#528]
there is no option for tag nick? how to tag nick? like on mirc and mibbit other widget we press nickname first alphabet and press tab button then nick got appeard on type panel but kiwiirc doesnt have? so help me out about tagging nick.

**Comment by legendskyk** [comment]
I mean to tag nickname from nicklist on type panel, like if a user nick is Kinny, then I have to just type K then press tab button on keyboard nick got appeared on the type  panel, thats for computer or laptop,

another problem about cell phone and tablets both keyboards doesnt have tab buttons so how we have to tag nicknames of chatters on room? hope i make understand the problem.

**Comment by legendskyk** [comment]
and the screen shot you posted here, how this popup comes out? because its not appear it to us please guide us how that pop up nicks?

**Comment by mestaritonttu** [comment]
You don't type @, you just use tab completion just like you described in your first comment.
Have you deployed Kiwi IRC yourself or are you using the https://kiwiirc.com/nextclient/ instance?

**Comment by Shillos** [comment]
Same here too when I tried tab and @ works the same on the new kiwi.

**Comment by legendskyk** [comment]
Yes, thats work for laptop or desktop computer only, the  main problem is for cell users, and also tablets users because cell phone keyboard does not have tab button nor tablets.
 
but its show nicknames when we type @ there is not any other easy method?
I installed as follow readme file

**Comment by prawnsalad** [comment]
@legendskyk right, on touch screens it's not so easy. We should think of a way to tap on the nick somewhere to mention them into the input box

**Comment by legendskyk** [comment]
@prawnsalad another thing also put in future update if someone nicks being tag in the room, notification beep go to the user who being tag in the room or in pm notification or popup system. thats suggestion.

**Comment by prawnsalad** [comment]
I've been playing around with this but it gets really messy trying to get double taps on mobile. I'm going to close this issue as we already have nick auto complete when typing @ already so it's not really worth messing things up for anything else.

When we have a native mobile app it will be much easier in there.
