### ISSUE TITLE
When I install this, it just serves a blank webpage [SOLVED]

### ISSUE THREAD

**Issue by desultory** [kiwiirc/kiwiirc#53]
I just installed this by running the following commands

git clone https://github.com/kiwiirc/kiwiirc.git
yarn install
yarn run build

and now I just have a blank webpage in the directory I installed it in.  I'm using apache and have the latest versions of apache2, node, and yarn and am running deiban jessie

**Comment by ItsOnlyBinary** [comment]
After building the output is in ./dist/ these are the files you need to copy to your webserver

**Comment by desultory** [comment]
I cloned an installed it in a webdir, /var/www/irc/ with /irc/ being the root where the files were cloned and installed.  Are you saying that the website should actually link yo /var/www/irc/dist?

**Comment by ItsOnlyBinary** [comment]
clone it to somewhere not in your webdir eg ~/ (home). run the build commands. when complete copy the contents of ./dist/ (the build output folder) to your webdir

**Comment by desultory** [comment]
ok I copied the contents to my webdir but now I can't connect to anything, even if I use the default connection information, nothing happens.

**Comment by desultory** [comment]
I could probably figure this out if I saw where it was logging to but I don't see it logging to /var/log/apache2/error.log.  If i enable direct connection it tries connecting forever and if i disable it, it just stops connecting immediately after i press connect.

**Comment by desultory** [comment]
if you give me a way to contact you directly I can send you a link to the site where it is hosted so you can help debug it, I'd prefer not to post it to the public

**Comment by ItsOnlyBinary** [comment]
you need to also run the gateway software 
https://github.com/kiwiirc/webircgateway
https://kiwiirc.com/downloads

for faster support:
https://kiwiirc.com/client/irc.freenode.net/#kiwiirc

**Comment by desultory** [comment]
I need to run the gateway even if I already have unreal running?

**Comment by ItsOnlyBinary** [comment]
yes, the gateway is the bridge between http and irc

**Comment by desultory** [comment]
The last issue was fixed with the latest version of kiwi irc so now everything is working
