### ISSUE TITLE
How to hide Prefix like @ + & ~ and just only icon show?

### ISSUE THREAD

**Issue by legendskyk** [kiwiirc/kiwiirc#532]
Hello,
I am successfully add icons infront of prefix of nicks like ~&@% but i wanted to show only icon images and hide the prefixs how it possible through css ?

**Comment by prawnsalad** [comment]
Does adding `display: none;` to `.kiwi-nicklist-user-prefix` not work?

**Comment by legendskyk** [comment]
thats not work

**Comment by legendskyk** [comment]
i mean not work by if we doing so then image icon also got hided.

**Comment by prawnsalad** [comment]
Ah, this will work for you then:

~~~css
.kiwi-nicklist-user-prefix {
    visibility: hidden;
}
.kiwi-nicklist-user-prefix:before {
    display: inline-block;
    content: "";
    background: url(https://avatars2.githubusercontent.com/u/725880?s=88&v=4);
    width: 50px;
    height: 50px;
}
~~~

![image](https://user-images.githubusercontent.com/725880/44792790-994cdf80-ab9c-11e8-8b8e-864048979097.png)

**Comment by legendskyk** [comment]
yes thanks its now got worked
