### ISSUE TITLE
Why its show users as bot in whois?

### ISSUE THREAD

**Issue by legendskyk** [kiwiirc/kiwiirc#533]
![whoisbot](https://user-images.githubusercontent.com/42233490/44795228-a9c48080-abc3-11e8-9d49-8c58a4b762cc.png)
why this shown every user as Is Bot?

**Comment by prawnsalad** [comment]
That would only show if the IRC server says it's a bot. Which network is this on so I can test it?

**Comment by legendskyk** [comment]
its my own network.

**Comment by legendskyk** [comment]
only this kiwirc is shown that in whois.

**Comment by prawnsalad** [comment]
Ok. But which network is it so I can test it? Or can you paste some raw traffic output when you whois somebody?

**Comment by TheBeerbarian** [comment]
The users on the network don't have mode +B somehow?

**Comment by legendskyk** [comment]
no user is not set as +B mode still its show as whois 
@prawnsalad server is irc.icqchat.net

**Comment by legendskyk** [comment]
> _Im2Big4U_35m is ~_Im2Big4U_3@679785.E05324.F18963.A647F3 * _Im2Big4U_35m
(29:20:06) _Im2Big4U_35m is connecting from ~_Im2Big4U_3@84.226.140.139 84.226.140.139
(29:20:06) _Im2Big4U_35m on #icqchat 
(29:20:06) _Im2Big4U_35m using irc-m01a.pink.icqchat.net Knowledge is power, lets discover our common ground
(29:20:06) _Im2Big4U_35m is using modes +GTciwx
(29:20:06) _Im2Big4U_35m is connected from Switzerland (CH)
(29:20:06) _Im2Big4U_35m has been idle 27secs, signed on Wed Aug 29 19:09:11 2018
(29:20:06) _Im2Big4U_35m End of /WHOIS list.

same user when i whois through mirc there is not shown as BOT.

**Comment by TheBeerbarian** [comment]
See it happening when I connect in with my Kiwiirc personal client.   The portion reporting what part of the world user is connecting form is causing it to look as a bot for some reason.

[C] WHOIS testguy testguy
[S] :irc-m01a.orange.icqchat.net 311 TestGuy TestGuy ~TestGuy 6B9A0B.6B51EB.027E5A.F593C4 * :https://kiwiirc.com/
[S] :irc-m01a.orange.icqchat.net 378 TestGuy TestGuy :is connecting from ~TestGuy@
[S] :irc-m01a.orange.icqchat.net 312 TestGuy TestGuy irc-m01a.orange.icqchat.net :Knowledge is power, lets discover our common ground
[S] :irc-m01a.orange.icqchat.net 379 TestGuy TestGuy :is using modes +GTciwx

**[S] :irc-m01a.orange.icqchat.net 335 TestGuy TestGuy :is connected from United States (US)**

[S] :irc-m01a.orange.icqchat.net 671 TestGuy TestGuy :is using a secure connection
[S] :irc-m01a.orange.icqchat.net 317 TestGuy TestGuy 821 1535566275 :seconds idle, signon time
[S] :irc-m01a.orange.icqchat.net 318 TestGuy TestGuy :End of /WHOIS list.
12:23:18
testguy
is TestGuy!~TestGuy@6B9A0B.6B51EB.027E5A.F593C4 * (https://kiwiirc.com/)
is connecting from 76.127.13.26 76.127.13.26
is using irc-m01a.orange.icqchat.net (Knowledge is power, lets discover our common ground)
is using modes +GTciwx
is using a secure connection
has been idle for 13 minutes 41 seconds
connected on Wed Aug 29 2018 12:11:15 GMT-0600 (Mountain Daylight Time)

bot: **is connected from United States (US)**

**Comment by TheBeerbarian** [comment]
If I remember a while back.. the author of one of the geo modules for inspircd was incorrectly using numeric 335 (whois reply for a bot) and it was causing this problem until they changed the numeric to an unused one.

**Comment by legendskyk** [comment]
so what is the solution for this?

**Comment by TheBeerbarian** [comment]
Yup.. here was the issue.. fixed 7 months ago with change to m_geoipban.cpp

https://github.com/inspircd/inspircd-extras/commit/322f4689482645c0b87ed9d46ba25b260f418f4c

**Comment by TheBeerbarian** [comment]
Solution is to update the m_geoipban module from inspircd-estras.

**Comment by prawnsalad** [comment]
Good shout, @TheBeerbarian 

@legendskyk I'm going to close this issue as it's an issue with the GeoIP module the network is running. You may want to poke them in their staff channel to update their server modules.
