### ISSUE TITLE
A Suggestion about Radio Streaming player option

### ISSUE THREAD

**Issue by legendskyk** [kiwiirc/kiwiirc#535]
Hello,
I am going to show a image should be have there option about Radio player where we put streaming link for live radio or for RJ shows etc... is that possible?
![radiostreamplayer](https://user-images.githubusercontent.com/42233490/44811810-01c4ac80-abef-11e8-9c0e-5ece0c6f9aa7.png)

**Comment by ItsOnlyBinary** [comment]
this would be possible as a plugin using 
https://github.com/kiwiirc/kiwiirc/blob/master/src/libs/GlobalApi.js#L110

**Comment by legendskyk** [comment]
How configured plugin?

**Comment by ItsOnlyBinary** [comment]
https://github.com/kiwiirc/kiwiirc/wiki/Plugins

**Comment by ItsOnlyBinary** [comment]
example as a html file https://gist.github.com/prawnsalad/d83476166da0b7113c50140201833388

**Comment by legendskyk** [comment]
I am not familiar with Java coding, can you more specific how to add my radio stream as java code? and how it will appear in the same place where i highlighted in the image?

**Comment by ItsOnlyBinary** [comment]
You need to make a plugin in javascript and use kiwi.addUi('header_channel', domElement)

https://github.com/kiwiirc/kiwiirc/wiki/Plugins

**Comment by plusin** [comment]
I cant make a plugin, can anybody give the code to integrate my shoutcast radio player to the webchat? please!
