### ISSUE TITLE
Suggestion about Admin and OP Remove Offensive Chat

### ISSUE THREAD

**Issue by legendskyk** [kiwiirc/kiwiirc#540]
Hi,
I suggest you guys for future update in kiwiirc there should be also have a function admin or operator remove the chat of a user who use abusive word by /remove usernick msg then that user msg got removed from chat window and not appear to anyone to control spamm and abuse in chat room is that possible?

**Comment by TheMythPT** [comment]
Depending in the IRCd used in the network you're in, there could already exists some other built-in ways to deal with spam (like blocking/replacing offensive words).

Cheers

**Comment by legendskyk** [comment]
there is but, like Mibbit widget op and admin can remove the chat from being appear to other users from channel window.

**Comment by TheMythPT** [comment]
Which doesn't make much sense, as the messages would only be erased from KiwiIRC itself but still be available to other users connected via other IRC clients such as mIRC, HexChat...

**Comment by legendskyk** [comment]
You not got my point, it will help out and new functions for those users like me who have own private server and web chat site where only kiwiirc be allowed to join through. 

thats function will help out that type of sites and servers...

**Comment by TheMythPT** [comment]
I'd recommend you to use some sort of spamfilter (if using UnrealIRCd or InspIRCd that's a built-in feature).
This kind of features would make devs having more work load and would be useful in very very rare cases.

Cheers
