### ISSUE TITLE
Connect to UnrealIRCd without webircgateway

### ISSUE THREAD

**Issue by finalhit** [kiwiirc/kiwiirc#550]
Since UnrealIRCd supports the [WebSocket protocol](https://www.unrealircd.org/docs/WebSocket_support), is it possible to use it without [webircgateway](https://github.com/kiwiirc/webircgateway)?

Tried it without success.

**Comment by finalhit** [comment]
Tried both local instance (connecting to port 443 which is redirected to port 6800) and
```
"server": "irc1.unrealircd.org",            
"port": 6500,
"tls": true,
"direct": true,
```
mentioned at https://www.unrealircd.org/files/dev/ws/websocket_unrealircd.html without success.

Is it possible to connect to UnrealIRCd without webircgateway?

**Comment by DanielOaks** [comment]
The specific way these projects implement websockets differs so that'd be why you're having trouble using 'em together right now, more discussion over here: https://github.com/ircv3/ircv3-specifications/pull/342

**Comment by finalhit** [comment]
UnrealIRCd 5 is compatible with KiwiIRC if you use websocket type 'text':
https://www.unrealircd.org/docs/WebSocket_support

But cannot find the following configuration options (used in webircgateway):
- [clients] username (it's mentioned in the source code as network.username, but cannot find a way to set it in config.json)
- [clients] realname (it's mentioned in the source code as network.gecos, but cannot find a way to set it in config.json)
- send_quit_on_client_close
