### ISSUE TITLE
Image Preview is broken and webirc not worked

### ISSUE THREAD

**Issue by dateno1** [kiwiirc/kiwiirc#569]
it broken after upgrade from old nodejs version to new vue version

![p2](https://user-images.githubusercontent.com/12645246/45915686-495bf280-be94-11e8-9675-580fbe1c860b.png)
original image link is OK

but
![p1](https://user-images.githubusercontent.com/12645246/45915687-58db3b80-be94-11e8-9d60-cd122e508ab4.png)
preview not work

Server : linux x64 + kiwi v1.1.0 + plugin-fileuploader + nginx (for reverse proxy)
Client : linux x64 + firefox 62.0 / Windows 10 x64 + firefox 62.0

kiwiIRC binary from GitHub (precompiled)
fileuploader plugin compiled by
**go get github.com/kiwiirc/plugin-fileuploader
cd "$(go env GOPATH)/src/github.com/kiwiirc/plugin-fileuploader"
dep ensure
go build -o fileuploader *.go
cd fileuploader-kiwiirc-plugin
yarn install
yarn build**
main.js + plugin-fileuploader.js.map copied on KiwiIRC/www/static/plugins/fileuplader

![config json](https://user-images.githubusercontent.com/12645246/45915755-9c827500-be95-11e8-89e1-a638220fdac8.png)
config.json (otherthing default value)

[config.conf.txt](https://github.com/kiwiirc/kiwiirc/files/2407959/config.conf.txt)
config.conf (domain/password replaced) attatched

[irc.example.com.conf.txt](https://github.com/kiwiirc/kiwiirc/files/2407663/irc.example.com.conf.txt)
nginx configure attatched (domain/some value replaced/removed)

![env](https://user-images.githubusercontent.com/12645246/45915836-ec157080-be96-11e8-995e-f2780053da9d.png)
.env

![web](https://user-images.githubusercontent.com/12645246/45915844-254de080-be97-11e8-90b3-3d87368e9c3c.png)
webirc not worked (it worked on old nodejs version)

![prox](https://user-images.githubusercontent.com/12645246/45915862-79f15b80-be97-11e8-9c1a-9e6a3c097a46.png)
nginx maybe work well (fileuploader can receive real IP)

**Comment by ItsOnlyBinary** [comment]
can you please add your ircd's webirc block so i can see how you have that configured. This is likely the issue with webirc not working as your other config looks fine. for the image preview i will try and look into that later

**Comment by dateno1** [comment]
> 
> 
> can you please add your ircd's webirc block so i can see how you have that configured. This is likely the issue with webirc not working as your other config looks fine. for the image preview i will try and look into that later

![ngircd](https://user-images.githubusercontent.com/12645246/45933973-3ea77780-bfd2-11e8-92de-113ccd0981a5.png)
ngircd.conf

![kiwi](https://user-images.githubusercontent.com/12645246/45933979-49620c80-bfd2-11e8-8681-1db2331a2570.png)
kiwi error

**Comment by ItsOnlyBinary** [comment]
This is where you need to set the same webirc password as in your ircd: https://github.com/kiwiirc/webircgateway/blob/master/config.conf.example#L86

Where it says `connected to Network!`
the word Network is the default name the client uses, as the client connects to the server it should get `NETWORK=Name` in a 005 numeric this will then update the network name on the left side
https://github.com/ngircd/ngircd/blob/master/doc/sample-ngircd.conf.tmpl#L61

**Comment by dateno1** [comment]
![old](https://user-images.githubusercontent.com/12645246/45935433-76201f00-bfe6-11e8-8a86-750b99cc9643.png)
same password with old nodejs version

> Where it says `connected to Network!`
> the word Network is the default name the client uses, as the client connects to the server it should get `NETWORK=Name` in a 005 numeric this will then update the network name on the left side
> https://github.com/ngircd/ngircd/blob/master/doc/sample-ngircd.conf.tmpl#L61
i can't understand what do you mean

it worked and can use chat (image view and webirc not worked)

**Comment by dateno1** [comment]
i think it kiwi(new version)'s bug

![ngircd](https://user-images.githubusercontent.com/12645246/46007551-47449e80-c0f5-11e8-910f-7346e51069d0.png)
ngircd with temp password for test

![kiwi](https://user-images.githubusercontent.com/12645246/46007594-64796d00-c0f5-11e8-95a9-8741ad391b47.png)
re-maked kiwi config.conf (copy and rename sample conf and just change upstream only)

it same result (it print syntax error)

if i delete webirc value(change to "") no error printed

**Comment by dateno1** [comment]
> 
> 
> It seems ngircd is too strict on its WEBIRC syntax and only allows 4 parameters where kiwi sends 5.
> So i have created a pull request to fix the issue in ngircd [ngircd/ngircd#247](https://github.com/ngircd/ngircd/pull/247)

thanks webirc fixed

now how can i fix image preview?

**Comment by ItsOnlyBinary** [comment]
I've not managed to reproduce the image preview issue. Currently image preview uses embed.ly so make sure that the urls provided by the fileuploader plugin are externally accessible

**Comment by dateno1** [comment]
> 
> 
> I've not managed to reproduce the image preview issue. Currently image preview uses embed.ly so make sure that the urls provided by the fileuploader plugin are externally accessible

![p2](https://user-images.githubusercontent.com/12645246/46122450-a6b8c080-c253-11e8-88c4-13b310ab1428.png)
it can accessed on external

but
![p1](https://user-images.githubusercontent.com/12645246/46122468-bd5f1780-c253-11e8-821b-1b717b375ca3.png)
can't work with embed.ly

it not print any error on screen and nginx's log

it work with TLS1.2/1.3 only webserver? (with HSTS/HPKP)

how can i debug it?

**Comment by ItsOnlyBinary** [comment]
i dont think embed.ly will be sending a referrer. just do a test with all of your referrer checking && 403 commented out.

**Comment by dateno1** [comment]
> 
> 
> i dont think embed.ly will be sending a referrer. just do a test with all of your referrer checking && 403 commented out.
> 
> also check your nginx logs

i can't find any error log and i can't find access log exclude kiwi client's ip

also i was tested with no referrer limit (same result)

i think embed.ly api can't process my webserver's TLS setting (but can't remove TLS on sub domain on my server because it registed on HSTS library by google and etc (if i remove TLS settings on my all sub domains they say 'it https only domain' to client) )

![c0101297_59b1d931f2726](https://user-images.githubusercontent.com/12645246/46161975-f46c1200-c2c1-11e8-9b61-52af61463434.png)
it has very strong and perfect setting (scanned by ssllab)

**Comment by ItsOnlyBinary** [comment]
Maybe you have ssl too secure/strict for embed.ly? 
you might need to add access_log, error_log params to your nginx configs.

Anyway as this is no longer a kiwiirc issue. I'm going to close this github issue.
Goodluck

**Comment by dateno1** [comment]
> 
> 
> Maybe you have ssl too secure/strict for embed.ly?
> you might need to add access_log, error_log params to your nginx configs.
> 
> Anyway as this is no longer a kiwiirc issue. I'm going to close this github issue.
> Goodluck

it already added but can't find any special event on log (it common settings for all of my domains) (can connected by win7 + ie8+/xp + chrome|opera|firefox/android 4.0.0+ internal browser)

can i use some of internal api like old version or use kiwi server for proxy like theLounge (also it protect privercy of client)?

**Comment by ItsOnlyBinary** [comment]
you need to look in your nginx logs for attempted connections and what is returned. search the log for a file id that you have been trying to open in media viewer. it wont necessarily shows as an error it might just show in normal log that it returned status code 403 etc
