### ISSUE TITLE
can't connect by chrome

### ISSUE THREAD

**Issue by dateno1** [kiwiirc/kiwiirc#580]
server : linux x64 + nodejs 8.10.0 + kiwiirc v1.1.0 + nginx (for reverse proxy)
client : windows 7 x86 sp1/windows 10 x64 rs1/linux x64 (server self)
browser : chrome 69.0.3497.100/firefox 62.0.2/internet explorer 11.0.9600.17843

3 machine same result

can connect to server by any browser but 'start button' on main not worked on chrome only

[test video.zip](https://github.com/kiwiirc/kiwiirc/files/2425584/test.zip)
video captured on virtualbox + windows 7 (same result on all machine)

internet explorer 11 fresh updated from 9/firefox and chrome fresh installed (without any extension, no setting changed, no anti-virus)

i can't find any error or warning on nginx log

**Comment by ItsOnlyBinary** [comment]
in chrome please check the console (F12), also check the network tab check for anything getting error 403, 404 etc (anything not 200, 101)

**Comment by ItsOnlyBinary** [comment]
Just tested chrome 69.0.3497.100 and its working fine here. so i suspect its something with your configuration

**Comment by dateno1** [comment]
> 
> 
> in chrome please check the console (F12), also check the network tab check for anything getting error 403, 404 etc (anything not 200, 101)

when i connect to server
![connect1](https://user-images.githubusercontent.com/12645246/46185134-b39ce900-c313-11e8-8ce9-06cd3319e22c.png)
![connect2](https://user-images.githubusercontent.com/12645246/46185140-b7307000-c313-11e8-859f-d1e89786d965.png)

when i click start button
![start1](https://user-images.githubusercontent.com/12645246/46185152-c0b9d800-c313-11e8-8771-c80a53fc8b4f.png)
![start2](https://user-images.githubusercontent.com/12645246/46185158-c44d5f00-c313-11e8-9335-ff3c8b5fcd8d.png)
![start3](https://user-images.githubusercontent.com/12645246/46185160-c7484f80-c313-11e8-85a3-3ecfaaf76a1a.png)

i will check both configure kiwi and nginx but i don't know why can't use chrome only

**Comment by dateno1** [comment]
i fixed problem by edit kiwi's config.conf

add it on **[allowed_origins]**
`*://*.example.com`
(example.com is my domain)

not removed error(400/websocket) on chrome but it work well

i don't know why only needs it but problem is fixed

thanks for your help

**Comment by ItsOnlyBinary** [comment]
if your reverse proxying webircgateway you need to add some extra config options to allow for protocol upgrade to websockets, see my nginx config here:

https://gist.github.com/ItsOnlyBinary/3e244106bfa4101f70f8a20c2d0e76b3

note mine is a little unusual as i use sockets not ports, and i alias my config. pay close attention to `location /webirc/`

**Comment by dateno1** [comment]
thanks for help

can you add link to readme?

almost people maybe read that

**Comment by MathiasJRL** [comment]
Have you been able to fix it?
I just installed it and the same error continues, I can't log in through Chrome, how can I fix this?
