### ISSUE TITLE
Startup age location sex

### ISSUE THREAD

**Issue by gonzasylv** [kiwiirc/kiwiirc#591]
hi, 

Is it being developed a startup screen, having as startup form (pseudo, age, city, sex) and put this information in the realname of the user in this form for example (18 M / F New-york) and that in the room and nicklist the nicks be in color according to sex? Girl = pink and boy = blue.

Also give the possibility to send the data in GET to be able to send the data via an external form (example: https://url.com?nick=blabla&age=20&sex=F&location=Newyork

I saw that there was a github that apparently tried but I can not make it work : 

https://github.com/CoryChaplin/kiwiirc-v2/tree/agl by @CoryChaplin 

Thanks

**Comment by ItsOnlyBinary** [comment]
This is not something that is widely used, so would not be something we would add into the core.
It could however be done as a thirdparty startup screen.

https://github.com/kiwiirc/kiwiirc/tree/master/src/thirdparty

**Comment by CoryChaplin** [comment]
Hi,

 

That branch (made by me) is still work in progress (for the day I’ll get back on it).

It mostly works but isn’t polished and isn’t updated to master.

It’s not relevant as core feature but is indeed a precious addition for social or dating chatroom sites.

 

Cory

 

 

De : gonzasylv <notifications@github.com>
Répondre à : kiwiirc/kiwiirc <reply@reply.github.com>
Date : mardi 2 octobre 2018 à 16:29
À : kiwiirc/kiwiirc <kiwiirc@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [kiwiirc/kiwiirc] Startup age location sex (#591)

 

hi,

Is it being developed a startup screen, having as startup form (pseudo, age, city, sex) and put this information in the realname of the user in this form for example (18 M / F New-york) and that in the room and nicklist the nicks be in color according to sex? Girl = pink and boy = blue.

Also give the possibility to send the data in GET to be able to send the data via an external form (example: https://url.com?nick=blabla&age=20&sex=F&location=Newyork

I saw that there was a github that apparently tried but I can not make it work :

https://github.com/CoryChaplin/kiwiirc-v2/tree/agl

Thanks
