### ISSUE TITLE
Text colors being reset when sending the message

### ISSUE THREAD

**Issue by TheMythPT** [kiwiirc/kiwiirc#592]
When we choose a text color, after hitting Enter to send the message, the color is reset.

I'm facing this issue in Chrome for Linux and Chrome for Android. 

Cheers.

**Comment by TheBeerbarian** [comment]
I like the bug that the color is reset to default after sending a message.  If it is fixed I would like the current bug to be a feature that can be a configured option.
With self hosted platforms used for my IRCd, I rather discourage people from constantly talking in color and rather it reset after a message.
Thanks. :)
