### ISSUE TITLE
Messageinfo broken on mobile phones in classic 

### ISSUE THREAD

**Issue by cab10** [kiwiirc/kiwiirc#613]
If I click on a text message with traditional IRC Layout the "Reply in private" is way to much on the right side (barely can see the "R") and also it overlays the nickname. 

https://user-images.githubusercontent.com/30303507/47173765-3b708480-d30f-11e8-8c22-a40162306afc.jpg

**Comment by AllanOcelot** [comment]
This issue was resolved - we also now use buttons on mobile to make them easier to click :) 
( Image here : https://imgur.com/a/AGR1shv )
