### ISSUE TITLE
closing of sidebar can be confusing when pinned

### ISSUE THREAD

**Issue by FinlayNash** [kiwiirc/kiwiirc#621]
So once this is open, how do we close it?

Clicking the most obvious option, the 'X', makes the user part the channel!

![capture](https://user-images.githubusercontent.com/44427142/47415001-46417400-d76a-11e8-90cf-b1c980fb0f19.PNG)

**Comment by mestaritonttu** [comment]
By clicking on the "11 people here". I agree that it is confusing.

**Comment by AllanOcelot** [comment]
I'll look into solutions for this and see what we can come up with, Thanks for raising the issue 👍

**Comment by AllanOcelot** [comment]
Perhaps if we have the 'Pin' icon turn red when the sidebar is pinned, this gives the user some feedback on the UI - It let's them know that the pinned option is currently 'on'.
Preview here: ( https://imgur.com/a/rLdbkW5 )

**Comment by mestaritonttu** [comment]
I think an essential part of the confusion is that the proximity of the close button to the others creates a mental association with them. Would it be too radical of a change to move the close button next to the channel name in the top bar?

**Comment by AllanOcelot** [comment]
I agree with that statement @mestaritonttu , I'll look into relocating the close button - this is just a temp fix for now to ensure people know how to unpin a sidebar etc :)
