### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by AlbozDroid** [kiwiirc/kiwiirc#631]
Hi,
I have installed Kiwi server at http://kupidi.com  but webirc is on  http://5.196.26.138:8080/

It used to work fine but now every browser complain about CORS not being enabled. 
**See error:**
```
Failed to load resource: the server responded with a status of 404 (Not Found)
kupidi.com/:1 Failed to load http://5.196.26.138:8080/webirc/kiwiirc/info?t=1540543440951: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://kupidi.com' is therefore not allowed access. The response had HTTP status code 404.
```
Anyone can help with where to enable cors?

**Comment by ItsOnlyBinary** [comment]
It seems you are trying to run the new client and connect to the old client, this is not supported.

webirc for the new client is here: https://github.com/kiwiirc/webircgateway

If you prefer pre-packaged installers please go here: https://kiwiirc.com/downloads/

**Comment by ItsOnlyBinary** [comment]
You seem to have this all sorted, closing this issue now ;)
