### ISSUE TITLE
Pending translations

### ISSUE THREAD

**Issue by zoltyvigo** [kiwiirc/kiwiirc#637]
![image](https://user-images.githubusercontent.com/6929524/47708482-78e9e180-dc2e-11e8-94af-117238a63a94.png)

![image](https://user-images.githubusercontent.com/6929524/47708495-80a98600-dc2e-11e8-86d3-b9d14101745f.png)

![image](https://user-images.githubusercontent.com/6929524/47708527-8901c100-dc2e-11e8-87f6-55afd14b666f.png)

![image](https://user-images.githubusercontent.com/6929524/47708549-961eb000-dc2e-11e8-9b38-1e86e370ceb8.png)

![image](https://user-images.githubusercontent.com/6929524/47708574-a6cf2600-dc2e-11e8-8a2c-72fd35cd154d.png)

![image](https://user-images.githubusercontent.com/6929524/47708632-c5cdb800-dc2e-11e8-8400-38eade0db388.png)

![image](https://user-images.githubusercontent.com/6929524/47708660-d120e380-dc2e-11e8-946e-066cdf7a93f9.png)

**Comment by ItsOnlyBinary** [comment]
#531 covers the need for aliases translations

**Comment by ItsOnlyBinary** [comment]
Ive created an issue for fileuploader translations here: https://github.com/kiwiirc/plugin-fileuploader/issues/51
