### ISSUE TITLE
Autocomplete nicknames with "@" not keeping the "@" in input

### ISSUE THREAD

**Issue by CoryChaplin** [kiwiirc/kiwiirc#65]
Steps to reproduce 
- Type @ + a few letters to open auto-complete popup, for example "@cor"
- Select a nickname

Result : The nickname is in the input box without the "@", for example "cory"

Expected result : the nickname is preceeded by @, for example "@cory"

**Comment by TheMythPT** [comment]
That wouldn't make much sense, since @ usually means channel op..

**Comment by prawnsalad** [comment]
> That wouldn't make much sense, since @ usually means channel op..

This is a good point and would confuse a lot of IRC users. Once the nick colouring is back in place in messages then nicks will stand out properly without the need for a @ prefix.

**Comment by cor** [comment]
That moment when your username is so short that you get emails from random issues 😆

**Comment by CoryChaplin** [comment]
This really deserves discussion imo.
@ does indeed have a meaning in IRC, and another in all communication tools. Is it better keep up with what all people using communication tools are familiar with or with IRC tradition ?
I think we need @nick.

**Comment by TheMythPT** [comment]
And if it's +nick? Will it be @+nick? Over confusing. And the majority of the IRC clients `DO NOT` preppend prefixes to nicknames on messages.
That happens only on nick list.

**Comment by prawnsalad** [comment]
@CoryChaplin for things like this that has a specific meaning in IRC its best to keep it as it is. We can't redefine what @ in front of a nick means as it's so integral. Inputing a nick is one thing but showing a nick is another.

**Comment by TheMythPT** [comment]
That's it. And once again, the `@` on KiwiIRC is to compensate the lack of `TAB` key on mobile keyboards. You can still use `TAB` on PC.
