### ISSUE TITLE
long nickname wrap

### ISSUE THREAD

**Issue by H7-25** [kiwiirc/kiwiirc#665]
Checking kiwiirc with Microsoft edge i've had this  issue, but i've not be able to reproduce it again.
strange thing was that nickname "amoledonneover50anche60" was the only one wrapping, others long nicks were overflowed as usual.

![kiwi_edge](https://user-images.githubusercontent.com/2895452/48537755-c747e300-e8b2-11e8-8808-8c691f102d64.png)

**Comment by AllanOcelot** [comment]
I'll check into this and see if I can replicate :)

**Comment by prawnsalad** [comment]
This is now fixed in master \o/
