### ISSUE TITLE
Any way to block IE totally from kiwiirc?!

### ISSUE THREAD

**Issue by Shillos** [kiwiirc/kiwiirc#667]
Is there a way to block anyone using IE on kiwiirc? Really it's very annoying when most can't use copy paste and much more and has so many bugs the browser itself. There are people that are so dumb they can't use Chrome or Firefox and I get people telling me that it doesn't work on IE very well and yet I don't understand why they want to use it. IE it's old and a terrible browser! Any suggestions on how to remove support from this?!

**Comment by prawnsalad** [comment]
This isn't built directly into kiwi, but you could add something like the following to your index.html page:
~~~html
<script>
if (window.navigator.userAgent.indexOf("MSIE ") > -1) {
    window.location = 'upgradebrowser.html';
}
</script>
~~~

This will redirect any IE users to a upgradebrowser.html page which you can create to explain why users should upgrade their browser.
