### ISSUE TITLE
Support comma-separated list of channels in shorthand URL

### ISSUE THREAD

**Issue by mestaritonttu** [kiwiirc/kiwiirc#67]
Would be cool to be able to point to multiple channels with this syntax: https://kiwiirc.com/nextclient/#irc://irc.freenode.net/kiwiirc

Like in the old client version :)

**Comment by prawnsalad** [comment]
Like this? https://kiwiirc.com/nextclient/#irc://irc.freenode.net/kiwiirc,channel2

**Comment by mestaritonttu** [comment]
Yeah, I'm not sure why it did not work for me before..
