### ISSUE TITLE
customServer ZNC connection screen enhancement

### ISSUE THREAD

**Issue by TheMythPT** [kiwiirc/kiwiirc#68]
On 'customServer' screen we have the option to choose to Connect to a network or to connect to a ZNC.
In order to connect to ZNC we have 3 fields: username, network, and password. 
That's good as since znc 1.0 it allows multiple networks per user.
But that also brings one small problem: ZNC prior to 1.0 don't support multiple networks.
Suppose that some one tried to connect, i.e, to ZNC 0.98. The syntax would be "this.username" + ":" + "this.password", so we won't put anything into network field. 
But the network field will also be sent, but in blank, resulting in "this.username" + "/" + "this.network" + ":" + "this.password", which will be translated to "username/:password", preventing the user to connect to the ZNC.
What I propose is to make network field as optional. If the user inputs something there it would be sent as: "this.username" + "/" + "this.network" + "this.password". Otherwise it should send: "this.username" + ":" + "this.password", which would allow people to connect to older ZNC software (those ones prior to 1.0).

**Comment by ItsOnlyBinary** [comment]
https://github.com/kiwiirc/kiwiirc/commit/6a1d63ad9ff05134e1c3e97f59f734f57e86c24e#diff-64d0400f823c99c168cc520e5c47745aR103

seems to already have this feature
