### ISSUE TITLE
show user sidebar in private messages

### ISSUE THREAD

**Issue by gonzasylv** [kiwiirc/kiwiirc#685]
hi,

Can you display the sidebar of the user in private messages, it is more pleasant and intuitive for the user to have it in private messages, for example: http://imgur.com/GgNKEF8l.png

**Comment by CoryChaplin** [comment]
Hi,

 

That’s a fork I did to first kiwiirc version and that is still to be ported to v2.

I’d say having the info bar itself is relevant for v2, the Age/Gender part will need to be an extension.

 

Elephantman 

 

De : gonzasylv <notifications@github.com>
Répondre à : kiwiirc/kiwiirc <reply@reply.github.com>
Date : mercredi 28 novembre 2018 à 00:30
À : kiwiirc/kiwiirc <kiwiirc@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [kiwiirc/kiwiirc] show user sidebar in private messages (#685)

 

hi,

Can you display the sidebar of the user in private messages, it is more pleasant and intuitive for the user to have it in private messages, for example: http://imgur.com/GgNKEF8l.png

**Comment by Shillos** [comment]
You could add some gravatar hash api or similar service for the picture. That way the users can't upload any abusive pics. If this could be done or as a plugin would be great! Similar to what irccloud did to their app.

**Comment by gonzasylv** [comment]
I was not referring to the avatar, I just wanted to ask if it was possible to make visible the current sidebar in the private window, I show the screen for the example.
