### ISSUE TITLE
If quit message ends with an URL, it ads ) to this

### ISSUE THREAD

**Issue by iwalkalone69** [kiwiirc/kiwiirc#69]
For example:

← Alex25Guapo (b3ptika9@AMYxeg.DaS9VH.virtual) has left (Chateando desde https://chathispano.com/webchat/)

Link is https://chathispano.com/webchat/) but it should be https://chathispano.com/webchat/

**Comment by TheMythPT** [comment]
The ")" isn't part of the URL (you can click it without problems). And if you do notice properly, the quit reason also starts with a "(", so it's consistent.

**Comment by iwalkalone69** [comment]
That is because GitHub fixes it, but it does not happen in Kiwi IRC. I've tested with last master last night.

**Comment by prawnsalad** [comment]
Now fixed in master
