### ISSUE TITLE
html plugins break kiwi on IE11

### ISSUE THREAD

**Issue by ItsOnlyBinary** [kiwiirc/kiwiirc#708]
the plugin loader for html files uses fetch() which does not exist in IE11

i have tried polyfilling with https://github.com/github/fetch

and replacing the following forEach with a for (x of y)
https://github.com/kiwiirc/kiwiirc/blob/master/src/main.js#L265

this is getting me:
SCRIPT1003: Expected ':'
https://gist.github.com/ItsOnlyBinary/1754abd319ea4c9233d8db083760a79d

**Comment by prawnsalad** [comment]
`test() {` is not valid syntax in IE11. You would need babel to transcribe that down to ES5
