### ISSUE TITLE
kick/ban buttons hard to read on darker themes (white/grey text)

### ISSUE THREAD

**Issue by ItsOnlyBinary** [kiwiirc/kiwiirc#712]
![image](https://user-images.githubusercontent.com/558946/49806198-013fc400-fd4f-11e8-977a-8a77b13ed0fe.png)
^^^ nightswatch

**Comment by AllanOcelot** [comment]
Resolved with #717  for both dark theme and nightswatch

**Comment by AllanOcelot** [comment]
Issue resolved.
