### ISSUE TITLE
Mobile Display Error

### ISSUE THREAD

**Issue by MrGrays** [kiwiirc/kiwiirc#716]
![display error](https://user-images.githubusercontent.com/43826343/50025744-737a0800-ffde-11e8-8641-ee6f4cc6a49c.png)

Issue where on Samsung internet using a Samsung Galaxy S5 the channel name is not displayed correctly.

**Comment by AllanOcelot** [comment]
I've discussed this with @ItsOnlyBinary - you are using his plugin.

I'm going to look at redeveloping the way the topic is handled, moving it over to flex layout, so it will have priority on spacing. For now I've recommended to @ItsOnlyBinary  to swap over to an icon, instead of text.
