### ISSUE TITLE
Reconnect after disconnect button wrap

### ISSUE THREAD

**Issue by MrGrays** [kiwiirc/kiwiirc#720]
![48371939_1151027181732976_1288447672918736896_n](https://user-images.githubusercontent.com/43826343/50057571-5c652280-0164-11e9-80d4-9184e43f24e4.jpg)

Reconnect to server wrap is not displaying correctly on mobile devices

**Comment by prawnsalad** [comment]
Quick note from discussion with @AllanOcelot; Moving the connect button to the top right, and making it available on all buffers

**Comment by AllanOcelot** [comment]
Fixed in #791
