### ISSUE TITLE
[Suggestion] Container Header Options revamp

### ISSUE THREAD

**Issue by AllanOcelot** [kiwiirc/kiwiirc#724]
At present, on mobile, having a long channel name can cause some issues with display.

If we change the channel name to display using flex we can solve this issue - to accommodate this change I've come up with some designs for how we could display the option icons we normally display in the container Header.

This would also allow our plugins to add a new 'tile' to the containerHeader options  - keeping the plugins in one modular type fashion.

https://imgur.com/a/UPBUj6P 

Please let me know your thoughts and feedback,
Allan

**Comment by TurtleChatRooms** [comment]
Would work perfect on my setup with the additional plugins that I have in place making my room name text fall out of sync

**Comment by AllanOcelot** [comment]
So, @ItsOnlyBinary  / @prawnsalad  I've had a rethink of this design, maybe something more along the lines of this ( https://imgur.com/a/sQAQoV5 ) .

My thinking is this - we have the 'bars' icon that will default open up the channel information window. 
At the top of the sidebar, we have a div containing clickable buttons - this div would be used primarily ( in default kiwi) for accessing the Userlist and other such sidebar.

However, it's really useful for plugins to have a div to insert into. Plugins could click one of these 'panels'  - open up a new sidebar with plugin specific settings etc.

Let me know your thoughts etc :)

**Comment by AllanOcelot** [comment]
I don't agree with this design / layout anymore. I think it's a bit too different from the rest of Kiwi.

I will revisit this issue in future, but we do need somewhere for plugins to put their icons/buttons - so as not to disturb the natural layout of Kiwi too much.
