### ISSUE TITLE
Issues on latest build

### ISSUE THREAD

**Issue by Shillos** [kiwiirc/kiwiirc#733]
Here is my gist https://gist.github.com/Shillos/b7fc3788f58885b88ff734cad36e63b0

**Comment by AllanOcelot** [comment]
Hi @Shillos  !

Thanks for spotting this, it seems someone recently merged an older PR into Kiwi, one that was made before the class-name linting checks were put in place. PR #735  fixes this, and should be merged in when @prawnsalad comes online.

**Comment by AllanOcelot** [comment]
Pull request fixed this issue, so closing it. Thank you for reporting it :)  👍
