### ISSUE TITLE
Add an option for default ban mask type and apply in ban actions

### ISSUE THREAD

**Issue by iwalkalone69** [kiwiirc/kiwiirc#74]
In preferences, we should have an option about ban type like:
* Nick: nick!*@*
* Username+host: *!username@host
* Host: *!*@host
etc.

Then, when using a /command or ban buttons, apply this mask.

**Comment by TheMythPT** [comment]
as a small help, here's the default ban types used by eggdrop (can be handy to choose some of them)

0 - *!user@host
1 - *!*user@host
2 - *!*@host
3 - *!*user@*.host
4 - *!*@*.host
5 - nick!user@host
6 - nick!*user@host
7 - nick!*@host
8 - nick!*user@*.host
9 - nick!*@*.host

**Comment by TheMythPT** [comment]
Just a side note: don't ever default to ` nick!*@* ` as banmask. It's useless, ineffective and ban evadable.
Just my humble opinion.

**Comment by Zappatta** [comment]
I want to start working on this issue, but am a bit confused by the current code. 

I see that commit 1d087c7ae23678cd0716eb8f45cde8126977c251 introduced "Default ban mask" to the settings component. The same commit also used this settings flag in ircClient.js. But that change has been later removed from ircClient.JS.

I am a bit confused 😕. Was the intention of the aforementioned commit to add this functionality? Does this functionality work now? Is it broken? Did it ever work? can I make it work by reintroducing the code from the that commit?

@iwalkalone69 @prawnsalad your input on this matter would be greatly appreciated. Thank you 😀

**Comment by prawnsalad** [comment]
Ah this feature was actually implemented.. this issue should have been closed :)

@Zappatta which part did you see that was removed?

**Comment by Zappatta** [comment]
@prawnsalad as far as I can see, the changes to ircClient.js introduced in that commit at not implemented in the master branch.

**Comment by prawnsalad** [comment]
The changes were removed from ircClient.js as they shouldn't have been there. I believe that was some earlier implementation @iwalkalone69 was trying out beforehand and accidentally left it in before cleaning up the PR.

**Comment by iwalkalone69** [comment]
Sorry, I could not review this before.

The changes in ircClient.js were undone as @prawnsalad requested in the PR conversation:

https://github.com/kiwiirc/kiwiirc/pull/114

Looking at changes in the closed pull request, I see there is no ircClient.js changes, as requested:

https://github.com/kiwiirc/kiwiirc/pull/114/files

In app settings, there are 2 config (the default ban mask and default kick reason). I've tested and, if you use the Ban or Kickban button in the channel options, it is working. Where is not aplied is in commands like /ban and maybe this is what it is left.

Hope it helps!

**Comment by Zappatta** [comment]
Ok I understand now :) Thanks 👍
