### ISSUE TITLE
[Suggestion] Make Whois URL & Channels Clicable!

### ISSUE THREAD

**Issue by Shillos** [kiwiirc/kiwiirc#758]
I thought this would be a good idea to make these clicable when someone does a whois to show up the channels as clickable to join the channel(s) and the url's that show up to open as a new window (so they don't leave the chat)! 
![kiwi-whois](https://user-images.githubusercontent.com/491386/50783651-312da900-12b4-11e9-9a2d-ce1379ac931f.png)

**Comment by Shillos** [comment]
A quick question is there a way to change the Real Name to whatever we want reflecting our own network name?!

**Comment by ItsOnlyBinary** [comment]
realname is controlled by webircgateway, so if your hosting your own yes, if your using kiwiirc.com no

**Comment by Shillos** [comment]
> 
> 
> realname is controlled by webircgateway, so if your hosting your own yes, if your using kiwiirc.com no

how do i change that cos i'm hosting on my own hosting!

**Comment by ItsOnlyBinary** [comment]
https://github.com/kiwiirc/webircgateway/blob/master/config.conf.example#L27

**Comment by Shillos** [comment]
Thanks! I hope also to see clicable urls and channels soon on the whois!

**Comment by Shillos** [comment]
Thought to close this one, while this was resolved!
