### ISSUE TITLE
nicks not detected and linked as users, "watch" is highlighted as a user that doesnt exist

### ISSUE THREAD

**Issue by ItsOnlyBinary** [kiwiirc/kiwiirc#76]
typing watch into channel gets picked up as a nick.

<a class="kiwi-nick" data-nick="watch" style="color:#3573ca">watch</a>

typing other nicks that are present in the current channel are not highlighted in this way and are seen as normal text

**Comment by prawnsalad** [comment]
Fixed in https://github.com/kiwiirc/kiwiirc/commit/baeb97230db3d7c8c0936c989b9bf9de1c015770
