### ISSUE TITLE
/mode #chan +b never gives output

### ISSUE THREAD

**Issue by KoraggKnightWolf** [kiwiirc/kiwiirc#761]
It appears that when on uses /mode #channel_name +b to view the channel ban list, nothing is returned, not even "End of channel ban list" if no bans are set. Other list modes like +e and +I give their respective outputs (an "End of" line, and either all entries or that one does not have access to view the respective list etc). 
It was suggested on IRC by itsonlyinary to perhaps also have this show up on the sidebar with the banned users tab. 
This issue would be important to resolve as it hinders ops to manage the banlist via the /mode #chan +b to view all set bans.

Regards,

Koragg

**Comment by mestaritonttu** [comment]
I don't get any output with +e or +I for what it's worth.
