### ISSUE TITLE
"is available" misleading for "not /AWAY"

### ISSUE THREAD

**Issue by KoraggKnightWolf** [kiwiirc/kiwiirc#771]
Refering to users who are not marked as being /AWAY as "is available" can be misleading as there are at times usermodes (or custom /WHOIS titles) which add "is available for help" to /WHOIS and users could assume that the showed text means that. Perhaps a better wording would be "here" or even as trivial as "not away" "not gone"? 

Regards,

Koragg

**Comment by DanielOaks** [comment]
I've heard "is away" vs "is not away" used, those are pretty nice

**Comment by AllanOcelot** [comment]
@ItsOnlyBinary  @prawnsalad  any feedback on this issue? 

This Issue was also opened before we added the status indicators so perhaps this has solved it?

**Comment by ItsOnlyBinary** [comment]
Im not sure on this one, i feel its fine.

is no longer away just sounds like they was previously away

**Comment by prawnsalad** [comment]
Away status is just that imo. You're either away or available. Custom whois entries are separate from this and have other meanings.
