### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by nk8** [kiwiirc/kiwiirc#78]
I'm a UI designer and would like to help KiwiIRC interface however possible. Just wanted to start off by asking community what areas they feel could use the most improvement?

**Comment by prawnsalad** [comment]
Hey, it's awesome to see a UI designer getting involved! :)

There are 4 main areas that I can see being a big downfall right now.

1. The connection screen. Just visit https://kiwiirc.com/nextclient/irc.freenode.net and the first screen you see is very plain, boring, and not very inviting. Maybe there's a better way to present that screen?
2. The app settings screen. Click the cog wheel in the top left corner. The screen that appears is very clunky, awkward to use, and not very appealing at all.
3. The network settings screen. If go here and add a network https://kiwiirc.com/nextclient/, the page that appear could be overwhelming for some. Too much going on, but I'm not sure how to simplify that.
4. The top left corner in the side bar, it has the user menu, add network button and settings. And then directly underneath the list of added networks. This looks very squashed to me. Perhaps theres a better way to make that look more appealing.

They're the big ones I think so take your pick :) Unless being a UI designer yourself you can suggest improvements in other areas too.

**Comment by mestaritonttu** [comment]
One thing that I've bumped into is link clicking behaviour: when you click a link, it reveals a view with all kinds of functionality: Reply in private, Preview and then you have to click the link next to the Preview button to actually open the link.

Maybe nk8 can dream up an alternative way to deal with this. My own reaction is that clicking a link should open it right away. Perhaps some small UI element could accompany it for getting this detailed view.

**Comment by nclzz** [comment]
I everyone, following @prawnsalad advice i'll introduce myself in here. I'm a UX/UI designer based in Italy with almost 10 years experience in the field and i would like to start contributing to the open source world. I've found a request for help in the @opensourcedesign jobs listing for Kiwi IRC and here I am.

I can take a look at the 4 main areas that you indicated and see if i can improve upon. They are a good starting point and are perfect for starting out and get to know the product better. 

@nk8 can we join forces?
