### ISSUE TITLE
[Feature Request] Replace Nickname Prefixes with Icons

### ISSUE THREAD

**Issue by corrupt3k** [kiwiirc/kiwiirc#787]
Something like this:
![prefixicons](https://user-images.githubusercontent.com/20589688/51496566-8ae6a680-1d7d-11e9-8db2-42fdc89cf1b3.png)

I have a plugin written that does this for the nicklist and channel. However, it replaces the prefixes after the fact instead of doing it at the point of object creation.

**Comment by AllanOcelot** [comment]
I'll look into adding icons - but maybe only for our users using the modern layout, as some users aren't fans of too many icons etc :)

**Comment by CoryChaplin** [comment]
I liked the status icons from previous kiwi.


Other option is to use that for online status and split ops/users with a block in the list.




Elephantman







On Tue, Jan 22, 2019 at 7:05 AM +0100, "Allan" <notifications@github.com> wrote:












I'll look into adding icons - but maybe only for our users using the modern layout, as some users aren't fans of too many icons etc :)

**Comment by AllanOcelot** [comment]
The best way to do this would be to make a custom theme , adding your icons of choice onto :
`.kiwi-nicklist-user-prefix` - I will make and contribute a simple theme to do this tonight using font awesome's icons - but I cannot guarantee it will be merged in with the master build.

**Comment by corrupt3k** [comment]
I got it working with the nicklist by adding this to my theme:
```
.kiwi-nicklist-user--mode-q .kiwi-nicklist-user-prefix {
	content: url(/chat/static/icons/owner.ico)
}
```

How do I get the same effect with channel messages?
Example:
![ss](https://user-images.githubusercontent.com/20589688/51568248-7d511f80-1e56-11e9-9d6a-37ac5ae44d2d.PNG)

**Comment by ItsOnlyBinary** [comment]
I guess the first step would be to make it work like the nicklist so that prefix can be overridden by css

**Comment by TurtleChatRooms** [comment]
i would like to be able to hide the prefix altogether in nicklist and messagelist if possible

**Comment by Shillos** [comment]
On the other-hand there are those of us that would rather prefer the old way than icons. So preferably to have an option to enable or disable this action.

**Comment by prawnsalad** [comment]
This as an option might be too much. For now this is easily changed via themes as @corrupt3k shows.

~~~css
.kiwi-nicklist-user--mode-o .kiwi-nicklist-user-prefix {
    content: url(https://kiwiirc.com/img/logo.png);
    height: 1em;
}
~~~
