### ISSUE TITLE
[Feature Request] Optional display of channel modes in channel list (via /list)

### ISSUE THREAD

**Issue by timkrumenacker** [kiwiirc/kiwiirc#815]
It would be pretty neat to have the option of displaying channel modes in the /list output.
Like this (note the "[+Pnt]"):

USERCOUNT | CHANNEL | TOPIC | JOIN
-----------|-----------|-----------|-----------
13 | #basecamp | [+Pnt] Ahoy acquainted unknowns... | JOIN

**Comment by prawnsalad** [comment]
You can now add `"showChanlistModes":true` to your config.json file, or set it in the advanced settings window. Thanks!

**Comment by Shillos** [comment]
I was wondering about this one with the modes in /list thanks! Hope to see modes also available in channel info or above would this also work there too?
