### ISSUE TITLE
[Discussion] Make the Giphy plugin a core plugin of Kiwi

### ISSUE THREAD

**Issue by AllanOcelot** [kiwiirc/kiwiirc#820]
@ItsOnlyBinary and I have created a Giphy plugin for Kiwi, allowing users to quickly search for, and send / view gif images from within the Kiwi MessageList.

I suggest merging this plugin into core (Still as a plugin) - and adding in an option to enable / disable (Disabled by default).

I also propose that if the user has the Modern layout selected, the plugin is turned on by default, because I'd class sending/receiving and displaying gifs as a modern feature.

**Steps / issues before this would be possible:**
1. We would need to have a Kiwi API key from within the plugin. I'm not sure how we would stop this from being abused. If this isn't possible, we can never provide the plugin in core.
2. We would need to put the Giphy 'app' into production - this will remove the rate limit on API calls. We would need to conform to their requests - such as having 'Powered by Giphy' when searching for gifs.
3. We would need to heavily test it, Giphy is a feature that many users expect to just 'work'. We should make sure our implementation does just that.

This is just a discussion at the moment, so ideas / feedback is encouraged.

**Comment by Shillos** [comment]
I use your Giphy plugin and i find it great, as of some degree i found that there is some trouble some people send the giphy on channels or private and others can't see the specific gif for some strange reason, not all of course. Does this have anything to do with kiwi not having an api or this could be just a bug?! It will be a great idea to see this as a core plugin with enabled or disabled option. This will help a lot of other plugins to be properly build. Thinking of gravatar as part of the project or plugin?! Giving off some ideas here! :-)

**Comment by AllanOcelot** [comment]
Great to hear you use the plugin @Shillos  :) 
It's one of the features I really wanted in Kiwi, and @ItsOnlyBinary really made it a reality for me.

So, if you have the plugin installed on your local Kiwi - and another client does not have the plugin, they should still see a link to the gif, if they are not even seeing a HTML link - it could be a bug :) 

If you have some spare time, please do some tests - issues for the plugin can be reported over here ( https://github.com/ItsOnlyBinary/my-kiwiirc-plugins ) 

Glad someone else loves this feature <3

**Comment by Shillos** [comment]
The link is shown not the preview i mean in the chat. So it may be a bug! Thanks I will try make some time on those issues.

**Comment by AllanOcelot** [comment]
I don't think there's sufficient interest to make this part of core - we will aim instead to present the themes/plugins Kiwi has to offer in a much clearer way, so users can easily see what plugins they may wish to add.
