### ISSUE TITLE
/quit reason truncated

### ISSUE THREAD

**Issue by glguy** [kiwiirc/kiwiirc#823]
The quit message appears to be truncated to the first word.

I tried: `/quit This is a test message`
The kiwiirc client shows: `glguy_test has left (Quit: This)`
Other users see the reason: `(Quit: This)`

I would expect the whole message to be shown.

Tested on https://kiwiirc.com/nextclient/

**Comment by Shillos** [comment]
This could be on the stable version. At least on the developer version it works fine.

**Comment by ItsOnlyBinary** [comment]
I have just tested this on /nextclient/ and it was working fine, could it be something with a specific ircd?

**Comment by glguy** [comment]
I tried it by connected to freenode. There could be an issue there, instead!

**Comment by ItsOnlyBinary** [comment]
oh when i tested on freenode i just got `Client Quit` no message at all

**Comment by glguy** [comment]
Note that if you're testing on freenode that quit messages are ignored until after you've been connected long enough.

**Comment by glguy** [comment]
My suspicion was that the quit message was lacking the leading `:` and that might explain variation across IRC implementations. I didn't know where to look in the code to confirm that.
