### ISSUE TITLE
Password input not visible for channels requiring a key

### ISSUE THREAD

**Issue by AllanOcelot** [kiwiirc/kiwiirc#826]
A nice first issue for someone who wishes to contribute to Kiwi, the input box on channels with a key requires a border or some styling to make it visible.

![image](https://user-images.githubusercontent.com/11334905/52786625-459f5700-3053-11e9-9c94-f1121ab2cceb.png)

**Comment by ivarmlee11** [comment]
I'll do this!

**Comment by ivarmlee11** [comment]
https://github.com/kiwiirc/kiwiirc/pull/828
