### ISSUE TITLE
UI consistency improvement with the two gear icons

### ISSUE THREAD

**Issue by chesty** [kiwiirc/kiwiirc#829]
Hi, love your work.

Here's a tiny insignificant inconsistency that doesn't really need adjusting but would be nice if it was.

There's a gear icon in the top right, clicking it opens the channel settings window, clicking it again closes the channel settings.

There's a gear icon in the top left, clicking it opens the general settings window, clicking it again does nothing. To close the window I have to move the mouse to the top right and click close, it's almost far enough to need a packed lunch.

Please consider closing the general settings window by clicking the gear icon again.

cheers

**Comment by ivarmlee11** [comment]
I'm in the process of fixing this based on your suggestion. This will feel better.

**Comment by chesty** [comment]
Thank you, I updated and it's perfect.
