### ISSUE TITLE
UserBox.vue displaying modes for nick using client, not nick being viewd.

### ISSUE THREAD

**Issue by TheBeerbarian** [kiwiirc/kiwiirc#830]
Noticed after recent Away feature merge.
Any user I view displays my modes, not the modes for the user I am viewing.

**Comment by AllanOcelot** [comment]
I'll make a hotfix for this right now and contact @prawnsalad  to get this merged in ASAP.

Thank you @TheBeerbarian  - something we must have overlooked sadly <3
