### ISSUE TITLE
Kick user box on touch screen messed up

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/kiwiirc#844]
![image](https://user-images.githubusercontent.com/725880/53352981-baa84180-391b-11e9-9ec9-21de0910fe17.png)

**Comment by prawnsalad** [comment]
On top of this, the kick+ban options should not be there as I wasn't an op

**Comment by AllanOcelot** [comment]
Looking into this issue now

**Comment by AllanOcelot** [comment]
This has now been resolved in #847

**Comment by AllanOcelot** [comment]
Screenshots provided below : 

![image](https://user-images.githubusercontent.com/11334905/58110256-1c104180-7be7-11e9-8204-b76a5d5f18d3.png)

![image](https://user-images.githubusercontent.com/11334905/58110297-2d594e00-7be7-11e9-9f1b-cff86d6c1d7e.png)
