### ISSUE TITLE
Nick order by channel status is still mixed

### ISSUE THREAD

**Issue by TheMythPT** [kiwiirc/kiwiirc#85]
![nick_order](https://user-images.githubusercontent.com/25697531/29165889-a7350d90-7dc4-11e7-88f4-9a1d90368f2b.png)
As you can see, some channel status modes are still mixed. On UnrealIRCd, if we use the whole package of channel status modes, the correct order to display them is `~ & @ % +`

**Comment by prawnsalad** [comment]
Fixed in https://github.com/kiwiirc/kiwiirc/compare/008a2cb5243b...98a8e765f082
