### ISSUE TITLE
Reply in private 

### ISSUE THREAD

**Issue by Indjov** [kiwiirc/kiwiirc#86]
Hello,
When you try to use that option from channel msg, and then it`s open private tab with my nickname not with the nickname wheare i want to type in private.
![msg](https://user-images.githubusercontent.com/5468168/29166874-d59f716e-7dd0-11e7-85fa-e24293a22a1f.PNG)
![nickmsg](https://user-images.githubusercontent.com/5468168/29166873-d59385fc-7dd0-11e7-91a2-5d4769924b5a.PNG)

**Comment by prawnsalad** [comment]
Fixed in https://github.com/kiwiirc/kiwiirc/commit/74dfd2263e83a352952fdb183c34fbcf6fea962e
