### ISSUE TITLE
Google recaptcha div must have g-recaptcha class

### ISSUE THREAD

**Issue by tomaw** [kiwiirc/kiwiirc#862]
It seems the recaptcha script replies on rendering in an element with a class of g-recaptcha. #688 broke that.

**Comment by ItsOnlyBinary** [comment]
will also need to add a lint exception for the class lines, or `g-` will need adding here: https://github.com/kiwiirc/kiwiirc/blob/master/config/eslint/rules/class-name-prefix.js#L21

Welcome screen also needs some css fixes

![kiwi](https://user-images.githubusercontent.com/558946/54154147-2240af80-4439-11e9-8ee3-9199f6351cc8.png)

**Comment by AllanOcelot** [comment]
Good find @tomaw , thank you!
@ItsOnlyBinary  - if you want to do the PR that adds the class back in and does the exception, I can hop on and easily style it.

**Comment by AllanOcelot** [comment]
Fixed in #865  :)
