### ISSUE TITLE
Capture Button on Upload Image from Camera

### ISSUE THREAD

**Issue by TurtleChatRooms** [kiwiirc/kiwiirc#863]
![capture button](https://user-images.githubusercontent.com/43826343/54154609-2e793c80-443a-11e9-94df-29e2f50433a1.jpg)

Cant see the capture button on Samsung S8 Plus

**Comment by prawnsalad** [comment]
Closing as a duplicate of https://github.com/kiwiirc/plugin-fileuploader/issues/54
