### ISSUE TITLE
License Inconsistency

### ISSUE THREAD

**Issue by damolp** [kiwiirc/kiwiirc#875]
According to the [docs](https://kiwiirc.com/docs/development) KiwiIRC is licensed under AGPL but according to the git repo it was originally [MIT](https://github.com/kiwiirc/kiwiirc/blame/51f582879d068419255f3e97854af13820bdfb38/LICENSE) and now [Apache 2.0](https://github.com/kiwiirc/kiwiirc/commit/b709d7a7f861a8a542583e3727889c41f172d6f2)

Can you please fix up the inconsistencies between the repo and the docs?

**Comment by prawnsalad** [comment]
Those docs were referencing the old version of Kiwi which was always AGPL. I've removed any mention of the license on that docs page as it's mentioned in each project repo anyway to remove any confusion.
