### ISSUE TITLE
Confirm tab/window closing

### ISSUE THREAD

**Issue by mestaritonttu** [kiwiirc/kiwiirc#88]
Kiwi does not ask "Stay on page" vs. "Leave" when closing. I think it is valuable to ask.

**Comment by mestaritonttu** [comment]
Here is how the old version did it:

https://github.com/prawnsalad/KiwiIRC/blob/master/client/src/views/application.js#L37

**Comment by prawnsalad** [comment]
This is now in master. Thanks!
