### ISSUE TITLE
open statebrowser button has bad colouring on nightswatch

### ISSUE THREAD

**Issue by ItsOnlyBinary** [kiwiirc/kiwiirc#880]
![image](https://user-images.githubusercontent.com/558946/55175064-86bc7800-5176-11e9-8424-efca28c38c61.png)

**Comment by ItsOnlyBinary** [comment]
also the time is black on join messages

**Comment by AllanOcelot** [comment]
@ItsOnlyBinary can you quickly test this and close the issue if solved please <3

**Comment by AllanOcelot** [comment]
Fixed in #893
