### ISSUE TITLE
Give me back the damn old version, the new one is an atrocity

### ISSUE THREAD

**Issue by sosofrauk** [kiwiirc/kiwiirc#894]
Seriously, for the love of your old time users, give me or us back the old version at least on the side, the new version is an atrocity and you're seriously killing my vibe. Need the old version back.

**Comment by prawnsalad** [comment]
We have been running the old and new version side by side for roughly a year now. Mentions were put on twitter several times and on the font page of the old client for many months. The old version is now being phased out as it no longer works on newer IRC networks and is becoming expensive to run from my own pocket.

Specifically, what about the new version don't you like? Now is a good time for some constructive feedback to see what can be improved!

(I'm going to close this issue as it's not an issue to the project, but we still get notifications on comments)

**Comment by sosofrauk** [comment]
a) it's a lot harder to set dark mode
b) the single screen sign-on is gone, it was useful and easy to pick your server, your channels, set your nick and log on almost automatically because it was so simple.
c)it're more slack-ey. Imagine old reddit and new reddit, where as I love old reddit. 
The new interface looks and feels like new reddt. What I loved about the old version was it's stripped down functionality, easy of use and it stayed the same for a very long time. It reminds me of a html editor and It's easier to read along the various lines of chat because each line that a user speaks is still attributed to their nickname, now I find it harder to keep an overview over what is being said and by whom.

**Comment by prawnsalad** [comment]
Thanks for these, it helps a lot!

2 questions come to mind.
For your point A, changing to the dark theme in both the old and new client is settings > theme. Are you seeing something different?

And for the point of finding it harder to follow what's being said, are you referring to the nick not being included in every message? If so, are you using the traditional message layout (found in the settings)?

**Comment by sosofrauk** [comment]
I've found the dark mode settings, but there are still certain usability issues that prevent me from using the new version and I'm looking out for alternatives.
I cannot switch between channels on one server in a simple way, the channels disappear both and I see no ability to switch between them on a single click on the tabs like it was before.
I also can't find the traditional messaging layout you are mentioning in the settings, and yes, the bubble before the nick makes it harder to follow the conversations. 
Earlier, the nicks and the conversions were stacked geometrically and with exactly the same space between the text above and below, now it just seems too "fluffy".

**Comment by prawnsalad** [comment]
Could you please take a screenshot of what youre seeing with 2 channels open? Switching channels is still a single click - you click the channel name.

Traditional layout is in the settings. 3 options down from the Theme.
