### ISSUE TITLE
Rework the Banned users display

### ISSUE THREAD

**Issue by AllanOcelot** [kiwiirc/kiwiirc#900]
The Banned users display should be reworked - it should show all the information , along with options to unban users etc, in a more clear manner.

**Comment by Shillos** [comment]
Shouldn't modes on channel also show up too. I mean it would be better for all to see the different modes (on topic or info sidebar) that apply also inclusive the ban unban and other op deop modes e.t.c. in channel. Let's say i put mode +G on channel but kiwi doesn't display it would be good to see it and even on the /list must show the modes of each channel.

**Comment by prawnsalad** [comment]
@AllanOcelot are you saying that we are missing info here?
![image](https://user-images.githubusercontent.com/725880/56198527-02516c80-6033-11e9-9804-26467abebdff.png)

**Comment by AllanOcelot** [comment]
This is how it displays on desktop currently:
![image](https://user-images.githubusercontent.com/11334905/56217913-f29a4e00-605b-11e9-8682-6cf05ff9ae8e.png)

I feel like it just needs some love to make it fit in with the rest of Kiwi, this is one thing we've just never updated. A bit of extra spacing - turning the delete icon into a button,  formatting the date better etc etc

As for info missing: I just assumed we would have more stuff backend to display ( Maybe a 'reason' for the ban, or a 'ban ends on xx/yy/zz' type thing)

**Comment by gonzasylv** [comment]
hi,

it would be possible to add an option in the config can be, to hide the window of banned users without mode, those who are not operators or more, to avoid bypasses.

**Comment by AllanOcelot** [comment]
@gonzasylv  we could look into adding that a feature in future :) - Nice idea!

**Comment by DarkTexas** [comment]
AFAIK ban reasons aren't saved on the ircd as Bans are basically modes only. They are executed via kick and neither logged or visible.

As for expiration timers.. Same there, Bans are not set to expire only if you use separate modules.

**Comment by prawnsalad** [comment]
These banlist changes have been worked in over a few different commits recently, closing as it's now redundant
