### ISSUE TITLE
Executable

### ISSUE THREAD

**Issue by djlolito** [kiwiirc/kiwiirc#902]
When you download a package already compiled from.

https://kiwiirc.com/downloads/index.html

It has a kiwiirc executable file, however when you do a yarn run build it is not generated.

How do you do it to generate it or where does that executable come from?

**Comment by prawnsalad** [comment]
Yarn is only used to build kiwi but the installation packages are already built. You would need to use your server distro package manager to install them, dpkg is debian/ubuntu/etc, yum for centod/redhat/etc

**Comment by ItsOnlyBinary** [comment]
The executable is built from here: https://github.com/kiwiirc/webircgateway

it will require a recent version of golang (unlikely the one in package manager)
