### ISSUE TITLE
Clicking on keyword "constructor" messes everything up

### ISSUE THREAD

**Issue by mestaritonttu** [kiwiirc/kiwiirc#91]
Steps to repro (try in a fresh session as it breaks the UI):
1. Be in a channel
2. Say constructor
3. Left-click the now red-colored constructor string

Result: a wide sidebar appears with "Close", but you cannot close it. The left sidebar also stops responding to clicks.

This is on Firefox 54

**Comment by prawnsalad** [comment]
This is part of this issue https://github.com/kiwiirc/kiwiirc/issues/76
