### ISSUE TITLE
[bug]: nicklist doesn't get updating channel modes in some cases

### ISSUE THREAD

**Issue by westor7** [kiwiirc/kiwiirc#910]
Hello,

I saw a strange behavior when a network bot was taking/giving a channel mode (+qo) on a user, i captured a video in order to let you see what was going on.

In some cases when the bot taking or giving the modes in kiwi nicklist side it doesn't updating the nicklist with the correct flag.

IRCD: Unreal3.2.10 + Unreal4.2.3
Video: http://j.mp/2vgxn7I

- Thanks!

**Comment by westor7** [comment]
There is also an nicklist order problem according the flags, as you can see in the image below there is a guy at the end that has @ and is not ordered correctly at the top of the nicklist.

https://i.imgur.com/Dgzz5hy.png

**Comment by TheMythPT** [comment]
Bug confirmed with the previous deb package (-1 than current) and latest git for the frontend at the time.
Seems that itsonlybinary was able to reproduce the bug too.

**Comment by ItsOnlyBinary** [comment]
This was broken by this commit https://github.com/kiwiirc/kiwiirc/commit/d0336ddb6572306ab3281129f33f6936fdfb8670

really not sure on how that seemingly unrelated change has broken reactivity
