### ISSUE TITLE
[suggestion]: make the PM icon white in dark+nightswatch themes

### ISSUE THREAD

**Issue by westor7** [kiwiirc/kiwiirc#917]
Hello,

As you are going to see in the image below the PM icon is dark and in dark+night themes that one doesn't display good, so my recommendation is to make it white.

Example Image: https://i.imgur.com/tHxC6my.png

- Thanks!

**Comment by AllanOcelot** [comment]
Hi @westor7  - I've added this suggestion into PR #916 :)

**Comment by westor7** [comment]
Thank you very much i will wait that in master to test it out!

**Comment by AllanOcelot** [comment]
I am going to quickly look into this again - as the PR I addressed this in is now outdated.

**Comment by AllanOcelot** [comment]
Fixed in #983 - should be merged in soon.

**Comment by AllanOcelot** [comment]
Merged in :)
