### ISSUE TITLE
[bug]: Timestamps doesn't display at all in nightswatch theme

### ISSUE THREAD

**Issue by westor7** [kiwiirc/kiwiirc#918]
Hello,

As you are going to see in the image below the timestamp doesn't display at all because the background color is not black.

Example Image: https://i.imgur.com/a4oULGm.png

- Thanks!

**Comment by AllanOcelot** [comment]
Hi @westor7  #916  seems to resolve this issue ( I've just checked locally ) - thank you for reporting it :)

**Comment by AllanOcelot** [comment]
Since #916  has been closed, I will double check this today.
