### ISSUE TITLE
[suggestion]: Add user mode classes to messagelist messages

### ISSUE THREAD

**Issue by westor7** [kiwiirc/kiwiirc#919]
Hello,

It would be nice and wonderful to add some classes in messagelist messages as there are already for nicklist, i will provide an image example to understand more.

Example Image: https://i.imgur.com/LkGsTUy.png

- Thanks!

**Comment by ItsOnlyBinary** [comment]
just to clarify a little, westor is looking for `.kiwi-nicklist-user--mode-o` but for messagelist

**Comment by westor7** [comment]
Duplicate: #787

**Comment by westor7** [comment]
This is perfect!!! very good job, i will wait that on master to test it out! thank you!

**Comment by AllanOcelot** [comment]
Since this has been merged and is now in master, I am closing this issue.

**Comment by westor7** [comment]
@AllanOcelot are you sure that it has been merge into master? :P

**Comment by ItsOnlyBinary** [comment]
This has not been merged yet
