### ISSUE TITLE
Make Sidebar's top:0px when on mobile devices

### ISSUE THREAD

**Issue by AllanOcelot** [kiwiirc/kiwiirc#922]
This is a simple fix, but it makes the Kiwi experience feel a bit tighter on mobile devices.

**Comment by prawnsalad** [comment]
The sidebar is already at the top, or are you meaning something else?

![image](https://user-images.githubusercontent.com/725880/56579677-ad7c9b80-65c8-11e9-94d9-da455d6208e0.png)

**Comment by AllanOcelot** [comment]
The sidebar sit's below the workspace::before ( The green line at the top ) - this makes the sidebar title (close x) look like it's line height is messed up. 

( We'll still need to play with the lineheight of the text to get it looking perfect ) 

![image](https://user-images.githubusercontent.com/11334905/56579889-3693d280-65c9-11e9-8f04-f34b112105e3.png)

**Comment by prawnsalad** [comment]
Ahh I see it, agreed!
