### ISSUE TITLE
[suggestion]: Add an config option to hide the network settings icon top left

### ISSUE THREAD

**Issue by westor7** [kiwiirc/kiwiirc#927]
Hello,

I know that this can also be made via CSS, but it would be good to have it as an option as there is already the option to hide the advanced.

Option like: `"hide_settings": true,`

- Thanks!

**Comment by AllanOcelot** [comment]
The top left icon is for Kiwi options, not network options - are you sure this is what you mean?

**Comment by westor7** [comment]
yes @AllanOcelot that one

**Comment by westor7** [comment]
Thank you my friend, i will wait that to master to test it out!
