### ISSUE TITLE
Nicklist Problem

### ISSUE THREAD

**Issue by H7-25** [kiwiirc/kiwiirc#959]
After a while nicklist look get crazy , it also show users from other channels , switching channel tabs reset the problem

![issue](https://user-images.githubusercontent.com/2895452/57180943-03d1c000-6e8e-11e9-9aa2-d4806f1fa81a.gif)

[Error] TypeError: undefined is not an object (evaluating 'n.nick')
(funzione anonima) — TypingUsersList.vue:43
filter
get — vue.common.prod.js:6:26582
evaluate — vue.common.prod.js:6:27730
(funzione anonima) — vue.common.prod.js:6:29627
i — TypingUsersList.vue:1:142
_render — vue.common.prod.js:6:35300
r — vue.common.prod.js:6:67994
get — vue.common.prod.js:6:26582
run — vue.common.prod.js:6:27469
Ut — vue.common.prod.js:6:25533
(funzione anonima) — vue.common.prod.js:6:12292
G — vue.common.prod.js:6:11687
promiseReactionJob

TypeError: undefined is not an object (evaluating 'u.nick')
sortedUsers — Nicklist.vue:61
get — vue.common.prod.js:6:26582
evaluate — vue.common.prod.js:6:27730
(funzione anonima) — vue.common.prod.js:6:29627
i — Nicklist.vue:3
_render — vue.common.prod.js:6:35300
r — vue.common.prod.js:6:67994
get — vue.common.prod.js:6:26582
run — vue.common.prod.js:6:27469
Ut — vue.common.prod.js:6:25533
(funzione anonima) — vue.common.prod.js:6:12292
G — vue.common.prod.js:6:11687
promiseReactionJob

**Comment by H7-25** [comment]
I renew this issue with a new video, at this time using websocket connection, the client was connected for more than 24h 
https://imgur.com/a/uYjENes

**Comment by prawnsalad** [comment]
Is this still happening, @H7-25 ?
