### ISSUE TITLE
Inline url previews

### ISSUE THREAD

**Issue by ItsOnlyBinary** [kiwiirc/kiwiirc#960]
prawnsalad i want to get it so that the preview is underneath the message to start with, but then you can pin it as it is now. at the top

I also suggest that this includes an option controlling the showing of inline previews by default

**Comment by prawnsalad** [comment]
Implemented in https://github.com/kiwiirc/kiwiirc/commit/8f3aed055b4bd64adb5191b9447fde4413ae7087
