### ISSUE TITLE
Nicklist issue on mobile view

### ISSUE THREAD

**Issue by H7-25** [kiwiirc/kiwiirc#966]
On mobile view when nicklist is visible the faded darker box on the left does not fill all the space in height.

![kiwiirc](https://user-images.githubusercontent.com/2895452/57434653-ba8dc180-723b-11e9-9733-111cc6f2c8f9.png)

**Comment by AllanOcelot** [comment]
I cannot replicate this issue exactly but there is an issue with the shadow. 

@prawnsalad  it seems that when the typing PR was merged we added in margin to the bottom of the mesagelist and not padding causing some issues with the shadow, going to try a HOTFIX and see if there is a knock on effect of using padding

**Comment by AllanOcelot** [comment]
Fixed in #968  - thanks for reporting the issue @H7-25  :)

**Comment by AllanOcelot** [comment]
FIx merged with #968
