### ISSUE TITLE
new versions of kiwi conflate PASS passwords and SASL passwords

### ISSUE THREAD

**Issue by slingamn** [kiwiirc/kiwiirc#974]
I have an older version of kiwi (not sure when exactly it's from, but the file mtimes say July 2018) installed here:

https://irc.darwin.network/kiwi/

with this config:

https://irc.darwin.network/kiwi/static/config.json

This successfully supplies the hardcoded password (which is not sensitive, just a roadblock for port probes) in the config file to the ircd, via the PASS command.

I installed version 19.04.24.1 alongside it here with the same config:

https://irc.darwin.network/kiwi__/

This version attempts to supply the hardcoded password as both the PASS password and as a SASL password for the nickname the user supplies. When the SASL authentication fails, Kiwi hangs up the connection.

Would it be possible for the config to accept a separate `serverPassword` field, so that these values are correctly distinguished? Is there a different workaround by which I can restore the previous behavior?

Thanks for your time.

**Comment by slingamn** [comment]
If absolutely necessary, I can work around this on the ircd side by adding a configuration option that says if a valid WEBIRC command was presented, then PASS is not required, then enabling this config and removing `password` from the Kiwi config. But I'd prefer not to do that because our auth logic is complicated enough as it is :-)

**Comment by slingamn** [comment]
A note: if I've understood the behavior correctly (send the password with PASS, then send it again as a SASL password, then disconnect if SASL fails), it appears to support both PASS and SASL, but in practice fails to support PASS at all (because there's no reason to believe that the PASS password is valid as a SASL password).

**Comment by slingamn** [comment]
Any interest in a workaround for this in webircgateway, i.e., a `pass` key for the "upstream" section of the config so that webircgateway can insert the appropriate `PASS` command?

**Comment by Shillos** [comment]
I think you are on the wrong place try https://github.com/kiwiirc/webircgateway make an issue there. This is more to do with webircgateway plugin

**Comment by slingamn** [comment]
I think this is a Kiwi issue. If the outcome of the discussion is that the best option is to work around the problem in webircgateway, that's fine, but my belief is that the root cause is Kiwi's failure to distinguish between the two kinds of password.

**Comment by Shillos** [comment]
There is a similar issue here i don't know if this has anything to do with it https://github.com/kiwiirc/webircgateway/issues/56 .

**Comment by slingamn** [comment]
I think that's unrelated, yeah.

**Comment by prawnsalad** [comment]
You can add disconnectOnSaslFail:false to your kiwi config for this. Reasoning here is that a lot of users enter a password to login, it connects if its correct or not, then the user assumes they have successfully logged in in all cases. Disconnecting on fail makes it more natural, not continuing if login has failed.

**Comment by crazycatdevs** [comment]
> You can add disconnectOnSaslFail:false to your kiwi config for this. Reasoning here is that a lot of users enter a password to login, it connects if its correct or not, then the user assumes they have successfully logged in in all cases. Disconnecting on fail makes it more natural, not continuing if login has failed.

I did that in my config.json but not sure I placed it well: I added it in startupOptions and it doesn't seems to work.
I'm using direct connexion (websocket) and using a password when the account is not registered or make an error in the pass throws an error "connexion failed, contact the administrator"

Did I place this option in a bad place ?
