### ISSUE TITLE
Feature: XDCC

### ISSUE THREAD

**Issue by Immortalin** [kiwiirc/kiwiirc#976]
ref: https://github.com/prawnsalad/KiwiIRC/issues/591

**Comment by prawnsalad** [comment]
Unless somebody sends a PR, we won't be supporting X/DCC. There are better options for file transfers these days.

**Comment by ProgramComputer** [comment]
XDCC can be added as a plugin to the gateway from https://github.com/ProgramComputer/plugin-XDCC and found as kiwiirc/webircgateway#103
