### ISSUE TITLE
[Suggestion]: Add an option to disable/enable away indicators

### ISSUE THREAD

**Issue by westor7** [kiwiirc/kiwiirc#979]
Hello,

It would be nice to exist an option under General to display or not the away indicators, currently is only available via CSS modifications.

- Thanks!

**Comment by AllanOcelot** [comment]
maybe having this as an advanced option, disabled by default would be best? ( Show the messages show for the majority of users)

**Comment by AllanOcelot** [comment]
I'm making a PR for this now - I'll add an advanced option for this, as I feel most of our users will want these enabled by default, but appreciate that some want them turned off :)

**Comment by AllanOcelot** [comment]
#994 deals with this, adding in a new option to the advanced options.

**Comment by digitalcircuit** [comment]
Now that #994 is merged, this issue can probably be closed, unless it's required to have the option in General rather than Advanced.

Setting is `showAwayStatusIndicators`, `true`/`false`.

**Comment by prawnsalad** [comment]
Good shout, @digitalcircuit. Closing!
