### ISSUE TITLE
url parameters at welcome screen not decoded

### ISSUE THREAD

**Issue by gsantner** [kiwiirc/kiwiirc#98]
Hi there,
I placed some link to kiwiirc (official instance) and found out, that it doesn't decode the query parameters properly. This is especially about the `%23` ascii encoded character for the hashtag `#`. If the browser submits the channel parameter ascii encoded the server fills the channel paramer just like that. Expected would be that the parameter gets decoded correctly and than placed in UI.

Test it:
* <https://kiwiirc.com/client/irc.freenode.net/?nick=user-dandelion&channel=#%23dandelion>

 I noticed that at a link which is reffering to my community.

<https://crowdin.com/project/diaspora-for-android>
```
<a href="https://kiwiirc.com/client/irc.freenode.net/?nick=user-dandelion%7C?channel=##dandelion" rel="nofollow" target="_blank">
  <img src="https://img.shields.io/badge/chat-on%20freenode-blue.svg" alt="chat-on%20freenode-blue.svg" />
</a>
```

**Comment by prawnsalad** [comment]
You don't need to use `channel=` as that's used for other webirc clients. Just add the channel at the end of the URL without any need for special encoding. In your case: https://kiwiirc.com/client/irc.freenode.net/?nick=user-dandelion##dandelion

**Comment by gsantner** [comment]
Thats what I had before. Still not working.

![bildschirmfoto von 2017-08-17 22-53-00](https://user-images.githubusercontent.com/6735650/29433319-f788522c-839e-11e7-9c90-2f72bb007fd9.png)

![bildschirmfoto von 2017-08-17 22-54-31](https://user-images.githubusercontent.com/6735650/29433340-14904140-839f-11e7-9468-ff5e8a959e97.png)

**Comment by prawnsalad** [comment]
That link is for HTML entities, not URI encodings. The fragment of the URL (anything after the #) does not need encoding in such a way.

While the URI RFCs do not mention that # is a supported character, every browser that I have tested from IE8+ chrome/firefox/safari/android all do support reading the # in URI fragments without issue.

For your example of joining the channel #chn%23abc, then it's the same procedure for the URI again. https://kiwiirc.com/client/irc.freenode.net#chn%23abc
These URIs work on every browser tested.

One point to note though, is that if you have a page open in your browser with a fragment and then manually change the fragment, you may need hit hit return twice for the page to reload.

**Comment by gsantner** [comment]
Sorry, I edited the link already before posting, but yep, had the wrong one posted right

**Comment by gsantner** [comment]
<https://kiwiirc.com/client/irc.freenode.net#chn%23abc> should be `#chn#abc`

**Comment by prawnsalad** [comment]
We have the new version of Kiwi at https://kiwiirc.com/nextclient/#irc://irc.freenode.net/#channel 
I'll look into the extra encoding in that version as I'll agree that makes sense to support them both. Could you create an issue for this at https://github.com/kiwiirc/kiwiirc ?

**Comment by gsantner** [comment]
Thanks for considering :D.

This is already the kiwiirc/kiwiirc repository

**Comment by prawnsalad** [comment]
Oh, so it is :D Sorry, talking about the old version in the new version repo threw me off.

Will open this issue to support both formats.
