### ISSUE TITLE
Skip welcome screen for iframe 

### ISSUE THREAD

**Issue by pjc0247** [kiwiirc/kiwiirc#980]
Can I make a iframe without welcome screen?

There're already nickname, server and channel data, so we can skip it.

```html
<iframe src="https://kiwiirc.com/client/irc.kiwiirc.com/?nick=kiwi566|?#aaaa" style="border:0; width:100%; height:450px;"></iframe>
```

**Comment by prawnsalad** [comment]
We don’t support auto connect on kiwiirc.com as it can very easily be abused to flood networks.
You probably wouldn’t want all the join/part spam either :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
