### ISSUE TITLE
[Mobile] Add an option, like some apps already do, to display password in plaintext

### ISSUE THREAD

**Issue by TheMythPT** [kiwiirc/kiwiirc#986]
This is what I said in IRC and I think it's quite explanatory:
> so, I was thinking in something: when using mobile, it's easy to make mistakes typing the password on the password field for SASL authentication. I was wondering if would make sense to have a "display password" thing?

**Comment by AllanOcelot** [comment]
Awaiting PR merge, great suggestion, thanks @TheMythPT  :)

**Comment by TheMythPT** [comment]
Great! Thanks for the hard work!!!
