### ISSUE TITLE
Make input field receive clipboard contents as plain text

### ISSUE THREAD

**Issue by mestaritonttu** [kiwiirc/kiwiirc#99]
Is there any reason why the input field accepts rich text or html? Currently, Firefox has a weird way of adding line breaks to copied html text. This results in unintended multi-message pastes in Kiwi.

I investigated the clipboard contents in Linux and Windows. It looks like we should get the clipboard target UTF8_STRING on Linux and CF_UNICODETEXT on Windows (it uses UTF-16 on Win). It might be that macOS uses the same target as Linux, but I was unable to verify.

For inspecting the clipboard I used [Inside clipboard](http://www.nirsoft.net/utils/inside_clipboard.html) on Windows (download link at the bottom) and xclip on Linux.

You can list the available targets with xclip like so:
```
$ xclip -selection clipboard -o -t TARGETS
TIMESTAMP
TARGETS
MULTIPLE
SAVE_TARGETS
text/html
text/_moz_htmlcontext
text/_moz_htmlinfo
UTF8_STRING
COMPOUND_TEXT
TEXT
STRING
text/x-moz-url-priv
```

**Comment by prawnsalad** [comment]
Now fixed in https://github.com/kiwiirc/kiwiirc/commit/7102419a3a075d97939ce6a888e7c9dc0f47e867
