### ISSUE TITLE
Switching between different tabs take ~5 seconds on Chromium 

### ISSUE THREAD

**Issue by NavyaZaveri** [kiwiirc/kiwiirc#995]
**OS**: Linux, Ubuntu 18.04 

**Browser:** Chromium 

**Client:** https://kiwiirc.com/nextclient/irc.freenode.net 

I've noticed that switching between channels now takes up at least ~ 3 -7 seconds, which is painfully frustrating. Not sure if this has anything to with how active/populous a channel is at a given point,  but there was no such problem before the UI updates.

**Comment by ItsOnlyBinary** [comment]
this was fixed yesterday but may take a little while to be made live on kiwiirc.com

https://github.com/kiwiirc/kiwiirc/commit/43176183de69a5bad04581ed80ae66d1349bdb7c

**Comment by prawnsalad** [comment]
Hey @NavyaZaveri I've now updated this on kiwiirc.com. It should now be near instantaneous for all channel sizes!

**Comment by NavyaZaveri** [comment]
@prawnsalad Has it been made live?

I tried the client right now, and switching from ##python to ##linux  took nearly 17 seconds...

If it helps, here's the profiling logs:
https://ufile.io/fnukhlev

**Comment by prawnsalad** [comment]
Can you clear your browser cache and try that again? It's almost instant for me and everyone else that's tried it since, using multiple browsers.

**Comment by NavyaZaveri** [comment]
Yup, that was it. Thanks for the fix!
