### ISSUE TITLE
User spammed when not registered in chan

### ISSUE THREAD

**Issue by AllanOcelot** [kiwiirc/kiwiirc#996]
When attempting to message a channel requiring users to be logged in  / registered, we are spamming the user with 
 >'You need to be identified to a registered account to message this channel'

This appears every time the user tries to type, we should limit the output of this message to one.

**Comment by prawnsalad** [comment]
Closing this as it's being worked towards in https://github.com/kiwiirc/kiwiirc/pull/1122
